characterMapEliza = {
  "eliza_be0_full_naked_002":              "eliza_be0_full_naked_002",              # Auto: Same
  "eliza_be0_full_under_002":              "eliza_be0_full_under_002",              # Auto: Same
  "eliza_be0_naked_002":                   "eliza_be0_naked_002",                   # Auto: Same
  "eliza_be0_under_002":                   "eliza_be0_under_002",                   # Auto: Same
  "eliza_be1_001":                         "eliza_be1_001",                         # Auto: Same
  "eliza_be1_002":                         "eliza_be1_002",                         # Auto: Same
  "eliza_be1_003":                         "eliza_be1_003",                         # Auto: Same
  "eliza_be1_cas_001":                     "eliza_be1_cas_001",                     # Auto: Same
  "eliza_be1_cas_002":                     "eliza_be1_cas_002",                     # Auto: Same
  "eliza_be1_cas_003":                     "eliza_be1_cas_003",                     # Auto: Same
  "eliza_be1_full_001":                    "eliza_be1_full_001",                    # Auto: Same
  "eliza_be1_full_002":                    "eliza_be1_full_002",                    # Auto: Same
  "eliza_be1_full_003":                    "eliza_be1_full_003",                    # Auto: Same
  "eliza_be1_full_cas_001":                "eliza_be1_full_cas_001",                # Auto: Same
  "eliza_be1_full_cas_002":                "eliza_be1_full_cas_002",                # Auto: Same
  "eliza_be1_full_cas_003":                "eliza_be1_full_cas_003",                # Auto: Same
  "eliza_be1_full_gym_001":                "eliza_be1_full_gym_001",                # Auto: Same
  "eliza_be1_full_gym_002":                "eliza_be1_full_gym_002",                # Auto: Same
  "eliza_be1_full_gym_003":                "eliza_be1_full_gym_003",                # Auto: Same
  "eliza_be1_full_naked_001":              "eliza_be1_full_naked_001",              # Auto: Same
  "eliza_be1_full_naked_002":              "eliza_be1_full_naked_002",              # Auto: Same
  "eliza_be1_full_naked_003":              "eliza_be1_full_naked_003",              # Auto: Same
  "eliza_be1_full_under_001":              "eliza_be1_full_under_001",              # Auto: Same
  "eliza_be1_full_under_002":              "eliza_be1_full_under_002",              # Auto: Same
  "eliza_be1_full_under_003":              "eliza_be1_full_under_003",              # Auto: Same
  "eliza_be1_gym_001":                     "eliza_be1_gym_001",                     # Auto: Same
  "eliza_be1_gym_002":                     "eliza_be1_gym_002",                     # Auto: Same
  "eliza_be1_gym_003":                     "eliza_be1_gym_003",                     # Auto: Same
  "eliza_be1_naked_001":                   "eliza_be1_naked_001",                   # Auto: Same
  "eliza_be1_naked_002":                   "eliza_be1_naked_002",                   # Auto: Same
  "eliza_be1_naked_003":                   "eliza_be1_naked_003",                   # Auto: Same
  "eliza_be1_under_001":                   "eliza_be1_under_001",                   # Auto: Same
  "eliza_be1_under_002":                   "eliza_be1_under_002",                   # Auto: Same
  "eliza_be1_under_003":                   "eliza_be1_under_003",                   # Auto: Same
  "eliza_be2_001":                         "eliza_be2_001",                         # Auto: Same
  "eliza_be2_002":                         "eliza_be2_002",                         # Auto: Same
  "eliza_be2_003":                         "eliza_be2_003",                         # Auto: Same
  "eliza_be2_cas_001":                     "eliza_be2_cas_001",                     # Auto: Same
  "eliza_be2_cas_002":                     "eliza_be2_cas_002",                     # Auto: Same
  "eliza_be2_cas_003":                     "eliza_be2_cas_003",                     # Auto: Same
  "eliza_be2_full_001":                    "eliza_be2_full_001",                    # Auto: Same
  "eliza_be2_full_002":                    "eliza_be2_full_002",                    # Auto: Same
  "eliza_be2_full_003":                    "eliza_be2_full_003",                    # Auto: Same
  "eliza_be2_full_cas_001":                "eliza_be2_full_cas_001",                # Auto: Same
  "eliza_be2_full_cas_002":                "eliza_be2_full_cas_002",                # Auto: Same
  "eliza_be2_full_cas_003":                "eliza_be2_full_cas_003",                # Auto: Same
  "eliza_be2_full_gym_001":                "eliza_be2_full_gym_001",                # Auto: Same
  "eliza_be2_full_gym_002":                "eliza_be2_full_gym_002",                # Auto: Same
  "eliza_be2_full_gym_003":                "eliza_be2_full_gym_003",                # Auto: Same
  "eliza_be2_full_naked_001":              "eliza_be2_full_naked_001",              # Auto: Same
  "eliza_be2_full_naked_002":              "eliza_be2_full_naked_002",              # Auto: Same
  "eliza_be2_full_naked_003":              "eliza_be2_full_naked_003",              # Auto: Same
  "eliza_be2_full_under_001":              "eliza_be2_full_under_001",              # Auto: Same
  "eliza_be2_full_under_002":              "eliza_be2_full_under_002",              # Auto: Same
  "eliza_be2_full_under_003":              "eliza_be2_full_under_003",              # Auto: Same
  "eliza_be2_gym_001":                     "eliza_be2_gym_001",                     # Auto: Same
  "eliza_be2_gym_002":                     "eliza_be2_gym_002",                     # Auto: Same
  "eliza_be2_gym_003":                     "eliza_be2_gym_003",                     # Auto: Same
  "eliza_be2_naked_001":                   "eliza_be2_naked_001",                   # Auto: Same
  "eliza_be2_naked_002":                   "eliza_be2_naked_002",                   # Auto: Same
  "eliza_be2_naked_003":                   "eliza_be2_naked_003",                   # Auto: Same
  "eliza_be2_under_001":                   "eliza_be2_under_001",                   # Auto: Same
  "eliza_be2_under_002":                   "eliza_be2_under_002",                   # Auto: Same
  "eliza_be2_under_003":                   "eliza_be2_under_003",                   # Auto: Same
  "eliza_base_001":                        "eliza_base_001",                        # Auto: Edited
  "eliza_base_002":                        "eliza_base_002",                        # Auto: Edited
  "eliza_base_003":                        "eliza_base_003",                        # Auto: Edited
  "eliza_base_cas_001":                    "eliza_base_cas_001",                    # Auto: Edited
  "eliza_base_cas_002":                    "eliza_base_cas_002",                    # Auto: Edited
  "eliza_base_cas_003":                    "eliza_base_cas_003",                    # Auto: Edited
  "eliza_base_full_001":                   "eliza_base_full_001",                   # Auto: Same
  "eliza_base_full_002":                   "eliza_base_full_002",                   # Auto: Same
  "eliza_base_full_003":                   "eliza_base_full_003",                   # Auto: Same
  "eliza_base_full_cas_001":               "eliza_base_full_cas_001",               # Auto: Same
  "eliza_base_full_cas_002":               "eliza_base_full_cas_002",               # Auto: Same
  "eliza_base_full_cas_003":               "eliza_base_full_cas_003",               # Auto: Same
  "eliza_base_full_gym_001":               "eliza_base_full_gym_001",               # Auto: Same
  "eliza_base_full_gym_002":               "eliza_base_full_gym_002",               # Auto: Same
  "eliza_base_full_gym_003":               "eliza_base_full_gym_003",               # Auto: Same
  "eliza_base_full_naked_001":             "eliza_base_full_naked_001",             # Auto: Same
  "eliza_base_full_naked_002":             "eliza_base_full_naked_002",             # Auto: Same
  "eliza_base_full_naked_003":             "eliza_base_full_naked_003",             # Auto: Edited
  "eliza_base_full_under_001":             "eliza_base_full_under_001",             # Auto: Same
  "eliza_base_full_under_002":             "eliza_base_full_under_002",             # Auto: Same
  "eliza_base_full_under_003":             "eliza_base_full_under_003",             # Auto: Same
  "eliza_base_gym_001":                    "eliza_base_gym_001",                    # Auto: Edited
  "eliza_base_gym_002":                    "eliza_base_gym_002",                    # Auto: Edited
  "eliza_base_gym_003":                    "eliza_base_gym_003",                    # Auto: Edited
  "eliza_base_naked_001":                  "eliza_base_naked_001",                  # Auto: Edited
  "eliza_base_naked_002":                  "eliza_base_naked_002",                  # Auto: Edited
  "eliza_base_naked_003":                  "eliza_base_naked_003",                  # Auto: Edited
  "eliza_base_under_001":                  "eliza_base_under_001",                  # Auto: Edited
  "eliza_base_under_002":                  "eliza_base_under_002",                  # Auto: Edited
  "eliza_base_under_003":                  "eliza_base_under_003",                  # Auto: Edited
  "eliza_ex_001_001":                      "eliza_ex_001_001",                      # Auto: Same
  "eliza_ex_001_neutral_001":              "eliza_ex_001_neutral_001",              # Auto: Same
  "eliza_ex_001_smile_001":                "eliza_ex_001_smile_001",                # Auto: Same
  "eliza_ex_002_001":                      "eliza_ex_002_smile_001",                # Auto: Renamed
  "eliza_ex_002_smile_001":                "eliza_ex_002_001",                      # Auto: Renamed
  "eliza_ex_003_001":                      "eliza_ex_003_open2_001",                # Auto: Renamed
  "eliza_ex_003_grin2_001":                "eliza_ex_003_grin2_001",                # Auto: Same
  "eliza_ex_003_grin_001":                 "eliza_ex_003_grin_001",                 # Auto: Same
  "eliza_ex_003_open_001":                 "eliza_ex_003_open_001",                 # Auto: Same
  "eliza_ex_004_001":                      "eliza_ex_004_open_001",                 # Auto: Renamed
  "eliza_ex_004_closed_001":               "eliza_ex_004_001",                      # Auto: Renamed
  "eliza_ex_004_smile_001":                "eliza_ex_004_smile_001",                # Auto: Same
  "eliza_ex_005_001":                      "eliza_ex_005_open_001",                 # Auto: Renamed
  "eliza_ex_005_closed_001":               "eliza_ex_005_001",                      # Auto: Renamed
  "eliza_ex_006_001":                      "eliza_ex_003_001",                      # Auto: Renamed
  "eliza_ex_007_001":                      "eliza_ex_001_smile2_001",               # Auto: Renamed
  "eliza_ex_008_001":                      "eliza_ex_005_aroused_001",              # Manual
  "eliza_ex_008_smile_001":                "eliza_ex_005_aroused2_001",             # Auto: Renamed
  "eliza_ex_009_002":                      "eliza_ex_009_closed_002",               # Auto: Renamed
  "eliza_ex_010_002":                      "eliza_ex_010_002",                      # Auto: Same
  "eliza_ex_011_002":                      "eliza_ex_012_002",                      # Auto: Renamed
  "eliza_ex_012_002":                      "eliza_ex_015_002",                      # Auto: Renamed
  "eliza_ex_013_002":                      "eliza_ex_014_002",                      # Auto: Renamed
  "eliza_ex_014_002":                      "eliza_ex_013_002",                      # Auto: Renamed
  "eliza_ex_015_002":                      "eliza_ex_014_daze_002",                 # Auto: Renamed
  "eliza_ex_016_002":                      "eliza_ex_014_daze2_002",                # Auto: Renamed
  "eliza_ex_017_003":                      "eliza_ex_003_irked_003",                # Auto: Renamed
  "eliza_ex_018_003":                      "eliza_ex_011_003",                      # Auto: Renamed
  "eliza_ex_019_003":                      "eliza_ex_016_003",                      # Auto: Renamed
  "eliza_ex_020_003":                      "eliza_ex_008_003",                      # Auto: Renamed
  "eliza_ex_021_003":                      "eliza_ex_007_open_003",                 # Auto: Renamed
  "eliza_ex_022_003":                      "eliza_ex_009_open_003",                 # Auto: Renamed
  "eliza_ex_full_001_001":                 "eliza_ex_full_001_001",                 # Auto: Same
  "eliza_ex_full_001_neutral_001":         "eliza_ex_full_001_neutral_001",         # Auto: Same
  "eliza_ex_full_001_smile_001":           "eliza_ex_full_001_smile_001",           # Auto: Same
  "eliza_ex_full_002_001":                 "eliza_ex_full_002_smile_001",           # Auto: Renamed
  "eliza_ex_full_002_smile_001":           "eliza_ex_full_002_001",                 # Auto: Renamed
  "eliza_ex_full_003_001":                 "eliza_ex_full_003_open2_001",           # Auto: Renamed
  "eliza_ex_full_003_grin2_001":           "eliza_ex_full_003_grin2_001",           # Auto: Same
  "eliza_ex_full_003_grin_001":            "eliza_ex_full_003_grin_001",            # Auto: Same
  "eliza_ex_full_003_open_001":            "eliza_ex_full_003_open_001",            # Auto: Same
  "eliza_ex_full_004_001":                 "eliza_ex_full_004_open_001",            # Auto: Renamed
  "eliza_ex_full_004_closed_001":          "eliza_ex_full_004_001",                 # Auto: Renamed
  "eliza_ex_full_004_smile_001":           "eliza_ex_full_004_smile_001",           # Auto: Same
  "eliza_ex_full_005_001":                 "eliza_ex_full_005_open_001",            # Auto: Renamed
  "eliza_ex_full_005_closed_001":          "eliza_ex_full_005_001",                 # Auto: Renamed
  "eliza_ex_full_006_001":                 "eliza_ex_full_003_001",                 # Auto: Renamed
  "eliza_ex_full_007_001":                 "eliza_ex_full_001_smile2_001",          # Auto: Renamed
  "eliza_ex_full_008_001":                 "eliza_ex_full_005_aroused_001",         # Manual
  "eliza_ex_full_008_smile_001":           "eliza_ex_full_005_aroused2_001",        # Auto: Renamed
  "eliza_ex_full_009_002":                 "eliza_ex_full_009_closed_002",          # Auto: Renamed
  "eliza_ex_full_010_002":                 "eliza_ex_full_010_002",                 # Auto: Same
  "eliza_ex_full_011_002":                 "eliza_ex_full_012_002",                 # Auto: Renamed
  "eliza_ex_full_012_002":                 "eliza_ex_full_015_002",                 # Auto: Renamed
  "eliza_ex_full_013_002":                 "eliza_ex_full_014_002",                 # Auto: Renamed
  "eliza_ex_full_014_002":                 "eliza_ex_full_013_002",                 # Auto: Renamed
  "eliza_ex_full_015_002":                 "eliza_ex_full_014_daze_002",            # Auto: Renamed
  "eliza_ex_full_016_002":                 "eliza_ex_full_014_daze2_002",           # Auto: Renamed
  "eliza_ex_full_017_003":                 "eliza_ex_full_003_irked_003",           # Auto: Renamed
  "eliza_ex_full_018_003":                 "eliza_ex_full_011_003",                 # Auto: Renamed
  "eliza_ex_full_019_003":                 "eliza_ex_full_016_003",                 # Auto: Renamed
  "eliza_ex_full_020_003":                 "eliza_ex_full_008_003",                 # Auto: Renamed
  "eliza_ex_full_021_003":                 "eliza_ex_full_007_open_003",            # Auto: Renamed
  "eliza_ex_full_022_003":                 "eliza_ex_full_009_open_003",            # Auto: Renamed
  "eliza_mut_full_pigtails_001":           "eliza_mut_full_pigtails_001",           # Auto: Same
  "eliza_mut_full_pigtails_002":           "eliza_mut_full_pigtails_002",           # Auto: Same
  "eliza_mut_full_pigtails_003":           "eliza_mut_full_pigtails_003",           # Auto: Same
  "eliza_mut_full_short_001":              "eliza_mut_full_short_001",              # Auto: Same
  "eliza_mut_full_short_002":              "eliza_mut_full_short_002",              # Auto: Same
  "eliza_mut_full_short_003":              "eliza_mut_full_short_003",              # Auto: Edited
  "eliza_mut_pigtails_001":                "eliza_mut_pigtails_001",                # Auto: Edited
  "eliza_mut_pigtails_002":                "eliza_mut_pigtails_002",                # Auto: Same
  "eliza_mut_pigtails_003":                "eliza_mut_pigtails_003",                # Auto: Edited
  "eliza_mut_short_001":                   "eliza_mut_short_001",                   # Auto: Same
  "eliza_mut_short_002":                   "eliza_mut_short_002",                   # Auto: Same
  "eliza_mut_short_003":                   "eliza_mut_short_003",                   # Auto: Edited
}
