characterMapMother = {
  "Mother_Base_001":                       "Mother_Base_001",                       # Auto: Edited
  "Mother_Base_002":                       "Mother_Base_002",                       # Auto: Edited
  "Mother_Base_Cas_001":                   "Mother_Base_Cas_001",                   # Auto: Edited
  "Mother_Base_Cas_002":                   "Mother_Base_Cas_002",                   # Auto: Edited
  "Mother_Base_Dress_001":                 "Mother_Base_Dress_001",                 # Auto: Edited
  "Mother_Base_Dress_002":                 "Mother_Base_Dress_002",                 # Auto: Edited
  "Mother_Base_Full_001":                  "Mother_Base_Full_001",                  # Auto: Same
  "Mother_Base_Full_002":                  "Mother_Base_Full_002",                  # Auto: Same
  "Mother_Base_Full_Cas_001":              "Mother_Base_Full_Cas_001",              # Auto: Same
  "Mother_Base_Full_Cas_002":              "Mother_Base_Full_Cas_002",              # Auto: Same
  "Mother_Base_Full_Dress_001":            "Mother_Base_Full_Dress_001",            # Auto: Same
  "Mother_Base_Full_Dress_002":            "Mother_Base_Full_Dress_002",            # Auto: Same
  "Mother_Base_Full_Gym_001":              "Mother_Base_Full_Gym_001",              # Auto: Same
  "Mother_Base_Full_Gym_002":              "Mother_Base_Full_Gym_002",              # Auto: Same
  "Mother_Base_Full_Naked_001":            "Mother_Base_Full_Naked_001",            # Auto: Same
  "Mother_Base_Full_Naked_002":            "Mother_Base_Full_Naked_002",            # Auto: Same
  "Mother_Base_Full_Preg_001":             "Mother_Base_Full_Preg_001",             # Auto: Same
  "Mother_Base_Full_Preg_002":             "Mother_Base_Full_Preg_002",             # Auto: Same
  "Mother_Base_Full_Suit_001":             "Mother_Base_Full_Suit_001",             # Auto: Same
  "Mother_Base_Full_Suit_002":             "Mother_Base_Full_Suit_002",             # Auto: Same
  "Mother_Base_Full_Train_001":            "Mother_Base_Full_Fit_001",              # Auto: Renamed
  "Mother_Base_Full_Train_002":            "Mother_Base_Full_Fit_002",              # Auto: Renamed
  "Mother_Base_Full_Under_001":            "Mother_Base_Full_Under_001",            # Auto: Same
  "Mother_Base_Full_Under_002":            "Mother_Base_Full_Under_002",            # Auto: Same
  "Mother_Base_Gym_001":                   "Mother_Base_Gym_001",                   # Auto: Edited
  "Mother_Base_Gym_002":                   "Mother_Base_Gym_002",                   # Auto: Edited
  "Mother_Base_Naked_001":                 "Mother_Base_Naked_001",                 # Auto: Edited
  "Mother_Base_Naked_002":                 "Mother_Base_Naked_002",                 # Auto: Edited
  "Mother_Base_Preg_001":                  "Mother_Base_Preg_001",                  # Auto: Edited
  "Mother_Base_Preg_002":                  "Mother_Base_Preg_002",                  # Auto: Edited
  "Mother_Base_Suit_001":                  "Mother_Base_Suit_001",                  # Auto: Edited
  "Mother_Base_Suit_002":                  "Mother_Base_Suit_002",                  # Auto: Edited
  "Mother_Base_Train_001":                 "",                                      # Auto: Deleted
  "Mother_Base_Train_002":                 "",                                      # Auto: Deleted
  "Mother_Base_Under_001":                 "Mother_Base_Under_001",                 # Auto: Edited
  "Mother_Base_Under_002":                 "Mother_Base_Under_002",                 # Auto: Edited
  "Mother_Ex_001_001":                     "Mother_Ex_001_001",                     # Auto: Edited
  "Mother_Ex_001_Neutral_001":             "Mother_Ex_001_Neutral_001",             # Auto: Edited
  "Mother_Ex_001_Smile2_001":              "Mother_Ex_001_Smile2_001",              # Auto: Edited
  "Mother_Ex_001_Smile_001":               "Mother_Ex_001_Smile_001",               # Auto: Edited
  "Mother_Ex_002_001":                     "",                                      # Auto: Deleted
  "Mother_Ex_003_001":                     "Mother_Ex_003_001",                     # Auto: Edited
  "Mother_Ex_003_Grin2_001":               "Mother_Ex_003_Grin2_001",               # Auto: Edited
  "Mother_Ex_003_Grin3_001":               "Mother_Ex_003_Grin3_001",               # Auto: Edited
  "Mother_Ex_003_Grin_001":                "Mother_Ex_003_Grin_001",                # Auto: Edited
  "Mother_Ex_003_Open2_001":               "Mother_Ex_003_Open2_001",               # Auto: Edited
  "Mother_Ex_003_Open_001":                "Mother_Ex_003_Open_001",                # Auto: Edited
  "Mother_Ex_004_001":                     "",                                      # Auto: Deleted
  "Mother_Ex_004_Open_001":                "",                                      # Auto: Deleted
  "Mother_Ex_004_Smile2_001":              "",                                      # Auto: Deleted
  "Mother_Ex_004_Smile_001":               "",                                      # Auto: Deleted
  "Mother_Ex_005_001":                     "",                                      # Auto: Deleted
  "Mother_Ex_006_002":                     "Mother_Ex_006_002",                     # Auto: Edited
  "Mother_Ex_006_Open_002":                "Mother_Ex_006_Open_002",                # Auto: Edited
  "Mother_Ex_006_Smile_002":               "Mother_Ex_006_Smile_002",               # Auto: Edited
  "Mother_Ex_007_002":                     "Mother_Ex_007_002",                     # Auto: Edited
  "Mother_Ex_008_002":                     "Mother_Ex_008_002",                     # Auto: Edited
  "Mother_Ex_009_002":                     "Mother_Ex_009_002",                     # Auto: Edited
  "Mother_Ex_009_Closed_002":              "Mother_Ex_009_Closed_002",              # Auto: Edited
  "Mother_Ex_009_Smile_002":               "",                                      # Auto: Deleted
  "Mother_Ex_010_002":                     "Mother_Ex_010_002",                     # Auto: Edited
  "Mother_Ex_011_002":                     "Mother_Ex_011_002",                     # Auto: Edited
  "Mother_Ex_012_002":                     "Mother_Ex_012_002",                     # Auto: Edited
  "Mother_Ex_013_002":                     "",                                      # Auto: Deleted
  "Mother_Ex_Full_001_001":                "Mother_Ex_Full_001_001",                # Auto: Same
  "Mother_Ex_Full_001_Neutral_001":        "Mother_Ex_Full_001_Neutral_001",        # Auto: Same
  "Mother_Ex_Full_001_Smile2_001":         "Mother_Ex_Full_001_Smile_001",          # Auto: Renamed
  "Mother_Ex_Full_001_Smile_001":          "Mother_Ex_Full_001_Smile2_001",         # Auto: Renamed
  "Mother_Ex_Full_002_001":                "",                                      # Auto: Deleted
  "Mother_Ex_Full_003_001":                "Mother_Ex_Full_003_001",                # Auto: Same
  "Mother_Ex_Full_003_Grin2_001":          "Mother_Ex_Full_003_Grin2_001",          # Auto: Same
  "Mother_Ex_Full_003_Grin3_001":          "Mother_Ex_Full_003_Grin3_001",          # Auto: Same
  "Mother_Ex_Full_003_Grin_001":           "Mother_Ex_Full_003_Grin_001",           # Auto: Same
  "Mother_Ex_Full_003_Open2_001":          "Mother_Ex_Full_003_Open2_001",          # Auto: Same
  "Mother_Ex_Full_003_Open_001":           "Mother_Ex_Full_003_Open_001",           # Auto: Same
  "Mother_Ex_Full_004_001":                "",                                      # Auto: Deleted
  "Mother_Ex_Full_004_Open_001":           "",                                      # Auto: Deleted
  "Mother_Ex_Full_004_Smile2_001":         "",                                      # Auto: Deleted
  "Mother_Ex_Full_004_Smile_001":          "",                                      # Auto: Deleted
  "Mother_Ex_Full_005_001":                "",                                      # Auto: Deleted
  "Mother_Ex_Full_006_002":                "Mother_Ex_Full_005_002",                # Auto: Renamed
  "Mother_Ex_Full_006_Open_002":           "Mother_Ex_Full_005_Open_002",           # Auto: Renamed
  "Mother_Ex_Full_006_Smile_002":          "Mother_Ex_Full_005_Smile2_002",         # Auto: Renamed
  "Mother_Ex_Full_007_002":                "Mother_Ex_Full_008_Open_002",           # Auto: Renamed
  "Mother_Ex_Full_008_002":                "Mother_Ex_Full_009_Closed_002",         # Auto: Renamed
  "Mother_Ex_Full_009_002":                "Mother_Ex_Full_004_Open_002",           # Auto: Renamed
  "Mother_Ex_Full_009_Closed_002":         "Mother_Ex_Full_004_002",                # Auto: Renamed
  "Mother_Ex_Full_009_Smile_002":          "Mother_Ex_Full_004_Smile_002",          # Auto: Renamed
  "Mother_Ex_Full_010_002":                "Mother_Ex_Full_004_Open2_002",          # Auto: Renamed
  "Mother_Ex_Full_011_002":                "Mother_Ex_Full_009_002",                # Auto: Renamed
  "Mother_Ex_Full_012_002":                "Mother_Ex_Full_011_002",                # Auto: Renamed
  "Mother_Ex_Full_013_002":                "Mother_Ex_Full_012_002",                # Auto: Renamed
}
