characterMapApril = {
  "April_Base_001":                        "April_Base_001",                        # Auto: Edited
  "April_Base_002":                        "April_Base_002",                        # Auto: Edited
  "April_Base_Male_001":                   "April_Base_Male_001",                   # Auto: Edited
  "April_Base_Naked_001":                  "April_Base_Naked_001",                  # Auto: Edited
  "April_Base_Naked_002":                  "April_Base_Naked_002",                  # Auto: Edited
  "April_Base_Night_001":                  "April_Base_Night_001",                  # Auto: Edited
  "April_Base_Night_002":                  "April_Base_Night_002",                  # Auto: Edited
  "April_Ex_001_001":                      "April_Ex_001_001",                      # Auto: Edited
  "April_Ex_001_Smile_001":                "April_Ex_001_Smile_001",                # Auto: Edited
  "April_Ex_002_001":                      "April_Ex_002_001",                      # Auto: Edited
  "April_Ex_003_001":                      "April_Ex_003_001",                      # Auto: Edited
  "April_Ex_004_001":                      "April_Ex_004_001",                      # Auto: Edited
  "April_Ex_004_Open_001":                 "April_Ex_004_Open_001",                 # Auto: Edited
  "April_Ex_005_001":                      "April_Ex_005_001",                      # Auto: Edited
  "April_Ex_005_Grin2_001":                "",                                      # Auto: Deleted
  "April_Ex_005_Grin_001":                 "",                                      # Auto: Deleted
  "April_Ex_006_001":                      "April_Ex_006_001",                      # Auto: Edited
  "April_Ex_007_001":                      "",                                      # Auto: Deleted
  "April_Ex_008_001":                      "",                                      # Auto: Deleted
  "April_Ex_008_Smile_001":                "",                                      # Auto: Deleted
  "April_Ex_009_002":                      "April_Ex_009_002",                      # Auto: Edited
  "April_Ex_010_002":                      "April_Ex_010_002",                      # Auto: Edited
  "April_Ex_011_002":                      "April_Ex_011_002",                      # Auto: Edited
  "April_Ex_012_002":                      "April_Ex_012_002",                      # Auto: Edited
  "April_Ex_013_002":                      "",                                      # Auto: Deleted
  "April_Ex_014_002":                      "",                                      # Auto: Deleted
  "April_Ex_015_002":                      "",                                      # Auto: Deleted
  "April_Ex_Male_001_001":                 "April_Ex_Male_001_001",                 # Auto: Edited
  "April_Ex_Male_002_001":                 "April_Ex_Male_002_001",                 # Auto: Edited
  "April_Ex_Male_003_001":                 "April_Ex_Male_003_001",                 # Auto: Edited
  "April_Ex_Male_004_001":                 "April_Ex_Male_004_001",                 # Auto: Edited
  "April_Ex_Male_005_001":                 "April_Ex_Male_005_001",                 # Auto: Edited
  "April_Ex_Male_006_001":                 "April_Ex_Male_006_001",                 # Auto: Edited
  "April_Ex_Male_007_001":                 "April_Ex_Male_007_001",                 # Auto: Edited
  "April_Ex_Male_008_001":                 "April_Ex_Male_008_001",                 # Auto: Edited
  "April_Ex_Male_009_001":                 "April_Ex_Male_009_001",                 # Auto: Edited
  "April_Ex_Male_010_001":                 "April_Ex_Male_010_001",                 # Auto: Edited
  "April_Ex_Male_011_001":                 "April_Ex_Male_011_001",                 # Auto: Edited
  "April_Ex_Male_012_001":                 "April_Ex_Male_012_001",                 # Auto: Edited
  "April_Ex_Male_013_001":                 "",                                      # Auto: Deleted
  "April_Ex_Male_014_001":                 "",                                      # Auto: Deleted
  "April_Ex_Male_015_001":                 "",                                      # Auto: Deleted
  "April_Misc_Night_Reveal":               "",                                      # Auto: Deleted
  "April_Mut_Naked_Skirt_001":             "",                                      # Auto: Deleted
  "April_Mut_Naked_Skirt_002":             "",                                      # Auto: Deleted
}
