characterMapErin = {
  "Erin_Base_001":                         "Erin_Base_001",                         # Auto: Edited
  "Erin_Base_002":                         "Erin_Base_002",                         # Auto: Edited
  "Erin_Base_003":                         "Erin_Base_003",                         # Auto: Edited
  "Erin_Base_Fit_001":                     "Erin_Base_Fit_001",                     # Auto: Edited
  "Erin_Base_Fit_002":                     "Erin_Base_Fit_002",                     # Auto: Edited
  "Erin_Base_Fit_003":                     "Erin_Base_Fit_003",                     # Auto: Edited
  "Erin_Base_Full_001":                    "Erin_Base_Full_001",                    # Auto: Edited
  "Erin_Base_Full_002":                    "Erin_Base_Full_002",                    # Auto: Edited
  "Erin_Base_Full_003":                    "Erin_Base_Full_003",                    # Auto: Edited
  "Erin_Base_Full_Fit_001":                "Erin_Base_Full_Fit_001",                # Auto: Edited
  "Erin_Base_Full_Fit_002":                "Erin_Base_Full_Fit_002",                # Auto: Edited
  "Erin_Base_Full_Fit_003":                "Erin_Base_Full_Fit_003",                # Auto: Edited
  "Erin_Base_Full_Naked_001":              "Erin_Base_Full_Naked_001",              # Auto: Edited
  "Erin_Base_Full_Naked_002":              "Erin_Base_Full_Naked_002",              # Auto: Edited
  "Erin_Base_Full_Naked_003":              "Erin_Base_Full_Naked_003",              # Auto: Edited
  "Erin_Base_Full_Swim_001":               "Erin_Base_Full_Swim_001",               # Auto: Edited
  "Erin_Base_Full_Swim_002":               "Erin_Base_Full_Swim_002",               # Auto: Edited
  "Erin_Base_Full_Swim_003":               "Erin_Base_Full_Swim_003",               # Auto: Edited
  "Erin_Base_Full_Under_001":              "Erin_Base_Full_Under_001",              # Auto: Edited
  "Erin_Base_Full_Under_002":              "Erin_Base_Full_Under_002",              # Auto: Edited
  "Erin_Base_Full_Under_003":              "Erin_Base_Full_Under_003",              # Auto: Edited
  "Erin_Base_Naked_001":                   "Erin_Base_Naked_001",                   # Auto: Edited
  "Erin_Base_Naked_002":                   "Erin_Base_Naked_002",                   # Auto: Edited
  "Erin_Base_Naked_003":                   "Erin_Base_Naked_003",                   # Auto: Edited
  "Erin_Base_Swim_001":                    "Erin_Base_Swim_001",                    # Auto: Edited
  "Erin_Base_Swim_002":                    "Erin_Base_Swim_002",                    # Auto: Edited
  "Erin_Base_Swim_003":                    "Erin_Base_Swim_003",                    # Auto: Edited
  "Erin_Base_Under_001":                   "Erin_Base_Under_001",                   # Auto: Edited
  "Erin_Base_Under_002":                   "Erin_Base_Under_002",                   # Auto: Edited
  "Erin_Base_Under_003":                   "Erin_Base_Under_003",                   # Auto: Edited
  "Erin_Ex_001_001":                       "Erin_Ex_001_001",                       # Auto: Edited
  "Erin_Ex_002_001":                       "Erin_Ex_002_001",                       # Auto: Edited
  "Erin_Ex_002_Smile_001":                 "Erin_Ex_002_Smile_001",                 # Auto: Edited
  "Erin_Ex_003_001":                       "Erin_Ex_003_001",                       # Auto: Edited
  "Erin_Ex_003_Smile_001":                 "",                                      # Auto: Deleted
  "Erin_Ex_004_001":                       "Erin_Ex_004_001",                       # Auto: Edited
  "Erin_Ex_005_001":                       "Erin_Ex_005_001",                       # Auto: Edited
  "Erin_Ex_005_Grin2_001":                 "",                                      # Auto: Deleted
  "Erin_Ex_005_Grin_001":                  "",                                      # Auto: Deleted
  "Erin_Ex_005_Open_001":                  "Erin_Ex_005_Open_001",                  # Auto: Edited
  "Erin_Ex_006_001":                       "Erin_Ex_006_001",                       # Auto: Edited
  "Erin_Ex_006_Smile_001":                 "Erin_Ex_006_Smile_001",                 # Auto: Edited
  "Erin_Ex_007_001":                       "",                                      # Auto: Deleted
  "Erin_Ex_008_001":                       "",                                      # Auto: Deleted
  "Erin_Ex_008_Open_001":                  "",                                      # Auto: Deleted
  "Erin_Ex_008_Smile2_001":                "",                                      # Auto: Deleted
  "Erin_Ex_008_Smile_001":                 "",                                      # Auto: Deleted
  "Erin_Ex_009_001":                       "",                                      # Auto: Deleted
  "Erin_Ex_010_001":                       "",                                      # Auto: Deleted
  "Erin_Ex_011_002":                       "Erin_Ex_011_002",                       # Auto: Edited
  "Erin_Ex_012_002":                       "",                                      # Auto: Deleted
  "Erin_Ex_013_002":                       "Erin_Ex_013_002",                       # Auto: Edited
  "Erin_Ex_014_002":                       "Erin_Ex_014_002",                       # Auto: Edited
  "Erin_Ex_014_Closed_002":                "",                                      # Auto: Deleted
  "Erin_Ex_015_002":                       "",                                      # Auto: Deleted
  "Erin_Ex_016_002":                       "",                                      # Auto: Deleted
  "Erin_Ex_017_002":                       "",                                      # Auto: Deleted
  "Erin_Ex_018_002":                       "",                                      # Auto: Deleted
  "Erin_Ex_019_002":                       "",                                      # Auto: Deleted
  "Erin_Ex_020_003":                       "Erin_Ex_020_003",                       # Auto: Edited
  "Erin_Ex_021_003":                       "",                                      # Auto: Deleted
  "Erin_Ex_022_003":                       "",                                      # Auto: Deleted
  "Erin_Ex_023_003":                       "",                                      # Auto: Deleted
  "Erin_Ex_024_003":                       "",                                      # Auto: Deleted
  "Erin_Ex_025_003":                       "",                                      # Auto: Deleted
  "Erin_Ex_026_003":                       "",                                      # Auto: Deleted
  "Erin_Ex_027_003":                       "",                                      # Auto: Deleted
  "Erin_Ex_028_003":                       "",                                      # Auto: Deleted
  "Erin_Ex_029_003":                       "",                                      # Auto: Deleted
  "Erin_Ex_030_003":                       "",                                      # Auto: Deleted
  "Erin_Ex_Full_001_001":                  "Erin_Ex_Full_001_001",                  # Auto: Edited
  "Erin_Ex_Full_002_001":                  "Erin_Ex_Full_002_001",                  # Auto: Edited
  "Erin_Ex_Full_002_Smile_001":            "Erin_Ex_Full_002_Smile_001",            # Auto: Edited
  "Erin_Ex_Full_003_001":                  "Erin_Ex_Full_003_001",                  # Auto: Edited
  "Erin_Ex_Full_003_Smile_001":            "",                                      # Auto: Deleted
  "Erin_Ex_Full_004_001":                  "Erin_Ex_Full_004_001",                  # Auto: Edited
  "Erin_Ex_Full_005_001":                  "Erin_Ex_Full_005_001",                  # Auto: Edited
  "Erin_Ex_Full_005_Grin2_001":            "",                                      # Auto: Deleted
  "Erin_Ex_Full_005_Grin_001":             "",                                      # Auto: Deleted
  "Erin_Ex_Full_005_Open_001":             "Erin_Ex_Full_005_Open_001",             # Auto: Edited
  "Erin_Ex_Full_006_001":                  "Erin_Ex_Full_006_001",                  # Auto: Edited
  "Erin_Ex_Full_006_Smile_001":            "Erin_Ex_Full_006_Smile_001",            # Auto: Edited
  "Erin_Ex_Full_007_001":                  "",                                      # Auto: Deleted
  "Erin_Ex_Full_008_001":                  "",                                      # Auto: Deleted
  "Erin_Ex_Full_008_Open_001":             "",                                      # Auto: Deleted
  "Erin_Ex_Full_008_Smile2_001":           "",                                      # Auto: Deleted
  "Erin_Ex_Full_008_Smile_001":            "",                                      # Auto: Deleted
  "Erin_Ex_Full_009_001":                  "",                                      # Auto: Deleted
  "Erin_Ex_Full_010_001":                  "",                                      # Auto: Deleted
  "Erin_Ex_Full_011_002":                  "Erin_Ex_Full_011_002",                  # Auto: Edited
  "Erin_Ex_Full_012_002":                  "",                                      # Auto: Deleted
  "Erin_Ex_Full_013_002":                  "Erin_Ex_Full_013_002",                  # Auto: Edited
  "Erin_Ex_Full_014_002":                  "Erin_Ex_Full_014_002",                  # Auto: Edited
  "Erin_Ex_Full_014_Closed_002":           "",                                      # Auto: Deleted
  "Erin_Ex_Full_015_002":                  "",                                      # Auto: Deleted
  "Erin_Ex_Full_016_002":                  "",                                      # Auto: Deleted
  "Erin_Ex_Full_017_002":                  "",                                      # Auto: Deleted
  "Erin_Ex_Full_018_002":                  "",                                      # Auto: Deleted
  "Erin_Ex_Full_019_002":                  "",                                      # Auto: Deleted
  "Erin_Ex_Full_020_003":                  "Erin_Ex_Full_020_003",                  # Auto: Edited
  "Erin_Ex_Full_021_003":                  "",                                      # Auto: Deleted
  "Erin_Ex_Full_022_003":                  "",                                      # Auto: Deleted
  "Erin_Ex_Full_023_003":                  "",                                      # Auto: Deleted
  "Erin_Ex_Full_024_003":                  "",                                      # Auto: Deleted
  "Erin_Ex_Full_025_003":                  "",                                      # Auto: Deleted
  "Erin_Ex_Full_026_003":                  "",                                      # Auto: Deleted
  "Erin_Ex_Full_026_Clean_003":            "",                                      # Auto: Deleted
  "Erin_Ex_Full_027_003":                  "",                                      # Auto: Deleted
  "Erin_Ex_Full_028_003":                  "",                                      # Auto: Deleted
  "Erin_Ex_Full_029_003":                  "",                                      # Auto: Deleted
  "Erin_Ex_Full_030_003":                  "",                                      # Auto: Deleted
}
