characterMapMika = {
  "Mika_Base_001":                         "Mika_Base_001",                         # Auto: Edited
  "Mika_Base_002":                         "Mika_Base_002",                         # Auto: Edited
  "Mika_Base_Cas_001":                     "Mika_Base_Cas_001",                     # Auto: Edited
  "Mika_Base_Cas_002":                     "Mika_Base_Cas_002",                     # Auto: Edited
  "Mika_Base_Fit_001":                     "Mika_Base_Fit_001",                     # Auto: Edited
  "Mika_Base_Fit_002":                     "Mika_Base_Fit_002",                     # Auto: Edited
  "Mika_Base_Full_001":                    "Mika_Base_Full_001",                    # Auto: Same
  "Mika_Base_Full_002":                    "Mika_Base_Full_002",                    # Auto: Same
  "Mika_Base_Full_Cas_001":                "Mika_Base_Full_Cas_001",                # Auto: Same
  "Mika_Base_Full_Cas_002":                "Mika_Base_Full_Cas_002",                # Auto: Same
  "Mika_Base_Full_Fit_001":                "Mika_Base_Full_Fit_001",                # Auto: Same
  "Mika_Base_Full_Fit_002":                "Mika_Base_Full_Fit_002",                # Auto: Same
  "Mika_Base_Full_Gym_001":                "Mika_Base_Full_Gym_001",                # Auto: Same
  "Mika_Base_Full_Gym_002":                "Mika_Base_Full_Gym_002",                # Auto: Same
  "Mika_Base_Full_Naked_001":              "Mika_Base_Full_Naked_001",              # Auto: Same
  "Mika_Base_Full_Naked_002":              "Mika_Base_Full_Naked_002",              # Auto: Same
  "Mika_Base_Full_Preg_001":               "Mika_Base_Full_Preg_001",               # Auto: Same
  "Mika_Base_Full_Preg_002":               "Mika_Base_Full_Preg_002",               # Auto: Same
  "Mika_Base_Full_Sailor_001":             "Mika_Base_Full_Sailor_001",             # Auto: Same
  "Mika_Base_Full_Sailor_002":             "Mika_Base_Full_Sailor_002",             # Auto: Same
  "Mika_Base_Full_Swim_001":               "Mika_Base_Full_Swim_001",               # Auto: Same
  "Mika_Base_Full_Swim_002":               "Mika_Base_Full_Swim_002",               # Auto: Same
  "Mika_Base_Full_Trench_001":             "Mika_Base_Full_Trench_001",             # Auto: Same
  "Mika_Base_Full_Trench_002":             "Mika_Base_Full_Trench_002",             # Auto: Same
  "Mika_Base_Full_Under_001":              "Mika_Base_Full_Under_001",              # Auto: Same
  "Mika_Base_Full_Under_002":              "Mika_Base_Full_Under_002",              # Auto: Same
  "Mika_Base_Gym_001":                     "Mika_Base_Gym_001",                     # Auto: Edited
  "Mika_Base_Gym_002":                     "Mika_Base_Gym_002",                     # Auto: Edited
  "Mika_Base_Male_001":                    "Mika_Base_Male_001",                    # Auto: Edited
  "Mika_Base_Naked_001":                   "Mika_Base_Naked_001",                   # Auto: Edited
  "Mika_Base_Naked_002":                   "Mika_Base_Naked_002",                   # Auto: Edited
  "Mika_Base_O_001":                       "",                                      # Auto: Deleted
  "Mika_Base_O_002":                       "",                                      # Auto: Deleted
  "Mika_Base_O_Naked_001":                 "",                                      # Auto: Deleted
  "Mika_Base_O_Naked_002":                 "",                                      # Auto: Deleted
  "Mika_Base_Preg_001":                    "Mika_Base_Preg_001",                    # Auto: Edited
  "Mika_Base_Preg_002":                    "Mika_Base_Preg_002",                    # Auto: Edited
  "Mika_Base_Sailor_001":                  "Mika_Base_Sailor_001",                  # Auto: Edited
  "Mika_Base_Sailor_002":                  "Mika_Base_Sailor_002",                  # Auto: Edited
  "Mika_Base_Swim_001":                    "Mika_Base_Swim_001",                    # Auto: Edited
  "Mika_Base_Swim_002":                    "Mika_Base_Swim_002",                    # Auto: Edited
  "Mika_Base_Trench_001":                  "Mika_Base_Trench_001",                  # Auto: Edited
  "Mika_Base_Trench_002":                  "Mika_Base_Trench_002",                  # Auto: Edited
  "Mika_Base_Under_001":                   "Mika_Base_Under_001",                   # Auto: Edited
  "Mika_Base_Under_002":                   "Mika_Base_Under_002",                   # Auto: Edited
  "Mika_Ex_001_001":                       "Mika_Ex_001_001",                       # Auto: Same
  "Mika_Ex_001_Neutral_001":               "Mika_Ex_001_Neutral_001",               # Auto: Same
  "Mika_Ex_001_Open_001":                  "Mika_Ex_001_Open_001",                  # Auto: Same
  "Mika_Ex_001_Smile_001":                 "Mika_Ex_001_Smile_001",                 # Auto: Same
  "Mika_Ex_002_001":                       "Mika_Ex_002_Smile_001",                 # Auto: Renamed
  "Mika_Ex_002_Open_001":                  "Mika_Ex_002_Open_001",                  # Auto: Same
  "Mika_Ex_002_Smile_001":                 "Mika_Ex_002_001",                       # Auto: Renamed
  "Mika_Ex_003_001":                       "Mika_Ex_003_001",                       # Auto: Same
  "Mika_Ex_003_Grin2_001":                 "Mika_Ex_003_Grin2_001",                 # Auto: Same
  "Mika_Ex_003_Grin_001":                  "Mika_Ex_003_Grin_001",                  # Auto: Same
  "Mika_Ex_003_Grit_001":                  "Mika_Ex_003_Grit_001",                  # Auto: Same
  "Mika_Ex_003_Irked2_001":                "Mika_Ex_003_Irked2_001",                # Auto: Same
  "Mika_Ex_003_Irked_001":                 "Mika_Ex_003_Irked_001",                 # Auto: Same
  "Mika_Ex_003_Open2_001":                 "Mika_Ex_003_Open2_001",                 # Auto: Same
  "Mika_Ex_003_Open_001":                  "Mika_Ex_003_Open_001",                  # Auto: Same
  "Mika_Ex_004_001":                       "Mika_Ex_004_Open_001",                  # Auto: Renamed
  "Mika_Ex_004_Closed_001":                "Mika_Ex_004_001",                       # Auto: Renamed
  "Mika_Ex_004_Smile_001":                 "Mika_Ex_004_Smile_001",                 # Auto: Same
  "Mika_Ex_005_001":                       "Mika_Ex_005_001",                       # Auto: Same
  "Mika_Ex_005_Aroused_001":               "Mika_Ex_005_Aroused_001",               # Auto: Same
  "Mika_Ex_005_Open_001":                  "Mika_Ex_005_Open_001",                  # Auto: Same
  "Mika_Ex_005_Smile2_001":                "Mika_Ex_005_Smile2_001",                # Auto: Same
  "Mika_Ex_005_Smile_001":                 "Mika_Ex_005_Smile_001",                 # Auto: Same
  "Mika_Ex_006_001":                       "Mika_Ex_006_001",                       # Auto: Same
  "Mika_Ex_006_Open_001":                  "Mika_Ex_006_Open_001",                  # Auto: Same
  "Mika_Ex_006_Smile2_001":                "Mika_Ex_006_Smile2_001",                # Auto: Same
  "Mika_Ex_006_Smile_001":                 "Mika_Ex_006_Smile_001",                 # Auto: Same
  "Mika_Ex_006_Wink_001":                  "Mika_Ex_006_Wink_001",                  # Auto: Same
  "Mika_Ex_007_002":                       "Mika_Ex_007_Open_002",                  # Auto: Renamed
  "Mika_Ex_008_002":                       "Mika_Ex_008_Open_002",                  # Auto: Renamed
  "Mika_Ex_009_002":                       "Mika_Ex_009_002",                       # Auto: Same
  "Mika_Ex_010_002":                       "Mika_Ex_010_002",                       # Auto: Same
  "Mika_Ex_011_002":                       "Mika_Ex_009_Closed_002",                # Auto: Renamed
  "Mika_Ex_012_002":                       "Mika_Ex_011_002",                       # Auto: Renamed
  "Mika_Ex_013_002":                       "Mika_Ex_012_002",                       # Auto: Renamed
  "Mika_Ex_Full_001_001":                  "Mika_Ex_Full_001_001",                  # Auto: Same
  "Mika_Ex_Full_001_Neutral_001":          "Mika_Ex_Full_001_Neutral_001",          # Auto: Same
  "Mika_Ex_Full_001_Open_001":             "Mika_Ex_Full_001_Open_001",             # Auto: Same
  "Mika_Ex_Full_001_Smile_001":            "Mika_Ex_Full_001_Smile_001",            # Auto: Same
  "Mika_Ex_Full_002_001":                  "Mika_Ex_Full_002_Smile_001",            # Auto: Renamed
  "Mika_Ex_Full_002_Open_001":             "Mika_Ex_Full_002_Open_001",             # Auto: Same
  "Mika_Ex_Full_002_Smile_001":            "Mika_Ex_Full_002_001",                  # Auto: Renamed
  "Mika_Ex_Full_003_001":                  "Mika_Ex_Full_003_001",                  # Auto: Same
  "Mika_Ex_Full_003_Grin2_001":            "Mika_Ex_Full_003_Grin2_001",            # Auto: Same
  "Mika_Ex_Full_003_Grin_001":             "Mika_Ex_Full_003_Grin_001",             # Auto: Same
  "Mika_Ex_Full_003_Grit_001":             "Mika_Ex_Full_003_Grit_001",             # Auto: Same
  "Mika_Ex_Full_003_Irked2_001":           "Mika_Ex_Full_003_Irked2_001",           # Auto: Same
  "Mika_Ex_Full_003_Irked_001":            "Mika_Ex_Full_003_Irked_001",            # Auto: Same
  "Mika_Ex_Full_003_Open2_001":            "Mika_Ex_Full_003_Open2_001",            # Auto: Same
  "Mika_Ex_Full_003_Open_001":             "Mika_Ex_Full_003_Open_001",             # Auto: Same
  "Mika_Ex_Full_004_001":                  "Mika_Ex_Full_004_Open_001",             # Auto: Renamed
  "Mika_Ex_Full_004_Closed_001":           "Mika_Ex_Full_004_001",                  # Auto: Renamed
  "Mika_Ex_Full_004_Smile_001":            "Mika_Ex_Full_004_Smile_001",            # Auto: Same
  "Mika_Ex_Full_005_001":                  "Mika_Ex_Full_005_001",                  # Auto: Same
  "Mika_Ex_Full_005_Aroused_001":          "Mika_Ex_Full_005_Aroused_001",          # Auto: Same
  "Mika_Ex_Full_005_Open_001":             "Mika_Ex_Full_005_Open_001",             # Auto: Same
  "Mika_Ex_Full_005_Smile2_001":           "Mika_Ex_Full_005_Smile2_001",           # Auto: Same
  "Mika_Ex_Full_005_Smile_001":            "Mika_Ex_Full_005_Smile_001",            # Auto: Same
  "Mika_Ex_Full_006_001":                  "Mika_Ex_Full_006_001",                  # Auto: Same
  "Mika_Ex_Full_006_Open_001":             "Mika_Ex_Full_006_Open_001",             # Auto: Same
  "Mika_Ex_Full_006_Smile2_001":           "Mika_Ex_Full_006_Smile2_001",           # Auto: Same
  "Mika_Ex_Full_006_Smile_001":            "Mika_Ex_Full_006_Smile_001",            # Auto: Same
  "Mika_Ex_Full_006_Wink_001":             "Mika_Ex_Full_006_Wink_001",             # Auto: Same
  "Mika_Ex_Full_007_002":                  "Mika_Ex_Full_007_Open_002",             # Auto: Renamed
  "Mika_Ex_Full_008_002":                  "Mika_Ex_Full_008_Open_002",             # Auto: Renamed
  "Mika_Ex_Full_009_002":                  "Mika_Ex_Full_009_002",                  # Auto: Same
  "Mika_Ex_Full_010_002":                  "Mika_Ex_Full_010_002",                  # Auto: Same
  "Mika_Ex_Full_011_002":                  "Mika_Ex_Full_009_Closed_002",           # Auto: Renamed
  "Mika_Ex_Full_012_002":                  "Mika_Ex_Full_011_002",                  # Auto: Renamed
  "Mika_Ex_Full_013_002":                  "Mika_Ex_Full_012_002",                  # Auto: Renamed
  "Mika_Ex_Male_001_001":                  "Mika_Ex_Male_001_001",                  # Auto: Edited
  "Mika_Ex_Male_002_001":                  "Mika_Ex_Male_002_001",                  # Auto: Edited
  "Mika_Ex_Male_003_001":                  "Mika_Ex_Male_003_001",                  # Auto: Edited
  "Mika_Ex_Male_004_001":                  "Mika_Ex_Male_004_001",                  # Auto: Edited
  "Mika_Ex_Male_004_Grin_001":             "",                                      # Auto: Deleted
  "Mika_Ex_Male_005_001":                  "Mika_Ex_Male_005_001",                  # Auto: Edited
  "Mika_Ex_Male_006_001":                  "Mika_Ex_Male_006_001",                  # Auto: Edited
  "Mika_Ex_Male_007_001":                  "Mika_Ex_Male_007_001",                  # Auto: Edited
  "Mika_Ex_Male_008_001":                  "Mika_Ex_Male_008_001",                  # Auto: Edited
  "Mika_Ex_Male_009_001":                  "Mika_Ex_Male_009_001",                  # Auto: Edited
  "Mika_Ex_Male_010_001":                  "Mika_Ex_Male_010_001",                  # Auto: Edited
  "Mika_Ex_Male_011_001":                  "Mika_Ex_Male_011_001",                  # Auto: Edited
  "Mika_Ex_O_001_001":                     "",                                      # Auto: Deleted
  "Mika_Ex_O_002_001":                     "",                                      # Auto: Deleted
  "Mika_Ex_O_003_001":                     "",                                      # Auto: Deleted
  "Mika_Ex_O_004_001":                     "",                                      # Auto: Deleted
  "Mika_Ex_O_005_001":                     "",                                      # Auto: Deleted
  "Mika_Ex_O_006_001":                     "",                                      # Auto: Deleted
  "Mika_Ex_O_007_001":                     "",                                      # Auto: Deleted
  "Mika_Ex_O_008_002":                     "",                                      # Auto: Deleted
  "Mika_Ex_O_009_002":                     "",                                      # Auto: Deleted
  "Mika_Ex_O_010_002":                     "",                                      # Auto: Deleted
  "Mika_Ex_O_011_002":                     "",                                      # Auto: Deleted
  "Mika_Ex_O_012_002":                     "",                                      # Auto: Deleted
  "Mika_Ex_O_013_002":                     "",                                      # Auto: Deleted
}
