characterMapJillian = {
  "Jillian_Base_001":                      "Jillian_Base_001",                      # Auto: Edited
  "Jillian_Base_002":                      "Jillian_Base_002",                      # Auto: Edited
  "Jillian_Base_Dom_001":                  "",                                      # Auto: Deleted
  "Jillian_Base_Dom_002":                  "",                                      # Auto: Deleted
  "Jillian_Base_Dom_Opened_001":           "",                                      # Auto: Deleted
  "Jillian_Base_Dom_Opened_002":           "",                                      # Auto: Deleted
  "Jillian_Base_Full_001":                 "Jillian_Base_Full_001",                 # Auto: Edited
  "Jillian_Base_Full_002":                 "Jillian_Base_Full_002",                 # Auto: Edited
  "Jillian_Base_Full_Dom_001":             "",                                      # Auto: Deleted
  "Jillian_Base_Full_Dom_002":             "",                                      # Auto: Deleted
  "Jillian_Base_Full_Dom_Opened_001":      "",                                      # Auto: Deleted
  "Jillian_Base_Full_Dom_Opened_002":      "",                                      # Auto: Deleted
  "Jillian_Base_Full_Maid_001":            "Jillian_Base_Full_Maid_001",            # Auto: Edited
  "Jillian_Base_Full_Maid_002":            "Jillian_Base_Full_Maid_002",            # Auto: Edited
  "Jillian_Base_Full_Maid_Opened_001":     "",                                      # Auto: Deleted
  "Jillian_Base_Full_Maid_Opened_002":     "",                                      # Auto: Deleted
  "Jillian_Base_Full_Naked_001":           "Jillian_Base_Full_Naked_001",           # Auto: Edited
  "Jillian_Base_Full_Naked_002":           "Jillian_Base_Full_Naked_002",           # Auto: Edited
  "Jillian_Base_Full_Opened_001":          "",                                      # Auto: Deleted
  "Jillian_Base_Full_Opened_002":          "",                                      # Auto: Deleted
  "Jillian_Base_Full_Preg_001":            "Jillian_Base_Full_Preg_001",            # Auto: Edited
  "Jillian_Base_Full_Preg_002":            "Jillian_Base_Full_Preg_002",            # Auto: Edited
  "Jillian_Base_Full_Under_001":           "Jillian_Base_Full_Under_001",           # Auto: Edited
  "Jillian_Base_Full_Under_002":           "Jillian_Base_Full_Under_002",           # Auto: Edited
  "Jillian_Base_Maid_001":                 "Jillian_Base_Maid_001",                 # Auto: Edited
  "Jillian_Base_Maid_002":                 "Jillian_Base_Maid_002",                 # Auto: Edited
  "Jillian_Base_Maid_Opened_001":          "",                                      # Auto: Deleted
  "Jillian_Base_Maid_Opened_002":          "",                                      # Auto: Deleted
  "Jillian_Base_Naked_001":                "Jillian_Base_Naked_001",                # Auto: Edited
  "Jillian_Base_Naked_002":                "Jillian_Base_Naked_002",                # Auto: Edited
  "Jillian_Base_Opened_001":               "",                                      # Auto: Deleted
  "Jillian_Base_Opened_002":               "",                                      # Auto: Deleted
  "Jillian_Base_Preg_001":                 "Jillian_Base_Preg_001",                 # Auto: Edited
  "Jillian_Base_Preg_002":                 "Jillian_Base_Preg_002",                 # Auto: Edited
  "Jillian_Base_Under_001":                "Jillian_Base_Under_001",                # Auto: Edited
  "Jillian_Base_Under_002":                "Jillian_Base_Under_002",                # Auto: Edited
  "Jillian_Ex_001_001":                    "Jillian_Ex_001_001",                    # Auto: Edited
  "Jillian_Ex_001_Neutral_001":            "Jillian_Ex_001_Neutral_001",            # Auto: Edited
  "Jillian_Ex_001_Smile_001":              "Jillian_Ex_001_Smile_001",              # Auto: Edited
  "Jillian_Ex_002_001":                    "Jillian_Ex_002_001",                    # Auto: Edited
  "Jillian_Ex_002_Smile_001":              "Jillian_Ex_002_Smile_001",              # Auto: Edited
  "Jillian_Ex_003_001":                    "Jillian_Ex_003_001",                    # Auto: Edited
  "Jillian_Ex_003_Grin2_001":              "Jillian_Ex_003_Grin2_001",              # Auto: Edited
  "Jillian_Ex_003_Grin_001":               "Jillian_Ex_003_Grin_001",               # Auto: Edited
  "Jillian_Ex_003_Open2_001":              "Jillian_Ex_003_Open2_001",              # Auto: Edited
  "Jillian_Ex_003_Open_001":               "Jillian_Ex_003_Open_001",               # Auto: Edited
  "Jillian_Ex_004_001":                    "Jillian_Ex_004_001",                    # Auto: Edited
  "Jillian_Ex_004_Closed_001":             "",                                      # Auto: Deleted
  "Jillian_Ex_004_Smile_001":              "Jillian_Ex_004_Smile_001",              # Auto: Edited
  "Jillian_Ex_005_001":                    "Jillian_Ex_005_001",                    # Auto: Edited
  "Jillian_Ex_005_Open_001":               "Jillian_Ex_005_Open_001",               # Auto: Edited
  "Jillian_Ex_005_Smile2_001":             "Jillian_Ex_005_Smile2_001",             # Auto: Edited
  "Jillian_Ex_005_Smile_001":              "Jillian_Ex_005_Smile_001",              # Auto: Edited
  "Jillian_Ex_006_001":                    "Jillian_Ex_006_001",                    # Auto: Edited
  "Jillian_Ex_006_Open_001":               "Jillian_Ex_006_Open_001",               # Auto: Edited
  "Jillian_Ex_006_Smile2_001":             "Jillian_Ex_006_Smile2_001",             # Auto: Edited
  "Jillian_Ex_006_Smile_001":              "Jillian_Ex_006_Smile_001",              # Auto: Edited
  "Jillian_Ex_007_001":                    "",                                      # Auto: Deleted
  "Jillian_Ex_008_001":                    "",                                      # Auto: Deleted
  "Jillian_Ex_009_001":                    "",                                      # Auto: Deleted
  "Jillian_Ex_010_002":                    "",                                      # Auto: Deleted
  "Jillian_Ex_011_002":                    "",                                      # Auto: Deleted
  "Jillian_Ex_012_002":                    "Jillian_Ex_012_002",                    # Auto: Edited
  "Jillian_Ex_013_002":                    "Jillian_Ex_013_002",                    # Auto: Edited
  "Jillian_Ex_014_002":                    "",                                      # Auto: Deleted
  "Jillian_Ex_015_002":                    "",                                      # Auto: Deleted
  "Jillian_Ex_016_002":                    "",                                      # Auto: Deleted
  "Jillian_Ex_017_002":                    "",                                      # Auto: Deleted
  "Jillian_Ex_Full_001_001":               "Jillian_Ex_Full_001_001",               # Auto: Edited
  "Jillian_Ex_Full_001_Neutral_001":       "Jillian_Ex_Full_001_Neutral_001",       # Auto: Edited
  "Jillian_Ex_Full_001_Smile_001":         "Jillian_Ex_Full_001_Smile_001",         # Auto: Edited
  "Jillian_Ex_Full_002_001":               "Jillian_Ex_Full_002_001",               # Auto: Edited
  "Jillian_Ex_Full_002_Smile_001":         "Jillian_Ex_Full_002_Smile_001",         # Auto: Edited
  "Jillian_Ex_Full_003_001":               "Jillian_Ex_Full_003_001",               # Auto: Edited
  "Jillian_Ex_Full_003_Grin2_001":         "Jillian_Ex_Full_003_Grin2_001",         # Auto: Edited
  "Jillian_Ex_Full_003_Grin_001":          "Jillian_Ex_Full_003_Grin_001",          # Auto: Edited
  "Jillian_Ex_Full_003_Open2_001":         "Jillian_Ex_Full_003_Open2_001",         # Auto: Edited
  "Jillian_Ex_Full_003_Open_001":          "Jillian_Ex_Full_003_Open_001",          # Auto: Edited
  "Jillian_Ex_Full_004_001":               "Jillian_Ex_Full_004_001",               # Auto: Edited
  "Jillian_Ex_Full_004_Closed_001":        "",                                      # Auto: Deleted
  "Jillian_Ex_Full_004_Smile_001":         "Jillian_Ex_Full_004_Smile_001",         # Auto: Edited
  "Jillian_Ex_Full_005_001":               "Jillian_Ex_Full_005_001",               # Auto: Edited
  "Jillian_Ex_Full_005_Open_001":          "Jillian_Ex_Full_005_Open_001",          # Auto: Edited
  "Jillian_Ex_Full_005_Smile2_001":        "Jillian_Ex_Full_005_Smile2_001",        # Auto: Edited
  "Jillian_Ex_Full_005_Smile_001":         "Jillian_Ex_Full_005_Smile_001",         # Auto: Edited
  "Jillian_Ex_Full_006_001":               "Jillian_Ex_Full_006_001",               # Auto: Edited
  "Jillian_Ex_Full_006_Open_001":          "Jillian_Ex_Full_006_Open_001",          # Auto: Edited
  "Jillian_Ex_Full_006_Smile2_001":        "Jillian_Ex_Full_006_Smile2_001",        # Auto: Edited
  "Jillian_Ex_Full_006_Smile_001":         "Jillian_Ex_Full_006_Smile_001",         # Auto: Edited
  "Jillian_Ex_Full_007_001":               "",                                      # Auto: Deleted
  "Jillian_Ex_Full_008_001":               "",                                      # Auto: Deleted
  "Jillian_Ex_Full_009_001":               "",                                      # Auto: Deleted
  "Jillian_Ex_Full_010_002":               "",                                      # Auto: Deleted
  "Jillian_Ex_Full_011_002":               "",                                      # Auto: Deleted
  "Jillian_Ex_Full_012_002":               "Jillian_Ex_Full_012_002",               # Auto: Edited
  "Jillian_Ex_Full_013_002":               "Jillian_Ex_Full_013_002",               # Auto: Edited
  "Jillian_Ex_Full_014_002":               "",                                      # Auto: Deleted
  "Jillian_Ex_Full_015_002":               "",                                      # Auto: Deleted
  "Jillian_Ex_Full_016_002":               "",                                      # Auto: Deleted
  "Jillian_Ex_Full_017_002":               "",                                      # Auto: Deleted
}
