characterMapChris = {
  "Chris_Base_Full_Naked_001":             "Chris_Base_Full_Naked_001",             # Auto: Edited
  "Chris_Base_Full_Naked_002":             "Chris_Base_Full_Naked_002",             # Auto: Edited
  "Chris_Base_Full_Naked_003":             "Chris_Base_Full_Naked_003",             # Auto: Edited
  "Chris_Base_Full_Punk_001":              "Chris_Base_Full_Punk_001",              # Auto: Edited
  "Chris_Base_Full_Punk_002":              "Chris_Base_Full_Punk_002",              # Auto: Edited
  "Chris_Base_Full_Punk_003":              "Chris_Base_Full_Punk_003",              # Auto: Edited
  "Chris_Base_Full_School_001":            "Chris_Base_Full_School_001",            # Auto: Edited
  "Chris_Base_Full_School_002":            "Chris_Base_Full_School_002",            # Auto: Edited
  "Chris_Base_Full_School_003":            "Chris_Base_Full_School_003",            # Auto: Edited
  "Chris_Base_Full_Under_001":             "Chris_Base_Full_Under_001",             # Auto: Edited
  "Chris_Base_Full_Under_002":             "Chris_Base_Full_Under_002",             # Auto: Edited
  "Chris_Base_Full_Under_003":             "Chris_Base_Full_Under_003",             # Auto: Edited
  "Chris_Base_Naked_001":                  "Chris_Base_Naked_001",                  # Auto: Edited
  "Chris_Base_Naked_002":                  "Chris_Base_Naked_002",                  # Auto: Edited
  "Chris_Base_Naked_003":                  "Chris_Base_Naked_003",                  # Auto: Edited
  "Chris_Base_Punk_001":                   "Chris_Base_Punk_001",                   # Auto: Edited
  "Chris_Base_Punk_002":                   "Chris_Base_Punk_002",                   # Auto: Edited
  "Chris_Base_Punk_003":                   "Chris_Base_Punk_003",                   # Auto: Edited
  "Chris_Base_School_001":                 "Chris_Base_School_001",                 # Auto: Edited
  "Chris_Base_School_002":                 "Chris_Base_School_002",                 # Auto: Edited
  "Chris_Base_School_003":                 "Chris_Base_School_003",                 # Auto: Edited
  "Chris_Base_Under_001":                  "Chris_Base_Under_001",                  # Auto: Edited
  "Chris_Base_Under_002":                  "Chris_Base_Under_002",                  # Auto: Edited
  "Chris_Base_Under_003":                  "Chris_Base_Under_003",                  # Auto: Edited
  "Chris_Ex_001_001":                      "Chris_Ex_001_001",                      # Auto: Edited
  "Chris_Ex_001_Smile_001":                "Chris_Ex_001_Smile_001",                # Auto: Edited
  "Chris_Ex_002_001":                      "Chris_Ex_002_001",                      # Auto: Edited
  "Chris_Ex_002_Smile_001":                "Chris_Ex_002_Smile_001",                # Auto: Edited
  "Chris_Ex_003_001":                      "Chris_Ex_003_001",                      # Auto: Edited
  "Chris_Ex_004_001":                      "Chris_Ex_004_001",                      # Auto: Edited
  "Chris_Ex_005_001":                      "Chris_Ex_005_001",                      # Auto: Edited
  "Chris_Ex_005_Smile_001":                "Chris_Ex_005_Smile_001",                # Auto: Edited
  "Chris_Ex_006_001":                      "Chris_Ex_006_001",                      # Auto: Edited
  "Chris_Ex_007_001":                      "Chris_Ex_007_001",                      # Auto: Edited
  "Chris_Ex_007_Smile_001":                "Chris_Ex_007_Smile_001",                # Auto: Edited
  "Chris_Ex_008_002":                      "",                                      # Auto: Deleted
  "Chris_Ex_009_002":                      "Chris_Ex_009_002",                      # Auto: Edited
  "Chris_Ex_010_002":                      "Chris_Ex_010_002",                      # Auto: Edited
  "Chris_Ex_011_002":                      "Chris_Ex_011_002",                      # Auto: Edited
  "Chris_Ex_011_Grin2_002":                "",                                      # Auto: Deleted
  "Chris_Ex_011_Grin_002":                 "",                                      # Auto: Deleted
  "Chris_Ex_011_Open_002":                 "",                                      # Auto: Deleted
  "Chris_Ex_012_002":                      "Chris_Ex_012_002",                      # Auto: Edited
  "Chris_Ex_013_002":                      "Chris_Ex_013_002",                      # Auto: Edited
  "Chris_Ex_014_002":                      "Chris_Ex_014_002",                      # Auto: Edited
  "Chris_Ex_014_Open_002":                 "",                                      # Auto: Deleted
  "Chris_Ex_014_Smile2_002":               "",                                      # Auto: Deleted
  "Chris_Ex_014_Smile_002":                "",                                      # Auto: Deleted
  "Chris_Ex_015_002":                      "Chris_Ex_015_002",                      # Auto: Edited
  "Chris_Ex_016_002":                      "Chris_Ex_016_002",                      # Auto: Edited
  "Chris_Ex_016_Closed_002":               "",                                      # Auto: Deleted
  "Chris_Ex_017_002":                      "Chris_Ex_017_002",                      # Auto: Edited
  "Chris_Ex_018_002":                      "Chris_Ex_018_002",                      # Auto: Edited
  "Chris_Ex_019_003":                      "",                                      # Auto: Deleted
  "Chris_Ex_020_003":                      "Chris_Ex_020_003",                      # Auto: Edited
  "Chris_Ex_021_003":                      "Chris_Ex_021_003",                      # Auto: Edited
  "Chris_Ex_022_003":                      "Chris_Ex_022_003",                      # Auto: Edited
  "Chris_Ex_023_003":                      "Chris_Ex_023_003",                      # Auto: Edited
  "Chris_Ex_024_003":                      "Chris_Ex_024_003",                      # Auto: Edited
  "Chris_Ex_025_003":                      "Chris_Ex_025_003",                      # Auto: Edited
  "Chris_Ex_026_003":                      "Chris_Ex_026_003",                      # Auto: Edited
  "Chris_Ex_027_003":                      "",                                      # Auto: Deleted
  "Chris_Ex_028_003":                      "",                                      # Auto: Deleted
  "Chris_Ex_029_003":                      "",                                      # Auto: Deleted
  "Chris_Ex_030_003":                      "",                                      # Auto: Deleted
  "Chris_Ex_Full_001_001":                 "Chris_Ex_Full_001_001",                 # Auto: Edited
  "Chris_Ex_Full_001_Smile_001":           "Chris_Ex_Full_001_Smile_001",           # Auto: Edited
  "Chris_Ex_Full_002_001":                 "Chris_Ex_Full_002_001",                 # Auto: Edited
  "Chris_Ex_Full_002_Smile_001":           "Chris_Ex_Full_002_Smile_001",           # Auto: Edited
  "Chris_Ex_Full_003_001":                 "Chris_Ex_Full_003_001",                 # Auto: Edited
  "Chris_Ex_Full_004_001":                 "Chris_Ex_Full_004_001",                 # Auto: Edited
  "Chris_Ex_Full_005_001":                 "Chris_Ex_Full_005_001",                 # Auto: Edited
  "Chris_Ex_Full_005_Smile_001":           "Chris_Ex_Full_005_Smile_001",           # Auto: Edited
  "Chris_Ex_Full_006_001":                 "Chris_Ex_Full_006_001",                 # Auto: Edited
  "Chris_Ex_Full_007_001":                 "Chris_Ex_Full_007_001",                 # Auto: Edited
  "Chris_Ex_Full_007_Smile_001":           "Chris_Ex_Full_007_Smile_001",           # Auto: Edited
  "Chris_Ex_Full_008_002":                 "",                                      # Auto: Deleted
  "Chris_Ex_Full_009_002":                 "Chris_Ex_Full_009_002",                 # Auto: Edited
  "Chris_Ex_Full_010_002":                 "Chris_Ex_Full_010_002",                 # Auto: Edited
  "Chris_Ex_Full_011_002":                 "Chris_Ex_Full_011_002",                 # Auto: Edited
  "Chris_Ex_Full_011_Grin2_002":           "",                                      # Auto: Deleted
  "Chris_Ex_Full_011_Grin_002":            "",                                      # Auto: Deleted
  "Chris_Ex_Full_011_Open_002":            "",                                      # Auto: Deleted
  "Chris_Ex_Full_012_002":                 "Chris_Ex_Full_012_002",                 # Auto: Edited
  "Chris_Ex_Full_013_002":                 "Chris_Ex_Full_013_002",                 # Auto: Edited
  "Chris_Ex_Full_014_002":                 "Chris_Ex_Full_014_002",                 # Auto: Edited
  "Chris_Ex_Full_014_Open_002":            "",                                      # Auto: Deleted
  "Chris_Ex_Full_014_Smile2_002":          "",                                      # Auto: Deleted
  "Chris_Ex_Full_014_Smile_002":           "",                                      # Auto: Deleted
  "Chris_Ex_Full_015_002":                 "Chris_Ex_Full_015_002",                 # Auto: Edited
  "Chris_Ex_Full_016_002":                 "Chris_Ex_Full_016_002",                 # Auto: Edited
  "Chris_Ex_Full_016_Closed_002":          "",                                      # Auto: Deleted
  "Chris_Ex_Full_017_002":                 "Chris_Ex_Full_017_002",                 # Auto: Edited
  "Chris_Ex_Full_018_002":                 "Chris_Ex_Full_018_002",                 # Auto: Edited
  "Chris_Ex_Full_019_003":                 "",                                      # Auto: Deleted
  "Chris_Ex_Full_020_003":                 "Chris_Ex_Full_020_003",                 # Auto: Edited
  "Chris_Ex_Full_021_003":                 "Chris_Ex_Full_021_003",                 # Auto: Edited
  "Chris_Ex_Full_022_003":                 "Chris_Ex_Full_022_003",                 # Auto: Edited
  "Chris_Ex_Full_023_003":                 "Chris_Ex_Full_023_003",                 # Auto: Edited
  "Chris_Ex_Full_024_003":                 "Chris_Ex_Full_024_003",                 # Auto: Edited
  "Chris_Ex_Full_025_003":                 "Chris_Ex_Full_025_003",                 # Auto: Edited
  "Chris_Ex_Full_026_003":                 "Chris_Ex_Full_026_003",                 # Auto: Edited
  "Chris_Ex_Full_027_003":                 "",                                      # Auto: Deleted
  "Chris_Ex_Full_028_003":                 "",                                      # Auto: Deleted
  "Chris_Ex_Full_029_003":                 "",                                      # Auto: Deleted
  "Chris_Ex_Full_030_003":                 "",                                      # Auto: Deleted
  "Chris_Mut_Full_Hair_001":               "Chris_Mut_Full_Hair_001",               # Auto: Edited
  "Chris_Mut_Full_Hair_002":               "Chris_Mut_Full_Hair_002",               # Auto: Edited
  "Chris_Mut_Full_Hair_003":               "Chris_Mut_Full_Hair_003",               # Auto: Edited
  "Chris_Mut_Full_Naked_Hair_001":         "Chris_Mut_Full_Naked_Hair_001",         # Auto: Edited
  "Chris_Mut_Full_Naked_Hair_002":         "Chris_Mut_Full_Naked_Hair_002",         # Auto: Edited
  "Chris_Mut_Full_Naked_Hair_003":         "Chris_Mut_Full_Naked_Hair_003",         # Auto: Edited
  "Chris_Mut_Full_Punk_Hair_001":          "Chris_Mut_Full_Punk_Hair_001",          # Auto: Edited
  "Chris_Mut_Full_Punk_Hair_002":          "Chris_Mut_Full_Punk_Hair_002",          # Auto: Edited
  "Chris_Mut_Full_Punk_Hair_003":          "Chris_Mut_Full_Punk_Hair_003",          # Auto: Edited
  "Chris_Mut_Full_School_Hair_001":        "Chris_Mut_Full_School_Hair_001",        # Auto: Edited
  "Chris_Mut_Full_School_Hair_002":        "Chris_Mut_Full_School_Hair_002",        # Auto: Edited
  "Chris_Mut_Full_School_Hair_003":        "Chris_Mut_Full_School_Hair_003",        # Auto: Edited
  "Chris_Mut_Full_Under_Hair_001":         "Chris_Mut_Full_Under_Hair_001",         # Auto: Edited
  "Chris_Mut_Full_Under_Hair_002":         "Chris_Mut_Full_Under_Hair_002",         # Auto: Edited
  "Chris_Mut_Full_Under_Hair_003":         "Chris_Mut_Full_Under_Hair_003",         # Auto: Edited
  "Chris_Mut_Hair_001":                    "Chris_Mut_Hair_001",                    # Auto: Edited
  "Chris_Mut_Hair_002":                    "Chris_Mut_Hair_002",                    # Auto: Edited
  "Chris_Mut_Hair_003":                    "Chris_Mut_Hair_003",                    # Auto: Edited
  "Chris_Mut_Naked_Hair_001":              "Chris_Mut_Naked_Hair_001",              # Auto: Edited
  "Chris_Mut_Naked_Hair_002":              "Chris_Mut_Naked_Hair_002",              # Auto: Edited
  "Chris_Mut_Naked_Hair_003":              "Chris_Mut_Naked_Hair_003",              # Auto: Edited
  "Chris_Mut_Punk_Hair_001":               "Chris_Mut_Punk_Hair_001",               # Auto: Edited
  "Chris_Mut_Punk_Hair_002":               "Chris_Mut_Punk_Hair_002",               # Auto: Edited
  "Chris_Mut_Punk_Hair_003":               "Chris_Mut_Punk_Hair_003",               # Auto: Edited
  "Chris_Mut_School_Hair_001":             "Chris_Mut_School_Hair_001",             # Auto: Edited
  "Chris_Mut_School_Hair_002":             "Chris_Mut_School_Hair_002",             # Auto: Edited
  "Chris_Mut_School_Hair_003":             "Chris_Mut_School_Hair_003",             # Auto: Edited
  "Chris_Mut_Under_Hair_001":              "Chris_Mut_Under_Hair_001",              # Auto: Edited
  "Chris_Mut_Under_Hair_002":              "Chris_Mut_Under_Hair_002",              # Auto: Edited
  "Chris_Mut_Under_Hair_003":              "Chris_Mut_Under_Hair_003",              # Auto: Edited
}
