characterMapAnna = {
  "Anna_BE0_Y_001":                        "",                                      # Auto: Deleted
  "Anna_BE0_Y_002":                        "",                                      # Auto: Deleted
  "Anna_BE1_Y_001":                        "",                                      # Auto: Deleted
  "Anna_BE1_Y_002":                        "",                                      # Auto: Deleted
  "Anna_BE1_Y_Naked_001":                  "",                                      # Auto: Deleted
  "Anna_BE1_Y_Naked_002":                  "",                                      # Auto: Deleted
  "Anna_Base_001":                         "Anna_Base_001",                         # Auto: Edited
  "Anna_Base_002":                         "Anna_Base_002",                         # Auto: Edited
  "Anna_Base_Full_001":                    "Anna_Base_Full_001",                    # Auto: Edited
  "Anna_Base_Full_002":                    "Anna_Base_Full_002",                    # Auto: Edited
  "Anna_Base_Y_001":                       "",                                      # Auto: Deleted
  "Anna_Base_Y_002":                       "",                                      # Auto: Deleted
  "Anna_Base_Y_Naked_001":                 "",                                      # Auto: Deleted
  "Anna_Base_Y_Naked_002":                 "",                                      # Auto: Deleted
  "Anna_Ex_001_001":                       "Anna_Ex_001_001",                       # Auto: Edited
  "Anna_Ex_001_Smile_001":                 "Anna_Ex_001_Smile_001",                 # Auto: Edited
  "Anna_Ex_002_001":                       "Anna_Ex_002_001",                       # Auto: Edited
  "Anna_Ex_002_Open_001":                  "Anna_Ex_002_Open_001",                  # Auto: Edited
  "Anna_Ex_003_001":                       "Anna_Ex_003_001",                       # Auto: Edited
  "Anna_Ex_004_001":                       "Anna_Ex_004_001",                       # Auto: Edited
  "Anna_Ex_004_Grin2_001":                 "",                                      # Auto: Deleted
  "Anna_Ex_004_Grin_001":                  "",                                      # Auto: Deleted
  "Anna_Ex_005_001":                       "Anna_Ex_005_001",                       # Auto: Edited
  "Anna_Ex_006_001":                       "Anna_Ex_006_001",                       # Auto: Edited
  "Anna_Ex_006_Open_001":                  "Anna_Ex_006_Open_001",                  # Auto: Edited
  "Anna_Ex_007_001":                       "",                                      # Auto: Deleted
  "Anna_Ex_007_Smile_001":                 "",                                      # Auto: Deleted
  "Anna_Ex_008_002":                       "Anna_Ex_008_002",                       # Auto: Edited
  "Anna_Ex_009_002":                       "Anna_Ex_009_002",                       # Auto: Edited
  "Anna_Ex_010_002":                       "Anna_Ex_010_002",                       # Auto: Edited
  "Anna_Ex_011_002":                       "Anna_Ex_011_002",                       # Auto: Edited
  "Anna_Ex_011_Closed_002":                "",                                      # Auto: Deleted
  "Anna_Ex_012_002":                       "Anna_Ex_012_002",                       # Auto: Edited
  "Anna_Ex_013_002":                       "",                                      # Auto: Deleted
  "Anna_Ex_Full_001_001":                  "Anna_Ex_Full_001_001",                  # Auto: Edited
  "Anna_Ex_Full_002_001":                  "Anna_Ex_Full_002_001",                  # Auto: Edited
  "Anna_Ex_Full_003_001":                  "Anna_Ex_Full_003_001",                  # Auto: Edited
  "Anna_Ex_Full_004_001":                  "Anna_Ex_Full_004_001",                  # Auto: Edited
  "Anna_Ex_Full_005_001":                  "Anna_Ex_Full_005_001",                  # Auto: Edited
  "Anna_Ex_Full_006_001":                  "Anna_Ex_Full_006_001",                  # Auto: Edited
  "Anna_Ex_Full_007_001":                  "",                                      # Auto: Deleted
  "Anna_Ex_Full_008_002":                  "Anna_Ex_Full_008_002",                  # Auto: Edited
  "Anna_Ex_Full_009_002":                  "Anna_Ex_Full_009_002",                  # Auto: Edited
  "Anna_Ex_Full_010_002":                  "Anna_Ex_Full_010_002",                  # Auto: Edited
  "Anna_Ex_Full_011_002":                  "Anna_Ex_Full_011_002",                  # Auto: Edited
  "Anna_Ex_Full_012_002":                  "Anna_Ex_Full_012_002",                  # Auto: Edited
  "Anna_Ex_Full_013_002":                  "",                                      # Auto: Deleted
  "Anna_Ex_Y_001_001":                     "",                                      # Auto: Deleted
  "Anna_Ex_Y_002_001":                     "",                                      # Auto: Deleted
  "Anna_Ex_Y_003_001":                     "",                                      # Auto: Deleted
  "Anna_Ex_Y_004_001":                     "",                                      # Auto: Deleted
  "Anna_Ex_Y_005_001":                     "",                                      # Auto: Deleted
  "Anna_Ex_Y_006_001":                     "",                                      # Auto: Deleted
  "Anna_Ex_Y_007_001":                     "",                                      # Auto: Deleted
  "Anna_Ex_Y_008_002":                     "",                                      # Auto: Deleted
  "Anna_Ex_Y_009_002":                     "",                                      # Auto: Deleted
  "Anna_Ex_Y_010_002":                     "",                                      # Auto: Deleted
  "Anna_Ex_Y_011_002":                     "",                                      # Auto: Deleted
  "Anna_Ex_Y_012_002":                     "",                                      # Auto: Deleted
  "Anna_Ex_Y_013_002":                     "",                                      # Auto: Deleted
}
