characterMapChris = {
  "christine_base_full_hair_001":          "",                                      # Auto: Deleted
  "christine_base_full_hair_002":          "",                                      # Auto: Deleted
  "christine_base_full_hair_003":          "",                                      # Auto: Deleted
  "christine_base_full_hair_naked_001":    "",                                      # Auto: Deleted
  "christine_base_full_hair_naked_002":    "",                                      # Auto: Deleted
  "christine_base_full_hair_naked_003":    "",                                      # Auto: Deleted
  "christine_base_full_hair_punk_001":     "",                                      # Auto: Deleted
  "christine_base_full_hair_punk_002":     "",                                      # Auto: Deleted
  "christine_base_full_hair_punk_003":     "",                                      # Auto: Deleted
  "christine_base_full_hair_school_001":   "",                                      # Auto: Deleted
  "christine_base_full_hair_school_002":   "",                                      # Auto: Deleted
  "christine_base_full_hair_school_003":   "",                                      # Auto: Deleted
  "christine_base_full_hair_under_001":    "",                                      # Auto: Deleted
  "christine_base_full_hair_under_002":    "",                                      # Auto: Deleted
  "christine_base_full_hair_under_003":    "",                                      # Auto: Deleted
  "christine_base_full_naked_001":         "",                                      # Auto: Deleted
  "christine_base_full_naked_002":         "",                                      # Auto: Deleted
  "christine_base_full_naked_003":         "",                                      # Auto: Deleted
  "christine_base_full_punk_001":          "",                                      # Auto: Deleted
  "christine_base_full_punk_002":          "",                                      # Auto: Deleted
  "christine_base_full_punk_003":          "",                                      # Auto: Deleted
  "christine_base_full_school_001":        "",                                      # Auto: Deleted
  "christine_base_full_school_002":        "",                                      # Auto: Deleted
  "christine_base_full_school_003":        "",                                      # Auto: Deleted
  "christine_base_full_under_001":         "",                                      # Auto: Deleted
  "christine_base_full_under_002":         "",                                      # Auto: Deleted
  "christine_base_full_under_003":         "",                                      # Auto: Deleted
  "christine_base_hair_001":               "",                                      # Auto: Deleted
  "christine_base_hair_002":               "",                                      # Auto: Deleted
  "christine_base_hair_003":               "",                                      # Auto: Deleted
  "christine_base_hair_naked_001":         "",                                      # Auto: Deleted
  "christine_base_hair_naked_002":         "",                                      # Auto: Deleted
  "christine_base_hair_naked_003":         "",                                      # Auto: Deleted
  "christine_base_hair_punk_001":          "",                                      # Auto: Deleted
  "christine_base_hair_punk_002":          "",                                      # Auto: Deleted
  "christine_base_hair_punk_003":          "",                                      # Auto: Deleted
  "christine_base_hair_school_001":        "",                                      # Auto: Deleted
  "christine_base_hair_school_002":        "",                                      # Auto: Deleted
  "christine_base_hair_school_003":        "",                                      # Auto: Deleted
  "christine_base_hair_under_001":         "",                                      # Auto: Deleted
  "christine_base_hair_under_002":         "",                                      # Auto: Deleted
  "christine_base_hair_under_003":         "",                                      # Auto: Deleted
  "christine_base_naked_001":              "",                                      # Auto: Deleted
  "christine_base_naked_002":              "",                                      # Auto: Deleted
  "christine_base_naked_003":              "",                                      # Auto: Deleted
  "christine_base_punk_001":               "",                                      # Auto: Deleted
  "christine_base_punk_002":               "",                                      # Auto: Deleted
  "christine_base_punk_003":               "",                                      # Auto: Deleted
  "christine_base_school_001":             "",                                      # Auto: Deleted
  "christine_base_school_002":             "",                                      # Auto: Deleted
  "christine_base_school_003":             "",                                      # Auto: Deleted
  "christine_base_under_001":              "",                                      # Auto: Deleted
  "christine_base_under_002":              "",                                      # Auto: Deleted
  "christine_base_under_003":              "",                                      # Auto: Deleted
  "christine_ex_001":                      "",                                      # Auto: Deleted
  "christine_ex_001_smile":                "",                                      # Auto: Deleted
  "christine_ex_002":                      "",                                      # Auto: Deleted
  "christine_ex_002_smile":                "",                                      # Auto: Deleted
  "christine_ex_003":                      "",                                      # Auto: Deleted
  "christine_ex_004":                      "",                                      # Auto: Deleted
  "christine_ex_005":                      "",                                      # Auto: Deleted
  "christine_ex_005_smile":                "",                                      # Auto: Deleted
  "christine_ex_006":                      "",                                      # Auto: Deleted
  "christine_ex_007":                      "",                                      # Auto: Deleted
  "christine_ex_008":                      "",                                      # Auto: Deleted
  "christine_ex_009":                      "",                                      # Auto: Deleted
  "christine_ex_010":                      "",                                      # Auto: Deleted
  "christine_ex_011":                      "",                                      # Auto: Deleted
  "christine_ex_011_grin":                 "",                                      # Auto: Deleted
  "christine_ex_011_grin2":                "",                                      # Auto: Deleted
  "christine_ex_011_open":                 "",                                      # Auto: Deleted
  "christine_ex_012":                      "",                                      # Auto: Deleted
  "christine_ex_013":                      "",                                      # Auto: Deleted
  "christine_ex_014":                      "",                                      # Auto: Deleted
  "christine_ex_014_open":                 "",                                      # Auto: Deleted
  "christine_ex_015":                      "",                                      # Auto: Deleted
  "christine_ex_016":                      "",                                      # Auto: Deleted
  "christine_ex_017":                      "",                                      # Auto: Deleted
  "christine_ex_018":                      "",                                      # Auto: Deleted
  "christine_ex_019":                      "",                                      # Auto: Deleted
  "christine_ex_020":                      "",                                      # Auto: Deleted
  "christine_ex_021":                      "",                                      # Auto: Deleted
  "christine_ex_022":                      "",                                      # Auto: Deleted
  "christine_ex_023":                      "",                                      # Auto: Deleted
  "christine_ex_024":                      "",                                      # Auto: Deleted
  "christine_ex_025":                      "",                                      # Auto: Deleted
  "christine_ex_026":                      "",                                      # Auto: Deleted
  "christine_ex_027":                      "",                                      # Auto: Deleted
  "christine_ex_028":                      "",                                      # Auto: Deleted
  "christine_ex_029":                      "",                                      # Auto: Deleted
  "christine_ex_030":                      "",                                      # Auto: Deleted
  "christine_ex_full_001":                 "",                                      # Auto: Deleted
  "christine_ex_full_001_smile":           "",                                      # Auto: Deleted
  "christine_ex_full_002":                 "",                                      # Auto: Deleted
  "christine_ex_full_002_smile":           "",                                      # Auto: Deleted
  "christine_ex_full_003":                 "",                                      # Auto: Deleted
  "christine_ex_full_004":                 "",                                      # Auto: Deleted
  "christine_ex_full_005":                 "",                                      # Auto: Deleted
  "christine_ex_full_005_smile":           "",                                      # Auto: Deleted
  "christine_ex_full_006":                 "",                                      # Auto: Deleted
  "christine_ex_full_007":                 "",                                      # Auto: Deleted
  "christine_ex_full_008":                 "",                                      # Auto: Deleted
  "christine_ex_full_009":                 "",                                      # Auto: Deleted
  "christine_ex_full_010":                 "",                                      # Auto: Deleted
  "christine_ex_full_011":                 "",                                      # Auto: Deleted
  "christine_ex_full_011_grin":            "",                                      # Auto: Deleted
  "christine_ex_full_011_grin2":           "",                                      # Auto: Deleted
  "christine_ex_full_011_open":            "",                                      # Auto: Deleted
  "christine_ex_full_012":                 "",                                      # Auto: Deleted
  "christine_ex_full_013":                 "",                                      # Auto: Deleted
  "christine_ex_full_014":                 "",                                      # Auto: Deleted
  "christine_ex_full_014_open":            "",                                      # Auto: Deleted
  "christine_ex_full_015":                 "",                                      # Auto: Deleted
  "christine_ex_full_016":                 "",                                      # Auto: Deleted
  "christine_ex_full_017":                 "",                                      # Auto: Deleted
  "christine_ex_full_018":                 "",                                      # Auto: Deleted
  "christine_ex_full_019":                 "",                                      # Auto: Deleted
  "christine_ex_full_020":                 "",                                      # Auto: Deleted
  "christine_ex_full_021":                 "",                                      # Auto: Deleted
  "christine_ex_full_022":                 "",                                      # Auto: Deleted
  "christine_ex_full_023":                 "",                                      # Auto: Deleted
  "christine_ex_full_024":                 "",                                      # Auto: Deleted
  "christine_ex_full_025":                 "",                                      # Auto: Deleted
  "christine_ex_full_026":                 "",                                      # Auto: Deleted
  "christine_ex_full_027":                 "",                                      # Auto: Deleted
  "christine_ex_full_028":                 "",                                      # Auto: Deleted
  "christine_ex_full_029":                 "",                                      # Auto: Deleted
  "christine_ex_full_030":                 "",                                      # Auto: Deleted
}
