characterMapMichelle = {
  "Michelle_BE1_001":                      "Michelle_BE1_001",                      # Auto: Same
  "Michelle_BE1_002":                      "Michelle_BE1_002",                      # Auto: Same
  "Michelle_BE1_003":                      "Michelle_BE1_003",                      # Auto: Same
  "Michelle_BE1_Full_001":                 "Michelle_BE1_Full_001",                 # Auto: Same
  "Michelle_BE1_Full_002":                 "Michelle_BE1_Full_002",                 # Auto: Same
  "Michelle_BE1_Full_003":                 "Michelle_BE1_Full_003",                 # Auto: Same
  "Michelle_BE1_Full_Naked_001":           "Michelle_BE1_Full_Naked_001",           # Auto: Same
  "Michelle_BE1_Full_Naked_002":           "Michelle_BE1_Full_Naked_002",           # Auto: Same
  "Michelle_BE1_Full_Naked_003":           "Michelle_BE1_Full_Naked_003",           # Auto: Same
  "Michelle_BE1_Naked_001":                "Michelle_BE1_Naked_001",                # Auto: Same
  "Michelle_BE1_Naked_002":                "Michelle_BE1_Naked_002",                # Auto: Same
  "Michelle_BE1_Naked_003":                "Michelle_BE1_Naked_003",                # Auto: Same
  "Michelle_BE2_001":                      "Michelle_BE2_001",                      # Auto: Same
  "Michelle_BE2_002":                      "Michelle_BE2_002",                      # Auto: Same
  "Michelle_BE2_003":                      "Michelle_BE2_003",                      # Auto: Same
  "Michelle_BE2_Cas_001":                  "Michelle_BE2_Cas_001",                  # Auto: Same
  "Michelle_BE2_Cas_002":                  "Michelle_BE2_Cas_002",                  # Auto: Same
  "Michelle_BE2_Cas_003":                  "Michelle_BE2_Cas_003",                  # Auto: Same
  "Michelle_BE2_Full_001":                 "Michelle_BE2_Full_001",                 # Auto: Same
  "Michelle_BE2_Full_002":                 "Michelle_BE2_Full_002",                 # Auto: Same
  "Michelle_BE2_Full_003":                 "Michelle_BE2_Full_003",                 # Auto: Same
  "Michelle_BE2_Full_Cas_001":             "Michelle_BE2_Full_Cas_001",             # Auto: Same
  "Michelle_BE2_Full_Cas_002":             "Michelle_BE2_Full_Cas_002",             # Auto: Same
  "Michelle_BE2_Full_Cas_003":             "Michelle_BE2_Full_Cas_003",             # Auto: Same
  "Michelle_BE2_Full_Gym_001":             "Michelle_BE2_Full_Gym_001",             # Auto: Same
  "Michelle_BE2_Full_Gym_002":             "Michelle_BE2_Full_Gym_002",             # Auto: Same
  "Michelle_BE2_Full_Gym_003":             "Michelle_BE2_Full_Gym_003",             # Auto: Same
  "Michelle_BE2_Full_Naked_001":           "Michelle_BE2_Full_Naked_001",           # Auto: Same
  "Michelle_BE2_Full_Naked_002":           "Michelle_BE2_Full_Naked_002",           # Auto: Same
  "Michelle_BE2_Full_Naked_003":           "Michelle_BE2_Full_Naked_003",           # Auto: Same
  "Michelle_BE2_Full_Nastic_001":          "Michelle_BE2_Full_Nastic_001",          # Auto: Same
  "Michelle_BE2_Full_Nastic_002":          "Michelle_BE2_Full_Nastic_002",          # Auto: Same
  "Michelle_BE2_Full_Nastic_003":          "Michelle_BE2_Full_Nastic_003",          # Auto: Same
  "Michelle_BE2_Full_Under_001":           "Michelle_BE2_Full_Under_001",           # Auto: Same
  "Michelle_BE2_Full_Under_002":           "Michelle_BE2_Full_Under_002",           # Auto: Same
  "Michelle_BE2_Full_Under_003":           "Michelle_BE2_Full_Under_003",           # Auto: Same
  "Michelle_BE2_Gym_001":                  "Michelle_BE2_Gym_001",                  # Auto: Same
  "Michelle_BE2_Gym_002":                  "Michelle_BE2_Gym_002",                  # Auto: Same
  "Michelle_BE2_Gym_003":                  "Michelle_BE2_Gym_003",                  # Auto: Same
  "Michelle_BE2_Naked_001":                "Michelle_BE2_Naked_001",                # Auto: Same
  "Michelle_BE2_Naked_002":                "Michelle_BE2_Naked_002",                # Auto: Same
  "Michelle_BE2_Naked_003":                "Michelle_BE2_Naked_003",                # Auto: Same
  "Michelle_BE2_Nastic_001":               "Michelle_BE2_Nastic_001",               # Auto: Same
  "Michelle_BE2_Nastic_002":               "Michelle_BE2_Nastic_002",               # Auto: Same
  "Michelle_BE2_Nastic_003":               "Michelle_BE2_Nastic_003",               # Auto: Same
  "Michelle_BE2_Under_001":                "Michelle_BE2_Under_001",                # Auto: Same
  "Michelle_BE2_Under_002":                "Michelle_BE2_Under_002",                # Auto: Same
  "Michelle_BE2_Under_003":                "Michelle_BE2_Under_003",                # Auto: Same
  "Michelle_Base_001":                     "Michelle_Base_001",                     # Auto: Edited
  "Michelle_Base_002":                     "Michelle_Base_002",                     # Auto: Edited
  "Michelle_Base_003":                     "Michelle_Base_003",                     # Auto: Edited
  "Michelle_Base_Cas_001":                 "Michelle_Base_Cas_001",                 # Auto: Edited
  "Michelle_Base_Cas_002":                 "Michelle_Base_Cas_002",                 # Auto: Edited
  "Michelle_Base_Cas_003":                 "Michelle_Base_Cas_003",                 # Auto: Edited
  "Michelle_Base_Dog_001":                 "Michelle_Base_Dog_001",                 # Auto: Edited
  "Michelle_Base_Dog_002":                 "Michelle_Base_Dog_002",                 # Auto: Edited
  "Michelle_Base_Dog_003":                 "Michelle_Base_Dog_003",                 # Auto: Edited
  "Michelle_Base_Dress_001":               "Michelle_Base_Dress_001",               # Auto: Edited
  "Michelle_Base_Dress_002":               "Michelle_Base_Dress_002",               # Auto: Edited
  "Michelle_Base_Dress_003":               "Michelle_Base_Dress_003",               # Auto: Edited
  "Michelle_Base_Full_001":                "Michelle_Base_Full_001",                # Auto: Same
  "Michelle_Base_Full_002":                "Michelle_Base_Full_002",                # Auto: Same
  "Michelle_Base_Full_003":                "Michelle_Base_Full_003",                # Auto: Same
  "Michelle_Base_Full_Cas_001":            "Michelle_Base_Full_Cas_001",            # Auto: Same
  "Michelle_Base_Full_Cas_002":            "Michelle_Base_Full_Cas_002",            # Auto: Same
  "Michelle_Base_Full_Cas_003":            "Michelle_Base_Full_Cas_003",            # Auto: Same
  "Michelle_Base_Full_Dog_001":            "Michelle_Base_Full_Dog_001",            # Auto: Same
  "Michelle_Base_Full_Dog_002":            "Michelle_Base_Full_Dog_002",            # Auto: Same
  "Michelle_Base_Full_Dog_003":            "Michelle_Base_Full_Dog_003",            # Auto: Same
  "Michelle_Base_Full_Dress_001":          "Michelle_Base_Full_Dress_001",          # Auto: Same
  "Michelle_Base_Full_Dress_002":          "Michelle_Base_Full_Dress_002",          # Auto: Same
  "Michelle_Base_Full_Dress_003":          "Michelle_Base_Full_Dress_003",          # Auto: Same
  "Michelle_Base_Full_Gym_001":            "Michelle_Base_Full_Gym_001",            # Auto: Same
  "Michelle_Base_Full_Gym_002":            "Michelle_Base_Full_Gym_002",            # Auto: Same
  "Michelle_Base_Full_Gym_003":            "Michelle_Base_Full_Gym_003",            # Auto: Same
  "Michelle_Base_Full_Naked_001":          "Michelle_Base_Full_Naked_001",          # Auto: Same
  "Michelle_Base_Full_Naked_002":          "Michelle_Base_Full_Naked_002",          # Auto: Same
  "Michelle_Base_Full_Naked_003":          "Michelle_Base_Full_Naked_003",          # Auto: Same
  "Michelle_Base_Full_Nastic_001":         "Michelle_Base_Full_Nastic_001",         # Auto: Same
  "Michelle_Base_Full_Nastic_002":         "Michelle_Base_Full_Nastic_002",         # Auto: Same
  "Michelle_Base_Full_Nastic_003":         "Michelle_Base_Full_Nastic_003",         # Auto: Same
  "Michelle_Base_Full_Under_001":          "Michelle_Base_Full_Under_001",          # Auto: Same
  "Michelle_Base_Full_Under_002":          "Michelle_Base_Full_Under_002",          # Auto: Same
  "Michelle_Base_Full_Under_003":          "Michelle_Base_Full_Under_003",          # Auto: Same
  "Michelle_Base_Gym_001":                 "Michelle_Base_Gym_001",                 # Auto: Edited
  "Michelle_Base_Gym_002":                 "Michelle_Base_Gym_002",                 # Auto: Edited
  "Michelle_Base_Gym_003":                 "Michelle_Base_Gym_003",                 # Auto: Edited
  "Michelle_Base_Naked_001":               "Michelle_Base_Naked_001",               # Auto: Edited
  "Michelle_Base_Naked_002":               "Michelle_Base_Naked_002",               # Auto: Edited
  "Michelle_Base_Naked_003":               "Michelle_Base_Naked_003",               # Auto: Edited
  "Michelle_Base_Nastic_001":              "Michelle_Base_Nastic_001",              # Auto: Edited
  "Michelle_Base_Nastic_002":              "Michelle_Base_Nastic_002",              # Auto: Edited
  "Michelle_Base_Nastic_003":              "Michelle_Base_Nastic_003",              # Auto: Edited
  "Michelle_Base_Under_001":               "Michelle_Base_Under_001",               # Auto: Edited
  "Michelle_Base_Under_002":               "Michelle_Base_Under_002",               # Auto: Edited
  "Michelle_Base_Under_003":               "Michelle_Base_Under_003",               # Auto: Edited
  "Michelle_Ex_001_001":                   "Michelle_Ex_001_001",                   # Auto: Same
  "Michelle_Ex_001_Neutral_001":           "Michelle_Ex_001_Neutral_001",           # Auto: Same
  "Michelle_Ex_001_Smile_001":             "Michelle_Ex_001_Smile_001",             # Auto: Same
  "Michelle_Ex_002_001":                   "Michelle_Ex_002_Smile_001",             # Auto: Renamed
  "Michelle_Ex_002_Smile_001":             "Michelle_Ex_002_001",                   # Auto: Renamed
  "Michelle_Ex_003_001":                   "Michelle_Ex_003_Open2_001",             # Auto: Renamed
  "Michelle_Ex_003_Grin2_001":             "Michelle_Ex_003_Grin2_001",             # Auto: Same
  "Michelle_Ex_003_Grin_001":              "Michelle_Ex_003_Grin_001",              # Auto: Same
  "Michelle_Ex_003_Open_001":              "Michelle_Ex_003_Open_001",              # Auto: Same
  "Michelle_Ex_004_001":                   "Michelle_Ex_004_Open_001",              # Auto: Renamed
  "Michelle_Ex_004_Closed_001":            "Michelle_Ex_004_001",                   # Auto: Renamed
  "Michelle_Ex_004_Smile_001":             "Michelle_Ex_004_Smile_001",             # Auto: Same
  "Michelle_Ex_005_001":                   "Michelle_Ex_004_Open2_001",             # Auto: Renamed
  "Michelle_Ex_006_001":                   "Michelle_Ex_003_001",                   # Auto: Renamed
  "Michelle_Ex_007_001":                   "Michelle_Ex_005_Aroused2_001",          # Auto: Renamed
  "Michelle_Ex_008_001":                   "Michelle_Ex_003_Grit2_001",             # Auto: Renamed
  "Michelle_Ex_009_002":                   "Michelle_Ex_005_Open_002",              # Auto: Renamed
  "Michelle_Ex_009_Closed_002":            "Michelle_Ex_005_002",                   # Auto: Renamed
  "Michelle_Ex_009_Smile2_002":            "Michelle_Ex_005_Smile2_002",            # Auto: Renamed
  "Michelle_Ex_009_Smile_002":             "Michelle_Ex_005_Smile_002",             # Auto: Renamed
  "Michelle_Ex_010_002":                   "Michelle_Ex_003_Irked_002",             # Auto: Renamed
  "Michelle_Ex_011_002":                   "Michelle_Ex_009_Closed_002",            # Auto: Renamed
  "Michelle_Ex_011_Closed_002":            "Michelle_Ex_006_002",                   # Auto: Renamed
  "Michelle_Ex_011_Smile2_002":            "Michelle_Ex_006_Smile2_002",            # Auto: Renamed
  "Michelle_Ex_011_Smile_002":             "Michelle_Ex_006_Smile_002",             # Auto: Renamed
  "Michelle_Ex_012_002":                   "Michelle_Ex_012_002",                   # Auto: Same
  "Michelle_Ex_013_002":                   "Michelle_Ex_012_Smile_002",             # Auto: Renamed
  "Michelle_Ex_014_002":                   "Michelle_Ex_006_Open2_002",             # Auto: Renamed
  "Michelle_Ex_015_002":                   "Michelle_Ex_008_002",                   # Auto: Renamed
  "Michelle_Ex_015_Open_002":              "Michelle_Ex_008_Open_002",              # Auto: Renamed
  "Michelle_Ex_016_002":                   "Michelle_Ex_003_Irked3_002",            # Auto: Renamed
  "Michelle_Ex_017_003":                   "Michelle_Ex_010_Open_003",              # Auto: Renamed
  "Michelle_Ex_018_003":                   "Michelle_Ex_011_003",                   # Auto: Renamed
  "Michelle_Ex_019_003":                   "Michelle_Ex_011_Open_003",              # Auto: Renamed
  "Michelle_Ex_020_003":                   "Michelle_Ex_010_Daze2_003",             # Auto: Renamed
  "Michelle_Ex_021_003":                   "Michelle_Ex_010_Daze_003",              # Auto: Renamed
  "Michelle_Ex_Full_001_001":              "Michelle_Ex_Full_001_001",              # Auto: Same
  "Michelle_Ex_Full_001_Neutral_001":      "Michelle_Ex_Full_001_Neutral_001",      # Auto: Same
  "Michelle_Ex_Full_001_Smile_001":        "Michelle_Ex_Full_001_Smile_001",        # Auto: Same
  "Michelle_Ex_Full_002_001":              "Michelle_Ex_Full_002_Smile_001",        # Auto: Renamed
  "Michelle_Ex_Full_002_Smile_001":        "Michelle_Ex_Full_002_001",              # Auto: Renamed
  "Michelle_Ex_Full_003_001":              "Michelle_Ex_Full_003_Open2_001",        # Auto: Renamed
  "Michelle_Ex_Full_003_Grin2_001":        "Michelle_Ex_Full_003_Grin2_001",        # Auto: Same
  "Michelle_Ex_Full_003_Grin_001":         "Michelle_Ex_Full_003_Grin_001",         # Auto: Same
  "Michelle_Ex_Full_003_Open_001":         "Michelle_Ex_Full_003_Open_001",         # Auto: Same
  "Michelle_Ex_Full_004_001":              "Michelle_Ex_Full_004_Open_001",         # Auto: Renamed
  "Michelle_Ex_Full_004_Closed_001":       "Michelle_Ex_Full_004_001",              # Auto: Renamed
  "Michelle_Ex_Full_004_Smile_001":        "Michelle_Ex_Full_004_Smile_001",        # Auto: Same
  "Michelle_Ex_Full_005_001":              "Michelle_Ex_Full_004_Open2_001",        # Auto: Renamed
  "Michelle_Ex_Full_006_001":              "Michelle_Ex_Full_003_001",              # Auto: Renamed
  "Michelle_Ex_Full_007_001":              "Michelle_Ex_Full_005_Aroused2_001",     # Auto: Renamed
  "Michelle_Ex_Full_008_001":              "Michelle_Ex_Full_003_Grit2_001",        # Auto: Renamed
  "Michelle_Ex_Full_009_002":              "Michelle_Ex_Full_005_Open_002",         # Auto: Renamed
  "Michelle_Ex_Full_009_Closed_002":       "Michelle_Ex_Full_005_002",              # Auto: Renamed
  "Michelle_Ex_Full_009_Smile2_002":       "Michelle_Ex_Full_005_Smile2_002",       # Auto: Renamed
  "Michelle_Ex_Full_009_Smile_002":        "Michelle_Ex_Full_005_Smile_002",        # Auto: Renamed
  "Michelle_Ex_Full_010_002":              "Michelle_Ex_Full_003_Irked_002",        # Auto: Renamed
  "Michelle_Ex_Full_011_002":              "Michelle_Ex_Full_009_Closed_002",       # Auto: Renamed
  "Michelle_Ex_Full_011_Closed_002":       "Michelle_Ex_Full_006_002",              # Auto: Renamed
  "Michelle_Ex_Full_011_Smile2_002":       "Michelle_Ex_Full_006_Smile2_002",       # Auto: Renamed
  "Michelle_Ex_Full_011_Smile_002":        "Michelle_Ex_Full_006_Smile_002",        # Auto: Renamed
  "Michelle_Ex_Full_012_002":              "Michelle_Ex_Full_012_002",              # Auto: Same
  "Michelle_Ex_Full_013_002":              "Michelle_Ex_Full_012_Smile_002",        # Auto: Renamed
  "Michelle_Ex_Full_014_002":              "Michelle_Ex_Full_006_Open2_002",        # Auto: Renamed
  "Michelle_Ex_Full_015_002":              "Michelle_Ex_Full_008_002",              # Auto: Renamed
  "Michelle_Ex_Full_015_Open_002":         "Michelle_Ex_Full_008_Open_002",         # Auto: Renamed
  "Michelle_Ex_Full_016_002":              "Michelle_Ex_Full_003_Irked3_002",       # Auto: Renamed
  "Michelle_Ex_Full_017_003":              "Michelle_Ex_Full_010_Open_003",         # Auto: Renamed
  "Michelle_Ex_Full_018_003":              "Michelle_Ex_Full_011_003",              # Auto: Renamed
  "Michelle_Ex_Full_019_003":              "Michelle_Ex_Full_011_Open_003",         # Auto: Renamed
  "Michelle_Ex_Full_020_003":              "Michelle_Ex_Full_010_Daze2_003",        # Auto: Renamed
  "Michelle_Ex_Full_021_003":              "Michelle_Ex_Full_010_Daze_003",         # Auto: Renamed
}
