characterMapCiel = {
  "Ciel_Base_001":                         "Ciel_Base_001",                         # Auto: Edited
  "Ciel_Base_002":                         "Ciel_Base_002",                         # Auto: Edited
  "Ciel_Base_003":                         "Ciel_Base_003",                         # Auto: Edited
  "Ciel_Base_Full_001":                    "Ciel_Base_Full_001",                    # Auto: Edited
  "Ciel_Base_Full_002":                    "Ciel_Base_Full_002",                    # Auto: Edited
  "Ciel_Base_Full_003":                    "Ciel_Base_Full_003",                    # Auto: Edited
  "Ciel_Ex_001_001":                       "Ciel_Ex_001_001",                       # Auto: Edited
  "Ciel_Ex_001_Smile_001":                 "Ciel_Ex_001_Smile_001",                 # Auto: Edited
  "Ciel_Ex_002_001":                       "Ciel_Ex_002_001",                       # Auto: Edited
  "Ciel_Ex_003_001":                       "Ciel_Ex_003_001",                       # Auto: Edited
  "Ciel_Ex_004_001":                       "Ciel_Ex_004_001",                       # Auto: Edited
  "Ciel_Ex_004_Grin2_001":                 "",                                      # Auto: Deleted
  "Ciel_Ex_004_Grin_001":                  "",                                      # Auto: Deleted
  "Ciel_Ex_005_001":                       "Ciel_Ex_005_001",                       # Auto: Edited
  "Ciel_Ex_006_001":                       "Ciel_Ex_006_001",                       # Auto: Edited
  "Ciel_Ex_007_001":                       "",                                      # Auto: Deleted
  "Ciel_Ex_008_002":                       "Ciel_Ex_008_002",                       # Auto: Edited
  "Ciel_Ex_009_002":                       "Ciel_Ex_009_002",                       # Auto: Edited
  "Ciel_Ex_010_002":                       "Ciel_Ex_010_002",                       # Auto: Edited
  "Ciel_Ex_011_002":                       "Ciel_Ex_011_002",                       # Auto: Edited
  "Ciel_Ex_012_002":                       "Ciel_Ex_012_002",                       # Auto: Edited
  "Ciel_Ex_013_002":                       "",                                      # Auto: Deleted
  "Ciel_Ex_014_003":                       "",                                      # Auto: Deleted
  "Ciel_Ex_015_003":                       "",                                      # Auto: Deleted
  "Ciel_Ex_016_003":                       "",                                      # Auto: Deleted
  "Ciel_Ex_Full_001_001":                  "Ciel_Ex_Full_001_001",                  # Auto: Edited
  "Ciel_Ex_Full_002_001":                  "Ciel_Ex_Full_002_001",                  # Auto: Edited
  "Ciel_Ex_Full_003_001":                  "Ciel_Ex_Full_003_001",                  # Auto: Edited
  "Ciel_Ex_Full_004_001":                  "Ciel_Ex_Full_004_001",                  # Auto: Edited
  "Ciel_Ex_Full_005_001":                  "Ciel_Ex_Full_005_001",                  # Auto: Edited
  "Ciel_Ex_Full_006_001":                  "Ciel_Ex_Full_006_001",                  # Auto: Edited
  "Ciel_Ex_Full_007_001":                  "",                                      # Auto: Deleted
  "Ciel_Ex_Full_008_002":                  "Ciel_Ex_Full_008_002",                  # Auto: Edited
  "Ciel_Ex_Full_009_002":                  "Ciel_Ex_Full_009_002",                  # Auto: Edited
  "Ciel_Ex_Full_010_002":                  "Ciel_Ex_Full_010_002",                  # Auto: Edited
  "Ciel_Ex_Full_011_002":                  "Ciel_Ex_Full_011_002",                  # Auto: Edited
  "Ciel_Ex_Full_012_002":                  "Ciel_Ex_Full_012_002",                  # Auto: Edited
  "Ciel_Ex_Full_013_002":                  "",                                      # Auto: Deleted
  "Ciel_Ex_Full_014_003":                  "",                                      # Auto: Deleted
  "Ciel_Ex_Full_015_003":                  "",                                      # Auto: Deleted
  "Ciel_Ex_Full_016_003":                  "",                                      # Auto: Deleted
}
