characterMapVanessa = {
  "Vanessa_BE0_003":                       "Vanessa_BE0_003",                       # Auto: Same
  "Vanessa_BE0_Cas_002":                   "Vanessa_BE0_Cas_002",                   # Auto: Same
  "Vanessa_BE0_Full_003":                  "Vanessa_BE0_Full_003",                  # Auto: Same
  "Vanessa_BE0_Full_Cas_002":              "Vanessa_BE0_Full_Cas_002",              # Auto: Same
  "Vanessa_BE0_Full_Naked_003":            "Vanessa_BE0_Full_Naked_003",            # Auto: Same
  "Vanessa_BE0_Full_Under_003":            "Vanessa_BE0_Full_Under_003",            # Auto: Same
  "Vanessa_BE0_Naked_003":                 "Vanessa_BE0_Naked_003",                 # Auto: Same
  "Vanessa_BE0_Under_003":                 "Vanessa_BE0_Under_003",                 # Auto: Same
  "Vanessa_BE1_001":                       "Vanessa_BE1_001",                       # Auto: Same
  "Vanessa_BE1_002":                       "Vanessa_BE1_002",                       # Auto: Same
  "Vanessa_BE1_003":                       "Vanessa_BE1_003",                       # Auto: Same
  "Vanessa_BE1_Cas_001":                   "Vanessa_BE1_Cas_001",                   # Auto: Same
  "Vanessa_BE1_Cas_002":                   "Vanessa_BE1_Cas_002",                   # Auto: Same
  "Vanessa_BE1_Cas_003":                   "Vanessa_BE1_Cas_003",                   # Auto: Same
  "Vanessa_BE1_Full_001":                  "Vanessa_BE1_Full_001",                  # Auto: Same
  "Vanessa_BE1_Full_002":                  "Vanessa_BE1_Full_002",                  # Auto: Same
  "Vanessa_BE1_Full_003":                  "Vanessa_BE1_Full_003",                  # Auto: Same
  "Vanessa_BE1_Full_Cas_001":              "Vanessa_BE1_Full_Cas_001",              # Auto: Same
  "Vanessa_BE1_Full_Cas_002":              "Vanessa_BE1_Full_Cas_002",              # Auto: Same
  "Vanessa_BE1_Full_Cas_003":              "Vanessa_BE1_Full_Cas_003",              # Auto: Same
  "Vanessa_BE1_Full_Gym_001":              "Vanessa_BE1_Full_Gym_001",              # Auto: Same
  "Vanessa_BE1_Full_Gym_002":              "Vanessa_BE1_Full_Gym_002",              # Auto: Same
  "Vanessa_BE1_Full_Gym_003":              "Vanessa_BE1_Full_Gym_003",              # Auto: Same
  "Vanessa_BE1_Full_Naked_001":            "Vanessa_BE1_Full_Naked_001",            # Auto: Same
  "Vanessa_BE1_Full_Naked_002":            "Vanessa_BE1_Full_Naked_002",            # Auto: Same
  "Vanessa_BE1_Full_Naked_003":            "Vanessa_BE1_Full_Naked_003",            # Auto: Same
  "Vanessa_BE1_Full_Night_001":            "Vanessa_BE1_Full_Night_001",            # Auto: Same
  "Vanessa_BE1_Full_Night_002":            "Vanessa_BE1_Full_Night_002",            # Auto: Same
  "Vanessa_BE1_Full_Night_003":            "Vanessa_BE1_Full_Night_003",            # Auto: Same
  "Vanessa_BE1_Full_Under_001":            "Vanessa_BE1_Full_Under_001",            # Auto: Same
  "Vanessa_BE1_Full_Under_002":            "Vanessa_BE1_Full_Under_002",            # Auto: Same
  "Vanessa_BE1_Full_Under_003":            "Vanessa_BE1_Full_Under_003",            # Auto: Same
  "Vanessa_BE1_Gym_001":                   "Vanessa_BE1_Gym_001",                   # Auto: Same
  "Vanessa_BE1_Gym_002":                   "Vanessa_BE1_Gym_002",                   # Auto: Same
  "Vanessa_BE1_Gym_003":                   "Vanessa_BE1_Gym_003",                   # Auto: Same
  "Vanessa_BE1_Naked_001":                 "Vanessa_BE1_Naked_001",                 # Auto: Same
  "Vanessa_BE1_Naked_002":                 "Vanessa_BE1_Naked_002",                 # Auto: Same
  "Vanessa_BE1_Naked_003":                 "Vanessa_BE1_Naked_003",                 # Auto: Same
  "Vanessa_BE1_Night_001":                 "Vanessa_BE1_Night_001",                 # Auto: Same
  "Vanessa_BE1_Night_002":                 "Vanessa_BE1_Night_002",                 # Auto: Same
  "Vanessa_BE1_Night_003":                 "Vanessa_BE1_Night_003",                 # Auto: Same
  "Vanessa_BE1_Under_001":                 "Vanessa_BE1_Under_001",                 # Auto: Same
  "Vanessa_BE1_Under_002":                 "Vanessa_BE1_Under_002",                 # Auto: Same
  "Vanessa_BE1_Under_003":                 "Vanessa_BE1_Under_003",                 # Auto: Same
  "Vanessa_Base_001":                      "Vanessa_Base_001",                      # Auto: Edited
  "Vanessa_Base_002":                      "Vanessa_Base_002",                      # Auto: Edited
  "Vanessa_Base_003":                      "Vanessa_Base_003",                      # Auto: Edited
  "Vanessa_Base_Cas_001":                  "Vanessa_Base_Cas_001",                  # Auto: Edited
  "Vanessa_Base_Cas_002":                  "Vanessa_Base_Cas_002",                  # Auto: Edited
  "Vanessa_Base_Cas_003":                  "Vanessa_Base_Cas_003",                  # Auto: Edited
  "Vanessa_Base_Full_001":                 "Vanessa_Base_Full_001",                 # Auto: Same
  "Vanessa_Base_Full_002":                 "Vanessa_Base_Full_002",                 # Auto: Edited
  "Vanessa_Base_Full_003":                 "Vanessa_Base_Full_003",                 # Auto: Edited
  "Vanessa_Base_Full_Cas_001":             "Vanessa_Base_Full_Cas_001",             # Auto: Same
  "Vanessa_Base_Full_Cas_002":             "Vanessa_Base_Full_Cas_002",             # Auto: Edited
  "Vanessa_Base_Full_Cas_003":             "Vanessa_Base_Full_Cas_003",             # Auto: Edited
  "Vanessa_Base_Full_Gym_001":             "Vanessa_Base_Full_Gym_001",             # Auto: Same
  "Vanessa_Base_Full_Gym_002":             "Vanessa_Base_Full_Gym_002",             # Auto: Edited
  "Vanessa_Base_Full_Gym_003":             "Vanessa_Base_Full_Gym_003",             # Auto: Edited
  "Vanessa_Base_Full_Naked_001":           "Vanessa_Base_Full_Naked_001",           # Auto: Same
  "Vanessa_Base_Full_Naked_002":           "Vanessa_Base_Full_Naked_002",           # Auto: Edited
  "Vanessa_Base_Full_Naked_003":           "Vanessa_Base_Full_Naked_003",           # Auto: Edited
  "Vanessa_Base_Full_Night_001":           "Vanessa_Base_Full_Night_001",           # Auto: Same
  "Vanessa_Base_Full_Night_002":           "Vanessa_Base_Full_Night_002",           # Auto: Edited
  "Vanessa_Base_Full_Night_003":           "Vanessa_Base_Full_Night_003",           # Auto: Edited
  "Vanessa_Base_Full_Under_001":           "Vanessa_Base_Full_Under_001",           # Auto: Same
  "Vanessa_Base_Full_Under_002":           "Vanessa_Base_Full_Under_002",           # Auto: Edited
  "Vanessa_Base_Full_Under_003":           "Vanessa_Base_Full_Under_003",           # Auto: Edited
  "Vanessa_Base_Gym_001":                  "Vanessa_Base_Gym_001",                  # Auto: Edited
  "Vanessa_Base_Gym_002":                  "Vanessa_Base_Gym_002",                  # Auto: Edited
  "Vanessa_Base_Gym_003":                  "Vanessa_Base_Gym_003",                  # Auto: Edited
  "Vanessa_Base_Naked_001":                "Vanessa_Base_Naked_001",                # Auto: Edited
  "Vanessa_Base_Naked_002":                "Vanessa_Base_Naked_002",                # Auto: Edited
  "Vanessa_Base_Naked_003":                "Vanessa_Base_Naked_003",                # Auto: Edited
  "Vanessa_Base_Night_001":                "Vanessa_Base_Night_001",                # Auto: Edited
  "Vanessa_Base_Night_002":                "Vanessa_Base_Night_002",                # Auto: Edited
  "Vanessa_Base_Night_003":                "Vanessa_Base_Night_003",                # Auto: Edited
  "Vanessa_Base_Under_001":                "Vanessa_Base_Under_001",                # Auto: Edited
  "Vanessa_Base_Under_002":                "Vanessa_Base_Under_002",                # Auto: Edited
  "Vanessa_Base_Under_003":                "Vanessa_Base_Under_003",                # Auto: Edited
  "Vanessa_Ex_001_001":                    "Vanessa_Ex_001_001",                    # Auto: Same
  "Vanessa_Ex_001_Neutral_001":            "Vanessa_Ex_001_Neutral_001",            # Auto: Edited
  "Vanessa_Ex_001_Smile_001":              "Vanessa_Ex_001_Smile_001",              # Auto: Same
  "Vanessa_Ex_002_001":                    "Vanessa_Ex_002_Smile_001",              # Auto: Renamed
  "Vanessa_Ex_002_Smile_001":              "Vanessa_Ex_002_001",                    # Auto: Renamed
  "Vanessa_Ex_003_001":                    "Vanessa_Ex_004_Open_001",               # Auto: Renamed
  "Vanessa_Ex_003_Smile_001":              "Vanessa_Ex_004_Smile_001",              # Auto: Renamed
  "Vanessa_Ex_004_001":                    "Vanessa_Ex_004_Open2_001",              # Auto: Renamed
  "Vanessa_Ex_005_001":                    "Vanessa_Ex_006_Open_001",               # Auto: Renamed
  "Vanessa_Ex_006_001":                    "Vanessa_Ex_006_001",                    # Auto: Edited
  "Vanessa_Ex_007_001":                    "Vanessa_Ex_005_Aroused2_001",           # Auto: Renamed
  "Vanessa_Ex_008_001":                    "Vanessa_Ex_002_Smile2_001",             # Auto: Renamed
  "Vanessa_Ex_009_002":                    "Vanessa_Ex_009_002",                    # Auto: Same
  "Vanessa_Ex_010_002":                    "Vanessa_Ex_011_002",                    # Auto: Renamed
  "Vanessa_Ex_011_002":                    "Vanessa_Ex_011_002",                    # Auto: Edited
  "Vanessa_Ex_012_002":                    "Vanessa_Ex_012_002",                    # Auto: Same
  "Vanessa_Ex_013_002":                    "Vanessa_Ex_008_002",                    # Auto: Renamed
  "Vanessa_Ex_014_002":                    "Vanessa_Ex_010_Open_002",               # Auto: Renamed
  "Vanessa_Ex_015_002":                    "Vanessa_Ex_013_002",                    # Auto: Renamed
  "Vanessa_Ex_016_002":                    "Vanessa_Ex_010_Open2_002",              # Auto: Renamed
  "Vanessa_Ex_017_002":                    "Vanessa_Ex_009_Open_002",               # Auto: Renamed
  "Vanessa_Ex_018_003":                    "Vanessa_Ex_003_Irked_003",              # Auto: Renamed
  "Vanessa_Ex_018_Open_003":               "Vanessa_Ex_003_Irked2_003",             # Auto: Renamed
  "Vanessa_Ex_018_Smile_003":              "Vanessa_Ex_003_Irked3_003",             # Auto: Renamed
  "Vanessa_Ex_019_003":                    "Vanessa_Ex_003_Open2_003",              # Auto: Renamed
  "Vanessa_Ex_019_Grin2_003":              "Vanessa_Ex_003_Grin2_003",              # Auto: Renamed
  "Vanessa_Ex_019_Grin_003":               "Vanessa_Ex_003_Grin_003",               # Auto: Renamed
  "Vanessa_Ex_020_003":                    "",                                      # Auto: Deleted
  "Vanessa_Ex_021_003":                    "Vanessa_Ex_011_Open_003",               # Auto: Renamed
  "Vanessa_Ex_Full_001_001":               "Vanessa_Ex_Full_001_001",               # Auto: Same
  "Vanessa_Ex_Full_001_Neutral_001":       "Vanessa_Ex_Full_001_Neutral_001",       # Auto: Edited
  "Vanessa_Ex_Full_001_Smile_001":         "Vanessa_Ex_Full_001_Smile_001",         # Auto: Same
  "Vanessa_Ex_Full_002_001":               "Vanessa_Ex_Full_002_Smile_001",         # Auto: Renamed
  "Vanessa_Ex_Full_002_Smile_001":         "Vanessa_Ex_Full_002_001",               # Auto: Renamed
  "Vanessa_Ex_Full_003_001":               "Vanessa_Ex_Full_004_Open_001",          # Auto: Renamed
  "Vanessa_Ex_Full_003_Smile_001":         "Vanessa_Ex_Full_004_Smile_001",         # Auto: Renamed
  "Vanessa_Ex_Full_004_001":               "Vanessa_Ex_Full_004_Open2_001",         # Auto: Renamed
  "Vanessa_Ex_Full_005_001":               "Vanessa_Ex_Full_006_Open_001",          # Auto: Renamed
  "Vanessa_Ex_Full_006_001":               "Vanessa_Ex_Full_006_001",               # Auto: Edited
  "Vanessa_Ex_Full_007_001":               "Vanessa_Ex_Full_005_Aroused2_001",      # Auto: Renamed
  "Vanessa_Ex_Full_008_001":               "Vanessa_Ex_Full_002_Smile2_001",        # Auto: Renamed
  "Vanessa_Ex_Full_009_002":               "Vanessa_Ex_Full_009_002",               # Auto: Same
  "Vanessa_Ex_Full_010_002":               "Vanessa_Ex_Full_011_002",               # Auto: Renamed
  "Vanessa_Ex_Full_011_002":               "Vanessa_Ex_Full_011_002",               # Auto: Edited
  "Vanessa_Ex_Full_012_002":               "Vanessa_Ex_Full_012_002",               # Auto: Same
  "Vanessa_Ex_Full_013_002":               "Vanessa_Ex_Full_008_002",               # Auto: Renamed
  "Vanessa_Ex_Full_014_002":               "Vanessa_Ex_Full_010_Open_002",          # Auto: Renamed
  "Vanessa_Ex_Full_015_002":               "Vanessa_Ex_Full_013_002",               # Auto: Renamed
  "Vanessa_Ex_Full_016_002":               "Vanessa_Ex_Full_010_Open2_002",         # Auto: Renamed
  "Vanessa_Ex_Full_017_002":               "Vanessa_Ex_Full_009_Open_002",          # Auto: Renamed
  "Vanessa_Ex_Full_018_003":               "Vanessa_Ex_Full_003_Irked_003",         # Auto: Renamed
  "Vanessa_Ex_Full_018_Open_003":          "Vanessa_Ex_Full_003_Irked2_003",        # Auto: Renamed
  "Vanessa_Ex_Full_018_Smile_003":         "Vanessa_Ex_Full_003_Irked3_003",        # Auto: Renamed
  "Vanessa_Ex_Full_019_003":               "Vanessa_Ex_Full_003_Open2_003",         # Auto: Renamed
  "Vanessa_Ex_Full_019_Grin2_003":         "Vanessa_Ex_Full_003_Grin2_003",         # Auto: Renamed
  "Vanessa_Ex_Full_019_Grin_003":          "Vanessa_Ex_Full_003_Grin_003",          # Auto: Renamed
  "Vanessa_Ex_Full_020_003":               "Vanessa_Ex_Full_007_003",               # Auto: Renamed
  "Vanessa_Ex_Full_021_003":               "Vanessa_Ex_Full_011_Open_003",          # Auto: Renamed
}
