characterMapChris = {
  "chris_base_full_naked_001":             "chris_base_full_naked_001",             # Auto: Edited
  "chris_base_full_naked_002":             "chris_base_full_naked_002",             # Auto: Edited
  "chris_base_full_naked_003":             "chris_base_full_naked_003",             # Auto: Edited
  "chris_base_full_punk_001":              "chris_base_full_punk_001",              # Auto: Edited
  "chris_base_full_punk_002":              "chris_base_full_punk_002",              # Auto: Edited
  "chris_base_full_punk_003":              "chris_base_full_punk_003",              # Auto: Edited
  "chris_base_full_school_001":            "chris_base_full_school_001",            # Auto: Edited
  "chris_base_full_school_002":            "chris_base_full_school_002",            # Auto: Edited
  "chris_base_full_school_003":            "chris_base_full_school_003",            # Auto: Edited
  "chris_base_full_under_001":             "chris_base_full_under_001",             # Auto: Edited
  "chris_base_full_under_002":             "chris_base_full_under_002",             # Auto: Edited
  "chris_base_full_under_003":             "chris_base_full_under_003",             # Auto: Edited
  "chris_base_naked_001":                  "chris_base_naked_001",                  # Auto: Edited
  "chris_base_naked_002":                  "chris_base_naked_002",                  # Auto: Edited
  "chris_base_naked_003":                  "chris_base_naked_003",                  # Auto: Edited
  "chris_base_punk_001":                   "chris_base_punk_001",                   # Auto: Edited
  "chris_base_punk_002":                   "chris_base_punk_002",                   # Auto: Edited
  "chris_base_punk_003":                   "chris_base_punk_003",                   # Auto: Edited
  "chris_base_school_001":                 "chris_base_school_001",                 # Auto: Edited
  "chris_base_school_002":                 "chris_base_school_002",                 # Auto: Edited
  "chris_base_school_003":                 "chris_base_school_003",                 # Auto: Edited
  "chris_base_under_001":                  "chris_base_under_001",                  # Auto: Edited
  "chris_base_under_002":                  "chris_base_under_002",                  # Auto: Edited
  "chris_base_under_003":                  "chris_base_under_003",                  # Auto: Edited
  "chris_ex_001_001":                      "chris_ex_001_001",                      # Auto: Edited
  "chris_ex_001_smile_001":                "chris_ex_001_smile_001",                # Auto: Edited
  "chris_ex_002_001":                      "chris_ex_002_001",                      # Auto: Edited
  "chris_ex_002_smile_001":                "chris_ex_002_smile_001",                # Auto: Edited
  "chris_ex_003_001":                      "chris_ex_003_001",                      # Auto: Edited
  "chris_ex_004_001":                      "chris_ex_004_001",                      # Auto: Edited
  "chris_ex_005_001":                      "chris_ex_005_001",                      # Auto: Edited
  "chris_ex_005_smile_001":                "chris_ex_005_smile_001",                # Auto: Edited
  "chris_ex_006_001":                      "chris_ex_006_001",                      # Auto: Edited
  "chris_ex_007_001":                      "chris_ex_007_001",                      # Auto: Edited
  "chris_ex_007_smile_001":                "chris_ex_007_smile_001",                # Auto: Edited
  "chris_ex_008_002":                      "",                                      # Auto: Deleted
  "chris_ex_009_002":                      "chris_ex_009_002",                      # Auto: Edited
  "chris_ex_010_002":                      "chris_ex_010_002",                      # Auto: Edited
  "chris_ex_011_002":                      "chris_ex_011_002",                      # Auto: Edited
  "chris_ex_011_grin2_002":                "",                                      # Auto: Deleted
  "chris_ex_011_grin_002":                 "",                                      # Auto: Deleted
  "chris_ex_011_open_002":                 "",                                      # Auto: Deleted
  "chris_ex_012_002":                      "chris_ex_012_002",                      # Auto: Edited
  "chris_ex_013_002":                      "chris_ex_013_002",                      # Auto: Edited
  "chris_ex_014_002":                      "chris_ex_014_002",                      # Auto: Edited
  "chris_ex_014_open_002":                 "",                                      # Auto: Deleted
  "chris_ex_014_smile2_002":               "",                                      # Auto: Deleted
  "chris_ex_014_smile_002":                "",                                      # Auto: Deleted
  "chris_ex_015_002":                      "chris_ex_015_002",                      # Auto: Edited
  "chris_ex_016_002":                      "chris_ex_016_002",                      # Auto: Edited
  "chris_ex_016_closed_002":               "",                                      # Auto: Deleted
  "chris_ex_017_002":                      "chris_ex_017_002",                      # Auto: Edited
  "chris_ex_018_002":                      "chris_ex_018_002",                      # Auto: Edited
  "chris_ex_019_003":                      "",                                      # Auto: Deleted
  "chris_ex_020_003":                      "chris_ex_020_003",                      # Auto: Edited
  "chris_ex_021_003":                      "chris_ex_021_003",                      # Auto: Edited
  "chris_ex_022_003":                      "chris_ex_022_003",                      # Auto: Edited
  "chris_ex_023_003":                      "chris_ex_023_003",                      # Auto: Edited
  "chris_ex_024_003":                      "chris_ex_024_003",                      # Auto: Edited
  "chris_ex_025_003":                      "chris_ex_025_003",                      # Auto: Edited
  "chris_ex_026_003":                      "chris_ex_026_003",                      # Auto: Edited
  "chris_ex_027_003":                      "",                                      # Auto: Deleted
  "chris_ex_028_003":                      "",                                      # Auto: Deleted
  "chris_ex_029_003":                      "",                                      # Auto: Deleted
  "chris_ex_030_003":                      "",                                      # Auto: Deleted
  "chris_ex_full_001_001":                 "chris_ex_full_001_001",                 # Auto: Edited
  "chris_ex_full_001_smile_001":           "chris_ex_full_001_smile_001",           # Auto: Edited
  "chris_ex_full_002_001":                 "chris_ex_full_002_001",                 # Auto: Edited
  "chris_ex_full_002_smile_001":           "chris_ex_full_002_smile_001",           # Auto: Edited
  "chris_ex_full_003_001":                 "chris_ex_full_003_001",                 # Auto: Edited
  "chris_ex_full_004_001":                 "chris_ex_full_004_001",                 # Auto: Edited
  "chris_ex_full_005_001":                 "chris_ex_full_005_001",                 # Auto: Edited
  "chris_ex_full_005_smile_001":           "chris_ex_full_005_smile_001",           # Auto: Edited
  "chris_ex_full_006_001":                 "chris_ex_full_006_001",                 # Auto: Edited
  "chris_ex_full_007_001":                 "chris_ex_full_007_001",                 # Auto: Edited
  "chris_ex_full_007_smile_001":           "chris_ex_full_007_smile_001",           # Auto: Edited
  "chris_ex_full_008_002":                 "",                                      # Auto: Deleted
  "chris_ex_full_009_002":                 "chris_ex_full_009_002",                 # Auto: Edited
  "chris_ex_full_010_002":                 "chris_ex_full_010_002",                 # Auto: Edited
  "chris_ex_full_011_002":                 "chris_ex_full_011_002",                 # Auto: Edited
  "chris_ex_full_011_grin2_002":           "",                                      # Auto: Deleted
  "chris_ex_full_011_grin_002":            "",                                      # Auto: Deleted
  "chris_ex_full_011_open_002":            "",                                      # Auto: Deleted
  "chris_ex_full_012_002":                 "chris_ex_full_012_002",                 # Auto: Edited
  "chris_ex_full_013_002":                 "chris_ex_full_013_002",                 # Auto: Edited
  "chris_ex_full_014_002":                 "chris_ex_full_014_002",                 # Auto: Edited
  "chris_ex_full_014_open_002":            "",                                      # Auto: Deleted
  "chris_ex_full_014_smile2_002":          "",                                      # Auto: Deleted
  "chris_ex_full_014_smile_002":           "",                                      # Auto: Deleted
  "chris_ex_full_015_002":                 "chris_ex_full_015_002",                 # Auto: Edited
  "chris_ex_full_016_002":                 "chris_ex_full_016_002",                 # Auto: Edited
  "chris_ex_full_016_closed_002":          "",                                      # Auto: Deleted
  "chris_ex_full_017_002":                 "chris_ex_full_017_002",                 # Auto: Edited
  "chris_ex_full_018_002":                 "chris_ex_full_018_002",                 # Auto: Edited
  "chris_ex_full_019_003":                 "",                                      # Auto: Deleted
  "chris_ex_full_020_003":                 "chris_ex_full_020_003",                 # Auto: Edited
  "chris_ex_full_021_003":                 "chris_ex_full_021_003",                 # Auto: Edited
  "chris_ex_full_022_003":                 "chris_ex_full_022_003",                 # Auto: Edited
  "chris_ex_full_023_003":                 "chris_ex_full_023_003",                 # Auto: Edited
  "chris_ex_full_024_003":                 "chris_ex_full_024_003",                 # Auto: Edited
  "chris_ex_full_025_003":                 "chris_ex_full_025_003",                 # Auto: Edited
  "chris_ex_full_026_003":                 "chris_ex_full_026_003",                 # Auto: Edited
  "chris_ex_full_027_003":                 "",                                      # Auto: Deleted
  "chris_ex_full_028_003":                 "",                                      # Auto: Deleted
  "chris_ex_full_029_003":                 "",                                      # Auto: Deleted
  "chris_ex_full_030_003":                 "",                                      # Auto: Deleted
  "chris_mut_full_hair_001":               "chris_mut_full_hair_001",               # Auto: Edited
  "chris_mut_full_hair_002":               "chris_mut_full_hair_002",               # Auto: Edited
  "chris_mut_full_hair_003":               "chris_mut_full_hair_003",               # Auto: Edited
  "chris_mut_full_naked_hair_001":         "chris_mut_full_naked_hair_001",         # Auto: Edited
  "chris_mut_full_naked_hair_002":         "chris_mut_full_naked_hair_002",         # Auto: Edited
  "chris_mut_full_naked_hair_003":         "chris_mut_full_naked_hair_003",         # Auto: Edited
  "chris_mut_full_punk_hair_001":          "chris_mut_full_punk_hair_001",          # Auto: Edited
  "chris_mut_full_punk_hair_002":          "chris_mut_full_punk_hair_002",          # Auto: Edited
  "chris_mut_full_punk_hair_003":          "chris_mut_full_punk_hair_003",          # Auto: Edited
  "chris_mut_full_school_hair_001":        "chris_mut_full_school_hair_001",        # Auto: Edited
  "chris_mut_full_school_hair_002":        "chris_mut_full_school_hair_002",        # Auto: Edited
  "chris_mut_full_school_hair_003":        "chris_mut_full_school_hair_003",        # Auto: Edited
  "chris_mut_full_under_hair_001":         "chris_mut_full_under_hair_001",         # Auto: Edited
  "chris_mut_full_under_hair_002":         "chris_mut_full_under_hair_002",         # Auto: Edited
  "chris_mut_full_under_hair_003":         "chris_mut_full_under_hair_003",         # Auto: Edited
  "chris_mut_hair_001":                    "chris_mut_hair_001",                    # Auto: Edited
  "chris_mut_hair_002":                    "chris_mut_hair_002",                    # Auto: Edited
  "chris_mut_hair_003":                    "chris_mut_hair_003",                    # Auto: Edited
  "chris_mut_naked_hair_001":              "chris_mut_naked_hair_001",              # Auto: Edited
  "chris_mut_naked_hair_002":              "chris_mut_naked_hair_002",              # Auto: Edited
  "chris_mut_naked_hair_003":              "chris_mut_naked_hair_003",              # Auto: Edited
  "chris_mut_punk_hair_001":               "chris_mut_punk_hair_001",               # Auto: Edited
  "chris_mut_punk_hair_002":               "chris_mut_punk_hair_002",               # Auto: Edited
  "chris_mut_punk_hair_003":               "chris_mut_punk_hair_003",               # Auto: Edited
  "chris_mut_school_hair_001":             "chris_mut_school_hair_001",             # Auto: Edited
  "chris_mut_school_hair_002":             "chris_mut_school_hair_002",             # Auto: Edited
  "chris_mut_school_hair_003":             "chris_mut_school_hair_003",             # Auto: Edited
  "chris_mut_under_hair_001":              "chris_mut_under_hair_001",              # Auto: Edited
  "chris_mut_under_hair_002":              "chris_mut_under_hair_002",              # Auto: Edited
  "chris_mut_under_hair_003":              "chris_mut_under_hair_003",              # Auto: Edited
}
