characterMapMelina = {
  "Melina_Base_001":                       "Melina_Base_001",                       # Auto: Edited
  "Melina_Base_002":                       "Melina_Base_002",                       # Auto: Edited
  "Melina_Base_Full_001":                  "Melina_Base_Full_001",                  # Auto: Edited
  "Melina_Base_Full_002":                  "Melina_Base_Full_002",                  # Auto: Edited
  "Melina_Base_Full_Gym_001":              "Melina_Base_Full_Gym_001",              # Auto: Edited
  "Melina_Base_Full_Gym_002":              "Melina_Base_Full_Gym_002",              # Auto: Edited
  "Melina_Base_Gym_001":                   "Melina_Base_Gym_001",                   # Auto: Edited
  "Melina_Base_Gym_002":                   "Melina_Base_Gym_002",                   # Auto: Edited
  "Melina_Base_Naked_001":                 "Melina_Base_Naked_001",                 # Auto: Edited
  "Melina_Base_Naked_002":                 "Melina_Base_Naked_002",                 # Auto: Edited
  "Melina_Ex_001_001":                     "Melina_Ex_001_001",                     # Auto: Edited
  "Melina_Ex_001_Smile_001":               "Melina_Ex_001_Smile_001",               # Auto: Edited
  "Melina_Ex_002_001":                     "Melina_Ex_002_001",                     # Auto: Edited
  "Melina_Ex_003_001":                     "Melina_Ex_003_001",                     # Auto: Edited
  "Melina_Ex_004_001":                     "Melina_Ex_004_001",                     # Auto: Edited
  "Melina_Ex_004_Grin2_001":               "",                                      # Auto: Deleted
  "Melina_Ex_004_Grin_001":                "",                                      # Auto: Deleted
  "Melina_Ex_004_Open_001":                "Melina_Ex_004_Open_001",                # Auto: Edited
  "Melina_Ex_005_001":                     "Melina_Ex_005_001",                     # Auto: Edited
  "Melina_Ex_006_001":                     "Melina_Ex_006_001",                     # Auto: Edited
  "Melina_Ex_007_001":                     "",                                      # Auto: Deleted
  "Melina_Ex_008_002":                     "Melina_Ex_008_002",                     # Auto: Edited
  "Melina_Ex_009_002":                     "Melina_Ex_009_002",                     # Auto: Edited
  "Melina_Ex_010_002":                     "Melina_Ex_010_002",                     # Auto: Edited
  "Melina_Ex_011_002":                     "Melina_Ex_011_002",                     # Auto: Edited
  "Melina_Ex_012_002":                     "Melina_Ex_012_002",                     # Auto: Edited
  "Melina_Ex_013_002":                     "",                                      # Auto: Deleted
  "Melina_Ex_014_002":                     "",                                      # Auto: Deleted
  "Melina_Ex_Full_001_001":                "Melina_Ex_Full_001_001",                # Auto: Edited
  "Melina_Ex_Full_002_001":                "Melina_Ex_Full_002_001",                # Auto: Edited
  "Melina_Ex_Full_003_001":                "Melina_Ex_Full_003_001",                # Auto: Edited
  "Melina_Ex_Full_004_001":                "Melina_Ex_Full_004_001",                # Auto: Edited
  "Melina_Ex_Full_005_001":                "Melina_Ex_Full_005_001",                # Auto: Edited
  "Melina_Ex_Full_006_001":                "Melina_Ex_Full_006_001",                # Auto: Edited
  "Melina_Ex_Full_007_001":                "",                                      # Auto: Deleted
  "Melina_Ex_Full_008_002":                "Melina_Ex_Full_008_002",                # Auto: Edited
  "Melina_Ex_Full_009_002":                "Melina_Ex_Full_009_002",                # Auto: Edited
  "Melina_Ex_Full_010_002":                "Melina_Ex_Full_010_002",                # Auto: Edited
  "Melina_Ex_Full_011_002":                "Melina_Ex_Full_011_002",                # Auto: Edited
  "Melina_Ex_Full_012_002":                "Melina_Ex_Full_012_002",                # Auto: Edited
  "Melina_Ex_Full_013_002":                "",                                      # Auto: Deleted
  "Melina_Ex_Full_014_002":                "",                                      # Auto: Deleted
  "Melina_Mut_Headband_001":               "",                                      # Auto: Deleted
  "Melina_Mut_Headband_002":               "",                                      # Auto: Deleted
  "Melina_Mut_Naked_Bra_001":              "",                                      # Auto: Deleted
  "Melina_Mut_Naked_Bra_002":              "",                                      # Auto: Deleted
  "Melina_Mut_Naked_Panties_001":          "",                                      # Auto: Deleted
  "Melina_Mut_Naked_Panties_002":          "",                                      # Auto: Deleted
  "Melina_Mut_Naked_Skirt_001":            "",                                      # Auto: Deleted
  "Melina_Mut_Naked_Skirt_002":            "",                                      # Auto: Deleted
}
