characterMapMartha = {
  "Martha_Base_001":                       "Martha_Base_001",                       # Auto: Edited
  "Martha_Base_002":                       "Martha_Base_002",                       # Auto: Edited
  "Martha_Base_003":                       "Martha_Base_003",                       # Auto: Edited
  "Martha_Base_Full_001":                  "Martha_Base_Full_001",                  # Auto: Edited
  "Martha_Base_Full_002":                  "Martha_Base_Full_002",                  # Auto: Edited
  "Martha_Base_Full_003":                  "Martha_Base_Full_003",                  # Auto: Edited
  "Martha_Base_Full_Gym_001":              "Martha_Base_Full_Gym_001",              # Auto: Edited
  "Martha_Base_Full_Gym_002":              "Martha_Base_Full_Gym_002",              # Auto: Edited
  "Martha_Base_Full_Gym_003":              "Martha_Base_Full_Gym_003",              # Auto: Edited
  "Martha_Base_Full_Naked_001":            "Martha_Base_Full_Naked_001",            # Auto: Edited
  "Martha_Base_Full_Naked_002":            "Martha_Base_Full_Naked_002",            # Auto: Edited
  "Martha_Base_Full_Naked_003":            "Martha_Base_Full_Naked_003",            # Auto: Edited
  "Martha_Base_Full_Under_001":            "Martha_Base_Full_Under_001",            # Auto: Edited
  "Martha_Base_Full_Under_002":            "Martha_Base_Full_Under_002",            # Auto: Edited
  "Martha_Base_Full_Under_003":            "Martha_Base_Full_Under_003",            # Auto: Edited
  "Martha_Base_Gym_001":                   "Martha_Base_Gym_001",                   # Auto: Edited
  "Martha_Base_Gym_002":                   "Martha_Base_Gym_002",                   # Auto: Edited
  "Martha_Base_Gym_003":                   "Martha_Base_Gym_003",                   # Auto: Edited
  "Martha_Base_Naked_001":                 "Martha_Base_Naked_001",                 # Auto: Edited
  "Martha_Base_Naked_002":                 "Martha_Base_Naked_002",                 # Auto: Edited
  "Martha_Base_Naked_003":                 "Martha_Base_Naked_003",                 # Auto: Edited
  "Martha_Base_Under_001":                 "Martha_Base_Under_001",                 # Auto: Edited
  "Martha_Base_Under_002":                 "Martha_Base_Under_002",                 # Auto: Edited
  "Martha_Base_Under_003":                 "Martha_Base_Under_003",                 # Auto: Edited
  "Martha_Ex_001_001":                     "Martha_Ex_001_001",                     # Auto: Edited
  "Martha_Ex_001_Smile_001":               "Martha_Ex_001_Smile_001",               # Auto: Edited
  "Martha_Ex_002_001":                     "Martha_Ex_002_001",                     # Auto: Edited
  "Martha_Ex_002_Smile_001":               "Martha_Ex_002_Smile_001",               # Auto: Edited
  "Martha_Ex_003_001":                     "Martha_Ex_003_001",                     # Auto: Edited
  "Martha_Ex_004_001":                     "Martha_Ex_004_001",                     # Auto: Edited
  "Martha_Ex_005_001":                     "Martha_Ex_005_001",                     # Auto: Edited
  "Martha_Ex_005_Closed_001":              "",                                      # Auto: Deleted
  "Martha_Ex_005_Grin2_001":               "",                                      # Auto: Deleted
  "Martha_Ex_005_Grin_001":                "",                                      # Auto: Deleted
  "Martha_Ex_005_Open_001":                "Martha_Ex_005_Open_001",                # Auto: Edited
  "Martha_Ex_006_001":                     "Martha_Ex_006_001",                     # Auto: Edited
  "Martha_Ex_007_001":                     "",                                      # Auto: Deleted
  "Martha_Ex_007_Closed_001":              "",                                      # Auto: Deleted
  "Martha_Ex_007_Smile_001":               "",                                      # Auto: Deleted
  "Martha_Ex_008_001":                     "",                                      # Auto: Deleted
  "Martha_Ex_009_001":                     "",                                      # Auto: Deleted
  "Martha_Ex_010_002":                     "Martha_Ex_010_002",                     # Auto: Edited
  "Martha_Ex_011_002":                     "Martha_Ex_011_002",                     # Auto: Edited
  "Martha_Ex_012_002":                     "Martha_Ex_012_002",                     # Auto: Edited
  "Martha_Ex_013_002":                     "Martha_Ex_013_002",                     # Auto: Edited
  "Martha_Ex_014_002":                     "Martha_Ex_014_002",                     # Auto: Edited
  "Martha_Ex_015_002":                     "Martha_Ex_015_002",                     # Auto: Edited
  "Martha_Ex_016_002":                     "Martha_Ex_016_002",                     # Auto: Edited
  "Martha_Ex_017_002":                     "Martha_Ex_017_002",                     # Auto: Edited
  "Martha_Ex_018_002":                     "Martha_Ex_018_002",                     # Auto: Edited
  "Martha_Ex_019_002":                     "",                                      # Auto: Deleted
  "Martha_Ex_020_002":                     "",                                      # Auto: Deleted
  "Martha_Ex_021_002":                     "",                                      # Auto: Deleted
  "Martha_Ex_022_002":                     "",                                      # Auto: Deleted
  "Martha_Ex_023_003":                     "Martha_Ex_023_003",                     # Auto: Edited
  "Martha_Ex_024_003":                     "Martha_Ex_024_003",                     # Auto: Edited
  "Martha_Ex_025_003":                     "Martha_Ex_025_003",                     # Auto: Edited
  "Martha_Ex_026_003":                     "",                                      # Auto: Deleted
  "Martha_Ex_027_003":                     "",                                      # Auto: Deleted
  "Martha_Ex_028_003":                     "",                                      # Auto: Deleted
  "Martha_Ex_029_003":                     "",                                      # Auto: Deleted
  "Martha_Ex_Full_001_001":                "Martha_Ex_Full_001_001",                # Auto: Edited
  "Martha_Ex_Full_001_Smile_001":          "Martha_Ex_Full_001_Smile_001",          # Auto: Edited
  "Martha_Ex_Full_002_001":                "Martha_Ex_Full_002_001",                # Auto: Edited
  "Martha_Ex_Full_002_Smile_001":          "Martha_Ex_Full_002_Smile_001",          # Auto: Edited
  "Martha_Ex_Full_003_001":                "Martha_Ex_Full_003_001",                # Auto: Edited
  "Martha_Ex_Full_004_001":                "Martha_Ex_Full_004_001",                # Auto: Edited
  "Martha_Ex_Full_005_001":                "Martha_Ex_Full_005_001",                # Auto: Edited
  "Martha_Ex_Full_005_Closed_001":         "",                                      # Auto: Deleted
  "Martha_Ex_Full_005_Grin2_001":          "",                                      # Auto: Deleted
  "Martha_Ex_Full_005_Grin_001":           "",                                      # Auto: Deleted
  "Martha_Ex_Full_005_Open_001":           "Martha_Ex_Full_005_Open_001",           # Auto: Edited
  "Martha_Ex_Full_006_001":                "Martha_Ex_Full_006_001",                # Auto: Edited
  "Martha_Ex_Full_007_001":                "",                                      # Auto: Deleted
  "Martha_Ex_Full_007_Closed_001":         "",                                      # Auto: Deleted
  "Martha_Ex_Full_007_Smile_001":          "",                                      # Auto: Deleted
  "Martha_Ex_Full_008_001":                "",                                      # Auto: Deleted
  "Martha_Ex_Full_009_001":                "",                                      # Auto: Deleted
  "Martha_Ex_Full_010_002":                "Martha_Ex_Full_010_002",                # Auto: Edited
  "Martha_Ex_Full_011_002":                "Martha_Ex_Full_011_002",                # Auto: Edited
  "Martha_Ex_Full_012_002":                "Martha_Ex_Full_012_002",                # Auto: Edited
  "Martha_Ex_Full_013_002":                "Martha_Ex_Full_013_002",                # Auto: Edited
  "Martha_Ex_Full_014_002":                "Martha_Ex_Full_014_002",                # Auto: Edited
  "Martha_Ex_Full_015_002":                "Martha_Ex_Full_015_002",                # Auto: Edited
  "Martha_Ex_Full_016_002":                "Martha_Ex_Full_016_002",                # Auto: Edited
  "Martha_Ex_Full_017_002":                "Martha_Ex_Full_017_002",                # Auto: Edited
  "Martha_Ex_Full_018_002":                "Martha_Ex_Full_018_002",                # Auto: Edited
  "Martha_Ex_Full_019_002":                "",                                      # Auto: Deleted
  "Martha_Ex_Full_020_002":                "",                                      # Auto: Deleted
  "Martha_Ex_Full_021_002":                "",                                      # Auto: Deleted
  "Martha_Ex_Full_022_002":                "",                                      # Auto: Deleted
  "Martha_Ex_Full_023_003":                "Martha_Ex_Full_023_003",                # Auto: Edited
  "Martha_Ex_Full_024_003":                "Martha_Ex_Full_024_003",                # Auto: Edited
  "Martha_Ex_Full_025_003":                "Martha_Ex_Full_025_003",                # Auto: Edited
  "Martha_Ex_Full_026_003":                "",                                      # Auto: Deleted
  "Martha_Ex_Full_027_003":                "",                                      # Auto: Deleted
  "Martha_Ex_Full_028_003":                "",                                      # Auto: Deleted
  "Martha_Ex_Full_029_003":                "",                                      # Auto: Deleted
}
