characterMapVanessa = {
  "vanessa_base_001":                      "vanessa_base_001",                      # Auto: Edited
  "vanessa_base_002":                      "vanessa_base_002",                      # Auto: Edited
  "vanessa_base_003":                      "vanessa_base_003",                      # Auto: Edited
  "vanessa_base_be1_001":                  "vanessa_be1_001",                       # Auto: Renamed
  "vanessa_base_be1_002":                  "vanessa_be1_002",                       # Auto: Renamed
  "vanessa_base_be1_003":                  "vanessa_be1_003",                       # Auto: Renamed
  "vanessa_base_breast_003":               "vanessa_be0_003",                       # Auto: Renamed
  "vanessa_base_casual_001":               "",                                      # Auto: Deleted
  "vanessa_base_casual_002":               "",                                      # Auto: Deleted
  "vanessa_base_casual_003":               "",                                      # Auto: Deleted
  "vanessa_base_casual_be1_001":           "vanessa_be1_cas_001",                   # Auto: Renamed
  "vanessa_base_casual_be1_002":           "vanessa_be1_cas_002",                   # Auto: Renamed
  "vanessa_base_casual_be1_003":           "vanessa_be1_cas_003",                   # Auto: Renamed
  "vanessa_base_casual_breast_002":        "vanessa_be0_cas_002",                   # Auto: Renamed
  "vanessa_base_full_001":                 "vanessa_base_full_001",                 # Auto: Same
  "vanessa_base_full_002":                 "vanessa_base_full_002",                 # Auto: Edited
  "vanessa_base_full_003":                 "vanessa_base_full_003",                 # Auto: Edited
  "vanessa_base_full_be1_001":             "vanessa_be1_full_001",                  # Auto: Renamed
  "vanessa_base_full_be1_002":             "vanessa_be1_full_002",                  # Auto: Renamed
  "vanessa_base_full_be1_003":             "vanessa_be1_full_003",                  # Auto: Renamed
  "vanessa_base_full_breast_003":          "vanessa_be0_full_003",                  # Auto: Renamed
  "vanessa_base_full_casual_001":          "vanessa_base_full_cas_001",             # Auto: Renamed
  "vanessa_base_full_casual_002":          "",                                      # Auto: Deleted
  "vanessa_base_full_casual_003":          "",                                      # Auto: Deleted
  "vanessa_base_full_casual_be1_001":      "vanessa_be1_full_cas_001",              # Auto: Renamed
  "vanessa_base_full_casual_be1_002":      "vanessa_be1_full_cas_002",              # Auto: Renamed
  "vanessa_base_full_casual_be1_003":      "vanessa_be1_full_cas_003",              # Auto: Renamed
  "vanessa_base_full_casual_breast_002":   "vanessa_be0_full_cas_002",              # Auto: Renamed
  "vanessa_base_full_gym_001":             "vanessa_base_full_gym_001",             # Auto: Same
  "vanessa_base_full_gym_002":             "vanessa_base_full_gym_002",             # Auto: Edited
  "vanessa_base_full_gym_003":             "vanessa_base_full_gym_003",             # Auto: Edited
  "vanessa_base_full_gym_be1_001":         "vanessa_be1_full_gym_001",              # Auto: Renamed
  "vanessa_base_full_gym_be1_002":         "vanessa_be1_full_gym_002",              # Auto: Renamed
  "vanessa_base_full_gym_be1_003":         "vanessa_be1_full_gym_003",              # Auto: Renamed
  "vanessa_base_full_naked_001":           "vanessa_base_full_naked_001",           # Auto: Same
  "vanessa_base_full_naked_002":           "vanessa_base_full_naked_002",           # Auto: Edited
  "vanessa_base_full_naked_003":           "vanessa_base_full_naked_003",           # Auto: Edited
  "vanessa_base_full_naked_be1_001":       "vanessa_be1_full_naked_001",            # Auto: Renamed
  "vanessa_base_full_naked_be1_002":       "vanessa_be1_full_naked_002",            # Auto: Renamed
  "vanessa_base_full_naked_be1_003":       "vanessa_be1_full_naked_003",            # Auto: Renamed
  "vanessa_base_full_naked_breast_003":    "vanessa_be0_full_naked_003",            # Auto: Renamed
  "vanessa_base_full_night_001":           "vanessa_base_full_night_001",           # Auto: Same
  "vanessa_base_full_night_002":           "vanessa_base_full_night_002",           # Auto: Edited
  "vanessa_base_full_night_003":           "vanessa_base_full_night_003",           # Auto: Edited
  "vanessa_base_full_night_be1_001":       "vanessa_be1_full_night_001",            # Auto: Renamed
  "vanessa_base_full_night_be1_002":       "vanessa_be1_full_night_002",            # Auto: Renamed
  "vanessa_base_full_night_be1_003":       "vanessa_be1_full_night_003",            # Auto: Renamed
  "vanessa_base_full_under_001":           "vanessa_base_full_under_001",           # Auto: Same
  "vanessa_base_full_under_002":           "vanessa_base_full_under_002",           # Auto: Edited
  "vanessa_base_full_under_003":           "vanessa_base_full_under_003",           # Auto: Edited
  "vanessa_base_full_under_be1_001":       "vanessa_be1_full_under_001",            # Auto: Renamed
  "vanessa_base_full_under_be1_002":       "vanessa_be1_full_under_002",            # Auto: Renamed
  "vanessa_base_full_under_be1_003":       "vanessa_be1_full_under_003",            # Auto: Renamed
  "vanessa_base_full_under_breast_003":    "vanessa_be0_full_under_003",            # Auto: Renamed
  "vanessa_base_gym_001":                  "vanessa_base_gym_001",                  # Auto: Edited
  "vanessa_base_gym_002":                  "vanessa_base_gym_002",                  # Auto: Edited
  "vanessa_base_gym_003":                  "vanessa_base_gym_003",                  # Auto: Edited
  "vanessa_base_gym_be1_001":              "vanessa_be1_gym_001",                   # Auto: Renamed
  "vanessa_base_gym_be1_002":              "vanessa_be1_gym_002",                   # Auto: Renamed
  "vanessa_base_gym_be1_003":              "vanessa_be1_gym_003",                   # Auto: Renamed
  "vanessa_base_naked_001":                "vanessa_base_naked_001",                # Auto: Edited
  "vanessa_base_naked_002":                "vanessa_base_naked_002",                # Auto: Edited
  "vanessa_base_naked_003":                "vanessa_base_naked_003",                # Auto: Edited
  "vanessa_base_naked_be1_001":            "vanessa_be1_naked_001",                 # Auto: Renamed
  "vanessa_base_naked_be1_002":            "vanessa_be1_naked_002",                 # Auto: Renamed
  "vanessa_base_naked_be1_003":            "vanessa_be1_naked_003",                 # Auto: Renamed
  "vanessa_base_naked_breast_003":         "vanessa_be0_naked_003",                 # Auto: Renamed
  "vanessa_base_night_001":                "vanessa_base_night_001",                # Auto: Edited
  "vanessa_base_night_002":                "vanessa_base_night_002",                # Auto: Edited
  "vanessa_base_night_003":                "vanessa_base_night_003",                # Auto: Edited
  "vanessa_base_night_be1_001":            "vanessa_be1_night_001",                 # Auto: Renamed
  "vanessa_base_night_be1_002":            "vanessa_be1_night_002",                 # Auto: Renamed
  "vanessa_base_night_be1_003":            "vanessa_be1_night_003",                 # Auto: Renamed
  "vanessa_base_under_001":                "vanessa_base_under_001",                # Auto: Edited
  "vanessa_base_under_002":                "vanessa_base_under_002",                # Auto: Edited
  "vanessa_base_under_003":                "vanessa_base_under_003",                # Auto: Edited
  "vanessa_base_under_be1_001":            "vanessa_be1_under_001",                 # Auto: Renamed
  "vanessa_base_under_be1_002":            "vanessa_be1_under_002",                 # Auto: Renamed
  "vanessa_base_under_be1_003":            "vanessa_be1_under_003",                 # Auto: Renamed
  "vanessa_base_under_breast_003":         "vanessa_be0_under_003",                 # Auto: Renamed
  "vanessa_ex_001":                        "vanessa_ex_001_001",                    # Auto: Renamed
  "vanessa_ex_001_neutral":                "vanessa_ex_001_neutral_001",            # Auto: Edited and renamed
  "vanessa_ex_001_smile":                  "vanessa_ex_001_smile_001",              # Auto: Renamed
  "vanessa_ex_002":                        "vanessa_ex_002_smile_001",              # Auto: Renamed
  "vanessa_ex_002_smile":                  "vanessa_ex_002_001",                    # Auto: Renamed
  "vanessa_ex_003":                        "vanessa_ex_004_open_001",               # Auto: Renamed
  "vanessa_ex_003_smile":                  "vanessa_ex_004_smile_001",              # Auto: Renamed
  "vanessa_ex_004":                        "vanessa_ex_004_open2_001",              # Auto: Renamed
  "vanessa_ex_005":                        "vanessa_ex_006_open_001",               # Auto: Renamed
  "vanessa_ex_006":                        "vanessa_ex_006_001",                    # Auto: Edited and renamed
  "vanessa_ex_007":                        "vanessa_ex_005_aroused2_001",           # Auto: Renamed
  "vanessa_ex_008":                        "vanessa_ex_002_smile2_001",             # Auto: Renamed
  "vanessa_ex_009":                        "vanessa_ex_009_002",                    # Auto: Renamed
  "vanessa_ex_010":                        "vanessa_ex_011_002",                    # Auto: Renamed
  "vanessa_ex_011":                        "vanessa_ex_011_002",                    # Auto: Edited and renamed
  "vanessa_ex_012":                        "vanessa_ex_012_002",                    # Auto: Renamed
  "vanessa_ex_013":                        "vanessa_ex_008_002",                    # Auto: Renamed
  "vanessa_ex_014":                        "vanessa_ex_010_open_002",               # Auto: Renamed
  "vanessa_ex_015":                        "vanessa_ex_013_002",                    # Auto: Renamed
  "vanessa_ex_016":                        "vanessa_ex_010_open2_002",              # Auto: Renamed
  "vanessa_ex_017":                        "vanessa_ex_009_open_002",               # Auto: Renamed
  "vanessa_ex_018":                        "vanessa_ex_003_irked_003",              # Auto: Renamed
  "vanessa_ex_018_open":                   "vanessa_ex_003_irked2_003",             # Auto: Renamed
  "vanessa_ex_018_smile":                  "vanessa_ex_003_irked3_003",             # Auto: Renamed
  "vanessa_ex_019":                        "vanessa_ex_003_open2_003",              # Auto: Renamed
  "vanessa_ex_019_grin":                   "vanessa_ex_003_grin_003",               # Auto: Renamed
  "vanessa_ex_019_grin2":                  "vanessa_ex_003_grin2_003",              # Auto: Renamed
  "vanessa_ex_020":                        "",                                      # Auto: Deleted
  "vanessa_ex_021":                        "vanessa_ex_011_open_003",               # Auto: Renamed
  "vanessa_ex_full_001":                   "vanessa_ex_full_001_001",               # Auto: Renamed
  "vanessa_ex_full_001_neutral":           "vanessa_ex_full_001_neutral_001",       # Auto: Edited and renamed
  "vanessa_ex_full_001_smile":             "vanessa_ex_full_001_smile_001",         # Auto: Renamed
  "vanessa_ex_full_002":                   "vanessa_ex_full_002_smile_001",         # Auto: Renamed
  "vanessa_ex_full_002_smile":             "vanessa_ex_full_002_001",               # Auto: Renamed
  "vanessa_ex_full_003":                   "vanessa_ex_full_004_open_001",          # Auto: Renamed
  "vanessa_ex_full_003_smile":             "vanessa_ex_full_004_smile_001",         # Auto: Renamed
  "vanessa_ex_full_004":                   "vanessa_ex_full_004_open2_001",         # Auto: Renamed
  "vanessa_ex_full_005":                   "vanessa_ex_full_006_open_001",          # Auto: Renamed
  "vanessa_ex_full_006":                   "vanessa_ex_full_006_001",               # Auto: Edited and renamed
  "vanessa_ex_full_007":                   "vanessa_ex_full_005_aroused2_001",      # Auto: Renamed
  "vanessa_ex_full_008":                   "vanessa_ex_full_002_smile2_001",        # Auto: Renamed
  "vanessa_ex_full_009":                   "vanessa_ex_full_009_002",               # Auto: Renamed
  "vanessa_ex_full_010":                   "vanessa_ex_full_011_002",               # Auto: Renamed
  "vanessa_ex_full_011":                   "vanessa_ex_full_011_002",               # Auto: Edited and renamed
  "vanessa_ex_full_012":                   "vanessa_ex_full_012_002",               # Auto: Renamed
  "vanessa_ex_full_013":                   "vanessa_ex_full_008_002",               # Auto: Renamed
  "vanessa_ex_full_014":                   "vanessa_ex_full_010_open_002",          # Auto: Renamed
  "vanessa_ex_full_015":                   "vanessa_ex_full_013_002",               # Auto: Renamed
  "vanessa_ex_full_016":                   "vanessa_ex_full_010_open2_002",         # Auto: Renamed
  "vanessa_ex_full_017":                   "vanessa_ex_full_009_open_002",          # Auto: Renamed
  "vanessa_ex_full_018":                   "vanessa_ex_full_003_irked_003",         # Auto: Renamed
  "vanessa_ex_full_018_open":              "vanessa_ex_full_003_irked2_003",        # Auto: Renamed
  "vanessa_ex_full_018_smile":             "vanessa_ex_full_003_irked3_003",        # Auto: Renamed
  "vanessa_ex_full_019":                   "vanessa_ex_full_003_open2_003",         # Auto: Renamed
  "vanessa_ex_full_019_grin":              "vanessa_ex_full_003_grin_003",          # Auto: Renamed
  "vanessa_ex_full_019_grin2":             "vanessa_ex_full_003_grin2_003",         # Auto: Renamed
  "vanessa_ex_full_020":                   "vanessa_ex_full_007_003",               # Auto: Renamed
  "vanessa_ex_full_021":                   "vanessa_ex_full_011_open_003",          # Auto: Renamed
}
