characterMapKaryn = {
  "karyn_base_001":                        "karyn_base_001",                        # Auto: Edited
  "karyn_base_002":                        "karyn_base_002",                        # Auto: Edited
  "karyn_base_003":                        "karyn_base_003",                        # Auto: Edited
  "karyn_base_be1_001":                    "",                                      # Auto: Deleted
  "karyn_base_be1_002":                    "karyn_be1_002",                         # Auto: Renamed
  "karyn_base_be1_003":                    "",                                      # Auto: Deleted
  "karyn_base_breast_002":                 "karyn_be0_002",                         # Auto: Renamed
  "karyn_base_casual_001":                 "",                                      # Auto: Deleted
  "karyn_base_casual_002":                 "",                                      # Auto: Deleted
  "karyn_base_casual_003":                 "",                                      # Auto: Deleted
  "karyn_base_cheer_001":                  "karyn_base_cheer_001",                  # Auto: Edited
  "karyn_base_cheer_002":                  "karyn_base_cheer_002",                  # Auto: Edited
  "karyn_base_cheer_003":                  "karyn_base_cheer_003",                  # Auto: Edited
  "karyn_base_cheer_be1_001":              "karyn_be1_cheer_001",                   # Auto: Renamed
  "karyn_base_cheer_be1_002":              "karyn_be1_cheer_002",                   # Auto: Renamed
  "karyn_base_cheer_be1_003":              "",                                      # Auto: Deleted
  "karyn_base_cosplay_001":                "karyn_base_cosplay_001",                # Auto: Edited
  "karyn_base_cosplay_002":                "karyn_base_cosplay_002",                # Auto: Edited
  "karyn_base_cosplay_003":                "karyn_base_cosplay_003",                # Auto: Edited
  "karyn_base_cosplay_be1_001":            "karyn_be1_cosplay_001",                 # Auto: Renamed
  "karyn_base_cosplay_be1_002":            "karyn_be1_cosplay_002",                 # Auto: Renamed
  "karyn_base_cosplay_be1_003":            "",                                      # Auto: Deleted
  "karyn_base_cosplay_breast_002":         "karyn_be0_cosplay_002",                 # Auto: Renamed
  "karyn_base_full_001":                   "karyn_base_full_001",                   # Auto: Same
  "karyn_base_full_002":                   "karyn_base_full_002",                   # Auto: Edited
  "karyn_base_full_003":                   "karyn_base_full_003",                   # Auto: Edited
  "karyn_base_full_be1_001":               "karyn_be1_full_001",                    # Auto: Renamed
  "karyn_base_full_be1_002":               "karyn_be1_full_002",                    # Auto: Renamed
  "karyn_base_full_be1_003":               "karyn_be1_full_003",                    # Auto: Renamed
  "karyn_base_full_breast_002":            "karyn_be0_full_002",                    # Auto: Renamed
  "karyn_base_full_casual_001":            "karyn_base_full_cas_001",               # Auto: Renamed
  "karyn_base_full_casual_002":            "",                                      # Auto: Deleted
  "karyn_base_full_casual_003":            "",                                      # Auto: Deleted
  "karyn_base_full_cheer_001":             "karyn_base_full_cheer_001",             # Auto: Same
  "karyn_base_full_cheer_002":             "karyn_base_full_cheer_002",             # Auto: Edited
  "karyn_base_full_cheer_003":             "karyn_base_full_cheer_003",             # Auto: Edited
  "karyn_base_full_cheer_be1_001":         "karyn_be1_full_cheer_001",              # Auto: Renamed
  "karyn_base_full_cheer_be1_002":         "karyn_be1_full_cheer_002",              # Auto: Renamed
  "karyn_base_full_cheer_be1_003":         "karyn_be1_full_cheer_003",              # Auto: Renamed
  "karyn_base_full_cosplay_001":           "karyn_base_full_cosplay_001",           # Auto: Same
  "karyn_base_full_cosplay_002":           "karyn_base_full_cosplay_002",           # Auto: Edited
  "karyn_base_full_cosplay_003":           "karyn_base_full_cosplay_003",           # Auto: Edited
  "karyn_base_full_cosplay_be1_001":       "karyn_be1_full_cosplay_001",            # Auto: Renamed
  "karyn_base_full_cosplay_be1_002":       "karyn_be1_full_cosplay_002",            # Auto: Renamed
  "karyn_base_full_cosplay_be1_003":       "karyn_be1_full_cosplay_003",            # Auto: Renamed
  "karyn_base_full_cosplay_breast_002":    "karyn_be0_full_cosplay_002",            # Auto: Renamed
  "karyn_base_full_naked_001":             "karyn_base_full_naked_001",             # Auto: Same
  "karyn_base_full_naked_002":             "karyn_base_full_naked_002",             # Auto: Edited
  "karyn_base_full_naked_003":             "karyn_base_full_naked_003",             # Auto: Edited
  "karyn_base_full_naked_be1_001":         "karyn_be1_full_naked_001",              # Auto: Renamed
  "karyn_base_full_naked_be1_002":         "karyn_be1_full_naked_002",              # Auto: Renamed
  "karyn_base_full_naked_be1_003":         "karyn_be1_full_naked_003",              # Auto: Renamed
  "karyn_base_full_naked_breast_003":      "karyn_be0_full_naked_003",              # Auto: Renamed
  "karyn_base_full_under_001":             "karyn_base_full_under_001",             # Auto: Same
  "karyn_base_full_under_002":             "karyn_base_full_under_002",             # Auto: Edited
  "karyn_base_full_under_003":             "karyn_base_full_under_003",             # Auto: Edited
  "karyn_base_full_under_be1_001":         "karyn_be1_full_under_001",              # Auto: Renamed
  "karyn_base_full_under_be1_002":         "karyn_be1_full_under_002",              # Auto: Renamed
  "karyn_base_full_under_be1_003":         "karyn_be1_full_under_003",              # Auto: Renamed
  "karyn_base_naked_001":                  "karyn_base_naked_001",                  # Auto: Edited
  "karyn_base_naked_002":                  "karyn_base_naked_002",                  # Auto: Edited
  "karyn_base_naked_003":                  "karyn_base_naked_003",                  # Auto: Edited
  "karyn_base_naked_be1_001":              "karyn_be1_naked_001",                   # Auto: Renamed
  "karyn_base_naked_be1_002":              "",                                      # Auto: Deleted
  "karyn_base_naked_be1_003":              "",                                      # Auto: Deleted
  "karyn_base_naked_breast_003":           "",                                      # Auto: Deleted
  "karyn_base_under_001":                  "karyn_base_under_001",                  # Auto: Edited
  "karyn_base_under_002":                  "karyn_base_under_002",                  # Auto: Edited
  "karyn_base_under_003":                  "karyn_base_under_003",                  # Auto: Edited
  "karyn_base_under_be1_001":              "karyn_be1_under_001",                   # Auto: Renamed
  "karyn_base_under_be1_002":              "",                                      # Auto: Deleted
  "karyn_base_under_be1_003":              "",                                      # Auto: Deleted
  "karyn_ex_001":                          "karyn_ex_001_001",                      # Auto: Renamed
  "karyn_ex_001_neutral":                  "karyn_ex_001_neutral_001",              # Auto: Edited and renamed
  "karyn_ex_001_smile":                    "karyn_ex_001_smile_001",                # Auto: Renamed
  "karyn_ex_002":                          "karyn_ex_002_smile_001",                # Auto: Renamed
  "karyn_ex_002_smile":                    "karyn_ex_002_001",                      # Auto: Renamed
  "karyn_ex_003":                          "karyn_ex_003_irked_001",                # Auto: Renamed
  "karyn_ex_003_open":                     "karyn_ex_003_irked2_001",               # Auto: Renamed
  "karyn_ex_004":                          "karyn_ex_003_open2_001",                # Auto: Renamed
  "karyn_ex_004_grin":                     "karyn_ex_003_grin_001",                 # Auto: Renamed
  "karyn_ex_004_grin2":                    "karyn_ex_003_grin2_001",                # Auto: Renamed
  "karyn_ex_004_open":                     "karyn_ex_003_open_001",                 # Auto: Renamed
  "karyn_ex_005":                          "karyn_ex_004_open2_001",                # Auto: Renamed
  "karyn_ex_005_smile":                    "karyn_ex_004_smile_001",                # Auto: Renamed
  "karyn_ex_006":                          "karyn_ex_006_open_001",                 # Auto: Renamed
  "karyn_ex_007":                          "karyn_ex_003_grit_001",                 # Auto: Renamed
  "karyn_ex_008":                          "karyn_ex_001_grin_001",                 # Auto: Renamed
  "karyn_ex_009":                          "karyn_ex_003_mad_001",                  # Auto: Renamed
  "karyn_ex_010":                          "karyn_ex_010_open_002",                 # Auto: Renamed
  "karyn_ex_011":                          "karyn_ex_012_002",                      # Auto: Renamed
  "karyn_ex_012":                          "karyn_ex_008_002",                      # Auto: Renamed
  "karyn_ex_013":                          "karyn_ex_008_open_002",                 # Auto: Renamed
  "karyn_ex_014":                          "karyn_ex_0013_002",                     # Auto: Renamed
  "karyn_ex_015":                          "karyn_ex_014_002",                      # Auto: Renamed
  "karyn_ex_016":                          "karyn_ex_015_002",                      # Auto: Renamed
  "karyn_ex_017":                          "karyn_ex_017_003",                      # Auto: Edited and renamed
  "karyn_ex_018":                          "karyn_ex_018_003",                      # Auto: Edited and renamed
  "karyn_ex_019":                          "karyn_ex_019_003",                      # Auto: Edited and renamed
  "karyn_ex_020":                          "",                                      # Auto: Deleted
  "karyn_ex_021":                          "",                                      # Auto: Deleted
  "karyn_ex_022":                          "",                                      # Auto: Deleted
  "karyn_ex_full_001":                     "karyn_ex_full_001_001",                 # Auto: Renamed
  "karyn_ex_full_001_smile":               "karyn_ex_full_001_smile_001",           # Auto: Renamed
  "karyn_ex_full_002":                     "karyn_ex_full_002_smile_001",           # Auto: Renamed
  "karyn_ex_full_002_smile":               "karyn_ex_full_002_001",                 # Auto: Renamed
  "karyn_ex_full_003":                     "karyn_ex_full_003_irked_001",           # Auto: Renamed
  "karyn_ex_full_003_open":                "karyn_ex_full_003_irked2_001",          # Auto: Renamed
  "karyn_ex_full_004":                     "karyn_ex_full_003_open2_001",           # Auto: Renamed
  "karyn_ex_full_004_grin":                "karyn_ex_full_003_grin_001",            # Auto: Renamed
  "karyn_ex_full_004_grin2":               "karyn_ex_full_003_grin2_001",           # Auto: Renamed
  "karyn_ex_full_004_open":                "karyn_ex_full_003_open_001",            # Auto: Renamed
  "karyn_ex_full_005":                     "karyn_ex_full_004_open2_001",           # Auto: Renamed
  "karyn_ex_full_005_smile":               "karyn_ex_full_004_smile_001",           # Auto: Renamed
  "karyn_ex_full_006":                     "karyn_ex_full_006_open_001",            # Auto: Renamed
  "karyn_ex_full_007":                     "karyn_ex_full_003_grit_001",            # Auto: Renamed
  "karyn_ex_full_008":                     "karyn_ex_full_001_grin_001",            # Auto: Renamed
  "karyn_ex_full_009":                     "karyn_ex_full_003_mad_001",             # Auto: Renamed
  "karyn_ex_full_010":                     "karyn_ex_full_010_open_002",            # Auto: Renamed
  "karyn_ex_full_011":                     "karyn_ex_full_012_002",                 # Auto: Renamed
  "karyn_ex_full_012":                     "karyn_ex_full_008_002",                 # Auto: Renamed
  "karyn_ex_full_013":                     "karyn_ex_full_008_open_002",            # Auto: Renamed
  "karyn_ex_full_014":                     "karyn_ex_full_0013_002",                # Auto: Renamed
  "karyn_ex_full_015":                     "karyn_ex_full_014_002",                 # Auto: Renamed
  "karyn_ex_full_016":                     "karyn_ex_full_015_002",                 # Auto: Renamed
  "karyn_ex_full_017":                     "karyn_ex_full_016_003",                 # Auto: Renamed
  "karyn_ex_full_018":                     "karyn_ex_full_009_003",                 # Auto: Renamed
  "karyn_ex_full_019":                     "karyn_ex_full_011_003",                 # Auto: Renamed
  "karyn_ex_full_020":                     "karyn_ex_full_017_003",                 # Auto: Renamed
  "karyn_ex_full_021":                     "karyn_ex_full_018_003",                 # Auto: Renamed
  "karyn_ex_full_022":                     "karyn_ex_full_019_003",                 # Auto: Renamed
}
