characterMapNurse = {
  "Nurse_BE1_001":                         "Nurse_BE1_001",                         # Auto: Same
  "Nurse_BE1_002":                         "Nurse_BE1_002",                         # Auto: Same
  "Nurse_BE1_003":                         "Nurse_BE1_003",                         # Auto: Same
  "Nurse_BE1_Full_001":                    "Nurse_BE1_Full_001",                    # Auto: Same
  "Nurse_BE1_Full_002":                    "Nurse_BE1_Full_002",                    # Auto: Same
  "Nurse_BE1_Full_003":                    "Nurse_BE1_Full_003",                    # Auto: Same
  "Nurse_BE1_Full_Naked_001":              "Nurse_BE1_Full_Naked_001",              # Auto: Same
  "Nurse_BE1_Full_Naked_002":              "Nurse_BE1_Full_Naked_002",              # Auto: Same
  "Nurse_BE1_Full_Naked_003":              "Nurse_BE1_Full_Naked_003",              # Auto: Same
  "Nurse_BE1_Full_Skimp_001":              "Nurse_BE1_Full_Skimp_001",              # Auto: Same
  "Nurse_BE1_Full_Skimp_002":              "Nurse_BE1_Full_Skimp_002",              # Auto: Same
  "Nurse_BE1_Full_Skimp_003":              "Nurse_BE1_Full_Skimp_003",              # Auto: Same
  "Nurse_BE1_Full_Under_001":              "Nurse_BE1_Full_Under_001",              # Auto: Same
  "Nurse_BE1_Full_Under_002":              "Nurse_BE1_Full_Under_002",              # Auto: Same
  "Nurse_BE1_Full_Under_003":              "Nurse_BE1_Full_Under_003",              # Auto: Same
  "Nurse_BE1_Naked_001":                   "Nurse_BE1_Naked_001",                   # Auto: Same
  "Nurse_BE1_Naked_002":                   "Nurse_BE1_Naked_002",                   # Auto: Same
  "Nurse_BE1_Naked_003":                   "Nurse_BE1_Naked_003",                   # Auto: Same
  "Nurse_BE1_Skimp_001":                   "Nurse_BE1_Skimp_001",                   # Auto: Same
  "Nurse_BE1_Skimp_002":                   "Nurse_BE1_Skimp_002",                   # Auto: Same
  "Nurse_BE1_Skimp_003":                   "Nurse_BE1_Skimp_003",                   # Auto: Same
  "Nurse_BE1_Under_001":                   "Nurse_BE1_Under_001",                   # Auto: Same
  "Nurse_BE1_Under_002":                   "Nurse_BE1_Under_002",                   # Auto: Same
  "Nurse_BE1_Under_003":                   "Nurse_BE1_Under_003",                   # Auto: Same
  "Nurse_Base_001":                        "Nurse_Base_001",                        # Auto: Edited
  "Nurse_Base_002":                        "Nurse_Base_002",                        # Auto: Edited
  "Nurse_Base_003":                        "Nurse_Base_003",                        # Auto: Edited
  "Nurse_Base_Full_001":                   "Nurse_Base_Full_001",                   # Auto: Same
  "Nurse_Base_Full_002":                   "Nurse_Base_Full_002",                   # Auto: Same
  "Nurse_Base_Full_003":                   "Nurse_Base_Full_003",                   # Auto: Same
  "Nurse_Base_Full_Naked_001":             "Nurse_Base_Full_Naked_001",             # Auto: Same
  "Nurse_Base_Full_Naked_002":             "Nurse_Base_Full_Naked_002",             # Auto: Same
  "Nurse_Base_Full_Naked_003":             "Nurse_Base_Full_Naked_003",             # Auto: Same
  "Nurse_Base_Full_Skimp_001":             "Nurse_Base_Full_Skimp_001",             # Auto: Same
  "Nurse_Base_Full_Skimp_002":             "Nurse_Base_Full_Skimp_002",             # Auto: Same
  "Nurse_Base_Full_Skimp_003":             "Nurse_Base_Full_Skimp_003",             # Auto: Same
  "Nurse_Base_Full_Under_001":             "Nurse_Base_Full_Under_001",             # Auto: Same
  "Nurse_Base_Full_Under_002":             "Nurse_Base_Full_Under_002",             # Auto: Same
  "Nurse_Base_Full_Under_003":             "Nurse_Base_Full_Under_003",             # Auto: Same
  "Nurse_Base_Naked_001":                  "Nurse_Base_Naked_001",                  # Auto: Edited
  "Nurse_Base_Naked_002":                  "Nurse_Base_Naked_002",                  # Auto: Edited
  "Nurse_Base_Naked_003":                  "Nurse_Base_Naked_003",                  # Auto: Edited
  "Nurse_Base_Skimp_001":                  "Nurse_Base_Skimp_001",                  # Auto: Edited
  "Nurse_Base_Skimp_002":                  "Nurse_Base_Skimp_002",                  # Auto: Edited
  "Nurse_Base_Skimp_003":                  "Nurse_Base_Skimp_003",                  # Auto: Edited
  "Nurse_Base_Under_001":                  "Nurse_Base_Under_001",                  # Auto: Edited
  "Nurse_Base_Under_002":                  "Nurse_Base_Under_002",                  # Auto: Edited
  "Nurse_Base_Under_003":                  "Nurse_Base_Under_003",                  # Auto: Edited
  "Nurse_Ex_001_001":                      "Nurse_Ex_001_001",                      # Auto: Same
  "Nurse_Ex_001_Neutral_001":              "Nurse_Ex_001_Neutral_001",              # Auto: Same
  "Nurse_Ex_001_Smile_001":                "Nurse_Ex_001_Smile_001",                # Auto: Same
  "Nurse_Ex_002_001":                      "Nurse_Ex_002_Smile_001",                # Auto: Renamed
  "Nurse_Ex_002_Smile_001":                "Nurse_Ex_002_001",                      # Auto: Renamed
  "Nurse_Ex_003_001":                      "Nurse_Ex_003_Irked_001",                # Auto: Renamed
  "Nurse_Ex_003_Grin2_001":                "Nurse_Ex_003_Smile2_001",               # Auto: Renamed
  "Nurse_Ex_003_Grin_001":                 "",                                      # Auto: Deleted
  "Nurse_Ex_003_Open2_002":                "Nurse_Ex_003_Open2_002",                # Auto: Same
  "Nurse_Ex_003_Open_001":                 "Nurse_Ex_003_Irked2_001",               # Auto: Renamed
  "Nurse_Ex_004_001":                      "Nurse_Ex_004_Open_001",                 # Auto: Renamed
  "Nurse_Ex_004_Closed_001":               "Nurse_Ex_004_001",                      # Auto: Renamed
  "Nurse_Ex_004_Smile_001":                "Nurse_Ex_004_Smile_001",                # Auto: Edited
  "Nurse_Ex_005_001":                      "Nurse_Ex_005_001",                      # Auto: Same
  "Nurse_Ex_005_Open_001":                 "Nurse_Ex_005_Open_001",                 # Auto: Same
  "Nurse_Ex_005_Smile2_001":               "Nurse_Ex_005_Smile2_001",               # Auto: Same
  "Nurse_Ex_005_Smile_001":                "Nurse_Ex_005_Smile_001",                # Auto: Same
  "Nurse_Ex_006_001":                      "Nurse_Ex_006_001",                      # Auto: Same
  "Nurse_Ex_006_Open_001":                 "Nurse_Ex_006_Open_001",                 # Auto: Same
  "Nurse_Ex_006_Smile2_001":               "Nurse_Ex_006_Smile2_001",               # Auto: Same
  "Nurse_Ex_006_Smile_001":                "Nurse_Ex_006_Smile_001",                # Auto: Same
  "Nurse_Ex_007_001":                      "Nurse_Ex_005_Aroused2_001",             # Auto: Renamed
  "Nurse_Ex_008_002":                      "",                                      # Auto: Deleted
  "Nurse_Ex_009_002":                      "Nurse_Ex_003_Grin_002",                 # Auto: Renamed
  "Nurse_Ex_010_002":                      "Nurse_Ex_012_002",                      # Auto: Renamed
  "Nurse_Ex_011_003":                      "Nurse_Ex_007_003",                      # Auto: Renamed
  "Nurse_Ex_012_003":                      "Nurse_Ex_008_003",                      # Auto: Renamed
  "Nurse_Ex_013_003":                      "Nurse_Ex_013_003",                      # Auto: Same
  "Nurse_Ex_Full_001_001":                 "Nurse_Ex_Full_001_001",                 # Auto: Same
  "Nurse_Ex_Full_001_Neutral_001":         "Nurse_Ex_Full_001_Neutral_001",         # Auto: Same
  "Nurse_Ex_Full_001_Smile_001":           "Nurse_Ex_Full_001_Smile_001",           # Auto: Same
  "Nurse_Ex_Full_002_001":                 "Nurse_Ex_Full_002_Smile_001",           # Auto: Renamed
  "Nurse_Ex_Full_002_Smile_001":           "Nurse_Ex_Full_002_001",                 # Auto: Renamed
  "Nurse_Ex_Full_003_001":                 "Nurse_Ex_Full_003_Irked_001",           # Auto: Renamed
  "Nurse_Ex_Full_003_Grin2_001":           "Nurse_Ex_Full_003_Smile2_001",          # Auto: Renamed
  "Nurse_Ex_Full_003_Grin_001":            "",                                      # Auto: Deleted
  "Nurse_Ex_Full_003_Open2_002":           "Nurse_Ex_Full_003_Open2_002",           # Auto: Same
  "Nurse_Ex_Full_003_Open_001":            "Nurse_Ex_Full_003_Irked2_001",          # Auto: Renamed
  "Nurse_Ex_Full_004_001":                 "Nurse_Ex_Full_004_Open_001",            # Auto: Renamed
  "Nurse_Ex_Full_004_Closed_001":          "Nurse_Ex_Full_004_001",                 # Auto: Renamed
  "Nurse_Ex_Full_004_Smile_001":           "Nurse_Ex_Full_004_Smile_001",           # Auto: Edited
  "Nurse_Ex_Full_005_001":                 "Nurse_Ex_Full_005_001",                 # Auto: Same
  "Nurse_Ex_Full_005_Open_001":            "Nurse_Ex_Full_005_Open_001",            # Auto: Same
  "Nurse_Ex_Full_005_Smile2_001":          "Nurse_Ex_Full_005_Smile2_001",          # Auto: Same
  "Nurse_Ex_Full_005_Smile_001":           "Nurse_Ex_Full_005_Smile_001",           # Auto: Same
  "Nurse_Ex_Full_006_001":                 "Nurse_Ex_Full_006_001",                 # Auto: Same
  "Nurse_Ex_Full_006_Open_001":            "Nurse_Ex_Full_006_Open_001",            # Auto: Same
  "Nurse_Ex_Full_006_Smile2_001":          "Nurse_Ex_Full_006_Smile2_001",          # Auto: Same
  "Nurse_Ex_Full_006_Smile_001":           "Nurse_Ex_Full_006_Smile_001",           # Auto: Same
  "Nurse_Ex_Full_007_001":                 "Nurse_Ex_Full_005_Aroused2_001",        # Auto: Renamed
  "Nurse_Ex_Full_008_002":                 "",                                      # Auto: Deleted
  "Nurse_Ex_Full_009_002":                 "Nurse_Ex_Full_003_Grin_002",            # Auto: Renamed
  "Nurse_Ex_Full_010_002":                 "Nurse_Ex_Full_012_002",                 # Auto: Renamed
  "Nurse_Ex_Full_011_003":                 "Nurse_Ex_Full_007_003",                 # Auto: Renamed
  "Nurse_Ex_Full_012_003":                 "Nurse_Ex_Full_008_003",                 # Auto: Renamed
  "Nurse_Ex_Full_013_003":                 "Nurse_Ex_Full_013_003",                 # Auto: Same
}
