characterMapKaryn = {
  "karyn_be0_002":                         "karyn_be0_002",                         # Auto: Same
  "karyn_be0_cosplay_002":                 "karyn_be0_cosplay_002",                 # Auto: Same
  "karyn_be0_full_002":                    "karyn_be0_full_002",                    # Auto: Same
  "karyn_be0_full_cosplay_002":            "karyn_be0_full_cosplay_002",            # Auto: Same
  "karyn_be0_full_naked_003":              "karyn_be0_full_naked_003",              # Auto: Same
  "karyn_be0_naked_003":                   "karyn_be0_naked_003",                   # Auto: Edited
  "karyn_be1_001":                         "karyn_be1_001",                         # Auto: Edited
  "karyn_be1_002":                         "karyn_be1_002",                         # Auto: Same
  "karyn_be1_003":                         "karyn_be1_003",                         # Auto: Edited
  "karyn_be1_cheer_001":                   "karyn_be1_cheer_001",                   # Auto: Same
  "karyn_be1_cheer_002":                   "karyn_be1_cheer_002",                   # Auto: Same
  "karyn_be1_cheer_003":                   "karyn_be1_cheer_003",                   # Auto: Edited
  "karyn_be1_cosplay_001":                 "karyn_be1_cosplay_001",                 # Auto: Same
  "karyn_be1_cosplay_002":                 "karyn_be1_cosplay_002",                 # Auto: Same
  "karyn_be1_cosplay_003":                 "karyn_be1_cosplay_003",                 # Auto: Edited
  "karyn_be1_full_001":                    "karyn_be1_full_001",                    # Auto: Same
  "karyn_be1_full_002":                    "karyn_be1_full_002",                    # Auto: Same
  "karyn_be1_full_003":                    "karyn_be1_full_003",                    # Auto: Same
  "karyn_be1_full_cheer_001":              "karyn_be1_full_cheer_001",              # Auto: Same
  "karyn_be1_full_cheer_002":              "karyn_be1_full_cheer_002",              # Auto: Same
  "karyn_be1_full_cheer_003":              "karyn_be1_full_cheer_003",              # Auto: Same
  "karyn_be1_full_cosplay_001":            "karyn_be1_full_cosplay_001",            # Auto: Same
  "karyn_be1_full_cosplay_002":            "karyn_be1_full_cosplay_002",            # Auto: Same
  "karyn_be1_full_cosplay_003":            "karyn_be1_full_cosplay_003",            # Auto: Same
  "karyn_be1_full_naked_001":              "karyn_be1_full_naked_001",              # Auto: Same
  "karyn_be1_full_naked_002":              "karyn_be1_full_naked_002",              # Auto: Same
  "karyn_be1_full_naked_003":              "karyn_be1_full_naked_003",              # Auto: Same
  "karyn_be1_full_under_001":              "karyn_be1_full_under_001",              # Auto: Same
  "karyn_be1_full_under_002":              "karyn_be1_full_under_002",              # Auto: Same
  "karyn_be1_full_under_003":              "karyn_be1_full_under_003",              # Auto: Same
  "karyn_be1_naked_001":                   "karyn_be1_naked_001",                   # Auto: Same
  "karyn_be1_naked_002":                   "karyn_be1_naked_002",                   # Auto: Edited
  "karyn_be1_naked_003":                   "karyn_be1_naked_003",                   # Auto: Edited
  "karyn_be1_under_001":                   "karyn_be1_under_001",                   # Auto: Same
  "karyn_be1_under_002":                   "karyn_be1_under_002",                   # Auto: Edited
  "karyn_be1_under_003":                   "karyn_be1_under_003",                   # Auto: Edited
  "karyn_base_001":                        "karyn_base_001",                        # Auto: Edited
  "karyn_base_002":                        "karyn_base_002",                        # Auto: Edited
  "karyn_base_003":                        "karyn_base_003",                        # Auto: Edited
  "karyn_base_cas_001":                    "karyn_base_cas_001",                    # Auto: Edited
  "karyn_base_cas_002":                    "karyn_base_cas_002",                    # Auto: Edited
  "karyn_base_cas_003":                    "karyn_base_cas_003",                    # Auto: Edited
  "karyn_base_cheer_001":                  "karyn_base_cheer_001",                  # Auto: Edited
  "karyn_base_cheer_002":                  "karyn_base_cheer_002",                  # Auto: Edited
  "karyn_base_cheer_003":                  "karyn_base_cheer_003",                  # Auto: Edited
  "karyn_base_cosplay_001":                "karyn_base_cosplay_001",                # Auto: Edited
  "karyn_base_cosplay_002":                "karyn_base_cosplay_002",                # Auto: Edited
  "karyn_base_cosplay_003":                "karyn_base_cosplay_003",                # Auto: Edited
  "karyn_base_full_001":                   "karyn_base_full_001",                   # Auto: Same
  "karyn_base_full_002":                   "karyn_base_full_002",                   # Auto: Edited
  "karyn_base_full_003":                   "karyn_base_full_003",                   # Auto: Edited
  "karyn_base_full_cas_001":               "karyn_base_full_cas_001",               # Auto: Same
  "karyn_base_full_cas_002":               "karyn_base_full_cas_002",               # Auto: Edited
  "karyn_base_full_cas_003":               "karyn_base_full_cas_003",               # Auto: Edited
  "karyn_base_full_cheer_001":             "karyn_base_full_cheer_001",             # Auto: Same
  "karyn_base_full_cheer_002":             "karyn_base_full_cheer_002",             # Auto: Edited
  "karyn_base_full_cheer_003":             "karyn_base_full_cheer_003",             # Auto: Edited
  "karyn_base_full_cosplay_001":           "karyn_base_full_cosplay_001",           # Auto: Same
  "karyn_base_full_cosplay_002":           "karyn_base_full_cosplay_002",           # Auto: Edited
  "karyn_base_full_cosplay_003":           "karyn_base_full_cosplay_003",           # Auto: Edited
  "karyn_base_full_naked_001":             "karyn_base_full_naked_001",             # Auto: Same
  "karyn_base_full_naked_002":             "karyn_base_full_naked_002",             # Auto: Edited
  "karyn_base_full_naked_003":             "karyn_base_full_naked_003",             # Auto: Edited
  "karyn_base_full_under_001":             "karyn_base_full_under_001",             # Auto: Same
  "karyn_base_full_under_002":             "karyn_base_full_under_002",             # Auto: Edited
  "karyn_base_full_under_003":             "karyn_base_full_under_003",             # Auto: Edited
  "karyn_base_naked_001":                  "karyn_base_naked_001",                  # Auto: Edited
  "karyn_base_naked_002":                  "karyn_base_naked_002",                  # Auto: Edited
  "karyn_base_naked_003":                  "karyn_base_naked_003",                  # Auto: Edited
  "karyn_base_under_001":                  "karyn_base_under_001",                  # Auto: Edited
  "karyn_base_under_002":                  "karyn_base_under_002",                  # Auto: Edited
  "karyn_base_under_003":                  "karyn_base_under_003",                  # Auto: Edited
  "karyn_ex_001_001":                      "karyn_ex_001_001",                      # Auto: Same
  "karyn_ex_001_neutral_001":              "karyn_ex_001_neutral_001",              # Auto: Edited
  "karyn_ex_001_open_001":                 "karyn_ex_001_open_001",                 # Auto: Edited
  "karyn_ex_001_smile_001":                "karyn_ex_001_smile_001",                # Auto: Same
  "karyn_ex_002_001":                      "karyn_ex_002_smile_001",                # Auto: Renamed
  "karyn_ex_002_smile_001":                "karyn_ex_002_001",                      # Auto: Renamed
  "karyn_ex_003_001":                      "karyn_ex_003_irked_001",                # Auto: Renamed
  "karyn_ex_003_open_001":                 "karyn_ex_003_irked2_001",               # Auto: Renamed
  "karyn_ex_004_001":                      "karyn_ex_003_open2_001",                # Auto: Renamed
  "karyn_ex_004_grin2_001":                "karyn_ex_003_grin2_001",                # Auto: Renamed
  "karyn_ex_004_grin_001":                 "karyn_ex_003_grin_001",                 # Auto: Renamed
  "karyn_ex_004_open_001":                 "karyn_ex_003_open_001",                 # Auto: Renamed
  "karyn_ex_005_001":                      "karyn_ex_004_open2_001",                # Auto: Renamed
  "karyn_ex_005_closed_001":               "Karyn_Ex_004_001",                                      # Auto: Deleted
  "karyn_ex_005_smile_001":                "karyn_ex_004_smile_001",                # Auto: Renamed
  "karyn_ex_006_001":                      "karyn_ex_006_open_001",                 # Auto: Renamed
  "karyn_ex_006_closed_001":               "Karyn_Ex_006_001",                                      # Auto: Deleted
  "karyn_ex_006_open2_001":                "karyn_ex_006_open2_001",                # Auto: Edited
  "karyn_ex_006_open_001":                 "karyn_ex_006_open_001",                 # Auto: Edited
  "karyn_ex_006_smile2_001":               "karyn_ex_006_smile2_001",               # Auto: Edited
  "karyn_ex_006_smile_001":                "karyn_ex_006_smile_001",                # Auto: Edited
  "karyn_ex_007_001":                      "karyn_ex_003_grit_001",                 # Auto: Renamed
  "karyn_ex_008_001":                      "karyn_ex_001_grin_001",                 # Auto: Renamed
  "karyn_ex_009_001":                      "karyn_ex_003_mad_001",                  # Auto: Renamed
  "karyn_ex_010_002":                      "karyn_ex_010_open_002",                 # Auto: Renamed
  "karyn_ex_011_002":                      "karyn_ex_012_002",                      # Auto: Renamed
  "karyn_ex_012_002":                      "karyn_ex_008_002",                      # Auto: Renamed
  "karyn_ex_013_002":                      "karyn_ex_008_open_002",                 # Auto: Renamed
  "karyn_ex_014_002":                      "karyn_ex_0013_002",                     # Auto: Renamed
  "karyn_ex_015_002":                      "karyn_ex_014_002",                      # Auto: Renamed
  "karyn_ex_016_002":                      "karyn_ex_015_002",                      # Auto: Renamed
  "karyn_ex_017_003":                      "karyn_ex_017_003",                      # Auto: Edited
  "karyn_ex_018_003":                      "karyn_ex_018_003",                      # Auto: Edited
  "karyn_ex_019_003":                      "karyn_ex_019_003",                      # Auto: Edited
  "karyn_ex_020_003":                      "Karyn_Ex_017_003",                                      # Auto: Deleted
  "karyn_ex_021_003":                      "karyn_ex_018_003",                                      # Auto: Deleted
  "karyn_ex_022_003":                      "karyn_ex_019_003",                                      # Auto: Deleted
  "karyn_ex_full_001_001":                 "karyn_ex_full_001_001",                 # Auto: Same
  "karyn_ex_full_001_neutral_001":         "karyn_ex_full_001_neutral_001",         # Auto: Same
  "karyn_ex_full_001_open_001":            "karyn_ex_full_001_open_001",            # Auto: Same
  "karyn_ex_full_001_smile_001":           "karyn_ex_full_001_smile_001",           # Auto: Same
  "karyn_ex_full_002_001":                 "karyn_ex_full_002_smile_001",           # Auto: Renamed
  "karyn_ex_full_002_smile_001":           "karyn_ex_full_002_001",                 # Auto: Renamed
  "karyn_ex_full_003_001":                 "karyn_ex_full_003_irked_001",           # Auto: Renamed
  "karyn_ex_full_003_open_001":            "karyn_ex_full_003_irked2_001",          # Auto: Renamed
  "karyn_ex_full_004_001":                 "karyn_ex_full_003_open2_001",           # Auto: Renamed
  "karyn_ex_full_004_grin2_001":           "karyn_ex_full_003_grin2_001",           # Auto: Renamed
  "karyn_ex_full_004_grin_001":            "karyn_ex_full_003_grin_001",            # Auto: Renamed
  "karyn_ex_full_004_open_001":            "karyn_ex_full_003_open_001",            # Auto: Renamed
  "karyn_ex_full_005_001":                 "karyn_ex_full_004_open2_001",           # Auto: Renamed
  "karyn_ex_full_005_closed_001":          "karyn_ex_full_004_001",                 # Auto: Renamed
  "karyn_ex_full_005_smile_001":           "karyn_ex_full_004_smile_001",           # Auto: Renamed
  "karyn_ex_full_006_001":                 "karyn_ex_full_006_open_001",            # Auto: Renamed
  "karyn_ex_full_006_closed_001":          "karyn_ex_full_006_001",                 # Auto: Renamed
  "karyn_ex_full_006_open2_001":           "karyn_ex_full_005_open_001",            # Auto: Renamed
  "karyn_ex_full_006_open_001":            "karyn_ex_full_005_001",                 # Auto: Renamed
  "karyn_ex_full_006_smile2_001":          "karyn_ex_full_005_aroused2_001",        # Auto: Renamed
  "karyn_ex_full_006_smile_001":           "karyn_ex_full_005_smile_001",           # Auto: Renamed
  "karyn_ex_full_007_001":                 "karyn_ex_full_003_grit_001",            # Auto: Renamed
  "karyn_ex_full_008_001":                 "karyn_ex_full_001_grin_001",            # Auto: Renamed
  "karyn_ex_full_009_001":                 "karyn_ex_full_003_mad_001",             # Auto: Renamed
  "karyn_ex_full_010_002":                 "karyn_ex_full_010_open_002",            # Auto: Renamed
  "karyn_ex_full_011_002":                 "karyn_ex_full_012_002",                 # Auto: Renamed
  "karyn_ex_full_012_002":                 "karyn_ex_full_008_002",                 # Auto: Renamed
  "karyn_ex_full_013_002":                 "karyn_ex_full_008_open_002",            # Auto: Renamed
  "karyn_ex_full_014_002":                 "karyn_ex_full_0013_002",                # Auto: Renamed
  "karyn_ex_full_015_002":                 "karyn_ex_full_014_002",                 # Auto: Renamed
  "karyn_ex_full_016_002":                 "karyn_ex_full_015_002",                 # Auto: Renamed
  "karyn_ex_full_017_003":                 "karyn_ex_full_016_003",                 # Auto: Renamed
  "karyn_ex_full_018_003":                 "karyn_ex_full_009_003",                 # Auto: Renamed
  "karyn_ex_full_019_003":                 "karyn_ex_full_011_003",                 # Auto: Renamed
  "karyn_ex_full_020_003":                 "karyn_ex_full_017_003",                 # Auto: Renamed
  "karyn_ex_full_021_003":                 "karyn_ex_full_018_003",                 # Auto: Renamed
  "karyn_ex_full_022_003":                 "karyn_ex_full_019_003",                 # Auto: Renamed
}
