characterMapKaryn = {
  "Karyn_BE0_002":                         "Karyn_BE0_002",                         # Auto: Same
  "Karyn_BE0_Cosplay_002":                 "Karyn_BE0_Cosplay_002",                 # Auto: Same
  "Karyn_BE0_Full_002":                    "Karyn_BE0_Full_002",                    # Auto: Same
  "Karyn_BE0_Full_Cosplay_002":            "Karyn_BE0_Full_Cosplay_002",            # Auto: Same
  "Karyn_BE0_Full_Naked_003":              "Karyn_BE0_Full_Naked_003",              # Auto: Same
  "Karyn_BE0_Naked_003":                   "Karyn_BE0_Naked_003",                   # Auto: Edited
  "Karyn_BE1_001":                         "Karyn_BE1_001",                         # Auto: Edited
  "Karyn_BE1_002":                         "Karyn_BE1_002",                         # Auto: Same
  "Karyn_BE1_003":                         "Karyn_BE1_003",                         # Auto: Edited
  "Karyn_BE1_Cheer_001":                   "Karyn_BE1_Cheer_001",                   # Auto: Same
  "Karyn_BE1_Cheer_002":                   "Karyn_BE1_Cheer_002",                   # Auto: Same
  "Karyn_BE1_Cheer_003":                   "Karyn_BE1_Cheer_003",                   # Auto: Edited
  "Karyn_BE1_Cosplay_001":                 "Karyn_BE1_Cosplay_001",                 # Auto: Same
  "Karyn_BE1_Cosplay_002":                 "Karyn_BE1_Cosplay_002",                 # Auto: Same
  "Karyn_BE1_Cosplay_003":                 "Karyn_BE1_Cosplay_003",                 # Auto: Edited
  "Karyn_BE1_Full_001":                    "Karyn_BE1_Full_001",                    # Auto: Same
  "Karyn_BE1_Full_002":                    "Karyn_BE1_Full_002",                    # Auto: Same
  "Karyn_BE1_Full_003":                    "Karyn_BE1_Full_003",                    # Auto: Same
  "Karyn_BE1_Full_Cheer_001":              "Karyn_BE1_Full_Cheer_001",              # Auto: Same
  "Karyn_BE1_Full_Cheer_002":              "Karyn_BE1_Full_Cheer_002",              # Auto: Same
  "Karyn_BE1_Full_Cheer_003":              "Karyn_BE1_Full_Cheer_003",              # Auto: Same
  "Karyn_BE1_Full_Cosplay_001":            "Karyn_BE1_Full_Cosplay_001",            # Auto: Same
  "Karyn_BE1_Full_Cosplay_002":            "Karyn_BE1_Full_Cosplay_002",            # Auto: Same
  "Karyn_BE1_Full_Cosplay_003":            "Karyn_BE1_Full_Cosplay_003",            # Auto: Same
  "Karyn_BE1_Full_Naked_001":              "Karyn_BE1_Full_Naked_001",              # Auto: Same
  "Karyn_BE1_Full_Naked_002":              "Karyn_BE1_Full_Naked_002",              # Auto: Same
  "Karyn_BE1_Full_Naked_003":              "Karyn_BE1_Full_Naked_003",              # Auto: Same
  "Karyn_BE1_Full_Under_001":              "Karyn_BE1_Full_Under_001",              # Auto: Same
  "Karyn_BE1_Full_Under_002":              "Karyn_BE1_Full_Under_002",              # Auto: Same
  "Karyn_BE1_Full_Under_003":              "Karyn_BE1_Full_Under_003",              # Auto: Same
  "Karyn_BE1_Naked_001":                   "Karyn_BE1_Naked_001",                   # Auto: Same
  "Karyn_BE1_Naked_002":                   "Karyn_BE1_Naked_002",                   # Auto: Edited
  "Karyn_BE1_Naked_003":                   "Karyn_BE1_Naked_003",                   # Auto: Edited
  "Karyn_BE1_Under_001":                   "Karyn_BE1_Under_001",                   # Auto: Same
  "Karyn_BE1_Under_002":                   "Karyn_BE1_Under_002",                   # Auto: Edited
  "Karyn_BE1_Under_003":                   "Karyn_BE1_Under_003",                   # Auto: Edited
  "Karyn_Base_001":                        "Karyn_Base_001",                        # Auto: Edited
  "Karyn_Base_002":                        "Karyn_Base_002",                        # Auto: Edited
  "Karyn_Base_003":                        "Karyn_Base_003",                        # Auto: Edited
  "Karyn_Base_Cas_001":                    "Karyn_Base_Cas_001",                    # Auto: Edited
  "Karyn_Base_Cas_002":                    "Karyn_Base_Cas_002",                    # Auto: Edited
  "Karyn_Base_Cas_003":                    "Karyn_Base_Cas_003",                    # Auto: Edited
  "Karyn_Base_Cheer_001":                  "Karyn_Base_Cheer_001",                  # Auto: Edited
  "Karyn_Base_Cheer_002":                  "Karyn_Base_Cheer_002",                  # Auto: Edited
  "Karyn_Base_Cheer_003":                  "Karyn_Base_Cheer_003",                  # Auto: Edited
  "Karyn_Base_Cosplay_001":                "Karyn_Base_Cosplay_001",                # Auto: Edited
  "Karyn_Base_Cosplay_002":                "Karyn_Base_Cosplay_002",                # Auto: Edited
  "Karyn_Base_Cosplay_003":                "Karyn_Base_Cosplay_003",                # Auto: Edited
  "Karyn_Base_Full_001":                   "Karyn_Base_Full_001",                   # Auto: Same
  "Karyn_Base_Full_002":                   "Karyn_Base_Full_002",                   # Auto: Edited
  "Karyn_Base_Full_003":                   "Karyn_Base_Full_003",                   # Auto: Edited
  "Karyn_Base_Full_Cas_001":               "Karyn_Base_Full_Cas_001",               # Auto: Same
  "Karyn_Base_Full_Cas_002":               "Karyn_Base_Full_Cas_002",               # Auto: Edited
  "Karyn_Base_Full_Cas_003":               "Karyn_Base_Full_Cas_003",               # Auto: Edited
  "Karyn_Base_Full_Cheer_001":             "Karyn_Base_Full_Cheer_001",             # Auto: Same
  "Karyn_Base_Full_Cheer_002":             "Karyn_Base_Full_Cheer_002",             # Auto: Edited
  "Karyn_Base_Full_Cheer_003":             "Karyn_Base_Full_Cheer_003",             # Auto: Edited
  "Karyn_Base_Full_Cosplay_001":           "Karyn_Base_Full_Cosplay_001",           # Auto: Same
  "Karyn_Base_Full_Cosplay_002":           "Karyn_Base_Full_Cosplay_002",           # Auto: Edited
  "Karyn_Base_Full_Cosplay_003":           "Karyn_Base_Full_Cosplay_003",           # Auto: Edited
  "Karyn_Base_Full_Naked_001":             "Karyn_Base_Full_Naked_001",             # Auto: Same
  "Karyn_Base_Full_Naked_002":             "Karyn_Base_Full_Naked_002",             # Auto: Edited
  "Karyn_Base_Full_Naked_003":             "Karyn_Base_Full_Naked_003",             # Auto: Edited
  "Karyn_Base_Full_Under_001":             "Karyn_Base_Full_Under_001",             # Auto: Same
  "Karyn_Base_Full_Under_002":             "Karyn_Base_Full_Under_002",             # Auto: Edited
  "Karyn_Base_Full_Under_003":             "Karyn_Base_Full_Under_003",             # Auto: Edited
  "Karyn_Base_Naked_001":                  "Karyn_Base_Naked_001",                  # Auto: Edited
  "Karyn_Base_Naked_002":                  "Karyn_Base_Naked_002",                  # Auto: Edited
  "Karyn_Base_Naked_003":                  "Karyn_Base_Naked_003",                  # Auto: Edited
  "Karyn_Base_Under_001":                  "Karyn_Base_Under_001",                  # Auto: Edited
  "Karyn_Base_Under_002":                  "Karyn_Base_Under_002",                  # Auto: Edited
  "Karyn_Base_Under_003":                  "Karyn_Base_Under_003",                  # Auto: Edited
  "Karyn_Ex_001_001":                      "Karyn_Ex_001_001",                      # Auto: Same
  "Karyn_Ex_001_Neutral_001":              "Karyn_Ex_001_Neutral_001",              # Auto: Edited
  "Karyn_Ex_001_Open_001":                 "Karyn_Ex_001_Open_001",                 # Auto: Edited
  "Karyn_Ex_001_Smile_001":                "Karyn_Ex_001_Smile_001",                # Auto: Same
  "Karyn_Ex_002_001":                      "Karyn_Ex_002_Smile_001",                # Auto: Renamed
  "Karyn_Ex_002_Smile_001":                "Karyn_Ex_002_001",                      # Auto: Renamed
  "Karyn_Ex_003_001":                      "Karyn_Ex_003_Irked_001",                # Auto: Renamed
  "Karyn_Ex_003_Open_001":                 "Karyn_Ex_003_Irked2_001",               # Auto: Renamed
  "Karyn_Ex_004_001":                      "Karyn_Ex_003_Open2_001",                # Auto: Renamed
  "Karyn_Ex_004_Grin2_001":                "Karyn_Ex_003_Grin2_001",                # Auto: Renamed
  "Karyn_Ex_004_Grin_001":                 "Karyn_Ex_003_Grin_001",                 # Auto: Renamed
  "Karyn_Ex_004_Open_001":                 "Karyn_Ex_003_Open_001",                 # Auto: Renamed
  "Karyn_Ex_005_001":                      "Karyn_Ex_004_Open2_001",                # Auto: Renamed
  "Karyn_Ex_005_Closed_001":               "",                                      # Auto: Deleted
  "Karyn_Ex_005_Smile_001":                "Karyn_Ex_004_Smile_001",                # Auto: Renamed
  "Karyn_Ex_006_001":                      "Karyn_Ex_006_Open_001",                 # Auto: Renamed
  "Karyn_Ex_006_Closed_001":               "",                                      # Auto: Deleted
  "Karyn_Ex_006_Open2_001":                "Karyn_Ex_006_Open2_001",                # Auto: Edited
  "Karyn_Ex_006_Open_001":                 "Karyn_Ex_006_Open_001",                 # Auto: Edited
  "Karyn_Ex_006_Smile2_001":               "Karyn_Ex_006_Smile2_001",               # Auto: Edited
  "Karyn_Ex_006_Smile_001":                "Karyn_Ex_006_Smile_001",                # Auto: Edited
  "Karyn_Ex_007_001":                      "Karyn_Ex_003_Grit_001",                 # Auto: Renamed
  "Karyn_Ex_008_001":                      "Karyn_Ex_001_Grin_001",                 # Auto: Renamed
  "Karyn_Ex_009_001":                      "Karyn_Ex_003_Mad_001",                  # Auto: Renamed
  "Karyn_Ex_010_002":                      "Karyn_Ex_010_Open_002",                 # Auto: Renamed
  "Karyn_Ex_011_002":                      "Karyn_Ex_012_002",                      # Auto: Renamed
  "Karyn_Ex_012_002":                      "Karyn_Ex_008_002",                      # Auto: Renamed
  "Karyn_Ex_013_002":                      "Karyn_Ex_008_Open_002",                 # Auto: Renamed
  "Karyn_Ex_014_002":                      "Karyn_Ex_0013_002",                     # Auto: Renamed
  "Karyn_Ex_015_002":                      "Karyn_Ex_014_002",                      # Auto: Renamed
  "Karyn_Ex_016_002":                      "Karyn_Ex_015_002",                      # Auto: Renamed
  "Karyn_Ex_017_003":                      "Karyn_Ex_017_003",                      # Auto: Edited
  "Karyn_Ex_018_003":                      "Karyn_Ex_018_003",                      # Auto: Edited
  "Karyn_Ex_019_003":                      "Karyn_Ex_019_003",                      # Auto: Edited
  "Karyn_Ex_020_003":                      "",                                      # Auto: Deleted
  "Karyn_Ex_021_003":                      "",                                      # Auto: Deleted
  "Karyn_Ex_022_003":                      "",                                      # Auto: Deleted
  "Karyn_Ex_Full_001_001":                 "Karyn_Ex_Full_001_001",                 # Auto: Same
  "Karyn_Ex_Full_001_Neutral_001":         "Karyn_Ex_Full_001_Neutral_001",         # Auto: Same
  "Karyn_Ex_Full_001_Open_001":            "Karyn_Ex_Full_001_Open_001",            # Auto: Same
  "Karyn_Ex_Full_001_Smile_001":           "Karyn_Ex_Full_001_Smile_001",           # Auto: Same
  "Karyn_Ex_Full_002_001":                 "Karyn_Ex_Full_002_Smile_001",           # Auto: Renamed
  "Karyn_Ex_Full_002_Smile_001":           "Karyn_Ex_Full_002_001",                 # Auto: Renamed
  "Karyn_Ex_Full_003_001":                 "Karyn_Ex_Full_003_Irked_001",           # Auto: Renamed
  "Karyn_Ex_Full_003_Open_001":            "Karyn_Ex_Full_003_Irked2_001",          # Auto: Renamed
  "Karyn_Ex_Full_004_001":                 "Karyn_Ex_Full_003_Open2_001",           # Auto: Renamed
  "Karyn_Ex_Full_004_Grin2_001":           "Karyn_Ex_Full_003_Grin2_001",           # Auto: Renamed
  "Karyn_Ex_Full_004_Grin_001":            "Karyn_Ex_Full_003_Grin_001",            # Auto: Renamed
  "Karyn_Ex_Full_004_Open_001":            "Karyn_Ex_Full_003_Open_001",            # Auto: Renamed
  "Karyn_Ex_Full_005_001":                 "Karyn_Ex_Full_004_Open2_001",           # Auto: Renamed
  "Karyn_Ex_Full_005_Closed_001":          "Karyn_Ex_Full_004_001",                 # Auto: Renamed
  "Karyn_Ex_Full_005_Smile_001":           "Karyn_Ex_Full_004_Smile_001",           # Auto: Renamed
  "Karyn_Ex_Full_006_001":                 "Karyn_Ex_Full_006_Open_001",            # Auto: Renamed
  "Karyn_Ex_Full_006_Closed_001":          "Karyn_Ex_Full_006_001",                 # Auto: Renamed
  "Karyn_Ex_Full_006_Open2_001":           "Karyn_Ex_Full_005_Open_001",            # Auto: Renamed
  "Karyn_Ex_Full_006_Open_001":            "Karyn_Ex_Full_005_001",                 # Auto: Renamed
  "Karyn_Ex_Full_006_Smile2_001":          "Karyn_Ex_Full_005_Aroused2_001",        # Auto: Renamed
  "Karyn_Ex_Full_006_Smile_001":           "Karyn_Ex_Full_005_Smile_001",           # Auto: Renamed
  "Karyn_Ex_Full_007_001":                 "Karyn_Ex_Full_003_Grit_001",            # Auto: Renamed
  "Karyn_Ex_Full_008_001":                 "Karyn_Ex_Full_001_Grin_001",            # Auto: Renamed
  "Karyn_Ex_Full_009_001":                 "Karyn_Ex_Full_003_Mad_001",             # Auto: Renamed
  "Karyn_Ex_Full_010_002":                 "Karyn_Ex_Full_010_Open_002",            # Auto: Renamed
  "Karyn_Ex_Full_011_002":                 "Karyn_Ex_Full_012_002",                 # Auto: Renamed
  "Karyn_Ex_Full_012_002":                 "Karyn_Ex_Full_008_002",                 # Auto: Renamed
  "Karyn_Ex_Full_013_002":                 "Karyn_Ex_Full_008_Open_002",            # Auto: Renamed
  "Karyn_Ex_Full_014_002":                 "Karyn_Ex_Full_0013_002",                # Auto: Renamed
  "Karyn_Ex_Full_015_002":                 "Karyn_Ex_Full_014_002",                 # Auto: Renamed
  "Karyn_Ex_Full_016_002":                 "Karyn_Ex_Full_015_002",                 # Auto: Renamed
  "Karyn_Ex_Full_017_003":                 "Karyn_Ex_Full_016_003",                 # Auto: Renamed
  "Karyn_Ex_Full_018_003":                 "Karyn_Ex_Full_009_003",                 # Auto: Renamed
  "Karyn_Ex_Full_019_003":                 "Karyn_Ex_Full_011_003",                 # Auto: Renamed
  "Karyn_Ex_Full_020_003":                 "Karyn_Ex_Full_017_003",                 # Auto: Renamed
  "Karyn_Ex_Full_021_003":                 "Karyn_Ex_Full_018_003",                 # Auto: Renamed
  "Karyn_Ex_Full_022_003":                 "Karyn_Ex_Full_019_003",                 # Auto: Renamed
}
