characterMapJenna = {
  "Jenna_Base_001":                        "Jenna_Base_001",                        # Auto: Edited
  "Jenna_Base_002":                        "Jenna_Base_002",                        # Auto: Edited
  "Jenna_Base_Full_001":                   "Jenna_Base_Full_001",                   # Auto: Same
  "Jenna_Base_Full_002":                   "Jenna_Base_Full_002",                   # Auto: Same
  "Jenna_Base_Full_Gown_001":              "Jenna_Base_Full_Gown_001",              # Auto: Same
  "Jenna_Base_Full_Gown_002":              "Jenna_Base_Full_Gown_002",              # Auto: Same
  "Jenna_Base_Full_Gym_001":               "Jenna_Base_Full_Gym_001",               # Auto: Same
  "Jenna_Base_Full_Gym_002":               "Jenna_Base_Full_Gym_002",               # Auto: Same
  "Jenna_Base_Full_Maid_001":              "Jenna_Base_Full_Maid_001",              # Auto: Same
  "Jenna_Base_Full_Maid_002":              "Jenna_Base_Full_Maid_002",              # Auto: Same
  "Jenna_Base_Full_Naked_001":             "Jenna_Base_Full_Naked_001",             # Auto: Same
  "Jenna_Base_Full_Naked_002":             "Jenna_Base_Full_Naked_002",             # Auto: Same
  "Jenna_Base_Full_Nighty_001":            "Jenna_Base_Full_Night_001",             # Auto: Renamed
  "Jenna_Base_Full_Nighty_002":            "Jenna_Base_Full_Night_002",             # Auto: Renamed
  "Jenna_Base_Full_Preg_001":              "Jenna_Base_Full_Preg_001",              # Auto: Same
  "Jenna_Base_Full_Preg_002":              "Jenna_Base_Full_Preg_002",              # Auto: Same
  "Jenna_Base_Full_School_001":            "Jenna_Base_Full_School_001",            # Auto: Same
  "Jenna_Base_Full_School_002":            "Jenna_Base_Full_School_002",            # Auto: Same
  "Jenna_Base_Full_Under_001":             "Jenna_Base_Full_Under_001",             # Auto: Same
  "Jenna_Base_Full_Under_002":             "Jenna_Base_Full_Under_002",             # Auto: Same
  "Jenna_Base_Full_Wedding_001":           "Jenna_Base_Full_Wedding_001",           # Auto: Same
  "Jenna_Base_Full_Wedding_002":           "Jenna_Base_Full_Wedding_002",           # Auto: Same
  "Jenna_Base_Gown_001":                   "Jenna_Base_Gown_001",                   # Auto: Edited
  "Jenna_Base_Gown_002":                   "Jenna_Base_Gown_002",                   # Auto: Edited
  "Jenna_Base_Gym_001":                    "Jenna_Base_Gym_001",                    # Auto: Edited
  "Jenna_Base_Gym_002":                    "Jenna_Base_Gym_002",                    # Auto: Edited
  "Jenna_Base_Maid_001":                   "Jenna_Base_Maid_001",                   # Auto: Edited
  "Jenna_Base_Maid_002":                   "Jenna_Base_Maid_002",                   # Auto: Edited
  "Jenna_Base_Naked_001":                  "Jenna_Base_Naked_001",                  # Auto: Edited
  "Jenna_Base_Naked_002":                  "Jenna_Base_Naked_002",                  # Auto: Edited
  "Jenna_Base_Nighty_001":                 "",                                      # Auto: Deleted
  "Jenna_Base_Nighty_002":                 "",                                      # Auto: Deleted
  "Jenna_Base_Preg_001":                   "Jenna_Base_Preg_001",                   # Auto: Edited
  "Jenna_Base_Preg_002":                   "Jenna_Base_Preg_002",                   # Auto: Edited
  "Jenna_Base_School_001":                 "Jenna_Base_School_001",                 # Auto: Edited
  "Jenna_Base_School_002":                 "Jenna_Base_School_002",                 # Auto: Edited
  "Jenna_Base_Under_001":                  "Jenna_Base_Under_001",                  # Auto: Edited
  "Jenna_Base_Under_002":                  "Jenna_Base_Under_002",                  # Auto: Edited
  "Jenna_Base_Wedding_001":                "Jenna_Base_Wedding_001",                # Auto: Edited
  "Jenna_Base_Wedding_002":                "Jenna_Base_Wedding_002",                # Auto: Edited
  "Jenna_Ex_001_001":                      "Jenna_Ex_001_001",                      # Auto: Same
  "Jenna_Ex_001_Neutral_001":              "Jenna_Ex_001_Neutral_001",              # Auto: Same
  "Jenna_Ex_001_Smile_001":                "Jenna_Ex_001_Smile_001",                # Auto: Same
  "Jenna_Ex_002_001":                      "Jenna_Ex_002_Smile_001",                # Auto: Renamed
  "Jenna_Ex_002_Smile_001":                "Jenna_Ex_002_001",                      # Auto: Renamed
  "Jenna_Ex_003_001":                      "Jenna_Ex_003_001",                      # Auto: Same
  "Jenna_Ex_003_Grin2_001":                "Jenna_Ex_003_Grin2_001",                # Auto: Same
  "Jenna_Ex_003_Grin_001":                 "Jenna_Ex_003_Grin_001",                 # Auto: Same
  "Jenna_Ex_003_Open2_001":                "Jenna_Ex_003_Open2_001",                # Auto: Same
  "Jenna_Ex_003_Open_001":                 "Jenna_Ex_003_Open_001",                 # Auto: Same
  "Jenna_Ex_004_001":                      "Jenna_Ex_004_Open_001",                 # Auto: Renamed
  "Jenna_Ex_004_Closed_001":               "Jenna_Ex_004_001",                      # Auto: Renamed
  "Jenna_Ex_004_Smile_001":                "Jenna_Ex_004_Smile_001",                # Auto: Same
  "Jenna_Ex_005_001":                      "Jenna_Ex_001_Smile2_001",               # Auto: Renamed
  "Jenna_Ex_006_001":                      "Jenna_Ex_005_Aroused2_001",             # Auto: Renamed
  "Jenna_Ex_007_002":                      "Jenna_Ex_007_Open_002",                 # Auto: Renamed
  "Jenna_Ex_007_Smile_002":                "Jenna_Ex_007_Smile_002",                # Auto: Same
  "Jenna_Ex_008_002":                      "Jenna_Ex_008_Open_002",                 # Auto: Renamed
  "Jenna_Ex_009_002":                      "Jenna_Ex_009_Closed_002",               # Auto: Renamed
  "Jenna_Ex_009_Smile_002":                "",                                      # Auto: Deleted
  "Jenna_Ex_010_002":                      "Jenna_Ex_010_002",                      # Auto: Same
  "Jenna_Ex_011_002":                      "Jenna_Ex_009_002",                      # Auto: Renamed
  "Jenna_Ex_012_002":                      "Jenna_Ex_011_002",                      # Auto: Renamed
  "Jenna_Ex_013_002":                      "Jenna_Ex_012_002",                      # Auto: Renamed
  "Jenna_Ex_Full_001_001":                 "Jenna_Ex_Full_001_001",                 # Auto: Same
  "Jenna_Ex_Full_001_Neutral_001":         "Jenna_Ex_Full_001_Neutral_001",         # Auto: Same
  "Jenna_Ex_Full_001_Smile_001":           "Jenna_Ex_Full_001_Smile_001",           # Auto: Same
  "Jenna_Ex_Full_002_001":                 "Jenna_Ex_Full_002_Smile_001",           # Auto: Renamed
  "Jenna_Ex_Full_002_Smile_001":           "Jenna_Ex_Full_002_001",                 # Auto: Renamed
  "Jenna_Ex_Full_003_001":                 "Jenna_Ex_Full_003_001",                 # Auto: Same
  "Jenna_Ex_Full_003_Grin2_001":           "Jenna_Ex_Full_003_Grin2_001",           # Auto: Same
  "Jenna_Ex_Full_003_Grin_001":            "Jenna_Ex_Full_003_Grin_001",            # Auto: Same
  "Jenna_Ex_Full_003_Open2_001":           "Jenna_Ex_Full_003_Open2_001",           # Auto: Same
  "Jenna_Ex_Full_003_Open_001":            "Jenna_Ex_Full_003_Open_001",            # Auto: Same
  "Jenna_Ex_Full_004_001":                 "Jenna_Ex_Full_004_Open_001",            # Auto: Renamed
  "Jenna_Ex_Full_004_Closed_001":          "Jenna_Ex_Full_004_001",                 # Auto: Renamed
  "Jenna_Ex_Full_004_Smile_001":           "Jenna_Ex_Full_004_Smile_001",           # Auto: Same
  "Jenna_Ex_Full_005_001":                 "Jenna_Ex_Full_001_Smile2_001",          # Auto: Renamed
  "Jenna_Ex_Full_006_001":                 "Jenna_Ex_Full_005_Aroused2_001",        # Auto: Renamed
  "Jenna_Ex_Full_007_002":                 "Jenna_Ex_Full_007_Open_002",            # Auto: Renamed
  "Jenna_Ex_Full_007_Smile_002":           "Jenna_Ex_Full_007_Smile_002",           # Auto: Same
  "Jenna_Ex_Full_008_002":                 "Jenna_Ex_Full_008_Open_002",            # Auto: Renamed
  "Jenna_Ex_Full_009_002":                 "Jenna_Ex_Full_009_Closed_002",          # Auto: Renamed
  "Jenna_Ex_Full_009_Smile_002":           "",                                      # Auto: Deleted
  "Jenna_Ex_Full_010_002":                 "Jenna_Ex_Full_010_002",                 # Auto: Same
  "Jenna_Ex_Full_011_002":                 "Jenna_Ex_Full_009_002",                 # Auto: Renamed
  "Jenna_Ex_Full_012_002":                 "Jenna_Ex_Full_011_002",                 # Auto: Renamed
  "Jenna_Ex_Full_013_002":                 "Jenna_Ex_Full_012_002",                 # Auto: Renamed
}
