characterMapErin = {
  "erin_base_001":                         "erin_base_001",                         # Auto: Edited
  "erin_base_002":                         "erin_base_002",                         # Auto: Edited
  "erin_base_003":                         "erin_base_003",                         # Auto: Edited
  "erin_base_fit_001":                     "erin_base_fit_001",                     # Auto: Edited
  "erin_base_fit_002":                     "erin_base_fit_002",                     # Auto: Edited
  "erin_base_fit_003":                     "erin_base_fit_003",                     # Auto: Edited
  "erin_base_full_001":                    "erin_base_full_001",                    # Auto: Edited
  "erin_base_full_002":                    "erin_base_full_002",                    # Auto: Edited
  "erin_base_full_003":                    "erin_base_full_003",                    # Auto: Edited
  "erin_base_full_fit_001":                "erin_base_full_fit_001",                # Auto: Edited
  "erin_base_full_fit_002":                "erin_base_full_fit_002",                # Auto: Edited
  "erin_base_full_fit_003":                "erin_base_full_fit_003",                # Auto: Edited
  "erin_base_full_naked_001":              "erin_base_full_naked_001",              # Auto: Edited
  "erin_base_full_naked_002":              "erin_base_full_naked_002",              # Auto: Edited
  "erin_base_full_naked_003":              "erin_base_full_naked_003",              # Auto: Edited
  "erin_base_full_swim_001":               "erin_base_full_swim_001",               # Auto: Edited
  "erin_base_full_swim_002":               "erin_base_full_swim_002",               # Auto: Edited
  "erin_base_full_swim_003":               "erin_base_full_swim_003",               # Auto: Edited
  "erin_base_full_under_001":              "erin_base_full_under_001",              # Auto: Edited
  "erin_base_full_under_002":              "erin_base_full_under_002",              # Auto: Edited
  "erin_base_full_under_003":              "erin_base_full_under_003",              # Auto: Edited
  "erin_base_naked_001":                   "erin_base_naked_001",                   # Auto: Edited
  "erin_base_naked_002":                   "erin_base_naked_002",                   # Auto: Edited
  "erin_base_naked_003":                   "erin_base_naked_003",                   # Auto: Edited
  "erin_base_swim_001":                    "erin_base_swim_001",                    # Auto: Edited
  "erin_base_swim_002":                    "erin_base_swim_002",                    # Auto: Edited
  "erin_base_swim_003":                    "erin_base_swim_003",                    # Auto: Edited
  "erin_base_under_001":                   "erin_base_under_001",                   # Auto: Edited
  "erin_base_under_002":                   "erin_base_under_002",                   # Auto: Edited
  "erin_base_under_003":                   "erin_base_under_003",                   # Auto: Edited
  "erin_ex_001_001":                       "erin_ex_001_001",                       # Auto: Edited
  "erin_ex_002_001":                       "erin_ex_002_001",                       # Auto: Edited
  "erin_ex_002_smile_001":                 "erin_ex_002_smile_001",                 # Auto: Edited
  "erin_ex_003_001":                       "erin_ex_003_001",                       # Auto: Edited
  "erin_ex_003_smile_001":                 "",                                      # Auto: Deleted
  "erin_ex_004_001":                       "erin_ex_004_001",                       # Auto: Edited
  "erin_ex_005_001":                       "erin_ex_005_001",                       # Auto: Edited
  "erin_ex_005_grin2_001":                 "",                                      # Auto: Deleted
  "erin_ex_005_grin_001":                  "",                                      # Auto: Deleted
  "erin_ex_005_open_001":                  "erin_ex_005_open_001",                  # Auto: Edited
  "erin_ex_006_001":                       "erin_ex_006_001",                       # Auto: Edited
  "erin_ex_006_smile_001":                 "erin_ex_006_smile_001",                 # Auto: Edited
  "erin_ex_007_001":                       "",                                      # Auto: Deleted
  "erin_ex_008_001":                       "",                                      # Auto: Deleted
  "erin_ex_008_open_001":                  "",                                      # Auto: Deleted
  "erin_ex_008_smile2_001":                "",                                      # Auto: Deleted
  "erin_ex_008_smile_001":                 "",                                      # Auto: Deleted
  "erin_ex_009_001":                       "",                                      # Auto: Deleted
  "erin_ex_010_001":                       "",                                      # Auto: Deleted
  "erin_ex_011_002":                       "erin_ex_011_002",                       # Auto: Edited
  "erin_ex_012_002":                       "",                                      # Auto: Deleted
  "erin_ex_013_002":                       "erin_ex_013_002",                       # Auto: Edited
  "erin_ex_014_002":                       "erin_ex_014_002",                       # Auto: Edited
  "erin_ex_014_closed_002":                "",                                      # Auto: Deleted
  "erin_ex_015_002":                       "",                                      # Auto: Deleted
  "erin_ex_016_002":                       "",                                      # Auto: Deleted
  "erin_ex_017_002":                       "",                                      # Auto: Deleted
  "erin_ex_018_002":                       "",                                      # Auto: Deleted
  "erin_ex_019_002":                       "",                                      # Auto: Deleted
  "erin_ex_020_003":                       "erin_ex_020_003",                       # Auto: Edited
  "erin_ex_021_003":                       "",                                      # Auto: Deleted
  "erin_ex_022_003":                       "",                                      # Auto: Deleted
  "erin_ex_023_003":                       "",                                      # Auto: Deleted
  "erin_ex_024_003":                       "",                                      # Auto: Deleted
  "erin_ex_025_003":                       "",                                      # Auto: Deleted
  "erin_ex_026_003":                       "",                                      # Auto: Deleted
  "erin_ex_027_003":                       "",                                      # Auto: Deleted
  "erin_ex_028_003":                       "",                                      # Auto: Deleted
  "erin_ex_029_003":                       "",                                      # Auto: Deleted
  "erin_ex_030_003":                       "",                                      # Auto: Deleted
  "erin_ex_full_001_001":                  "erin_ex_full_001_001",                  # Auto: Edited
  "erin_ex_full_002_001":                  "erin_ex_full_002_001",                  # Auto: Edited
  "erin_ex_full_002_smile_001":            "erin_ex_full_002_smile_001",            # Auto: Edited
  "erin_ex_full_003_001":                  "erin_ex_full_003_001",                  # Auto: Edited
  "erin_ex_full_003_smile_001":            "",                                      # Auto: Deleted
  "erin_ex_full_004_001":                  "erin_ex_full_004_001",                  # Auto: Edited
  "erin_ex_full_005_001":                  "erin_ex_full_005_001",                  # Auto: Edited
  "erin_ex_full_005_grin2_001":            "",                                      # Auto: Deleted
  "erin_ex_full_005_grin_001":             "",                                      # Auto: Deleted
  "erin_ex_full_005_open_001":             "erin_ex_full_005_open_001",             # Auto: Edited
  "erin_ex_full_006_001":                  "erin_ex_full_006_001",                  # Auto: Edited
  "erin_ex_full_006_smile_001":            "erin_ex_full_006_smile_001",            # Auto: Edited
  "erin_ex_full_007_001":                  "",                                      # Auto: Deleted
  "erin_ex_full_008_001":                  "",                                      # Auto: Deleted
  "erin_ex_full_008_open_001":             "",                                      # Auto: Deleted
  "erin_ex_full_008_smile2_001":           "",                                      # Auto: Deleted
  "erin_ex_full_008_smile_001":            "",                                      # Auto: Deleted
  "erin_ex_full_009_001":                  "",                                      # Auto: Deleted
  "erin_ex_full_010_001":                  "",                                      # Auto: Deleted
  "erin_ex_full_011_002":                  "erin_ex_full_011_002",                  # Auto: Edited
  "erin_ex_full_012_002":                  "",                                      # Auto: Deleted
  "erin_ex_full_013_002":                  "erin_ex_full_013_002",                  # Auto: Edited
  "erin_ex_full_014_002":                  "erin_ex_full_014_002",                  # Auto: Edited
  "erin_ex_full_014_closed_002":           "",                                      # Auto: Deleted
  "erin_ex_full_015_002":                  "",                                      # Auto: Deleted
  "erin_ex_full_016_002":                  "",                                      # Auto: Deleted
  "erin_ex_full_017_002":                  "",                                      # Auto: Deleted
  "erin_ex_full_018_002":                  "",                                      # Auto: Deleted
  "erin_ex_full_019_002":                  "",                                      # Auto: Deleted
  "erin_ex_full_020_003":                  "erin_ex_full_020_003",                  # Auto: Edited
  "erin_ex_full_021_003":                  "",                                      # Auto: Deleted
  "erin_ex_full_022_003":                  "",                                      # Auto: Deleted
  "erin_ex_full_023_003":                  "",                                      # Auto: Deleted
  "erin_ex_full_024_003":                  "",                                      # Auto: Deleted
  "erin_ex_full_025_003":                  "",                                      # Auto: Deleted
  "erin_ex_full_026_003":                  "",                                      # Auto: Deleted
  "erin_ex_full_026_clean_003":            "",                                      # Auto: Deleted
  "erin_ex_full_027_003":                  "",                                      # Auto: Deleted
  "erin_ex_full_028_003":                  "",                                      # Auto: Deleted
  "erin_ex_full_029_003":                  "",                                      # Auto: Deleted
  "erin_ex_full_030_003":                  "",                                      # Auto: Deleted
}
