characterMapEliza = {
  "Eliza_BE0_Full_Naked_002":              "Eliza_BE0_Full_Naked_002",              # Auto: Same
  "Eliza_BE0_Full_Under_002":              "Eliza_BE0_Full_Under_002",              # Auto: Same
  "Eliza_BE0_Naked_002":                   "Eliza_BE0_Naked_002",                   # Auto: Same
  "Eliza_BE0_Under_002":                   "Eliza_BE0_Under_002",                   # Auto: Same
  "Eliza_BE1_001":                         "Eliza_BE1_001",                         # Auto: Same
  "Eliza_BE1_002":                         "Eliza_BE1_002",                         # Auto: Same
  "Eliza_BE1_003":                         "Eliza_BE1_003",                         # Auto: Same
  "Eliza_BE1_Cas_001":                     "Eliza_BE1_Cas_001",                     # Auto: Same
  "Eliza_BE1_Cas_002":                     "Eliza_BE1_Cas_002",                     # Auto: Same
  "Eliza_BE1_Cas_003":                     "Eliza_BE1_Cas_003",                     # Auto: Same
  "Eliza_BE1_Full_001":                    "Eliza_BE1_Full_001",                    # Auto: Same
  "Eliza_BE1_Full_002":                    "Eliza_BE1_Full_002",                    # Auto: Same
  "Eliza_BE1_Full_003":                    "Eliza_BE1_Full_003",                    # Auto: Same
  "Eliza_BE1_Full_Cas_001":                "Eliza_BE1_Full_Cas_001",                # Auto: Same
  "Eliza_BE1_Full_Cas_002":                "Eliza_BE1_Full_Cas_002",                # Auto: Same
  "Eliza_BE1_Full_Cas_003":                "Eliza_BE1_Full_Cas_003",                # Auto: Same
  "Eliza_BE1_Full_Gym_001":                "Eliza_BE1_Full_Gym_001",                # Auto: Same
  "Eliza_BE1_Full_Gym_002":                "Eliza_BE1_Full_Gym_002",                # Auto: Same
  "Eliza_BE1_Full_Gym_003":                "Eliza_BE1_Full_Gym_003",                # Auto: Same
  "Eliza_BE1_Full_Naked_001":              "Eliza_BE1_Full_Naked_001",              # Auto: Same
  "Eliza_BE1_Full_Naked_002":              "Eliza_BE1_Full_Naked_002",              # Auto: Same
  "Eliza_BE1_Full_Naked_003":              "Eliza_BE1_Full_Naked_003",              # Auto: Same
  "Eliza_BE1_Full_Under_001":              "Eliza_BE1_Full_Under_001",              # Auto: Same
  "Eliza_BE1_Full_Under_002":              "Eliza_BE1_Full_Under_002",              # Auto: Same
  "Eliza_BE1_Full_Under_003":              "Eliza_BE1_Full_Under_003",              # Auto: Same
  "Eliza_BE1_Gym_001":                     "Eliza_BE1_Gym_001",                     # Auto: Same
  "Eliza_BE1_Gym_002":                     "Eliza_BE1_Gym_002",                     # Auto: Same
  "Eliza_BE1_Gym_003":                     "Eliza_BE1_Gym_003",                     # Auto: Same
  "Eliza_BE1_Naked_001":                   "Eliza_BE1_Naked_001",                   # Auto: Same
  "Eliza_BE1_Naked_002":                   "Eliza_BE1_Naked_002",                   # Auto: Same
  "Eliza_BE1_Naked_003":                   "Eliza_BE1_Naked_003",                   # Auto: Same
  "Eliza_BE1_Under_001":                   "Eliza_BE1_Under_001",                   # Auto: Same
  "Eliza_BE1_Under_002":                   "Eliza_BE1_Under_002",                   # Auto: Same
  "Eliza_BE1_Under_003":                   "Eliza_BE1_Under_003",                   # Auto: Same
  "Eliza_BE2_001":                         "Eliza_BE2_001",                         # Auto: Same
  "Eliza_BE2_002":                         "Eliza_BE2_002",                         # Auto: Same
  "Eliza_BE2_003":                         "Eliza_BE2_003",                         # Auto: Same
  "Eliza_BE2_Cas_001":                     "Eliza_BE2_Cas_001",                     # Auto: Same
  "Eliza_BE2_Cas_002":                     "Eliza_BE2_Cas_002",                     # Auto: Same
  "Eliza_BE2_Cas_003":                     "Eliza_BE2_Cas_003",                     # Auto: Same
  "Eliza_BE2_Full_001":                    "Eliza_BE2_Full_001",                    # Auto: Same
  "Eliza_BE2_Full_002":                    "Eliza_BE2_Full_002",                    # Auto: Same
  "Eliza_BE2_Full_003":                    "Eliza_BE2_Full_003",                    # Auto: Same
  "Eliza_BE2_Full_Cas_001":                "Eliza_BE2_Full_Cas_001",                # Auto: Same
  "Eliza_BE2_Full_Cas_002":                "Eliza_BE2_Full_Cas_002",                # Auto: Same
  "Eliza_BE2_Full_Cas_003":                "Eliza_BE2_Full_Cas_003",                # Auto: Same
  "Eliza_BE2_Full_Gym_001":                "Eliza_BE2_Full_Gym_001",                # Auto: Same
  "Eliza_BE2_Full_Gym_002":                "Eliza_BE2_Full_Gym_002",                # Auto: Same
  "Eliza_BE2_Full_Gym_003":                "Eliza_BE2_Full_Gym_003",                # Auto: Same
  "Eliza_BE2_Full_Naked_001":              "Eliza_BE2_Full_Naked_001",              # Auto: Same
  "Eliza_BE2_Full_Naked_002":              "Eliza_BE2_Full_Naked_002",              # Auto: Same
  "Eliza_BE2_Full_Naked_003":              "Eliza_BE2_Full_Naked_003",              # Auto: Same
  "Eliza_BE2_Full_Under_001":              "Eliza_BE2_Full_Under_001",              # Auto: Same
  "Eliza_BE2_Full_Under_002":              "Eliza_BE2_Full_Under_002",              # Auto: Same
  "Eliza_BE2_Full_Under_003":              "Eliza_BE2_Full_Under_003",              # Auto: Same
  "Eliza_BE2_Gym_001":                     "Eliza_BE2_Gym_001",                     # Auto: Same
  "Eliza_BE2_Gym_002":                     "Eliza_BE2_Gym_002",                     # Auto: Same
  "Eliza_BE2_Gym_003":                     "Eliza_BE2_Gym_003",                     # Auto: Same
  "Eliza_BE2_Naked_001":                   "Eliza_BE2_Naked_001",                   # Auto: Same
  "Eliza_BE2_Naked_002":                   "Eliza_BE2_Naked_002",                   # Auto: Same
  "Eliza_BE2_Naked_003":                   "Eliza_BE2_Naked_003",                   # Auto: Same
  "Eliza_BE2_Under_001":                   "Eliza_BE2_Under_001",                   # Auto: Same
  "Eliza_BE2_Under_002":                   "Eliza_BE2_Under_002",                   # Auto: Same
  "Eliza_BE2_Under_003":                   "Eliza_BE2_Under_003",                   # Auto: Same
  "Eliza_Base_001":                        "Eliza_Base_001",                        # Auto: Edited
  "Eliza_Base_002":                        "Eliza_Base_002",                        # Auto: Edited
  "Eliza_Base_003":                        "Eliza_Base_003",                        # Auto: Edited
  "Eliza_Base_Cas_001":                    "Eliza_Base_Cas_001",                    # Auto: Edited
  "Eliza_Base_Cas_002":                    "Eliza_Base_Cas_002",                    # Auto: Edited
  "Eliza_Base_Cas_003":                    "Eliza_Base_Cas_003",                    # Auto: Edited
  "Eliza_Base_Full_001":                   "Eliza_Base_Full_001",                   # Auto: Same
  "Eliza_Base_Full_002":                   "Eliza_Base_Full_002",                   # Auto: Same
  "Eliza_Base_Full_003":                   "Eliza_Base_Full_003",                   # Auto: Same
  "Eliza_Base_Full_Cas_001":               "Eliza_Base_Full_Cas_001",               # Auto: Same
  "Eliza_Base_Full_Cas_002":               "Eliza_Base_Full_Cas_002",               # Auto: Same
  "Eliza_Base_Full_Cas_003":               "Eliza_Base_Full_Cas_003",               # Auto: Same
  "Eliza_Base_Full_Gym_001":               "Eliza_Base_Full_Gym_001",               # Auto: Same
  "Eliza_Base_Full_Gym_002":               "Eliza_Base_Full_Gym_002",               # Auto: Same
  "Eliza_Base_Full_Gym_003":               "Eliza_Base_Full_Gym_003",               # Auto: Same
  "Eliza_Base_Full_Naked_001":             "Eliza_Base_Full_Naked_001",             # Auto: Same
  "Eliza_Base_Full_Naked_002":             "Eliza_Base_Full_Naked_002",             # Auto: Same
  "Eliza_Base_Full_Naked_003":             "Eliza_Base_Full_Naked_003",             # Auto: Edited
  "Eliza_Base_Full_Under_001":             "Eliza_Base_Full_Under_001",             # Auto: Same
  "Eliza_Base_Full_Under_002":             "Eliza_Base_Full_Under_002",             # Auto: Same
  "Eliza_Base_Full_Under_003":             "Eliza_Base_Full_Under_003",             # Auto: Same
  "Eliza_Base_Gym_001":                    "Eliza_Base_Gym_001",                    # Auto: Edited
  "Eliza_Base_Gym_002":                    "Eliza_Base_Gym_002",                    # Auto: Edited
  "Eliza_Base_Gym_003":                    "Eliza_Base_Gym_003",                    # Auto: Edited
  "Eliza_Base_Naked_001":                  "Eliza_Base_Naked_001",                  # Auto: Edited
  "Eliza_Base_Naked_002":                  "Eliza_Base_Naked_002",                  # Auto: Edited
  "Eliza_Base_Naked_003":                  "Eliza_Base_Naked_003",                  # Auto: Edited
  "Eliza_Base_Under_001":                  "Eliza_Base_Under_001",                  # Auto: Edited
  "Eliza_Base_Under_002":                  "Eliza_Base_Under_002",                  # Auto: Edited
  "Eliza_Base_Under_003":                  "Eliza_Base_Under_003",                  # Auto: Edited
  "Eliza_Ex_001_001":                      "Eliza_Ex_001_001",                      # Auto: Same
  "Eliza_Ex_001_Neutral_001":              "Eliza_Ex_001_Neutral_001",              # Auto: Same
  "Eliza_Ex_001_Smile_001":                "Eliza_Ex_001_Smile_001",                # Auto: Same
  "Eliza_Ex_002_001":                      "Eliza_Ex_002_Smile_001",                # Auto: Renamed
  "Eliza_Ex_002_Smile_001":                "Eliza_Ex_002_001",                      # Auto: Renamed
  "Eliza_Ex_003_001":                      "Eliza_Ex_003_Open2_001",                # Auto: Renamed
  "Eliza_Ex_003_Grin2_001":                "Eliza_Ex_003_Grin2_001",                # Auto: Same
  "Eliza_Ex_003_Grin_001":                 "Eliza_Ex_003_Grin_001",                 # Auto: Same
  "Eliza_Ex_003_Open_001":                 "Eliza_Ex_003_Open_001",                 # Auto: Same
  "Eliza_Ex_004_001":                      "Eliza_Ex_004_Open_001",                 # Auto: Renamed
  "Eliza_Ex_004_Closed_001":               "Eliza_Ex_004_001",                      # Auto: Renamed
  "Eliza_Ex_004_Smile_001":                "Eliza_Ex_004_Smile_001",                # Auto: Same
  "Eliza_Ex_005_001":                      "Eliza_Ex_005_Open_001",                 # Auto: Renamed
  "Eliza_Ex_005_Closed_001":               "Eliza_Ex_005_001",                      # Auto: Renamed
  "Eliza_Ex_006_001":                      "Eliza_Ex_003_001",                      # Auto: Renamed
  "Eliza_Ex_007_001":                      "Eliza_Ex_001_Smile2_001",               # Auto: Renamed
  "Eliza_Ex_008_001":                      "",                                      # Auto: Deleted
  "Eliza_Ex_008_Smile_001":                "Eliza_Ex_005_Aroused2_001",             # Auto: Renamed
  "Eliza_Ex_009_002":                      "Eliza_Ex_009_Closed_002",               # Auto: Renamed
  "Eliza_Ex_010_002":                      "Eliza_Ex_010_002",                      # Auto: Same
  "Eliza_Ex_011_002":                      "Eliza_Ex_012_002",                      # Auto: Renamed
  "Eliza_Ex_012_002":                      "Eliza_Ex_015_002",                      # Auto: Renamed
  "Eliza_Ex_013_002":                      "Eliza_Ex_014_002",                      # Auto: Renamed
  "Eliza_Ex_014_002":                      "Eliza_Ex_013_002",                      # Auto: Renamed
  "Eliza_Ex_015_002":                      "Eliza_Ex_014_Daze_002",                 # Auto: Renamed
  "Eliza_Ex_016_002":                      "Eliza_Ex_014_Daze2_002",                # Auto: Renamed
  "Eliza_Ex_017_003":                      "Eliza_Ex_003_Irked_003",                # Auto: Renamed
  "Eliza_Ex_018_003":                      "Eliza_Ex_011_003",                      # Auto: Renamed
  "Eliza_Ex_019_003":                      "Eliza_Ex_016_003",                      # Auto: Renamed
  "Eliza_Ex_020_003":                      "Eliza_Ex_008_003",                      # Auto: Renamed
  "Eliza_Ex_021_003":                      "Eliza_Ex_007_Open_003",                 # Auto: Renamed
  "Eliza_Ex_022_003":                      "Eliza_Ex_009_Open_003",                 # Auto: Renamed
  "Eliza_Ex_Full_001_001":                 "Eliza_Ex_Full_001_001",                 # Auto: Same
  "Eliza_Ex_Full_001_Neutral_001":         "Eliza_Ex_Full_001_Neutral_001",         # Auto: Same
  "Eliza_Ex_Full_001_Smile_001":           "Eliza_Ex_Full_001_Smile_001",           # Auto: Same
  "Eliza_Ex_Full_002_001":                 "Eliza_Ex_Full_002_Smile_001",           # Auto: Renamed
  "Eliza_Ex_Full_002_Smile_001":           "Eliza_Ex_Full_002_001",                 # Auto: Renamed
  "Eliza_Ex_Full_003_001":                 "Eliza_Ex_Full_003_Open2_001",           # Auto: Renamed
  "Eliza_Ex_Full_003_Grin2_001":           "Eliza_Ex_Full_003_Grin2_001",           # Auto: Same
  "Eliza_Ex_Full_003_Grin_001":            "Eliza_Ex_Full_003_Grin_001",            # Auto: Same
  "Eliza_Ex_Full_003_Open_001":            "Eliza_Ex_Full_003_Open_001",            # Auto: Same
  "Eliza_Ex_Full_004_001":                 "Eliza_Ex_Full_004_Open_001",            # Auto: Renamed
  "Eliza_Ex_Full_004_Closed_001":          "Eliza_Ex_Full_004_001",                 # Auto: Renamed
  "Eliza_Ex_Full_004_Smile_001":           "Eliza_Ex_Full_004_Smile_001",           # Auto: Same
  "Eliza_Ex_Full_005_001":                 "Eliza_Ex_Full_005_Open_001",            # Auto: Renamed
  "Eliza_Ex_Full_005_Closed_001":          "Eliza_Ex_Full_005_001",                 # Auto: Renamed
  "Eliza_Ex_Full_006_001":                 "Eliza_Ex_Full_003_001",                 # Auto: Renamed
  "Eliza_Ex_Full_007_001":                 "Eliza_Ex_Full_001_Smile2_001",          # Auto: Renamed
  "Eliza_Ex_Full_008_001":                 "",                                      # Auto: Deleted
  "Eliza_Ex_Full_008_Smile_001":           "Eliza_Ex_Full_005_Aroused2_001",        # Auto: Renamed
  "Eliza_Ex_Full_009_002":                 "Eliza_Ex_Full_009_Closed_002",          # Auto: Renamed
  "Eliza_Ex_Full_010_002":                 "Eliza_Ex_Full_010_002",                 # Auto: Same
  "Eliza_Ex_Full_011_002":                 "Eliza_Ex_Full_012_002",                 # Auto: Renamed
  "Eliza_Ex_Full_012_002":                 "Eliza_Ex_Full_015_002",                 # Auto: Renamed
  "Eliza_Ex_Full_013_002":                 "Eliza_Ex_Full_014_002",                 # Auto: Renamed
  "Eliza_Ex_Full_014_002":                 "Eliza_Ex_Full_013_002",                 # Auto: Renamed
  "Eliza_Ex_Full_015_002":                 "Eliza_Ex_Full_014_Daze_002",            # Auto: Renamed
  "Eliza_Ex_Full_016_002":                 "Eliza_Ex_Full_014_Daze2_002",           # Auto: Renamed
  "Eliza_Ex_Full_017_003":                 "Eliza_Ex_Full_003_Irked_003",           # Auto: Renamed
  "Eliza_Ex_Full_018_003":                 "Eliza_Ex_Full_011_003",                 # Auto: Renamed
  "Eliza_Ex_Full_019_003":                 "Eliza_Ex_Full_016_003",                 # Auto: Renamed
  "Eliza_Ex_Full_020_003":                 "Eliza_Ex_Full_008_003",                 # Auto: Renamed
  "Eliza_Ex_Full_021_003":                 "Eliza_Ex_Full_007_Open_003",            # Auto: Renamed
  "Eliza_Ex_Full_022_003":                 "Eliza_Ex_Full_009_Open_003",            # Auto: Renamed
  "Eliza_Mut_Full_Pigtails_001":           "Eliza_Mut_Full_Pigtails_001",           # Auto: Same
  "Eliza_Mut_Full_Pigtails_002":           "Eliza_Mut_Full_Pigtails_002",           # Auto: Same
  "Eliza_Mut_Full_Pigtails_003":           "Eliza_Mut_Full_Pigtails_003",           # Auto: Same
  "Eliza_Mut_Full_Short_001":              "Eliza_Mut_Full_Short_001",              # Auto: Same
  "Eliza_Mut_Full_Short_002":              "Eliza_Mut_Full_Short_002",              # Auto: Same
  "Eliza_Mut_Full_Short_003":              "Eliza_Mut_Full_Short_003",              # Auto: Edited
  "Eliza_Mut_Pigtails_001":                "Eliza_Mut_Pigtails_001",                # Auto: Edited
  "Eliza_Mut_Pigtails_002":                "Eliza_Mut_Pigtails_002",                # Auto: Same
  "Eliza_Mut_Pigtails_003":                "Eliza_Mut_Pigtails_003",                # Auto: Edited
  "Eliza_Mut_Short_001":                   "Eliza_Mut_Short_001",                   # Auto: Same
  "Eliza_Mut_Short_002":                   "Eliza_Mut_Short_002",                   # Auto: Same
  "Eliza_Mut_Short_003":                   "Eliza_Mut_Short_003",                   # Auto: Edited
}
