#!/bin/bash
python3 ./compare_character.py Alma     --code > character_map_35_alma.py
python3 ./compare_character.py Amber    --code > character_map_35_amber.py
python3 ./compare_character.py Anna     --code > character_map_35_anna.py
python3 ./compare_character.py April    --code > character_map_35_april.py
python3 ./compare_character.py Candice  --code > character_map_35_candice.py
python3 ./compare_character.py Chris    --code > character_map_35_chris.py
python3 ./compare_character.py Ciel     --code > character_map_35_ciel.py
python3 ./compare_character.py Cindy    --code > character_map_35_cindy.py
python3 ./compare_character.py Donald   --code > character_map_35_donald.py
python3 ./compare_character.py Eliza    --code > character_map_35_eliza.py
python3 ./compare_character.py Erin     --code > character_map_35_erin.py
python3 ./compare_character.py Ermach   --code > character_map_35_ermach.py
python3 ./compare_character.py Hillary  --code > character_map_35_hillary.py
python3 ./compare_character.py Jenna    --code > character_map_35_jenna.py
python3 ./compare_character.py Jennifer --code > character_map_35_jennifer.py
python3 ./compare_character.py Jillian  --code > character_map_35_jillian.py
python3 ./compare_character.py Karyn    --code > character_map_35_karyn.py
python3 ./compare_character.py Kayla    --code > character_map_35_kayla.py
python3 ./compare_character.py Main     --code > character_map_35_main.py
python3 ./compare_character.py Martha   --code > character_map_35_martha.py
python3 ./compare_character.py Melina   --code > character_map_35_melina.py
python3 ./compare_character.py Michelle --code > character_map_35_michelle.py
python3 ./compare_character.py Mika     --code > character_map_35_mika.py
python3 ./compare_character.py Mother   --code > character_map_35_mother.py
python3 ./compare_character.py Nelson   --code > character_map_35_nelson.py
python3 ./compare_character.py Nick     --code > character_map_35_nick.py
python3 ./compare_character.py Nurse    --code > character_map_35_nurse.py
python3 ./compare_character.py Sean     --code > character_map_35_sean.py
python3 ./compare_character.py Vanessa  --code > character_map_35_vanessa.py
python3 ./compare_character.py Waitress --code > character_map_35_waitress.py

