backgroundMap45 = {
  "aprilroomday":                "coxaprilday",                 # Auto: Renamed
  "aprilroomdusk":               "coxaprildusk",                # Auto: Renamed
  "aprilroomnight":              "coxaprilnight",               # Auto: Renamed
  "aprilroomnightlit":           "coxaprillit",                 # Auto: Renamed
  "ashleycalvinhome":            "ashleycalvinhome",            # Auto: Same
  "ashleyhomeday":               "degardlivingday",             # Auto: Renamed
  "ashleyhomedoorwayday":        "degarddoorday",               # Auto: Renamed
  "ashleyhomedoorwaydusk":       "degarddoordusk",              # Auto: Renamed
  "ashleyhomedusk":              "degardlivingdusk",            # Auto: Renamed
  "ashleyhomelit":               "degardlivinglit",             # Auto: Renamed
  "ashleyroomday":               "degardashleyday",             # Auto: Renamed
  "ashleyroomdusk":              "degardashleydusk",            # Auto: Renamed
  "ashleyroomlight":             "degardashleylight",           # Auto: Renamed
  "ashleyroomlit":               "degardashleylit",             # Auto: Renamed
  "ashleyroomnight":             "degardashleynight",           # Auto: Renamed
  "black":                       "black",
  "chastitybedroomday":          "degardchastityday",           # Auto: Renamed
  "chastitybedroomdusk":         "degardchastitydusk",          # Auto: Renamed
  "chastitybedroomnight":        "degardchastitynightlit",      # Auto: Renamed
  "cielhome":                    "pirelivingday",               # Auto: Renamed
  "cielhomenightoff":            "pirelivingnight",             # Auto: Renamed
  "cielhomenighton":             "pirelivingnightlit",          # Auto: Renamed
  "classroom001":                "",                            # Auto: Deleted
  "classroom002":                "",                            # Auto: Deleted
  "classroom003":                "",                            # Auto: Deleted
  "classroom003dusk":            "",                            # Auto: Deleted
  "classroom004":                "",                            # Auto: Deleted
  "clubroomday":                 "",                            # Auto: Deleted
  "clubroomdusk":                "",                            # Auto: Deleted
  "clubroomnight":               "",                            # Auto: Deleted
  "crosswalk":                   "towncrosswalkday",            # Auto: Renamed
  "earth":                       "earth",                       # Auto: Same
  "elizaschoolcafeday":          "elizaschoolcafeday",          # Auto: Renamed
  "elizaschoolcafedusk":         "elizaschoolcafedusk",         # Auto: Renamed
  "elizaschoolclassroomday":     "elizaschoolclassroomday",     # Auto: Renamed
  "elizaschoolclassroomdusk":    "elizaschoolclassroomdusk",    # Auto: Renamed
  "elizaschoolclub2day":         "elizaschoolclub2day",         # Auto: Renamed
  "elizaschoolclub2dusk":        "elizaschoolclub2dusk",        # Auto: Renamed
  "elizaschoolclubroomday":      "elizaschoolclubroomday",      # Auto: Renamed
  "elizaschoolclubroomdusk":     "elizaschoolclubroomdusk",     # Auto: Renamed
  "elizaschoolentranceday":      "elizaschoolentranceday",      # Auto: Renamed
  "elizaschoolentrancedusk":     "elizaschoolentrancedusk",     # Auto: Renamed
  "elizaschoolfieldday":         "elizaschoolfieldday",         # Auto: Renamed
  "elizaschoolfielddusk":        "elizaschoolfielddusk",        # Auto: Renamed
  "elizaschoolgymday":           "elizaschoolgymday",           # Auto: Renamed
  "elizaschoolgymdusk":          "elizaschoolgymdusk",          # Auto: Renamed
  "elizaschoolgymclosetday":     "elizaschoolgymclosetday",     # Auto: Renamed
  "elizaschoolgymclosetdusk":    "elizaschoolgymclosetdusk",    # Auto: Renamed
  "elizaschoolhallday":          "elizaschoolhallday",          # Auto: Renamed
  "elizaschoolhalldusk":         "elizaschoolhalldusk",         # Auto: Renamed
  "elizaschoollibraryday":       "elizaschoollibraryday",       # Auto: Renamed
  "elizaschoollibrarydusk":      "elizaschoollibrarydusk",      # Auto: Renamed
  "elizaschoollockerday":        "elizaschoollockerday",        # Auto: Renamed
  "elizaschoollockerdusk":       "elizaschoollockerdusk",       # Auto: Renamed
  "elizaschoolloungeday":        "elizaschoolloungeday",        # Auto: Renamed
  "elizaschoolloungedusk":       "elizaschoolloungedusk",       # Auto: Renamed
  "elizaschoolnurseday":         "elizaschoolnurseday",         # Auto: Renamed
  "elizaschoolnursedusk":        "elizaschoolnursedusk",        # Auto: Renamed
  "elizaschoolparkday":          "elizaschoolparkday",          # Auto: Renamed
  "elizaschoolparkdusk":         "elizaschoolparkdusk",         # Auto: Renamed
  "elizaschoolpoolday":          "elizaschoolpoolday",          # Auto: Renamed
  "elizaschoolpooldusk":         "elizaschoolpooldusk",         # Auto: Renamed
  "elizaschoolroofday":          "elizaschoolroofday",          # Auto: Renamed
  "elizaschoolroofdusk":         "elizaschoolroofdusk",         # Auto: Renamed
  "elizaschoolshowersday":       "elizaschoolshowersday",       # Auto: Renamed
  "elizaschoolsideday":          "elizaschoolsideday",          # Auto: Renamed
  "elizaschoolsidedusk":         "elizaschoolsidedusk",         # Auto: Renamed
  "elizabedday":                 "mansionelizaday",             # Auto: Renamed
  "elizabeddusk":                "mansionelizadusk",            # Auto: Renamed
  "elizabednight":               "mansionelizalit",             # Auto: Renamed
  "erinlivingdusk":              "beoulvelivingdusk",           # Auto: Renamed
  "gymclosetday":                "",                            # Auto: Deleted
  "gymclosetnight":              "",                            # Auto: Deleted
  "gymday":                      "",                            # Auto: Deleted
  "gymdusk":                     "",                            # Auto: Deleted
  "heatherbedday":               "mansionheatherday",           # Auto: Renamed
  "heatherbeddusk":              "mansionheatherdusk",          # Auto: Renamed
  "heatherbednight":             "mansionheathernightlit",      # Auto: Renamed
  "heatherhomeofficeday":        "mansionofficeday",            # Auto: Renamed
  "heatherhomeofficenight":      "mansionofficenightlit",       # Auto: Renamed
  "heatherofficeday":            "heatherofficeday",            # Auto: Same
  "heatherofficedusk":           "heatherofficedusk",           # Auto: Same
  "highrestaurant":              "restaurant2insideday",        # Auto: Renamed
  "hospital1ceiling":            "hospital1ceiling",            # Auto: Same
  "hospital1hallday":            "hospital1hallday",            # Auto: Same
  "hospital1hallnight":          "hospital1hallnight",          # Auto: Same
  "hospital1hallnightlit":       "hospital1hallnightlit",       # Auto: Same
  "hospital1officeday":          "hospital1officeday",          # Auto: Same
  "hospital1outsideday":         "hospital1outsideday",         # Auto: Same
  "hospital1outsidenight":       "hospital1outsidenight",       # Auto: Same
  "hospital1outsidenightlit":    "hospital1outsidenightlit",    # Auto: Same
  "hospital1prison":             "hospital1prison",             # Auto: Same
  "hospital1receptionday":       "hospital1receptionday",       # Auto: Same
  "hospital1receptionnight":     "hospital1receptionnight",     # Auto: Same
  "hospital1room2day":           "hospital1room2day",           # Auto: Same
  "hospital1room2night":         "hospital1room2night",         # Auto: Same
  "hospital1roomday":            "hospital1roomday",            # Auto: Same
  "hospital1roomnight":          "hospital1roomnight",          # Auto: Same
  "hospital1se404":              "hospital1se404",              # Auto: Same
  "hospital1stairsday":          "hospital1stairsday",          # Auto: Same
  "hospital1stairsnight":        "hospital1stairsnight",        # Auto: Same
  "hospital1stairsnightlit":     "hospital1stairsnightlit",     # Auto: Same
  "hospital1waitingday":         "hospital1waitingday",         # Auto: Same
  "hospital1waitingnight":       "hospital1waitingnight",       # Auto: Same
  "hospital2bathroomday":        "hospital2bathroomday",        # Auto: Same
  "hospital2hallday":            "hospital2hallday",            # Auto: Same
  "hospital2halldusk":           "hospital2halldusk",           # Auto: Same
  "hospital2hallnight":          "hospital2hallnight",          # Auto: Same
  "hospital2hallnightlit":       "hospital2hallnightlit",       # Auto: Same
  "hospital2receptionday":       "hospital2receptionday",       # Auto: Same
  "hospital2receptionnight":     "hospital2receptionnight",     # Auto: Same
  "hospital2room2day":           "hospital2room2day",           # Auto: Same
  "hospital2room2night":         "hospital2room2night",         # Auto: Same
  "hospital2roomday":            "hospital2roomday",            # Auto: Same
  "hospital2roomdusk":           "hospital2roomdusk",           # Auto: Same
  "hospital2roomnight":          "hospital2roomnight",          # Auto: Same
  "hospital2roomnightlit":       "hospital2roomnightlit",       # Auto: Same
  "jennabedday":                 "mansionjennaday",             # Auto: Renamed
  "jennabeddusk":                "mansionjennadusk",            # Auto: Renamed
  "jennabednight":               "mansionjennanightlit",        # Auto: Renamed
  "karaoke":                     "karaoke",                     # Auto: Same
  "kinkroom":                    "kinkroom",                    # Auto: Same
  "lockerroomday":               "",                            # Auto: Deleted
  "lockerroomdusk":              "",                            # Auto: Deleted
  "lockerroomnight":             "",                            # Auto: Deleted
  "mainbedday":                  "mansioncalvinday",            # Auto: Renamed
  "mainbeddusk":                 "mansioncalvindusk",           # Auto: Renamed
  "mainbednight":                "mansioncalvinnightlit",       # Auto: Renamed
  "mansionatticbedday":          "mansionatticbedday",          # Auto: Same
  "mansionatticbeddusk":         "mansionatticbeddusk",         # Auto: Same
  "mansionatticbednight":        "mansionatticbednight",        # Auto: Same
  "mansionbasementbedday":       "mansionbasementbedday",       # Auto: Same
  "mansionbathroom":             "mansionbathroom",             # Auto: Same
  "mansiondiningday":            "mansiondiningday",            # Auto: Same
  "mansiondiningdusk":           "mansiondiningdusk",           # Auto: Same
  "mansiondiningnight":          "mansiondiningnightlit",       # Auto: Renamed
  "mansionentryday":             "mansionentryday",             # Auto: Same
  "mansionentrydusk":            "mansionentrydusk",            # Auto: Same
  "mansionentrynight":           "mansionentrynightlit",        # Auto: Renamed
  "mansionfatherstudyday":       "mansionfatherstudyday",       # Auto: Same
  "mansionfatherstudydusk":      "mansionfatherstudydusk",      # Auto: Same
  "mansionfatherstudynight":     "mansionfatherstudynightlit",  # Auto: Renamed
  "mansionfrontday":             "mansionfrontday",             # Auto: Same
  "mansionfrontdusk":            "mansionfrontdusk",            # Auto: Same
  "mansionfrontnight":           "mansionfrontnightlit",        # Auto: Renamed
  "mansionhalldark":             "mansionhallnight",            # Auto: Renamed
  "mansionhallday":              "mansionhallday",              # Auto: Same
  "mansionhalldusk":             "mansionhalldusk",             # Auto: Same
  "mansionhallnight":            "mansionhallnightlit",         # Auto: Renamed
  "mansionjacuzzi":              "mansionjacuzziday",           # Auto: Renamed
  "mansionkitchenday":           "mansionkitchenday",           # Auto: Same
  "mansionkitchendusk":          "mansionkitchendusk",          # Auto: Same
  "mansionkitchennight":         "mansionkitchennightlit",      # Auto: Renamed
  "mansionlivingday":            "mansionlivingday",            # Auto: Same
  "mansionlivingdusk":           "mansionlivingdusk",           # Auto: Same
  "mansionlivingnight":          "mansionlivingnightlit",       # Auto: Renamed
  "mansionmeetingday":           "mansionmeetingday",           # Auto: Same
  "mansionmeetingdusk":          "mansionmeetingdusk",          # Auto: Same
  "mansionmeetingnight":         "mansionmeetingnightlit",      # Auto: Renamed
  "mansionpoolday":              "mansionpoolday",              # Auto: Same
  "mansionroofday":              "mansionroofday",              # Auto: Same
  "mansionstairsdark":           "mansionstairsdark",           # Auto: Same
  "mansionstairsday":            "mansionstairsday",            # Auto: Same
  "mansionstairsdusk":           "mansionstairsdusk",           # Auto: Same
  "mansionstairsnight":          "mansionstairsnight",          # Auto: Same
  "mansionyardday":              "mansionyardday",              # Auto: Same
  "mansionyardnight":            "mansionyardnight",            # Auto: Same
  "marthahomeday":               "vilsonglivingday",            # Auto: Renamed
  "marthahomenight":             "vilsonglivingnightlit",       # Auto: Renamed
  "mikabathroomday":             "greenfieldbathday",           # Auto: Renamed
  "mikahomeday":                 "greenfieldlivingday",         # Auto: Renamed
  "mikahomedusk":                "greenfieldlivingdusk",        # Auto: Renamed
  "mikahomelit":                 "greenfieldlivingnightlit",    # Auto: Renamed
  "mikahomenight":               "greenfieldlivingnight",       # Auto: Renamed
  "mikaroomday":                 "greenfieldmikaday",           # Auto: Renamed
  "mikaroomdusk":                "greenfieldmikadusk",          # Auto: Renamed
  "mikaroomlit":                 "greenfieldmikanightlit",      # Auto: Renamed
  "mikaroomnight":               "greenfieldmikanight",         # Auto: Renamed
  "mikaroomnightlit":            "greenfieldmikanightlit2",     # Auto: Renamed
  "mikebathroomnight":           "greenfieldbathnight",         # Auto: Renamed
  "miyadormhallday":             "",                            # Auto: Deleted
  "miyadormhalldusk":            "",                            # Auto: Deleted
  "miyadormhallnight":           "",                            # Auto: Deleted
  "miyadormroomday":             "collegemiyaday",              # Auto: Renamed
  "miyadormroomdusk":            "collegemiyadusk",             # Auto: Renamed
  "miyadormroomnight":           "collegemiyanightlit",         # Auto: Renamed
  "miyaschoolfielddusk":         "",                            # Auto: Deleted
  "nicolebedday":                "",                            # Auto: Deleted
  "nikuback":                    "nikuback",                    # Auto: Same
  "parktreesday":                "townparktreesday",            # Auto: Renamed
  "parktreesdusk":               "townparktreesdusk",           # Auto: Renamed
  "parktreesnight":              "townparktreesnight",          # Auto: Renamed
  "parkday":                     "townparkday",                 # Auto: Renamed
  "parkdusk":                    "townparkdusk",                # Auto: Renamed
  "parknight":                   "townparknightlit",            # Auto: Renamed
  "pianohall":                   "schoolpianoday",              # Auto: Renamed
  "restaurantday":               "restaurantday",               # Auto: Same
  "restaurantdusk":              "restaurantdusk",              # Auto: Same
  "restaurantinside":            "restaurantinside",            # Auto: Same
  "restaurantnight":             "restaurantnight",             # Auto: Same
  "schoolarcheryday":            "schoolarcheryday",            # Auto: Same
  "schoolarcherydusk":           "schoolarcherydusk",           # Auto: Same
  "schoolcenterpark":            "",                            # Auto: Deleted
  "schooldancehallday":          "schooldanceday",              # Auto: Renamed
  "schooldancehallnight":        "schooldancenightlit",         # Auto: Renamed
  "schoolfieldday":              "schoolfieldday",              # Auto: Edited
  "schoolfielddusk":             "schoolfielddusk",             # Auto: Edited
  "schoolfieldnight":            "",                            # Auto: Deleted
  "schoolgirlrestroom":          "schoolrestroomgirlday",       # Auto: Renamed
  "schoolhall":                  "",                            # Auto: Deleted
  "schoolhall2":                 "",                            # Auto: Deleted
  "schoolnurseday":              "schoolnurseday",              # Auto: Edited
  "schoolnursedusk":             "schoolnursedusk",             # Auto: Edited
  "schoolnursenight":            "",                            # Auto: Deleted
  "schooloutside":               "schooloutsideday",
  "schooloutside2":              "schooloutsideday",
  "schooloutsidedusk":           "schooloutsidedusk",           # Auto: Edited
  "schoolparkday":               "schoolparkday",               # Auto: Edited
  "schoolparkdusk":              "schoolparkdusk",              # Auto: Edited
  "schoolparknight":             "",                            # Auto: Deleted
  "schoolrooftopday":            "schoolroofday",               # Auto: Renamed
  "schoolrooftopdusk":           "schoolroofdusk",              # Auto: Renamed
  "schoolrooftopnight":          "schoolroofnight",             # Auto: Renamed
  "schoolsideday":               "schoolsideday",               # Auto: Same
  "schoolsidedusk":              "schoolsidedusk",              # Auto: Same
  "schoolsidenight":             "schoolsidenight",             # Auto: Same
  "sidewalk":                    "townsidewalkday",             # Auto: Renamed
  "skyclear":                    "skyclear",                    # Auto: Same
  "skycloudy":                   "skycloudy",                   # Auto: Same
  "skydusk":                     "skydusk",                     # Auto: Same
  "street":                      "townstreetnickday",           # Auto: Renamed
  "streettoashleyday":           "townstreetashleyday",         # Auto: Renamed
  "streettoashleydusk":          "townstreetashleydusk",        # Auto: Renamed
  "streettoashleynight":         "townstreetashleynight",       # Auto: Renamed
  "streettomikaday":             "townstreetmikaday",           # Auto: Renamed
  "streettomikadusk":            "townstreetmikadusk",          # Auto: Renamed
  "streettomikanight":           "townstreetmikanight",         # Auto: Renamed
  "white":                       "white",
};

backgroundMap35 = {
  "aprilroomday":                "coxaprilday",                 # Auto: Renamed
  "aprilroomdusk":               "coxaprildusk",                # Auto: Renamed
  "aprilroomnight":              "coxaprilnight",               # Auto: Renamed
  "aprilroomnightlit":           "coxaprillit",                 # Auto: Renamed
  "archeryday":                  "",                            # Auto: Deleted
  "archerydusk":                 "",                            # Auto: Deleted
  "ashleycalvinhome":            "ashleycalvinhome",            # Auto: Renamed
  "ashleyhomedoorwayday":        "degarddoorday",               # Auto: Renamed
  "ashleyhomedoorwaydusk":       "degarddoordusk",              # Auto: Renamed
  "ashleyhomeday":               "degardlivingday",             # Auto: Renamed
  "ashleyhomedusk":              "degardlivingdusk",            # Auto: Renamed
  "ashleyhomelit":               "degardlivinglit",             # Auto: Renamed
  "ashleyroomday":               "degardashleyday",             # Auto: Renamed
  "ashleyroomdusk":              "degardashleydusk",            # Auto: Renamed
  "ashleyroomlight":             "degardashleylight",           # Auto: Renamed
  "ashleyroomlit":               "degardashleylit",             # Auto: Renamed
  "ashleyroomnight":             "degardashleynight",           # Auto: Renamed
  "black":                       "black",
  "chastitybedroomday":          "degardchastityday",           # Auto: Renamed
  "chastitybedroomdusk":         "degardchastitydusk",          # Auto: Renamed
  "chastitybedroomnight":        "degardchastitynightlit",      # Auto: Renamed
  "cielhomeday":                 "pirelivingday",               # Auto: Renamed
  "cielhomenightoff":            "pirelivingnight",             # Auto: Renamed
  "cielhomenighton":             "pirelivingnightlit",          # Auto: Renamed
  "classroom4":                  "",                            # Auto: Deleted
  "classroom001":                "",                            # Auto: Deleted
  "classroom002":                "",                            # Auto: Deleted
  "classroom003":                "",                            # Auto: Deleted
  "classroom003dusk":            "",                            # Auto: Deleted
  "clubroomday":                 "",                            # Auto: Deleted
  "clubroomdusk":                "",                            # Auto: Deleted
  "clubroomnight":               "",                            # Auto: Deleted
  "crosswalk":                   "towncrosswalkday",            # Auto: Renamed
  "dancehallday":                "schooldanceday",              # Auto: Renamed
  "dancehallnight":              "schooldancenightlit",         # Auto: Renamed
  "earth":                       "earth",                       # Auto: Same
  "elizabedday":                 "mansionelizaday",
  "elizabeddusk":                "mansionelizadusk",
  "elizabednight":               "mansionelizalit",
  "elizaschoolcafeday":          "elizaschoolcafeday",          # Auto: Renamed
  "elizaschoolcafedusk":         "elizaschoolcafedusk",         # Auto: Renamed
  "elizaschoolclassroomday":     "elizaschoolclassroomday",     # Auto: Renamed
  "elizaschoolclassroomdusk":    "elizaschoolclassroomdusk",    # Auto: Renamed
  "elizaschoolclub2day":         "elizaschoolclub2day",         # Auto: Renamed
  "elizaschoolclub2dusk":        "elizaschoolclub2dusk",        # Auto: Renamed
  "elizaschoolclubroomday":      "elizaschoolclubroomday",      # Auto: Renamed
  "elizaschoolclubroomdusk":     "elizaschoolclubroomdusk",     # Auto: Renamed
  "elizaschoolentranceday":      "elizaschoolentranceday",      # Auto: Renamed
  "elizaschoolentrancedusk":     "elizaschoolentrancedusk",     # Auto: Renamed
  "elizaschoolfieldday":         "elizaschoolfieldday",         # Auto: Renamed
  "elizaschoolfielddusk":        "elizaschoolfielddusk",        # Auto: Renamed
  "elizaschoolgymday":           "elizaschoolgymday",           # Auto: Renamed
  "elizaschoolgymdusk":          "elizaschoolgymdusk",          # Auto: Renamed
  "elizaschoolgymclosetday":     "elizaschoolgymclosetday",     # Auto: Renamed
  "elizaschoolgymclosetdusk":    "elizaschoolgymclosetdusk",    # Auto: Renamed
  "elizaschoolhallday":          "elizaschoolhallday",          # Auto: Renamed
  "elizaschoolhalldusk":         "elizaschoolhalldusk",         # Auto: Renamed
  "elizaschoollibraryday":       "elizaschoollibraryday",       # Auto: Renamed
  "elizaschoollibrarydusk":      "elizaschoollibrarydusk",      # Auto: Renamed
  "elizaschoollockerday":        "elizaschoollockerday",        # Auto: Renamed
  "elizaschoollockerdusk":       "elizaschoollockerdusk",       # Auto: Renamed
  "elizaschoolloungeday":        "elizaschoolloungeday",        # Auto: Renamed
  "elizaschoolloungedusk":       "elizaschoolloungedusk",       # Auto: Renamed
  "elizaschoolnurseday":         "elizaschoolnurseday",         # Auto: Renamed
  "elizaschoolnursedusk":        "elizaschoolnursedusk",        # Auto: Renamed
  "elizaschoolparkday":          "elizaschoolparkday",          # Auto: Renamed
  "elizaschoolparkdusk":         "elizaschoolparkdusk",         # Auto: Renamed
  "elizaschoolpoolday":          "elizaschoolpoolday",          # Auto: Renamed
  "elizaschoolpooldusk":         "elizaschoolpooldusk",         # Auto: Renamed
  "elizaschoolroofday":          "elizaschoolroofday",          # Auto: Renamed
  "elizaschoolroofdusk":         "elizaschoolroofdusk",         # Auto: Renamed
  "elizaschoolshowersday":       "elizaschoolshowersday",       # Auto: Renamed
  "elizaschoolsideday":          "elizaschoolsideday",          # Auto: Renamed
  "elizaschoolsidedusk":         "elizaschoolsidedusk",         # Auto: Renamed
  "flash":                       "",                            # Auto: Deleted
  "flashwhite":                  "",                            # Auto: Deleted
  "gymclosetday":                "",                            # Auto: Deleted
  "gymclosetnight":              "",                            # Auto: Deleted
  "gymday":                      "",                            # Auto: Deleted
  "gymdusk":                     "",                            # Auto: Deleted
  "heatherhomeofficeday":        "mansionofficeday",
  "heatherofficeday":            "heatherofficeday",            # Auto: Same
  "heatherofficedusk":           "heatherofficedusk",           # Auto: Same
  "highrestaurant":              "restaurant2insideday",        # Auto: Renamed
  "hospital1hallday":            "hospital1hallday",            # Auto: Same
  "hospital1hallnight":          "hospital1hallnight",          # Auto: Same
  "hospital1hallnightlit":       "hospital1hallnightlit",       # Auto: Same
  "hospital1officeday":          "hospital1officeday",          # Auto: Same
  "hospital1outsideday":         "hospital1outsideday",         # Auto: Same
  "hospital1outsidenight":       "hospital1outsidenight",       # Auto: Same
  "hospital1outsidenightlit":    "hospital1outsidenightlit",    # Auto: Same
  "hospital1prison":             "hospital1prison",             # Auto: Same
  "hospital1receptionday":       "hospital1receptionday",       # Auto: Same
  "hospital1receptionnight":     "hospital1receptionnight",     # Auto: Same
  "hospital1room2day":           "hospital1room2day",           # Auto: Same
  "hospital1room2night":         "hospital1room2night",         # Auto: Same
  "hospital1roomday":            "hospital1roomday",            # Auto: Same
  "hospital1roomnight":          "hospital1roomnight",          # Auto: Same
  "hospital1stairsday":          "hospital1stairsday",          # Auto: Same
  "hospital1stairsnight":        "hospital1stairsnight",        # Auto: Same
  "hospital1stairsnightlit":     "hospital1stairsnightlit",     # Auto: Same
  "hospital1waitingday":         "hospital1waitingday",         # Auto: Same
  "hospital1waitingnight":       "hospital1waitingnight",       # Auto: Same
  "hospital2bathroomday":        "hospital2bathroomday",        # Auto: Edited
  "hospital2hallday":            "hospital2hallday",            # Auto: Same
  "hospital2halldusk":           "hospital2halldusk",           # Auto: Same
  "hospital2hallnight":          "hospital2hallnight",          # Auto: Same
  "hospital2hallnightlit":       "hospital2hallnightlit",       # Auto: Same
  "hospital2receptionday":       "hospital2receptionday",       # Auto: Same
  "hospital2receptionnight":     "hospital2receptionnight",     # Auto: Same
  "hospital2room2day":           "hospital2room2day",           # Auto: Edited
  "hospital2room2night":         "hospital2room2night",         # Auto: Edited
  "hospital2roomday":            "hospital2roomday",            # Auto: Same
  "hospital2roomdusk":           "hospital2roomdusk",           # Auto: Same
  "hospital2roomnight":          "hospital2roomnight",          # Auto: Same
  "hospital2roomnightlit":       "hospital2roomnightlit",       # Auto: Same
  "karaoke":                     "karaoke",                     # Auto: Same
  "kinkroom":                    "kinkroom",                    # Auto: Same
  "lockerroomday":               "",                            # Auto: Deleted
  "lockerroomdusk":              "",                            # Auto: Deleted
  "lockerroomnight":             "",                            # Auto: Deleted
  "mainbedday":                  "mansioncalvinday",
  "mainbeddusk":                 "mansioncalvindusk",
  "mansionatticbedroomday":      "mansionatticbedday",          # Auto: Renamed
  "mansionatticbedroomdusk":     "mansionatticbeddusk",         # Auto: Renamed
  "mansionatticbedroomnight":    "mansionatticbednight",        # Auto: Renamed
  "mansionbasementbedroomday":   "mansionbasementbedday",       # Auto: Renamed
  "mansionbathroom":             "mansionbathroom",             # Auto: Same
  "mansioncalvinbedroomday":     "mansioncalvinday",            # Auto: Renamed
  "mansioncalvinbedroomdusk":    "mansioncalvindusk",           # Auto: Renamed
  "mansioncalvinbedroomnight":   "mansioncalvinnightlit",       # Auto: Renamed
  "mansiondiningday":            "mansiondiningday",
  "mansiondiningroomday":        "mansiondiningday",            # Auto: Renamed
  "mansiondiningroomdusk":       "mansiondiningdusk",           # Auto: Renamed
  "mansiondiningroomnight":      "mansiondiningnightlit",       # Auto: Renamed
  "mansionelizabedroomday":      "mansionelizaday",             # Auto: Renamed
  "mansionelizabedroomdusk":     "mansionelizadusk",            # Auto: Renamed
  "mansionelizabedroomnight":    "mansionelizalit",             # Auto: Renamed
  "mansionentrywayday":          "mansionentryday",             # Auto: Renamed
  "mansionentrywaydusk":         "mansionentrydusk",            # Auto: Renamed
  "mansionentrywaynight":        "mansionentrynightlit",        # Auto: Renamed
  "mansionfatherstudyday":       "mansionfatherstudyday",       # Auto: Same
  "mansionfatherstudydusk":      "mansionfatherstudydusk",      # Auto: Same
  "mansionfatherstudynight":     "mansionfatherstudynightlit",  # Auto: Renamed
  "mansionfrontday":             "mansionfrontday",             # Auto: Same
  "mansionfrontdusk":            "mansionfrontdusk",            # Auto: Same
  "mansionfrontnight":           "mansionfrontnightlit",        # Auto: Renamed
  "mansionhalldark":             "mansionhallnight",
  "mansionhallday":              "mansionhallday",
  "mansionhalldusk":             "mansionhalldusk",
  "mansionhallnight":            "mansionhallnightlit",
  "mansionhallwaydark":          "mansionhallnight",            # Auto: Renamed
  "mansionhallwayday":           "mansionhallday",              # Auto: Renamed
  "mansionhallwaydusk":          "mansionhalldusk",             # Auto: Renamed
  "mansionhallwaynight":         "mansionhallnightlit",         # Auto: Renamed
  "mansionhallwaystairsdark":    "mansionstairsdark",           # Auto: Renamed
  "mansionhallwaystairsday":     "mansionstairsday",            # Auto: Renamed
  "mansionhallwaystairsdusk":    "mansionstairsdusk",           # Auto: Renamed
  "mansionhallwaystairsnight":   "mansionstairsnight",          # Auto: Renamed
  "mansionjacuzzi":              "mansionjacuzziday",           # Auto: Renamed
  "mansionjennabedroomday":      "mansionjennaday",             # Auto: Renamed
  "mansionjennabedroomdusk":     "mansionjennadusk",            # Auto: Renamed
  "mansionjennabedroomnight":    "mansionjennanightlit",        # Auto: Renamed
  "mansionkitchenday":           "mansionkitchenday",           # Auto: Same
  "mansionkitchendusk":          "mansionkitchendusk",          # Auto: Same
  "mansionkitchennight":         "mansionkitchennightlit",      # Auto: Renamed
  "mansionlivingday":            "mansionlivingday",
  "mansionlivingroomday":        "mansionlivingday",            # Auto: Renamed
  "mansionlivingroomdusk":       "mansionlivingdusk",           # Auto: Renamed
  "mansionlivingroomnight":      "mansionlivingnightlit",       # Auto: Renamed
  "mansionmeetingroomday":       "mansionmeetingday",           # Auto: Renamed
  "mansionmeetingroomdusk":      "mansionmeetingdusk",          # Auto: Renamed
  "mansionmeetingroomnight":     "mansionmeetingnightlit",      # Auto: Renamed
  "mansionmotherbedroomday":     "mansionheatherday",           # Auto: Renamed
  "mansionmotherbedroomdusk":    "mansionheatherdusk",          # Auto: Renamed
  "mansionmotherbedroomnight":   "mansionheathernightlit",      # Auto: Renamed
  "mansionmotherofficeday":      "mansionofficeday",            # Auto: Renamed
  "mansionmotherofficenight":    "mansionofficenightlit",       # Auto: Renamed
  "mansionpoolday":              "mansionpoolday",              # Auto: Same
  "mansionrooftopday":           "mansionroofday",              # Auto: Renamed
  "mansionyardday":              "mansionyardday",              # Auto: Same
  "mansionyardnight":            "mansionyardnight",            # Auto: Same
  "mikabathroomday":             "greenfieldbathday",           # Auto: Renamed
  "mikabathroomnight":           "greenfieldbathnight",         # Auto: Renamed
  "mikahouseday":                "greenfieldlivingday",         # Auto: Renamed
  "mikahousedusk":               "greenfieldlivingdusk",        # Auto: Renamed
  "mikahouselit":                "greenfieldlivingnightlit",    # Auto: Renamed
  "mikahousenight":              "greenfieldlivingnight",       # Auto: Renamed
  "mikaroomdusk":                "greenfieldmikadusk",          # Auto: Renamed
  "mikaroomlit":                 "greenfieldmikanightlit",      # Auto: Renamed
  "mikaroommorning":             "greenfieldmikaday",           # Auto: Renamed
  "mikaroomnight":               "greenfieldmikanight",         # Auto: Renamed
  "mikaroomnightlit":            "greenfieldmikanightlit2",     # Auto: Renamed
  "miyadormhallday":             "",                            # Auto: Deleted
  "miyadormhalldusk":            "",                            # Auto: Deleted
  "miyadormhallnight":           "",                            # Auto: Deleted
  "miyadormroomday":             "collegemiyaday",              # Auto: Renamed
  "miyadormroomdusk":            "collegemiyadusk",             # Auto: Renamed
  "miyadormroomnight":           "collegemiyanightlit",         # Auto: Renamed
  "miyaschoolfielddusk":         "",                            # Auto: Deleted
  "nicolebedroomday":            "",                            # Auto: Deleted
  "nicolebedroom":               "",                            # Auto: Deleted
  "nursesroomday":               "",                            # Auto: Deleted
  "nursesroomdusk":              "",                            # Auto: Deleted
  "nursesroomnight":             "",                            # Auto: Deleted
  "parktreesday":                "townparktreesday",            # Auto: Renamed
  "parktreesdusk":               "townparktreesdusk",           # Auto: Renamed
  "parktreesnight":              "townparktreesnight",          # Auto: Renamed
  "parkday":                     "townparkday",                 # Auto: Renamed
  "parkdusk":                    "townparkdusk",                # Auto: Renamed
  "parknight":                   "townparknightlit",            # Auto: Renamed
  "pianohall":                   "schoolpianoday",              # Auto: Renamed
  "restaurantnight":             "restaurantnight",             # Auto: Edited
  "restaurantday":               "",                            # Auto: Deleted
  "restaurantdusk":              "",                            # Auto: Deleted
  "restaurantinside":            "",                            # Auto: Deleted
  "schoolfieldday":              "",                            # Auto: Deleted
  "schoolfielddusk":             "",                            # Auto: Deleted
  "schoolfieldnight":            "",                            # Auto: Deleted
  "schoolcenterpark":            "",                            # Auto: Deleted
  "schoolgirlsrestroom":         "schoolrestroomgirlday",       # Auto: Renamed
  "schoolhall":                  "",                            # Auto: Deleted
  "schoolhall2":                 "",                            # Auto: Deleted
  "schooloutside":               "schooloutsideday",
  "schooloutside2":              "schooloutsideday",
  "schooloutsidedawn":           "",                            # Auto: Deleted
  "schoolparkday":               "",                            # Auto: Deleted
  "schoolparkdusk":              "",                            # Auto: Deleted
  "schoolparknight":             "",                            # Auto: Deleted
  "schoolrooftopday":            "schoolroofday",               # Auto: Renamed
  "schoolrooftopdusk":           "schoolroofdusk",              # Auto: Renamed
  "schoolrooftopnight":          "schoolroofnight",             # Auto: Renamed
  "schoolsideday":               "schoolsideday",               # Auto: Renamed
  "schoolsidedusk":              "schoolsidedusk",              # Auto: Renamed
  "schoolsidenight":             "schoolsidenight",             # Auto: Renamed
  "sidewalk":                    "townsidewalkday",             # Auto: Renamed
  "street":                      "townstreetnickday",           # Auto: Renamed
  "streettoashleyday":           "townstreetashleyday",         # Auto: Renamed
  "streettoashleydusk":          "townstreetashleydusk",        # Auto: Renamed
  "streettoashleynight":         "townstreetashleynight",       # Auto: Renamed
  "streettomikaday":             "townstreetmikaday",           # Auto: Renamed
  "streettomikadusk":            "townstreetmikadusk",          # Auto: Renamed
  "streettomikanight":           "townstreetmikanight",         # Auto: Renamed
};
