# Holds cgreplacements and background replacements so i dont have to scroll by them
# DONT EVER TOUCH THESE, THEY WERE TROUGHROLY TESTED BEFORE HAND
cgreplacers = {
    "cg anna 1": ["cgbase anna grope 1", "cgeyes anna grope 1", "cgex anna grope 1"],
    "cg anna 2": ["cgbase anna grope 1", "cgeyes anna grope 2", "cgex anna grope 3"],
    "cg anna 3": ["cgbase anna grope 1", "cgeyes anna grope 3", "cgex anna grope 4"],
    "cg anna 4": ["cgbase anna grope 1", "cgeyes anna grope 4", "cgex anna grope 2"],
    "cg anna 5": [
        "cgbase anna grope 1",
        "cgeyes anna grope 2",
        "cgex anna grope 3",
        "cgalt anna grope 1",
    ],
    "cg anna 6": [
        "cgbase anna grope 1",
        "cgeyes anna grope 4",
        "cgex anna grope 2",
        "cgalt anna grope 1",
    ],
    "cg ashley robe cut 1": ["cg ashley robecut 1"],
    "cg ashley robe cut 2": ["cg ashley robecut 2"],
    "cg ashley robe cut combine": ["cg ashley robecut combine"],
    "cg ashley sleeping 1": ["cgcut ashley sleeping 1"],
    "cg betmel kiss": ["cgbase betmel kiss 1"],
    "cgbase chastity sit": ["cgbase chastity sit 1"],
    "cgbe1 chastity sit": ["cgbe1 chastity sit 1"],
    "cgbase chastity vib": ["cgbase chastity vib 1"],
    "cgbe1 chastity vib": ["cgbe1 chastity vib 1"],
    "cg eliza sleep 1": ["cgbase eliza sleep 1", "cgex eliza sleep 1"],
    "cg eliza sleep 2": ["cgbase eliza sleep 1", "cgex eliza sleep 2"],
    "cg eliza sleep 3": ["cgbase eliza sleep 1", "cgex eliza sleep 3"],
    "cg eliza sleep 4": ["cgbase eliza sleep 1", "cgex eliza sleep 4"],
    "cg eliza sleep 5": ["cgbase eliza sleep 1", "cgex eliza sleep 5"],
    "cg eliza sleep 6": ["cgbase eliza sleep 1", "cgex eliza sleep 6"],
    "cgex eliza sleep br 1": [""],
    "cg fair 1": ["cgbase fair podium 1"],
    "cg mother suit shot": ["cgcut heather suit 1"],
    "cg hope gym 1": [
        "cgbase hope gstretch 1",
        "cgeyes hope gstretch 1",
        "cgex hope gstretch 1",
    ],
    "cg hope gym 2": [
        "cgbase hope gstretch 1",
        "cgeyes hope gstretch 2",
        "cgex hope gstretch 2",
    ],
    "cg hope cos 1": ["cgbase hope scos 1"],
    "cg hope fit 1": [
        "cgbase hope stretch 1",
        "cgeyes hope stretch 1",
        "cgex hope stretch 1",
    ],
    "cg hope fit 2": ["cgzoom hope stretch 1"],
    "cg hope fit 3": [
        "cgbase hope stretch 1",
        "cgeyes hope stretch 2",
        "cgex hope stretch 2",
    ],
    "cg iida 1": ["cgbase iida bmas 1", "cgeyes iida bmas 1", "cgex iida bmas 1"],
    "cg iida 2": ["cgbase iida bmas 1", "cgeyes iida bmas 2", "cgex iida bmas 2"],
    "cg iida 3": ["cgbase iida bmas 1", "cgeyes iida bmas 3", "cgex iida bmas 3"],
    "cg iida 4": ["cgbase iida teach 1", "cgeyes iida teach 1", "cgex iida teach 1"],
    "cg iida 5": ["cgbase iida teach 1", "cgeyes iida teach 2", "cgex iida teach 2"],
    "cg melina 30": ["cgzoom melina desk 1"],
    "cg melina 5": ["cgzoom melina grass 1"],
    "cg mika bike 1": ["cgbase mika bike 1"],
    "cg mika 1": ["cgbase mika sweat 1", "cgeyes mika sweat 1", "cgex mika sweat 3"],
    "cg mika 2": ["cgbase mika sweat 1", "cgeyes mika sweat 2", "cgex mika sweat 1"],
    "cg mika 3": ["cgbase mika sweat 1", "cgeyes mika sweat 3", "cgex mika sweat 2"],
    "cg mika 4": ["cgzoom mika sweat 1"],
    "cg miya mas 6": ["cgzoom miya mas 1"],
    "cg miya swim 1": [
        "cgbase miya swimpose 1",
        "cgeyes miya swimpose 1",
        "cgex miya swimpose 1",
    ],
    "cg miya swim 2": ["cgzoom miya swimpose 1"],
    "cg miya swim 4": [
        "cgbase miya swimpose 1",
        "cgeyes miya swimpose 2",
        "cgalt miya swimpose 1",
    ],
    "cg miya swim 3": ["cgzoom miya swimpose 2"],
    "cg miya ball 7": [
        "cgbase miya volley 1",
        "cgeyes miya volley 4",
        "cgex miya volley 4",
        "cgpose miya volley 3",
    ],
    "cgcover nicole mas 1": ["cgcut nicole mas 1"],
    "cgpose1 nicole mas": ["cgalt nicole mas 1"],
    "cgpose2 nicole mas": ["cgliq nicole mas 1"],
    "cgpose3 nicole mas": ["cgpose nicole mas 1"],
    "cgpose4 nicole mas": ["cgnip nicole mas 1"],
    "cg ashley 60": [
        "cgbase ashley butt 1",
        "cgeyes ashley butt 1",
        "cgex ashley butt 1",
    ],
    "cg ashley 61": [
        "cgbase ashley butt 1",
        "cgeyes ashley butt 2",
        "cgex ashley butt 2",
    ],
    "cg ashley 62": [
        "cgbase ashley butt 1",
        "cgeyes ashley butt 3",
        "cgex ashley butt 3",
    ],
    "cg ashley 63": [
        "cgbase ashley butt 1",
        "cgeyes ashley butt 1",
        "cgex ashley butt 1",
        "cgalt ashley butt 1",
    ],
    "cg ashley 64": [
        "cgbase ashley butt 1",
        "cgeyes ashley butt 1",
        "cgex ashley butt 1",
        "cgalt ashley butt 1",
    ],
    "cg ashley 65": [
        "cgbase ashley butt 1",
        "cgeyes ashley butt 4",
        "cgex ashley butt 4",
        "cgalt ashley butt 1",
    ],
    "cg ashley 66": [
        "cgbase ashley butt 1",
        "cgeyes ashley butt 1",
        "cgex ashley butt 1",
        "cgalt ashley butt 1",
    ],
    "cg ashley 67": [
        "cgbase ashley butt 1",
        "cgeyes ashley butt 5",
        "cgex ashley butt 5",
        "cgalt ashley butt 2",
    ],
    "cg ashley 68": [
        "cgbase ashley butt 1",
        "cgeyes ashley butt 5",
        "cgex ashley butt 5",
        "cgalt ashley butt 2",
    ],
    "cg ashley 69": [
        "cgbase ashley butt 1",
        "cgeyes ashley butt 6",
        "cgex ashley butt 6",
        "cgalt ashley butt 2",
    ],
    "cg ashley 78": [
        "cgbase ashley dlift 1",
        "cgeyes ashley dlift 1",
        "cgex ashley dlift 1",
    ],
    "cg ashley 79": [
        "cgbase ashley dlift 1",
        "cgeyes ashley dlift 2",
        "cgex ashley dlift 2",
    ],
    "cg ashley 80": [
        "cgbase ashley dlift 1",
        "cgeyes ashley dlift 3",
        "cgex ashley dlift 3",
    ],
    "cg ashley 81": [
        "cgbase ashley dlift 1",
        "cgeyes ashley dlift 4",
        "cgex ashley dlift 4",
        "cgalt ashley dlift 1",
    ],
    "cg ashley 82": [
        "cgbase ashley dlift 1",
        "cgeyes ashley dlift 5",
        "cgex ashley dlift 5",
        "cgalt ashley dlift 2",
    ],
    "cg ashley 83": [
        "cgbase ashley dlift 1",
        "cgeyes ashley dlift 6",
        "cgex ashley dlift 6",
        "cgalt ashley dlift 2",
    ],
    "cg ashley 84": [
        "cgbase ashley dlift 1",
        "cgeyes ashley dlift 2",
        "cgex ashley dlift 2",
        "cgalt ashley dlift 2",
    ],
    "cg ashley 85": [
        "cgbase ashley dlift 1",
        "cgeyes ashley dlift 3",
        "cgex ashley dlift 3",
        "cgalt ashley dlift 2",
    ],
    "cg ashley 86": [
        "cgbase ashley dlift 1",
        "cgeyes ashley dlift 1",
        "cgex ashley dlift 1",
        "cgalt ashley dlift 2",
    ],
    "cg ashley 87": [
        "cgbase ashley dlift 1",
        "cgeyes ashley dlift 6",
        "cgex ashley dlift 6",
        "cgalt ashley dlift 3",
    ],
    "cg ashley 88": [
        "cgbase ashley dlift 1",
        "cgeyes ashley dlift 6",
        "cgex ashley dlift 6",
        "cgalt ashley dlift 3",
    ],
    "cg ashley 89": [
        "cgbase ashley dlift 1",
        "cgeyes ashley dlift 4",
        "cgex ashley dlift 4",
        "cgalt ashley dlift 3",
    ],
    "cg ashley 90": [
        "cgbase ashley dlift 1",
        "cgpose ashley dlift 1",
        "cgalt ashley dlift 3",
    ],
    "cg ashley 91": [
        "cgbase ashley dlift 1",
        "cgeyes ashley dlift 5",
        "cgex ashley dlift 5",
        "cgalt ashley dlift 3",
    ],
    "cg ashley 70": [
        "cgbase ashley dtit 1",
        "cgeyes ashley dtit 5",
        "cgex ashley dtit 5",
        "cgpose ashley dtit 2",
        "cgnip ashley dtit 1",
    ],
    "cg ashley 71": [
        "cgbase ashley dtit 1",
        "cgeyes ashley dtit 6",
        "cgex ashley dtit 6",
        "cgpose ashley dtit 2",
        "cgnip ashley dtit 1",
    ],
    "cg ashley 72": [
        "cgbase ashley dtit 1",
        "cgeyes ashley dtit 7",
        "cgex ashley dtit 7",
        "cgpose ashley dtit 2",
        "cgnip ashley dtit 1",
    ],
    "cg ashley 73": [
        "cgbase ashley dtit 1",
        "cgeyes ashley dtit 3",
        "cgex ashley dtit 3",
    ],
    "cg ashley 74": [
        "cgbase ashley dtit 1",
        "cgpose ashley dtit 1",
        "cgpose ashley dtit 1",
    ],
    "cg ashley 75": [
        "cgbase ashley dtit 1",
        "cgcum ashley dtit 3",
        "cgpose ashley dtit 3",
        "cgnip ashley dtit 1",
    ],
    "cg ashley 76": [
        "cgbase ashley dtit 1",
        "cgcum ashley dtit 4",
        "cgpose ashley dtit 3",
        "cgnip ashley dtit 1",
    ],
    "cg ashley 77": [
        "cgbase ashley dtit 1",
        "cgcum ashley dtit 5",
        "cgpose ashley dtit 3",
        "cgnip ashley dtit 1",
    ],
    "cg ashley 100": [
        "cgbase ashley dvib 1",
        "cgpose ashley dvib 1",
        "cgalt ashley dvib 1",
        "cgcut ashley dvib 1",
    ],
    "cg ashley 101": [
        "cgbase ashley dvib 1",
        "cgeyes ashley dvib 5",
        "cgex ashley dvib 5",
        "cgpose ashley dvib 1",
    ],
    "cg ashley 102": [
        "cgbase ashley dvib 1",
        "cgeyes ashley dvib 4",
        "cgex ashley dvib 4",
        "cgpose ashley dvib 1",
    ],
    "cg ashley 92": [
        "cgbase ashley dvib 1",
        "cgeyes ashley dvib 1",
        "cgex ashley dvib 3",
    ],
    "cg ashley 93": [
        "cgbase ashley dvib 1",
        "cgeyes ashley dvib 2",
        "cgex ashley dvib 1",
    ],
    "cg ashley 94": [
        "cgbase ashley dvib 1",
        "cgeyes ashley dvib 3",
        "cgex ashley dvib 2",
    ],
    "cg ashley 95": [
        "cgbase ashley dvib 1",
        "cgeyes ashley dvib 3",
        "cgex ashley dvib 2",
        "cgpose ashley dvib 1",
    ],
    "cg ashley 96": [
        "cgbase ashley dvib 1",
        "cgeyes ashley dvib 2",
        "cgex ashley dvib 1",
        "cgpose ashley dvib 1",
    ],
    "cg ashley 97": [
        "cgbase ashley dvib 1",
        "cgeyes ashley dvib 4",
        "cgex ashley dvib 4",
        "cgpose ashley dvib 1",
    ],
    "cg ashley 98": [
        "cgbase ashley dvib 1",
        "cgeyes ashley dvib 1",
        "cgex ashley dvib 3",
        "cgpose ashley dvib 1",
    ],
    "cg ashley 99": [
        "cgbase ashley dvib 1",
        "cgpose ashley dvib 1",
        "cgalt ashley dvib 1",
    ],
    "cg ashley 46": [
        "cgbase ashley floor 1",
        "cgeyes ashley floor 1",
        "cgex ashley floor 1",
    ],
    "cg ashley 47": [
        "cgbase ashley floor 1",
        "cgeyes ashley floor 1",
        "cgex ashley floor 1",
        "cgcut ashley floor 1",
    ],
    "cg ashley 48": [
        "cgbase ashley floor 1",
        "cgeyes ashley floor 2",
        "cgex ashley floor 2",
        "cgcut ashley floor 1",
    ],
    "cg ashley 49": [
        "cgbase ashley floor 1",
        "cgeyes ashley floor 3",
        "cgex ashley floor 3",
        "cgcut ashley floor 1",
    ],
    "cg ashley 50": [
        "cgbase ashley floor 1",
        "cgeyes ashley floor 3",
        "cgex ashley floor 3",
    ],
    "cg ashley 51": [
        "cgbase ashley floor 1",
        "cgeyes ashley floor 2",
        "cgex ashley floor 2",
    ],
    "cg ashley 52": [
        "cgbase ashley floor 1",
        "cgeyes ashley floor 1",
        "cgex ashley floor 1",
        "cgalt ashley floor 1",
    ],
    "cg ashley 53": ["cgzoom ashley floor 1"],
    "cg ashley 54": [
        "cgbase ashley floor 1",
        "cgeyes ashley floor 1",
        "cgex ashley floor 4",
        "cgalt ashley floor 1",
    ],
    "cg ashley 55": [
        "cgbase ashley floor 1",
        "cgeyes ashley floor 1",
        "cgex ashley floor 1",
        "cgalt ashley floor 2",
    ],
    "cg ashley 56": [
        "cgbase ashley floor 1",
        "cgeyes ashley floor 2",
        "cgex ashley floor 2",
        "cgalt ashley floor 2",
    ],
    "cg ashley 57": [
        "cgbase ashley floor 1",
        "cgeyes ashley floor 1",
        "cgex ashley floor 4",
        "cgalt ashley floor 2",
    ],
    "cg ashley 58": [
        "cgbase ashley floor 1",
        "cgeyes ashley floor 4",
        "cgex ashley floor 1",
        "cgalt ashley floor 3",
    ],
    "cg ashley 59": [
        "cgbase ashley floor 1",
        "cgeyes ashley floor 5",
        "cgex ashley floor 5",
        "cgalt ashley floor 4",
    ],
    "cg ashley 35": [
        "cgbase ashley handjob 1",
        "cgeyes ashley handjob 1",
        "cgex ashley handjob 1",
    ],
    "cg ashley 36": [
        "cgbase ashley handjob 1",
        "cgeyes ashley handjob 2",
        "cgex ashley handjob 2",
    ],
    "cg ashley 37": [
        "cgbase ashley handjob 1",
        "cgeyes ashley handjob 3",
        "cgex ashley handjob 2",
    ],
    "cg ashley 38": [
        "cgbase ashley handjob 1",
        "cgeyes ashley handjob 3",
        "cgex ashley handjob 2",
        "cgalt ashley handjob 1",
    ],
    "cg ashley 39": [
        "cgbase ashley handjob 1",
        "cgeyes ashley handjob 4",
        "cgex ashley handjob 3",
        "cgalt ashley handjob 1",
    ],
    "cg ashley 40": [
        "cgbase ashley handjob 1",
        "cgeyes ashley handjob 1",
        "cgex ashley handjob 1",
        "cgalt ashley handjob 1",
        "cgliq ashley handjob 1",
    ],
    "cg ashley 41": [
        "cgbase ashley handjob 1",
        "cgeyes ashley handjob 5",
        "cgex ashley handjob 1",
        "cgalt ashley handjob 1",
        "cgliq ashley handjob 1",
    ],
    "cg ashley 42": [
        "cgbase ashley handjob 1",
        "cgeyes ashley handjob 3",
        "cgex ashley handjob 2",
        "cgalt ashley handjob 1",
        "cgliq ashley handjob 1",
    ],
    "cg ashley 43": [
        "cgbase ashley handjob 1",
        "cgeyes ashley handjob 4",
        "cgex ashley handjob 3",
        "cgalt ashley handjob 1",
        "cgliq ashley handjob 1",
    ],
    "cg ashley 44": [
        "cgbase ashley handjob 1",
        "cgex ashley handjob 8",
        "cgalt ashley handjob 1 behind cgex",
    ],
    "cg ashley 45": [
        "cgbase ashley handjob 1",
        "cgex ashley handjob 9",
        "cgalt ashley handjob 1 behind cgex",
    ],
    "cg ashley 13": [
        "cgbase ashley lick 1",
        "cgeyes ashley lick 2",
        "cgex ashley lick 2",
    ],
    "cg ashley 14": [
        "cgbase ashley lick 1",
        "cgeyes ashley lick 4",
        "cgex ashley lick 4",
    ],
    "cg ashley 15": [
        "cgbase ashley lick 1",
        "cgeyes ashley lick 1",
        "cgex ashley lick 1",
    ],
    "cg ashley 16": [
        "cgbase ashley lick 1",
        "cgeyes ashley lick 2",
        "cgex ashley lick 2",
        "cgalt ashley lick 1",
    ],
    "cg ashley 17": [
        "cgbase ashley lick 1",
        "cgeyes ashley lick 4",
        "cgex ashley lick 4",
        "cgalt ashley lick 1",
    ],
    "cg ashley 18": [
        "cgbase ashley lick 1",
        "cgeyes ashley lick 1",
        "cgex ashley lick 1",
        "cgalt ashley lick 1",
    ],
    "cg ashley 19": [
        "cgbase ashley lick 1",
        "cgeyes ashley lick 3",
        "cgex ashley lick 3",
        "cgalt ashley lick 1",
    ],
    "cg ashley 20": [
        "cgbase ashley lick 1",
        "cgeyes ashley lick 3",
        "cgex ashley lick 3",
        "cgalt ashley lick 2",
    ],
    "cg ashley 21": [
        "cgbase ashley lick 1",
        "cgeyes ashley lick 4",
        "cgex ashley lick 4",
        "cgalt ashley lick 2",
    ],
    "cg ashley 22": [
        "cgbase ashley lick 1",
        "cgeyes ashley lick 1",
        "cgex ashley lick 1",
        "cgalt ashley lick 2",
    ],
    "cg ashley 23": [
        "cgbase ashley lick 1",
        "cgeyes ashley lick 3",
        "cgex ashley lick 5",
        "cgalt ashley lick 3",
    ],
    "cg ashley 24": [
        "cgbase ashley lick 1",
        "cgeyes ashley lick 3",
        "cgex ashley lick 3",
        "cgalt ashley lick 3",
    ],
    "cg ashley 25": [
        "cgbase ashley lick 1",
        "cgeyes ashley lick 5",
        "cgex ashley lick 6",
        "cgalt ashley lick 4",
        "cgnip ashley lick 1",
    ],
    "cg ashley 26": [
        "cgbase ashley lick 2",
        "cgeyes ashley lick 7",
        "cgex ashley lick 9",
    ],
    "cg ashley 27": [
        "cgbase ashley lick 2",
        "cgeyes ashley lick 8",
        "cgex ashley lick 8",
    ],
    "cg ashley 28": [
        "cgbase ashley lick 2",
        "cgeyes ashley lick 7",
        "cgex ashley lick 9",
        "cgcut ashley lick 1",
    ],
    "cg ashley 29": [
        "cgbase ashley lick 2",
        "cgeyes ashley lick 8",
        "cgex ashley lick 8",
        "cgcut ashley lick 1",
    ],
    "cg ashley 30": [
        "cgbase ashley lick 2",
        "cgliq ashley lick 1",
        "cgpose ashley lick 3",
    ],
    "cg ashley 31": [
        "cgbase ashley lick 2",
        "cgeyes ashley lick 9",
        "cgex ashley lick 10",
        "cgliq ashley lick 1",
    ],
    "cg ashley 32": [
        "cgbase ashley lick 1",
        "cgeyes ashley lick 5",
        "cgex ashley lick 8",
        "cgalt ashley lick 4",
    ],
    "cg ashley 33": [
        "cgbase ashley lick 1",
        "cgeyes ashley lick 7",
        "cgex ashley lick 8",
        "cgalt ashley lick 4",
    ],
    "cg ashley 34": [
        "cgbase ashley lick 1",
        "cgeyes ashley lick 2",
        "cgex ashley lick 1",
        "cgalt ashley lick 4",
    ],
    "cg ashley 1": ["cgbase ashley mas 1", "cgeyes ashley mas 1", "cgex ashley mas 1"],
    "cg ashley 2": ["cgbase ashley mas 1", "cgeyes ashley mas 2", "cgex ashley mas 2"],
    "cg ashley 3": ["cgbase ashley mas 1", "cgeyes ashley mas 3", "cgex ashley mas 3"],
    "cg ashley 4": [
        "cgbase ashley mas 1",
        "cgeyes ashley mas 1",
        "cgex ashley mas 1",
        "cgalt ashley mas 1",
    ],
    "cg ashley 5": [
        "cgbase ashley mas 1",
        "cgeyes ashley mas 3",
        "cgex ashley mas 3",
        "cgalt ashley mas 1",
    ],
    "cg ashley 6": [
        "cgbase ashley mas 1",
        "cgeyes ashley mas 2",
        "cgex ashley mas 2",
        "cgalt ashley mas 1",
    ],
    "cg ashley 7": [
        "cgbase ashley mas 1",
        "cgeyes ashley mas 5",
        "cgex ashley mas 5",
        "cgalt ashley mas 2",
    ],
    "cg ashley 8": [
        "cgbase ashley mas 1",
        "cgeyes ashley mas 1",
        "cgex ashley mas 1",
        "cgalt ashley mas 2",
    ],
    "cg ashley 9": [
        "cgbase ashley mas 1",
        "cgeyes ashley mas 2",
        "cgex ashley mas 2",
        "cgalt ashley mas 2",
    ],
    "cg ashley 10": [
        "cgbase ashley mas 1",
        "cgeyes ashley mas 5",
        "cgex ashley mas 5",
        "cgalt ashley mas 3",
    ],
    "cg ashley 11": [
        "cgbase ashley mas 1",
        "cgeyes ashley mas 4",
        "cgex ashley mas 4",
        "cgalt ashley mas 3",
    ],
    "cg ashley 12": ["cgzoom ashley mas 2"],
    "cg ashley piano 1": [
        "cgbase ashley piano 1",
        "cgeyes ashley piano 1",
        "cgex ashley piano 3",
    ],
    "cg ashley piano 2": [
        "cgbase ashley piano 1",
        "cgeyes ashley piano 1",
        "cgex ashley piano 2",
    ],
    "cg ashley piano 3": [
        "cgbase ashley piano 1",
        "cgeyes ashley piano 1",
        "cgex ashley piano 1",
    ],
    "cg ashley piano 4": [
        "cgbase ashley piano 1",
        "cgeyes ashley piano 2",
        "cgex ashley piano 2",
    ],
    "cg ashley piano 5": [
        "cgbase ashley piano 1",
        "cgeyes ashley piano 2",
        "cgex ashley piano 1",
    ],
    "cg ashley piano 6": [
        "cgbase ashley piano 1",
        "cgeyes ashley piano 3",
        "cgex ashley piano 1",
    ],
    "cg ashley piano 7": [
        "cgbase ashley piano 1",
        "cgeyes ashley piano 3",
        "cgex ashley piano 3",
    ],
    "cg ashley piano 8": [
        "cgbase ashley piano 1",
        "cgeyes ashley piano 3",
        "cgex ashley piano 2",
    ],
    "cg ashley piano 9": [
        "cgbase ashley piano 1",
        "cgeyes ashley piano 3",
        "cgex ashley piano 1",
    ],
    "cg betmel 1": [
        "cgbase betmel dress 1",
        "cgmeyes betmel dress 1",
        "cgmex betmel dress 1",
        "cgbeyes betmel dress 1",
        "cgbex betmel dress 1",
    ],
    "cg betmel 2": [
        "cgbase betmel dress 1",
        "cgmeyes betmel dress 2",
        "cgmex betmel dress 2",
        "cgbeyes betmel dress 1",
        "cgbex betmel dress 1",
    ],
    "cg betmel 3": [
        "cgbase betmel dress 1",
        "cgmeyes betmel dress 2",
        "cgmex betmel dress 2",
        "cgbeyes betmel dress 2",
        "cgbex betmel dress 2",
    ],
    "cg betmel 4": [
        "cgbase betmel dress 1",
        "cgmeyes betmel dress 2",
        "cgmex betmel dress 2",
        "cgbeyes betmel dress 3",
        "cgbex betmel dress 3",
    ],
    "cg betmel 5": [
        "cgbase betmel dress 1",
        "cgmeyes betmel dress 2",
        "cgmex betmel dress 2",
        "cgbeyes betmel dress 3",
        "cgbex betmel dress 3",
        "cgpose betmel dress 1",
    ],
    "cg betmel 6": [
        "cgbase betmel dress 1",
        "cgmeyes betmel dress 2",
        "cgmex betmel dress 2",
        "cgbeyes betmel dress 2",
        "cgbex betmel dress 2",
        "cgpose betmel dress 1",
    ],
    "cg betmel 7": [
        "cgbase betmel dress 1",
        "cgmeyes betmel dress 2",
        "cgmex betmel dress 2",
        "cgbeyes betmel dress 1",
        "cgbex betmel dress 1",
        "cgpose betmel dress 1",
    ],
    "cg betmel 8": [
        "cgbase betmel dress 1",
        "cgmeyes betmel dress 3",
        "cgmex betmel dress 4",
        "cgbeyes betmel dress 2",
        "cgbex betmel dress 2",
        "cgpose betmel dress 2",
    ],
    "cg betmel 9": [
        "cgbase betmel dress 1",
        "cgmeyes betmel dress 3",
        "cgmex betmel dress 4",
        "cgbeyes betmel dress 3",
        "cgbex betmel dress 3",
        "cgpose betmel dress 2",
    ],
    "cg betmel 10": [
        "cgbase betmel dress 1",
        "cgmeyes betmel dress 4",
        "cgmex betmel dress 3",
        "cgbeyes betmel dress 3",
        "cgbex betmel dress 3",
        "cgpose betmel dress 2",
    ],
    "cg betmel 11": [
        "cgbase betmel dress 1",
        "cgmeyes betmel dress 4",
        "cgmex betmel dress 3",
        "cgbeyes betmel dress 2",
        "cgbex betmel dress 2",
        "cgpose betmel dress 2",
    ],
    "cg betmel 12": [
        "cgbase betmel dress 1",
        "cgmeyes betmel dress 4",
        "cgmex betmel dress 3",
        "cgbeyes betmel dress 3",
        "cgbex betmel dress 3",
        "cgpose betmel dress 1",
    ],
    "cg betmel 13": [
        "cgbase betmel dress 1",
        "cgmeyes betmel dress 1",
        "cgmex betmel dress 1",
        "cgbeyes betmel dress 1",
        "cgbex betmel dress 1",
        "cgpose betmel dress 1",
    ],
    "cg betmel 14": [
        "cg betmel 14",
        "cgbase betmel dress 1",
        "cgbase betmel kiss 1 as cg2:",
        "    ypos 0",
        "    xpos 388",
        "cgpose betmel dress 1 behind cg2",
    ],
    "cg betmel 15": [
        "cgbase betmel dress 1",
        "cgbase betmel kiss 1 as cg2:",
        "    ypos 0",
        "    xpos 388",
    ],
    "cg betmel 16": [
        "cgbase betmel mas 1",
        "cgmeyes betmel mas 1",
        "cgmex betmel mas 1",
        "cgbeyes betmel mas 1",
        "cgbex betmel mas 1",
    ],
    "cg betmel 17": [
        "cgbase betmel mas 1",
        "cgmeyes betmel mas 2",
        "cgmex betmel mas 2",
        "cgbeyes betmel mas 1",
        "cgbex betmel mas 1",
    ],
    "cg betmel 18": [
        "cgbase betmel mas 2",
        "cgmeyes betmel mas 2",
        "cgmex betmel mas 2",
        "cgbeyes betmel mas 2",
        "cgbex betmel mas 5",
    ],
    "cg betmel 19": [
        "cgbase betmel mas 2",
        "cgmeyes betmel mas 2",
        "cgmex betmel mas 2",
        "cgbeyes betmel mas 3",
        "cgbex betmel mas 4",
    ],
    "cg betmel 20": [
        "cgbase betmel mas 2",
        "cgmeyes betmel mas 1",
        "cgmex betmel mas 1",
        "cgbeyes betmel mas 2",
        "cgbex betmel mas 5",
    ],
    "cg betmel 21": [
        "cgbase betmel mas 2",
        "cgmeyes betmel mas 3",
        "cgmex betmel mas 3",
        "cgbeyes betmel mas 2",
        "cgbex betmel mas 5",
        "cgmpose betmel mas 1",
        "cgbpose betmel mas 1 behind cgbex",
    ],
    "cg betmel 22": [
        "cgbase betmel mas 2",
        "cgmeyes betmel mas 3",
        "cgmex betmel mas 3",
        "cgbeyes betmel mas 4",
        "cgbex betmel mas 6",
        "cgmpose betmel mas 1",
        "cgbpose betmel mas 1 behind cgbex",
        "cgcut betmel mas 1 as t",
        "cgcut betmel mas 2",
    ],
    "cg betmel 23": [
        "cgbase betmel mas 2",
        "cgmeyes betmel mas 4",
        "cgmex betmel mas 4",
        "cgbeyes betmel mas 3",
        "cgbex betmel mas 4",
        "cgmpose betmel mas 1",
        "cgbpose betmel mas 1 behind cgbex",
        "cgcut betmel mas 1 as t",
        "cgcut betmel mas 2",
    ],
    "cg betmel 24": [
        "cgbase betmel mas 2",
        "cgmeyes betmel mas 4",
        "cgmex betmel mas 4",
        "cgbeyes betmel mas 4",
        "cgbex betmel mas 6",
        "cgmpose betmel mas 1",
        "cgbpose betmel mas 1 behind cgbex",
        "cgcut betmel mas 1 as t",
        "cgcut betmel mas 2",
    ],
    "cg betmel 25": [
        "cgbase betmel mas 2",
        "cgmeyes betmel mas 5",
        "cgmex betmel mas 5",
        "cgbeyes betmel mas 5",
        "cgbex betmel mas 6",
        "cgmpose betmel mas 1",
        "cgbpose betmel mas 1 behind cgbex",
    ],
    "cg betmel 26": [
        "cgbase betmel mas 2",
        "cgmeyes betmel mas 2",
        "cgmex betmel mas 2",
        "cgbeyes betmel mas 2",
        "cgbex betmel mas 5",
        "cgmpose betmel mas 1",
        "cgbpose betmel mas 1 behind cgbex",
    ],
    "cg betmel 27": [
        "cgbase betmel mas 2",
        "cgmeyes betmel mas 1",
        "cgmex betmel mas 1",
        "cgbeyes betmel mas 2",
        "cgbex betmel mas 5",
        "cgmpose betmel mas 1",
        "cgbpose betmel mas 1 behind cgbex",
    ],
    "cg cinren 36": [
        "cgbase cinrei desk 1",
        "cgreyes cinrei desk 1",
        "cgrex cinrei desk 1",
        "cgceyes cinrei desk 1",
        "cgcex cinrei desk 1",
    ],
    "cg cinren 37": [
        "cgbase cinrei desk 1",
        "cgreyes cinrei desk 2",
        "cgrex cinrei desk 2",
        "cgceyes cinrei desk 1",
        "cgcex cinrei desk 1",
    ],
    "cg cinren 38": [
        "cgbase cinrei desk 1",
        "cgreyes cinrei desk 3",
        "cgrex cinrei desk 3",
        "cgceyes cinrei desk 1",
        "cgcex cinrei desk 1",
        "cgalt cinrei desk 1",
    ],
    "cg cinren 39": [
        "cgbase cinrei desk 1",
        "cgreyes cinrei desk 1",
        "cgrex cinrei desk 1",
        "cgceyes cinrei desk 1",
        "cgcex cinrei desk 1",
        "cgalt cinrei desk 1",
    ],
    "cg cinren 40": [
        "cgbase cinrei desk 1",
        "cgreyes cinrei desk 2",
        "cgrex cinrei desk 2",
        "cgceyes cinrei desk 1",
        "cgcex cinrei desk 1",
        "cgalt cinrei desk 1",
    ],
    "cg cinren 41": [
        "cgbase cinrei desk 1",
        "cgreyes cinrei desk 6",
        "cgrex cinrei desk 5",
        "cgceyes cinrei desk 1",
        "cgcex cinrei desk 1",
        "cgalt cinrei desk 2",
    ],
    "cg cinren 42": [
        "cgbase cinrei desk 1",
        "cgreyes cinrei desk 2",
        "cgrex cinrei desk 2",
        "cgceyes cinrei desk 1",
        "cgcex cinrei desk 1",
        "cgalt cinrei desk 2",
    ],
    "cg cinren 43": [
        "cgbase cinrei desk 1",
        "cgreyes cinrei desk 5",
        "cgrex cinrei desk 4",
        "cgceyes cinrei desk 1",
        "cgcex cinrei desk 1",
        "cgalt cinrei desk 2",
    ],
    "cg cinren 44": [
        "cgbase cinrei desk 1",
        "cgreyes cinrei desk 5",
        "cgrex cinrei desk 4",
        "cgceyes cinrei desk 2",
        "cgcex cinrei desk 2",
        "cgalt cinrei desk 2",
        "cgpose cinrei desk 1",
    ],
    "cg cinren 45": [
        "cgbase cinrei desk 1",
        "cgreyes cinrei desk 6",
        "cgrex cinrei desk 5 behind cgpose",
        "cgceyes cinrei desk 1",
        "cgcex cinrei desk 1",
        "cgalt cinrei desk 3",
        "cgpose cinrei desk 1 behind cgalt",
    ],
    "cg cinren 46": [
        "cgbase cinrei desk 1",
        "cgreyes cinrei desk 1",
        "cgrex cinrei desk 1 behind cgpose",
        "cgceyes cinrei desk 1",
        "cgcex cinrei desk 1",
        "cgalt cinrei desk 3",
        "cgpose cinrei desk 1 behind cgalt",
    ],
    "cg cinren 47": [
        "cgbase cinrei desk 1",
        "cgreyes cinrei desk 2",
        "cgrex cinrei desk 2",
        "cgceyes cinrei desk 1",
        "cgcex cinrei desk 1",
        "cgalt cinrei desk 2",
        "cgpose cinrei desk 1",
        "cgliq cinrei desk 1",
    ],
    "cg cinren 48": [
        "cgbase cinrei desk 1",
        "cgreyes cinrei desk 7",
        "cgrex cinrei desk 6",
        "cgceyes cinrei desk 1",
        "cgcex cinrei desk 1",
        "cgalt cinrei desk 4",
        "cgpose cinrei desk 1 behind cgalt",
        "cgliq cinrei desk 1",
    ],
    "cg cinren 49": [
        "cgbase cinrei desk 1",
        "cgreyes cinrei desk 8",
        "cgrex cinrei desk 7",
        "cgceyes cinrei desk 1",
        "cgcex cinrei desk 1",
        "cgalt cinrei desk 4",
        "cgpose cinrei desk 1 behind cgalt",
        "cgliq cinrei desk 1",
    ],
    "cg cinren 50": [
        "cgbase cinrei desk 1",
        "cgreyes cinrei desk 8",
        "cgrex cinrei desk 7",
        "cgceyes cinrei desk 1",
        "cgcex cinrei desk 1",
        "cgalt cinrei desk 4",
        "cgpose cinrei desk 1 behind cgalt",
        "cgliq cinrei desk 1",
    ],
    "cg cinren 51": [
        "cgbase cinrei desk 1",
        "cgreyes cinrei desk 8",
        "cgrex cinrei desk 7",
        "cgceyes cinrei desk 2",
        "cgcex cinrei desk 2",
        "cgalt cinrei desk 4",
        "cgpose cinrei desk 1 behind cgalt",
        "cgliq cinrei desk 1",
    ],
    "cg cinren 52": [
        "cgbase cinrei desk 1",
        "cgreyes cinrei desk 6",
        "cgrex cinrei desk 5",
        "cgceyes cinrei desk 3",
        "cgcex cinrei desk 3",
        "cgalt cinrei desk 4",
        "cgpose cinrei desk 1 behind cgalt",
        "cgliq cinrei desk 1",
    ],
    "cg cinren 53": [
        "cgbase cinrei desk 1",
        "cgreyes cinrei desk 6",
        "cgrex cinrei desk 5",
        "cgceyes cinrei desk 4",
        "cgcex cinrei desk 4",
        "cgalt cinrei desk 4",
        "cgpose cinrei desk 1 behind cgalt",
        "cgliq cinrei desk 1",
    ],
    "cg cinren 54": [
        "cgbase cinrei desk 1",
        "cgreyes cinrei desk 8",
        "cgrex cinrei desk 7",
        "cgceyes cinrei desk 5",
        "cgcex cinrei desk 5",
        "cgalt cinrei desk 2",
        "cgpose cinrei desk 1",
        "cgliq cinrei desk 1",
    ],
    "cg cinren 55": [
        "cgbase cinrei desk 1",
        "cgreyes cinrei desk 6",
        "cgrex cinrei desk 5",
        "cgceyes cinrei desk 3",
        "cgcex cinrei desk 3",
        "cgalt cinrei desk 5",
        "cgpose cinrei desk 1",
        "cgliq cinrei desk 1",
    ],
    "cg cinren 56": [
        "cgbase cinrei desk 1",
        "cgreyes cinrei desk 9",
        "cgceyes cinrei desk 5",
        "cgcex cinrei desk 5",
        "cgalt cinrei desk 6",
        "cgpose cinrei desk 1 behind cgalt",
        "cgliq cinrei desk 1 behind cgalt",
    ],
    "cg cinren 17": [
        "cgbase cinrei sight 1",
        "cgceyes cinrei sight 1",
        "cgcex cinrei sight 1",
        "cgrex cinrei sight 1",
    ],
    "cg cinren 18": [
        "cgbase cinrei sight 1",
        "cgceyes cinrei sight 4",
        "cgcex cinrei sight 4",
        "cgrex cinrei sight 2",
        "cgalt cinrei sight 1",
    ],
    "cg cinren 19": [
        "cgbase cinrei sight 1",
        "cgceyes cinrei sight 2",
        "cgcex cinrei sight 2",
        "cgrex cinrei sight 3",
        "cgalt cinrei sight 1",
    ],
    "cg cinren 20": [
        "cgbase cinrei sight 1",
        "cgrex cinrei sight 2",
        "cgalt cinrei sight 1",
        "cgpose cinrei sight 2",
    ],
    "cg cinren 21": [
        "cgbase cinrei sight 1",
        "cgrex cinrei sight 3",
        "cgalt cinrei sight 1",
        "cgpose cinrei sight 2",
    ],
    "cg cinren 22": [
        "cgbase cinrei sight 1",
        "cgrex cinrei sight 2",
        "cgalt cinrei sight 1",
        "cgpose cinrei sight 1",
    ],
    "cg cinren 23": [
        "cgbase cinrei sight 1",
        "cgceyes cinrei sight 5",
        "cgcex cinrei sight 5",
        "cgrex cinrei sight 2",
        "cgalt cinrei sight 2",
        "cgcut cinrei sight 1",
    ],
    "cg cinren 24": [
        "cgbase cinrei sight 1",
        "cgceyes cinrei sight 4",
        "cgcex cinrei sight 4",
        "cgrex cinrei sight 1",
        "cgalt cinrei sight 1",
    ],
    "cg cinren 25": [
        "cgbase cinrei sight 1",
        "cgceyes cinrei sight 4",
        "cgcex cinrei sight 4",
        "cgrex cinrei sight 4",
        "cgalt cinrei sight 1",
        "cgpose cinrei sight 3",
    ],
    "cg cinren 26": [
        "cgbase cinrei sight 1",
        "cgceyes cinrei sight 4",
        "cgcex cinrei sight 4",
        "cgrex cinrei sight 1",
        "cgalt cinrei sight 1",
        "cgpose cinrei sight 3",
    ],
    "cg cinren 27": [
        "cgbase cinrei sight 1",
        "cgceyes cinrei sight 4",
        "cgcex cinrei sight 4",
        "cgrex cinrei sight 5",
        "cgalt cinrei sight 1",
        "cgpose cinrei sight 3",
    ],
    "cg cinren 28": [
        "cgbase cinrei sight 1",
        "cgceyes cinrei sight 3",
        "cgcex cinrei sight 3",
        "cgrex cinrei sight 4",
        "cgalt cinrei sight 1",
        "cgpose cinrei sight 3",
    ],
    "cg cinren 29": [
        "cgbase cinrei sight 1",
        "cgceyes cinrei sight 3",
        "cgcex cinrei sight 3",
        "cgrex cinrei sight 4",
        "cgalt cinrei sight 1",
        "cgliq cinrei sight 1",
        "cgpose cinrei sight 3 behind cgliq",
    ],
    "cg cinren 30": [
        "cgbase cinrei sight 1",
        "cgceyes cinrei sight 4",
        "cgcex cinrei sight 4",
        "cgrex cinrei sight 5",
        "cgalt cinrei sight 1",
        "cgliq cinrei sight 1",
        "cgpose cinrei sight 3 behind cgliq",
    ],
    "cg cinren 31": ["cgzoom cinrei sight 1"],
    "cg cinren 32": [
        "cgbase cinrei sight 1",
        "cgrex cinrei sight 5",
        "cgalt cinrei sight 1",
        "cgliq cinrei sight 1",
        "cgpose cinrei sight 3 behind cgliq",
        "cgpose cinrei sight 4 as t",
    ],
    "cg cinren 33": [
        "cgbase cinrei sight 1",
        "cgceyes cinrei sight 1",
        "cgcex cinrei sight 1",
        "cgrex cinrei sight 2",
        "cgalt cinrei sight 1",
        "cgliq cinrei sight 1",
        "cgpose cinrei sight 3 behind cgliq",
    ],
    "cg cinren 34": [
        "cgbase cinrei sight 1",
        "cgceyes cinrei sight 5",
        "cgcex cinrei sight 5",
        "cgrex cinrei sight 2",
        "cgalt cinrei sight 2",
        "cgcut cinrei sight 1",
        "cgliq cinrei sight 1",
        "cgpose cinrei sight 3 behind cgliq",
    ],
    "cg cinren 35": [
        "cgbase cinrei sight 1",
        "cgceyes cinrei sight 6",
        "cgcex cinrei sight 6",
        "cgrex cinrei sight 2",
        "cgalt cinrei sight 2",
        "cgcut cinrei sight 1",
        "cgliq cinrei sight 1",
        "cgpose cinrei sight 3 behind cgliq",
    ],
    "cg cinren 1": [
        "cgbase cinrei tied 1",
        "cgceyes cinrei tied 2",
        "cgcex cinrei tied 2",
        "cgrex cinrei tied 1",
    ],
    "cg cinren 2": [
        "cgbase cinrei tied 1",
        "cgceyes cinrei tied 1",
        "cgcex cinrei tied 1",
        "cgrex cinrei tied 1",
    ],
    "cg cinren 3": [
        "cgbase cinrei tied 1",
        "cgceyes cinrei tied 3",
        "cgcex cinrei tied 3",
        "cgrex cinrei tied 2",
    ],
    "cg cinren 4": [
        "cgbase cinrei tied 1",
        "cgceyes cinrei tied 2",
        "cgcex cinrei tied 2",
        "cgrex cinrei tied 1",
        "cgpose cinrei tied 1",
    ],
    "cg cinren 5": [
        "cgbase cinrei tied 1",
        "cgceyes cinrei tied 1",
        "cgcex cinrei tied 1",
        "cgrex cinrei tied 2",
        "cgpose cinrei tied 1",
    ],
    "cg cinren 6": [
        "cgbase cinrei tied 1",
        "cgceyes cinrei tied 3",
        "cgcex cinrei tied 3",
        "cgrex cinrei tied 2",
        "cgpose cinrei tied 2",
    ],
    "cg cinren 7": [
        "cgbase cinrei tied 1",
        "cgceyes cinrei tied 2",
        "cgcex cinrei tied 2",
        "cgrex cinrei tied 2",
        "cgpose cinrei tied 2",
    ],
    "cg cinren 8": [
        "cgbase cinrei tied 1",
        "cgceyes cinrei tied 3",
        "cgcex cinrei tied 3",
        "cgrex cinrei tied 3",
        "cgpose cinrei tied 2",
    ],
    "cg cinren 9": [
        "cgbase cinrei tied 1",
        "cgceyes cinrei tied 3",
        "cgcex cinrei tied 3",
        "cgrex cinrei tied 1",
        "cgpose cinrei tied 2",
        "cgalt cinrei tied 1",
    ],
    "cg cinren 10": [
        "cgbase cinrei tied 1",
        "cgceyes cinrei tied 1",
        "cgcex cinrei tied 1",
        "cgrex cinrei tied 2",
        "cgpose cinrei tied 2",
        "cgalt cinrei tied 1",
    ],
    "cg cinren 11": [
        "cgbase cinrei tied 1",
        "cgrex cinrei tied 4",
        "cgpose cinrei tied 2",
        "cgalt cinrei tied 1",
        "cgcut cinrei tied 1",
    ],
    "cg cinren 12": [
        "cgbase cinrei tied 1",
        "cgceyes cinrei tied 3",
        "cgcex cinrei tied 3",
        "cgrex cinrei tied 1",
        "cgpose cinrei tied 2",
        "cgalt cinrei tied 2",
    ],
    "cg cinren 13": [
        "cgbase cinrei tied 1",
        "cgceyes cinrei tied 3",
        "cgcex cinrei tied 5",
        "cgrex cinrei tied 2",
        "cgpose cinrei tied 4",
        "cgpose cinrei tied 2 as t behind cgpose",
    ],
    "cg cinren 14": [
        "cgbase cinrei tied 1",
        "cgceyes cinrei tied 3",
        "cgcex cinrei tied 5",
        "cgrex cinrei tied 3",
        "cgpose cinrei tied 3",
        "cgpose cinrei tied 2 as t behind cgpose",
        "cgalt cinrei tied 2 behind t",
    ],
    "cg cinren 15": [
        "cgbase cinrei tied 1",
        "cgceyes cinrei tied 3",
        "cgcex cinrei tied 3",
        "cgrex cinrei tied 3",
        "cgpose cinrei tied 3",
        "cgpose cinrei tied 2 as t behind cgpose",
        "cgalt cinrei tied 2 behind t",
    ],
    "cg cinren 16": [
        "cgbase cinrei tied 1",
        "cgceyes cinrei tied 3",
        "cgcex cinrei tied 4",
        "cgrex cinrei tied 4",
        "cgpose cinrei tied 3",
        "cgpose cinrei tied 2 as t behind cgpose",
        "cgalt cinrei tied 2 behind t",
    ],
    "cg mother 19": ["cgbase heather front 1", "cgex heather front 1"],
    "cg mother 20": ["cgbase heather front 1", "cgex heather front 2"],
    "cg mother 21": [
        "cgbase heather meeting 1",
        "cgeyes heather meeting 2",
        "cgex heather meeting 2",
    ],
    "cg mother 22": [
        "cgbase heather meeting 1",
        "cgeyes heather meeting 1",
        "cgex heather meeting 1",
    ],
    "cg mother 23": [
        "cgbase heather meeting 1",
        "cgeyes heather meeting 3",
        "cgex heather meeting 1",
    ],
    "cg mother 24": [
        "cgbase heather meeting 1",
        "cgeyes heather meeting 1",
        "cgex heather meeting 3",
    ],
    "cg mother 25": [
        "cgbase heather meeting 1",
        "cgeyes heather meeting 2",
        "cgex heather meeting 4",
    ],
    "cg mother 1": [
        "cgbase heather sblow 1",
        "cgeyes heather sblow 1",
        "cgex heather sblow 1",
    ],
    "cg mother 2": [
        "cgbase heather sblow 1",
        "cgeyes heather sblow 2",
        "cgex heather sblow 1",
    ],
    "cg mother 5": [
        "cgbase heather sblow 1",
        "cgeyes heather sblow 3",
        "cgex heather sblow 2",
        "cgpose heather sblow 1",
        "cgalt heather sblow 1",
    ],
    "cg mother 8": [
        "cgbase heather sblow 1",
        "cgpose heather sblow 1",
        "cgalt heather sblow 2",
    ],
    "cg mother 9": [
        "cgbase heather sblow 1",
        "cgpose heather sblow 1",
        "cgalt heather sblow 3",
    ],
    "cg mother 10": [
        "cgbase heather sblow 1",
        "cgeyes heather sblow 4",
        "cgex heather sblow 3",
    ],
    "cg mother 11": [
        "cgbase heather sblow 1",
        "cgeyes heather sblow 5",
        "cgex heather sblow 3",
    ],
    "cg mother 12": [
        "cgbase heather sblow 1",
        "cgeyes heather sblow 6",
        "cgex heather sblow 4",
        "cgalt heather sblow 1",
    ],
    "cg mother 18": [
        "cgbase heather sblow 1",
        "cgeyes heather sblow 6",
        "cgpose heather sblow 1",
        "cgalt heather sblow 4",
    ],
    "cg mother 3": [
        "cgbase heather sblow 2",
        "cgeyes heather sblow 7",
        "cgex heather sblow 5",
    ],
    "cg mother 4": [
        "cgbase heather sblow 2",
        "cgeyes heather sblow 8",
        "cgex heather sblow 5",
    ],
    "cg mother 6": [
        "cgbase heather sblow 2",
        "cgeyes heather sblow 7",
        "cgex heather sblow 7",
    ],
    "cg mother 7": [
        "cgbase heather sblow 2",
        "cgeyes heather sblow 8",
        "cgex heather sblow 7",
    ],
    "cg mother 13": [
        "cgbase heather sblow 2",
        "cgeyes heather sblow 7",
        "cgex heather sblow 6",
    ],
    "cg mother 14": [
        "cgbase heather sblow 2",
        "cgeyes heather sblow 9",
        "cgex heather sblow 6",
    ],
    "cg mother 15": [
        "cgbase heather sblow 2",
        "cgeyes heather sblow 10",
        "cgex heather sblow 8",
    ],
    "cg mother 16": [
        "cgbase heather sblow 2",
        "cgeyes heather sblow 9",
        "cgex heather sblow 9",
    ],
    "cg mother 17": [
        "cgbase heather sblow 2",
        "cgeyes heather sblow 10",
        "cgex heather sblow 9",
    ],
    "cg jenapril gate 1": [
        "cgbase jenapr fence 2",
        "cgjeyes jenapr fence 3",
        "cgjex jenapr fence 3",
    ],
    "cg jenapril gate 2": [
        "cgbase jenapr fence 1",
        "cgjeyes jenapr fence 1",
        "cgjex jenapr fence 1",
        "cgaeyes jenapr fence 2",
        "cgaex jenapr fence 2",
    ],
    "cg jenapril gate 3": [
        "cgbase jenapr fence 1",
        "cgjeyes jenapr fence 3",
        "cgjex jenapr fence 2",
        "cgaeyes jenapr fence 1",
        "cgaex jenapr fence 1",
    ],
    "cg jenapril gate 4": [
        "cgbase jenapr fence 1",
        "cgjeyes jenapr fence 3",
        "cgjex jenapr fence 1",
        "cgaeyes jenapr fence 2",
        "cgaex jenapr fence 2",
    ],
    "cg jenapril gate 5": [
        "cgbase jenapr fence 1",
        "cgjeyes jenapr fence 3",
        "cgjex jenapr fence 3",
        "cgpose jenapr fence 1",
        "cgalt jenapr fence 1",
    ],
    "cg jenapril gate 6": [
        "cgbase jenapr fence 1",
        "cgjeyes jenapr fence 3",
        "cgjex jenapr fence 2",
        "cgpose jenapr fence 2",
    ],
    "cg jenapril gate 7": [
        "cgbase jenapr fence 1",
        "cgjeyes jenapr fence 1",
        "cgjex jenapr fence 2",
        "cgaeyes jenapr fence 2",
        "cgaex jenapr fence 3",
    ],
    "cg jenapril gate 8": [
        "cgbase jenapr fence 2",
        "cgjeyes jenapr fence 1",
        "cgjex jenapr fence 1",
    ],
    "cg melina 27": [
        "cgbase melina desk 1",
        "cgeyes melina desk 1",
        "cgex melina desk 1",
    ],
    "cg melina 28": [
        "cgbase melina desk 1",
        "cgeyes melina desk 2",
        "cgex melina desk 2",
    ],
    "cg melina 29": [
        "cgbase melina desk 1",
        "cgeyes melina desk 3",
        "cgex melina desk 3",
    ],
    "cg melina 31": [
        "cgbase melina desk 1",
        "cgeyes melina desk 4",
        "cgex melina desk 4",
        "cgpose melina desk 1",
    ],
    "cg melina 32": [
        "cgbase melina desk 1",
        "cgeyes melina desk 3",
        "cgex melina desk 3",
        "cgpose melina desk 1",
    ],
    "cg melina 33": [
        "cgbase melina desk 1",
        "cgeyes melina desk 5",
        "cgex melina desk 5",
        "cgpose melina desk 1",
    ],
    "cg melina 34": [
        "cgbase melina desk 1",
        "cgeyes melina desk 2",
        "cgex melina desk 2",
        "cgpose melina desk 1",
    ],
    "cg melina 35": [
        "cgbase melina desk 1",
        "cgeyes melina desk 6",
        "cgex melina desk 6",
        "cgpose melina desk 1",
    ],
    "cg melina 36": [
        "cgbase melina desk 1",
        "cgeyes melina desk 4",
        "cgex melina desk 4",
        "cgpose melina desk 1",
        "cgalt melina desk 1",
    ],
    "cg melina 37": [
        "cgbase melina desk 1",
        "cgeyes melina desk 3",
        "cgex melina desk 3",
        "cgpose melina desk 2",
        "cgalt melina desk 3",
        "cgnip melina desk 1",
        "cgbreak melina desk 1",
    ],
    "cg melina 38": [
        "cgbase melina desk 1",
        "cgeyes melina desk 6",
        "cgex melina desk 6",
        "cgpose melina desk 2",
        "cgalt melina desk 3",
        "cgnip melina desk 1",
        "cgbreak melina desk 1",
    ],
    "cg melina 39": [
        "cgbase melina desk 1",
        "cgeyes melina desk 4",
        "cgex melina desk 4",
        "cgpose melina desk 2",
        "cgalt melina desk 3",
        "cgnip melina desk 1",
        "cgbreak melina desk 1",
    ],
    "cg melina 40": [
        "cgbase melina desk 1",
        "cgeyes melina desk 5",
        "cgex melina desk 5",
        "cgpose melina desk 2",
        "cgalt melina desk 3",
        "cgnip melina desk 1",
        "cgbreak melina desk 1",
    ],
    "cg melina 41": [
        "cgbase melina desk 1",
        "cgeyes melina desk 1",
        "cgex melina desk 1",
        "cgpose melina desk 2",
        "cgalt melina desk 2",
        "cgnip melina desk 1",
        "cgbreak melina desk 1",
    ],
    "cg melina 42": [
        "cgbase melina desk 1",
        "cgeyes melina desk 2",
        "cgex melina desk 2",
        "cgpose melina desk 2",
        "cgalt melina desk 2",
        "cgnip melina desk 1",
        "cgbreak melina desk 1",
    ],
    "cg melina 43": [
        "cgbase melina desk 1",
        "cgeyes melina desk 5",
        "cgex melina desk 5",
        "cgpose melina desk 2",
        "cgalt melina desk 2",
        "cgnip melina desk 1",
        "cgbreak melina desk 1",
    ],
    "cg melina 44": [
        "cgbase melina desk 1",
        "cgeyes melina desk 3",
        "cgex melina desk 3",
        "cgpose melina desk 2",
        "cgalt melina desk 2",
        "cgnip melina desk 1",
        "cgbreak melina desk 1",
    ],
    "cg melina 45": [
        "cgbase melina desk 1",
        "cgeyes melina desk 7",
        "cgex melina desk 2",
        "cgpose melina desk 2",
        "cgalt melina desk 2",
        "cgnip melina desk 1",
        "cgbreak melina desk 1",
    ],
    "cg melina 46": [
        "cgbase melina desk 1",
        "cgeyes melina desk 4",
        "cgex melina desk 4",
        "cgpose melina desk 2",
        "cgalt melina desk 2",
        "cgnip melina desk 1",
        "cgbreak melina desk 1",
    ],
    "cg melina 47": [
        "cgbase melina desk 1",
        "cgeyes melina desk 6",
        "cgex melina desk 6",
        "cgpose melina desk 2",
        "cgalt melina desk 2",
        "cgnip melina desk 1",
        "cgbreak melina desk 1",
    ],
    "cg melina 48": [
        "cgbase melina desk 1",
        "cgeyes melina desk 3",
        "cgex melina desk 3",
        "cgpose melina desk 2",
        "cgbreak melina desk 1",
    ],
    "cg melina 49": [
        "cgbase melina desk 1",
        "cgeyes melina desk 1",
        "cgex melina desk 1",
        "cgpose melina desk 2",
        "cgbreak melina desk 1",
    ],
    "cg melina 50": [
        "cgbase melina desk 1",
        "cgeyes melina desk 6",
        "cgex melina desk 6",
        "cgpose melina desk 2",
        "cgbreak melina desk 1",
    ],
    "cg melina 51": [
        "cgbase melina desk 1",
        "cgeyes melina desk 5",
        "cgex melina desk 5",
        "cgpose melina desk 2",
        "cgbreak melina desk 1",
    ],
    "cg melina 52": [
        "cgbase melina desk 1",
        "cgeyes melina desk 4",
        "cgex melina desk 4",
        "cgpose melina desk 2",
        "cgbreak melina desk 1",
    ],
    "cg melina 53": [
        "cgbase melina desk 1",
        "cgeyes melina desk 1",
        "cgex melina desk 1",
        "cgpose melina desk 1",
        "cgalt melina desk 1",
    ],
    "cg melina 54": [
        "cgbase melina desk 1",
        "cgeyes melina desk 5",
        "cgex melina desk 5",
        "cgpose melina desk 1",
        "cgalt melina desk 1",
    ],
    "cg melina 55": [
        "cgbase melina desk 1",
        "cgeyes melina desk 3",
        "cgex melina desk 3",
        "cgpose melina desk 1",
        "cgalt melina desk 1",
    ],
    "cg melina 56": [
        "cgbase melina desk 1",
        "cgeyes melina desk 2",
        "cgex melina desk 2",
        "cgpose melina desk 1",
        "cgalt melina desk 1",
    ],
    "cg melina 57": [
        "cgbase melina desk 1",
        "cgeyes melina desk 5",
        "cgex melina desk 5",
        "cgpose melina desk 2",
        "cgalt melina desk 4",
        "cgnip melina desk 1",
        "cgbreak melina desk 1",
    ],
    "cg melina 1": [
        "cgbase melina grass 1",
        "cgeyes melina grass 1",
        "cgex melina grass 1",
    ],
    "cg melina 2": [
        "cgbase melina grass 1",
        "cgeyes melina grass 5",
        "cgex melina grass 4",
    ],
    "cg melina 3": [
        "cgbase melina grass 2",
        "cgeyes melina grass 3",
        "cgex melina grass 3",
    ],
    "cg melina 4": [
        "cgbase melina grass 2",
        "cgeyes melina grass 1",
        "cgex melina grass 1",
    ],
    "cg melina 6": [
        "cgbase melina grass 2",
        "cgeyes melina grass 4",
        "cgex melina grass 5",
    ],
    "cg melina 7": [
        "cgbase melina grass 2",
        "cgeyes melina grass 3",
        "cgex melina grass 3",
        "cgalt melina grass 1",
    ],
    "cg melina 8": [
        "cgbase melina grass 2",
        "cgeyes melina grass 5",
        "cgex melina grass 4",
        "cgalt melina grass 1",
    ],
    "cg melina 9": [
        "cgbase melina grass 2",
        "cgeyes melina grass 4",
        "cgex melina grass 5",
        "cgalt melina grass 1",
    ],
    "cg melina 10": [
        "cgbase melina grass 2",
        "cgeyes melina grass 1",
        "cgex melina grass 1",
        "cgalt melina grass 1",
    ],
    "cg melina 11": [
        "cgbase melina grass 2",
        "cgeyes melina grass 2",
        "cgex melina grass 2",
        "cgalt melina grass 1",
    ],
    "cg melina 12": [
        "cgbase melina grass 3",
        "cgeyes melina grass 4",
        "cgex melina grass 5",
    ],
    "cg melina 13": [
        "cgbase melina grass 3",
        "cgeyes melina grass 2",
        "cgex melina grass 2",
    ],
    "cg melina 14": [
        "cgbase melina grass 3",
        "cgeyes melina grass 1",
        "cgex melina grass 1",
    ],
    "cg melina 15": [
        "cgbase melina grass 3",
        "cgeyes melina grass 3",
        "cgex melina grass 3",
    ],
    "cg melina 16": [
        "cgbase melina grass 3",
        "cgeyes melina grass 5",
        "cgex melina grass 4",
    ],
    "cg melina 17": [
        "cgbase melina grass 3",
        "cgeyes melina grass 5",
        "cgex melina grass 4",
        "cgalt melina grass 2",
    ],
    "cg melina 18": [
        "cgbase melina grass 3",
        "cgeyes melina grass 4",
        "cgex melina grass 5",
        "cgalt melina grass 2",
    ],
    "cg melina 19": [
        "cgbase melina grass 3",
        "cgeyes melina grass 2",
        "cgex melina grass 2",
        "cgalt melina grass 2",
    ],
    "cg melina 20": [
        "cgbase melina grass 3",
        "cgeyes melina grass 1",
        "cgex melina grass 1",
        "cgalt melina grass 2",
    ],
    "cg melina 21": [
        "cgbase melina grass 3",
        "cgeyes melina grass 4",
        "cgex melina grass 5",
        "cgalt melina grass 2",
        "cgliq melina grass 1",
        "cgnip melina grass 1",
    ],
    "cg melina 22": [
        "cgbase melina grass 3",
        "cgeyes melina grass 5",
        "cgex melina grass 4",
        "cgalt melina grass 2",
        "cgliq melina grass 1",
        "cgnip melina grass 1",
    ],
    "cg melina 23": [
        "cgbase melina grass 3",
        "cgeyes melina grass 2",
        "cgex melina grass 2",
        "cgalt melina grass 2",
        "cgliq melina grass 1",
        "cgnip melina grass 1",
    ],
    "cg melina 24": [
        "cgbase melina grass 3",
        "cgeyes melina grass 3",
        "cgex melina grass 3",
        "cgalt melina grass 2",
        "cgliq melina grass 1",
        "cgnip melina grass 1",
    ],
    "cg melina 25": [
        "cgbase melina grass 3",
        "cgcum melina grass 1",
        "cgalt melina grass 2",
        "cgnip melina grass 1",
    ],
    "cg melina 26": ["cgbase melina grass 3", "cgcum melina grass 2"],
    "cg nicole rape 1": [
        "cgbase nicole sfloor1 1",
        "cgeyes nicole sfloor1 1",
        "cgex nicole sfloor1 1",
    ],
    "cg nicole rape 2": [
        "cgbase nicole sfloor1 1",
        "cgeyes nicole sfloor1 2",
        "cgex nicole sfloor1 2",
    ],
    "cg nicole rape 3": [
        "cgbase nicole sfloor1 1",
        "cgeyes nicole sfloor1 3",
        "cgex nicole sfloor1 3",
    ],
    "cg nicole rape 4": [
        "cgbase nicole sfloor1 2",
        "cgeyes nicole sfloor1 1",
        "cgex nicole sfloor1 1",
    ],
    "cg nicole rape 5": [
        "cgbase nicole sfloor1 2",
        "cgeyes nicole sfloor1 2",
        "cgex nicole sfloor1 2",
    ],
    "cg nicole rape 6": [
        "cgbase nicole sfloor1 2",
        "cgeyes nicole sfloor1 3",
        "cgex nicole sfloor1 3",
    ],
    "cg nicole rape 7": [
        "cgbase nicole sfloor1 2",
        "cgeyes nicole sfloor1 4",
        "cgex nicole sfloor1 4",
        "cgalt nicole sfloor1 1",
    ],
    "cg nicole rape 8": [
        "cgbase nicole sfloor1 2",
        "cgeyes nicole sfloor1 3",
        "cgex nicole sfloor1 3",
        "cgalt nicole sfloor1 1",
    ],
    "cg nicole rape 9": [
        "cgbase nicole sfloor1 2",
        "cgeyes nicole sfloor1 2",
        "cgex nicole sfloor1 2",
        "cgalt nicole sfloor1 1",
    ],
    "cg nicole rape 10": [
        "cgbase nicole sfloor1 2",
        "cgeyes nicole sfloor1 1",
        "cgex nicole sfloor1 1",
        "cgalt nicole sfloor1 2",
    ],
    "cg nicole rape 11": [
        "cgbase nicole sfloor1 2",
        "cgeyes nicole sfloor1 3",
        "cgex nicole sfloor1 3",
        "cgalt nicole sfloor1 2",
        "cgcut nicole sfloor1 1",
    ],
    "cg nicole rape 12": [
        "cgbase nicole sfloor1 2",
        "cgeyes nicole sfloor1 5",
        "cgex nicole sfloor1 5",
        "cgalt nicole sfloor1 2",
        "cgcut nicole sfloor1 1",
    ],
    "cg nicole rape 13": [
        "cgbase nicole sfloor1 2",
        "cgeyes nicole sfloor1 5",
        "cgex nicole sfloor1 5",
        "cgalt nicole sfloor1 3",
    ],
    "cg nicole rape 14": [
        "cgbase nicole sfloor2 1",
        "cgeyes nicole sfloor2 1",
        "cgex nicole sfloor2 1",
    ],
    "cg nicole rape 15": [
        "cgbase nicole sfloor2 1",
        "cgeyes nicole sfloor2 2",
        "cgex nicole sfloor2 2",
    ],
    "cg nicole rape 16": [
        "cgbase nicole sfloor2 1",
        "cgeyes nicole sfloor2 3",
        "cgex nicole sfloor2 3",
        "cgalt nicole sfloor2 1",
    ],
    "cg nicole rape 17": [
        "cgbase nicole sfloor2 1",
        "cgeyes nicole sfloor2 2",
        "cgex nicole sfloor2 2",
        "cgalt nicole sfloor2 1",
    ],
    "cg nicole rape 18": [
        "cgbase nicole sfloor2 1",
        "cgeyes nicole sfloor2 1",
        "cgex nicole sfloor2 1",
        "cgalt nicole sfloor2 2",
    ],
    "cg nicole rape 19": [
        "cgbase nicole sfloor2 1",
        "cgeyes nicole sfloor2 1",
        "cgex nicole sfloor2 1",
        "cgalt nicole sfloor2 2",
        "cgpose nicole sfloor2 1",
    ],
    "cg nicole rape 20": [
        "cgbase nicole sfloor2 1",
        "cgeyes nicole sfloor2 4",
        "cgex nicole sfloor2 4",
        "cgalt nicole sfloor2 2",
        "cgpose nicole sfloor2 1",
    ],
    "cg nicole rape 21": [
        "cgbase nicole sfloor2 1",
        "cgeyes nicole sfloor2 1",
        "cgex nicole sfloor2 1",
        "cgalt nicole sfloor2 3",
    ],
    "cg nicole rape 22": [
        "cgbase nicole sfloor2 1",
        "cgeyes nicole sfloor2 5",
        "cgex nicole sfloor2 5",
        "cgalt nicole sfloor2 4",
    ],
    "cg nicole rape 23": [
        "cgbase nicole sfloor3 1",
        "cgeyes nicole sfloor3 1",
        "cgex nicole sfloor3 1",
    ],
    "cg nicole rape 24": [
        "cgbase nicole sfloor3 1",
        "cgeyes nicole sfloor3 2",
        "cgex nicole sfloor3 2",
    ],
    "cg nicole rape 25": ["cgbase nicole sfloor3 1", "cgpose nicole sfloor3 1"],
    "cg nicole rape 26": [
        "cgbase nicole sfloor3 1",
        "cgeyes nicole sfloor3 2",
        "cgex nicole sfloor3 2",
        "cgpose nicole sfloor3 2",
    ],
    "cg nicole rape 27": [
        "cgbase nicole sfloor3 1",
        "cgeyes nicole sfloor3 3",
        "cgex nicole sfloor3 3",
        "cgpose nicole sfloor3 2",
    ],
    "cg nicole rape 28": [
        "cgbase nicole sfloor3 1",
        "cgeyes nicole sfloor3 1",
        "cgex nicole sfloor3 1",
        "cgpose nicole sfloor3 2",
    ],
    "cg nicole rape 29": [
        "cgbase nicole sfloor3 1",
        "cgeyes nicole sfloor3 4",
        "cgex nicole sfloor3 4",
        "cgpose nicole sfloor3 2",
    ],
    "cg nicole rape 30": [
        "cgbase nicole sfloor3 1",
        "cgeyes nicole sfloor3 5",
        "cgex nicole sfloor3 5",
    ],
    "cg nicole rape 31": [
        "cgbase nicole sfloor3 1",
        "cgeyes nicole sfloor3 6",
        "cgex nicole sfloor3 6",
    ],
}
