characterMapVanessa = {
    "vanessa_be0_003":                       "vanessa_be0_003",                       # Auto: Same
    "vanessa_be0_cas_002":                   "vanessa_be0_cas_002",                   # Auto: Same
    "vanessa_be0_full_003":                  "vanessa_be0_full_003",                  # Auto: Same
    "vanessa_be0_full_cas_002":              "vanessa_be0_full_cas_002",              # Auto: Same
    "vanessa_be0_full_naked_003":            "vanessa_be0_full_naked_003",            # Auto: Same
    "vanessa_be0_full_under_003":            "vanessa_be0_full_under_003",            # Auto: Same
    "vanessa_be0_naked_003":                 "vanessa_be0_naked_003",                 # Auto: Same
    "vanessa_be0_under_003":                 "vanessa_be0_under_003",                 # Auto: Same
    "vanessa_be1_001":                       "vanessa_be1_001",                       # Auto: Same
    "vanessa_be1_002":                       "vanessa_be1_002",                       # Auto: Same
    "vanessa_be1_003":                       "vanessa_be1_003",                       # Auto: Same
    "vanessa_be1_cas_001":                   "vanessa_be1_cas_001",                   # Auto: Same
    "vanessa_be1_cas_002":                   "vanessa_be1_cas_002",                   # Auto: Same
    "vanessa_be1_cas_003":                   "vanessa_be1_cas_003",                   # Auto: Same
    "vanessa_be1_full_001":                  "vanessa_be1_full_001",                  # Auto: Same
    "vanessa_be1_full_002":                  "vanessa_be1_full_002",                  # Auto: Same
    "vanessa_be1_full_003":                  "vanessa_be1_full_003",                  # Auto: Same
    "vanessa_be1_full_cas_001":              "vanessa_be1_full_cas_001",              # Auto: Same
    "vanessa_be1_full_cas_002":              "vanessa_be1_full_cas_002",              # Auto: Same
    "vanessa_be1_full_cas_003":              "vanessa_be1_full_cas_003",              # Auto: Same
    "vanessa_be1_full_gym_001":              "vanessa_be1_full_gym_001",              # Auto: Same
    "vanessa_be1_full_gym_002":              "vanessa_be1_full_gym_002",              # Auto: Same
    "vanessa_be1_full_gym_003":              "vanessa_be1_full_gym_003",              # Auto: Same
    "vanessa_be1_full_naked_001":            "vanessa_be1_full_naked_001",            # Auto: Same
    "vanessa_be1_full_naked_002":            "vanessa_be1_full_naked_002",            # Auto: Same
    "vanessa_be1_full_naked_003":            "vanessa_be1_full_naked_003",            # Auto: Same
    "vanessa_be1_full_night_001":            "vanessa_be1_full_night_001",            # Auto: Same
    "vanessa_be1_full_night_002":            "vanessa_be1_full_night_002",            # Auto: Same
    "vanessa_be1_full_night_003":            "vanessa_be1_full_night_003",            # Auto: Same
    "vanessa_be1_full_under_001":            "vanessa_be1_full_under_001",            # Auto: Same
    "vanessa_be1_full_under_002":            "vanessa_be1_full_under_002",            # Auto: Same
    "vanessa_be1_full_under_003":            "vanessa_be1_full_under_003",            # Auto: Same
    "vanessa_be1_gym_001":                   "vanessa_be1_gym_001",                   # Auto: Same
    "vanessa_be1_gym_002":                   "vanessa_be1_gym_002",                   # Auto: Same
    "vanessa_be1_gym_003":                   "vanessa_be1_gym_003",                   # Auto: Same
    "vanessa_be1_naked_001":                 "vanessa_be1_naked_001",                 # Auto: Same
    "vanessa_be1_naked_002":                 "vanessa_be1_naked_002",                 # Auto: Same
    "vanessa_be1_naked_003":                 "vanessa_be1_naked_003",                 # Auto: Same
    "vanessa_be1_night_001":                 "vanessa_be1_night_001",                 # Auto: Same
    "vanessa_be1_night_002":                 "vanessa_be1_night_002",                 # Auto: Same
    "vanessa_be1_night_003":                 "vanessa_be1_night_003",                 # Auto: Same
    "vanessa_be1_under_001":                 "vanessa_be1_under_001",                 # Auto: Same
    "vanessa_be1_under_002":                 "vanessa_be1_under_002",                 # Auto: Same
    "vanessa_be1_under_003":                 "vanessa_be1_under_003",                 # Auto: Same
    "vanessa_base_001":                      "vanessa_base_001",                      # Auto: Edited
    "vanessa_base_002":                      "vanessa_base_002",                      # Auto: Edited
    "vanessa_base_003":                      "vanessa_base_003",                      # Auto: Edited
    "vanessa_base_cas_001":                  "vanessa_base_cas_001",                  # Auto: Edited
    "vanessa_base_cas_002":                  "vanessa_base_cas_002",                  # Auto: Edited
    "vanessa_base_cas_003":                  "vanessa_base_cas_003",                  # Auto: Edited
    "vanessa_base_full_001":                 "vanessa_base_full_001",                 # Auto: Same
    "vanessa_base_full_002":                 "vanessa_base_full_002",                 # Auto: Edited
    "vanessa_base_full_003":                 "vanessa_base_full_003",                 # Auto: Edited
    "vanessa_base_full_cas_001":             "vanessa_base_full_cas_001",             # Auto: Same
    "vanessa_base_full_cas_002":             "vanessa_base_full_cas_002",             # Auto: Edited
    "vanessa_base_full_cas_003":             "vanessa_base_full_cas_003",             # Auto: Edited
    "vanessa_base_full_gym_001":             "vanessa_base_full_gym_001",             # Auto: Same
    "vanessa_base_full_gym_002":             "vanessa_base_full_gym_002",             # Auto: Edited
    "vanessa_base_full_gym_003":             "vanessa_base_full_gym_003",             # Auto: Edited
    "vanessa_base_full_naked_001":           "vanessa_base_full_naked_001",           # Auto: Same
    "vanessa_base_full_naked_002":           "vanessa_base_full_naked_002",           # Auto: Edited
    "vanessa_base_full_naked_003":           "vanessa_base_full_naked_003",           # Auto: Edited
    "vanessa_base_full_night_001":           "vanessa_base_full_night_001",           # Auto: Same
    "vanessa_base_full_night_002":           "vanessa_base_full_night_002",           # Auto: Edited
    "vanessa_base_full_night_003":           "vanessa_base_full_night_003",           # Auto: Edited
    "vanessa_base_full_under_001":           "vanessa_base_full_under_001",           # Auto: Same
    "vanessa_base_full_under_002":           "vanessa_base_full_under_002",           # Auto: Edited
    "vanessa_base_full_under_003":           "vanessa_base_full_under_003",           # Auto: Edited
    "vanessa_base_gym_001":                  "vanessa_base_gym_001",                  # Auto: Edited
    "vanessa_base_gym_002":                  "vanessa_base_gym_002",                  # Auto: Edited
    "vanessa_base_gym_003":                  "vanessa_base_gym_003",                  # Auto: Edited
    "vanessa_base_naked_001":                "vanessa_base_naked_001",                # Auto: Edited
    "vanessa_base_naked_002":                "vanessa_base_naked_002",                # Auto: Edited
    "vanessa_base_naked_003":                "vanessa_base_naked_003",                # Auto: Edited
    "vanessa_base_night_001":                "vanessa_base_night_001",                # Auto: Edited
    "vanessa_base_night_002":                "vanessa_base_night_002",                # Auto: Edited
    "vanessa_base_night_003":                "vanessa_base_night_003",                # Auto: Edited
    "vanessa_base_under_001":                "vanessa_base_under_001",                # Auto: Edited
    "vanessa_base_under_002":                "vanessa_base_under_002",                # Auto: Edited
    "vanessa_base_under_003":                "vanessa_base_under_003",                # Auto: Edited
    "vanessa_ex_001_001":                    "vanessa_ex_001_001",                    # Auto: Same
    "vanessa_ex_001_neutral_001":            "vanessa_ex_001_neutral_001",            # Auto: Edited
    "vanessa_ex_001_smile_001":              "vanessa_ex_001_smile_001",              # Auto: Same
    "vanessa_ex_002_001":                    "vanessa_ex_002_smile_001",              # Auto: Renamed
    "vanessa_ex_002_smile_001":              "vanessa_ex_002_001",                    # Auto: Renamed
    "vanessa_ex_003_001":                    "vanessa_ex_004_open_001",               # Auto: Renamed
    "vanessa_ex_003_smile_001":              "vanessa_ex_004_smile_001",              # Auto: Renamed
    "vanessa_ex_004_001":                    "vanessa_ex_004_open2_001",              # Auto: Renamed
    "vanessa_ex_005_001":                    "vanessa_ex_006_open_001",               # Auto: Renamed
    "vanessa_ex_006_001":                    "vanessa_ex_005_open_001",
    "vanessa_ex_007_001":                    "vanessa_ex_005_aroused2_001",           # Auto: Renamed
    "vanessa_ex_008_001":                    "vanessa_ex_002_smile2_001",             # Auto: Renamed
    "vanessa_ex_009_002":                    "vanessa_ex_009_002",                    # Auto: Same
    "vanessa_ex_010_002":                    "vanessa_ex_011_002",                    # Auto: Renamed
    "vanessa_ex_011_002":                    "vanessa_ex_012_002",                    # Not exact, but close
    "vanessa_ex_012_002":                    "vanessa_ex_012_002",                    # Auto: Same
    "vanessa_ex_013_002":                    "vanessa_ex_008_002",                    # Auto: Renamed
    "vanessa_ex_014_002":                    "vanessa_ex_010_open_002",               # Auto: Renamed
    "vanessa_ex_015_002":                    "vanessa_ex_013_002",                    # Auto: Renamed
    "vanessa_ex_016_002":                    "vanessa_ex_010_open2_002",              # Auto: Renamed
    "vanessa_ex_017_002":                    "vanessa_ex_009_open_002",               # Auto: Renamed
    "vanessa_ex_018_003":                    "vanessa_ex_003_irked_003",              # Auto: Renamed
    "vanessa_ex_018_open_003":               "vanessa_ex_003_irked2_003",             # Auto: Renamed
    "vanessa_ex_018_smile_003":              "vanessa_ex_003_irked3_003",             # Auto: Renamed
    "vanessa_ex_019_003":                    "vanessa_ex_003_open2_003",              # Auto: Renamed
    "vanessa_ex_019_grin2_003":              "vanessa_ex_003_grin2_003",              # Auto: Renamed
    "vanessa_ex_019_grin_003":               "vanessa_ex_003_grin_003",               # Auto: Renamed
    "vanessa_ex_020_003":                    "vanessa_ex_007_003",
    "vanessa_ex_021_003":                    "vanessa_ex_011_open_003",               # Auto: Renamed
    "vanessa_ex_full_001_001":               "vanessa_ex_full_001_001",               # Auto: Same
    "vanessa_ex_full_001_neutral_001":       "vanessa_ex_full_001_neutral_001",       # Auto: Edited
    "vanessa_ex_full_001_smile_001":         "vanessa_ex_full_001_smile_001",         # Auto: Same
    "vanessa_ex_full_002_001":               "vanessa_ex_full_002_smile_001",         # Auto: Renamed
    "vanessa_ex_full_002_smile_001":         "vanessa_ex_full_002_001",               # Auto: Renamed
    "vanessa_ex_full_003_001":               "vanessa_ex_full_004_open_001",          # Auto: Renamed
    "vanessa_ex_full_003_smile_001":         "vanessa_ex_full_004_smile_001",         # Auto: Renamed
    "vanessa_ex_full_004_001":               "vanessa_ex_full_004_open2_001",         # Auto: Renamed
    "vanessa_ex_full_005_001":               "vanessa_ex_full_006_open_001",          # Auto: Renamed
    "vanessa_ex_full_006_001":               "vanessa_ex_full_005_open_001",
    "vanessa_ex_full_007_001":               "vanessa_ex_full_005_aroused2_001",      # Auto: Renamed
    "vanessa_ex_full_008_001":               "vanessa_ex_full_002_smile2_001",        # Auto: Renamed
    "vanessa_ex_full_009_002":               "vanessa_ex_full_009_002",               # Auto: Same
    "vanessa_ex_full_010_002":               "vanessa_ex_full_011_002",               # Auto: Renamed
    "vanessa_ex_full_011_002":               "vanessa_ex_full_012_002",
    "vanessa_ex_full_012_002":               "vanessa_ex_full_012_002",               # Auto: Same
    "vanessa_ex_full_013_002":               "vanessa_ex_full_008_002",               # Auto: Renamed
    "vanessa_ex_full_014_002":               "vanessa_ex_full_010_open_002",          # Auto: Renamed
    "vanessa_ex_full_015_002":               "vanessa_ex_full_013_002",               # Auto: Renamed
    "vanessa_ex_full_016_002":               "vanessa_ex_full_010_open2_002",         # Auto: Renamed
    "vanessa_ex_full_017_002":               "vanessa_ex_full_009_open_002",          # Auto: Renamed
    "vanessa_ex_full_018_003":               "vanessa_ex_full_003_irked_003",         # Auto: Renamed
    "vanessa_ex_full_018_open_003":          "vanessa_ex_full_003_irked2_003",        # Auto: Renamed
    "vanessa_ex_full_018_smile_003":         "vanessa_ex_full_003_irked3_003",        # Auto: Renamed
    "vanessa_ex_full_019_003":               "vanessa_ex_full_003_open2_003",         # Auto: Renamed
    "vanessa_ex_full_019_grin2_003":         "vanessa_ex_full_003_grin2_003",         # Auto: Renamed
    "vanessa_ex_full_019_grin_003":          "vanessa_ex_full_003_grin_003",          # Auto: Renamed
    "vanessa_ex_full_020_003":               "vanessa_ex_full_007_003",               # Auto: Renamed
    "vanessa_ex_full_021_003":               "vanessa_ex_full_011_open_003",          # Auto: Renamed
}
