characterMapAnna = {
    "anna_be0_y_001":                        "",                                      # Auto: Deleted
    "anna_be0_y_002":                        "",                                      # Auto: Deleted
    "anna_be1_y_001":                        "",                                      # Auto: Deleted
    "anna_be1_y_002":                        "",                                      # Auto: Deleted
    "anna_be1_y_naked_001":                  "",                                      # Auto: Deleted
    "anna_be1_y_naked_002":                  "",                                      # Auto: Deleted
    "anna_base_001":                         "anna_base_001",                         # Auto: Edited
    "anna_base_002":                         "anna_base_002",                         # Auto: Edited
    "anna_base_full_001":                    "anna_base_full_001",                    # Auto: Edited
    "anna_base_full_002":                    "anna_base_full_002",                    # Auto: Edited
    "anna_base_y_001":                       "",                                      # Auto: Deleted
    "anna_base_y_002":                       "",                                      # Auto: Deleted
    "anna_base_y_naked_001":                 "",                                      # Auto: Deleted
    "anna_base_y_naked_002":                 "",                                      # Auto: Deleted
    "anna_ex_001_001":                       "anna_ex_001_001",                       # Auto: Edited
    "anna_ex_001_smile_001":                 "anna_ex_001_smile_001",                 # Auto: Edited
    "anna_ex_002_001":                       "anna_ex_002_001",                       # Auto: Edited
    "anna_ex_002_open_001":                  "anna_ex_002_open_001",                  # Auto: Edited
    "anna_ex_003_001":                       "anna_ex_003_001",                       # Auto: Edited
    "anna_ex_004_001":                       "anna_ex_004_001",                       # Auto: Edited
    "anna_ex_004_grin2_001":                 "",                                      # Auto: Deleted
    "anna_ex_004_grin_001":                  "",                                      # Auto: Deleted
    "anna_ex_005_001":                       "anna_ex_005_001",                       # Auto: Edited
    "anna_ex_006_001":                       "anna_ex_006_001",                       # Auto: Edited
    "anna_ex_006_open_001":                  "anna_ex_006_open_001",                  # Auto: Edited
    "anna_ex_007_001":                       "",                                      # Auto: Deleted
    "anna_ex_007_smile_001":                 "",                                      # Auto: Deleted
    "anna_ex_008_002":                       "anna_ex_008_002",                       # Auto: Edited
    "anna_ex_009_002":                       "anna_ex_009_002",                       # Auto: Edited
    "anna_ex_010_002":                       "anna_ex_010_002",                       # Auto: Edited
    "anna_ex_011_002":                       "anna_ex_011_002",                       # Auto: Edited
    "anna_ex_011_closed_002":                "",                                      # Auto: Deleted
    "anna_ex_012_002":                       "anna_ex_012_002",                       # Auto: Edited
    "anna_ex_013_002":                       "",                                      # Auto: Deleted
    "anna_ex_full_001_001":                  "anna_ex_full_001_001",                  # Auto: Edited
    "anna_ex_full_002_001":                  "anna_ex_full_002_001",                  # Auto: Edited
    "anna_ex_full_003_001":                  "anna_ex_full_003_001",                  # Auto: Edited
    "anna_ex_full_004_001":                  "anna_ex_full_004_001",                  # Auto: Edited
    "anna_ex_full_005_001":                  "anna_ex_full_005_001",                  # Auto: Edited
    "anna_ex_full_006_001":                  "anna_ex_full_006_001",                  # Auto: Edited
    "anna_ex_full_007_001":                  "",                                      # Auto: Deleted
    "anna_ex_full_008_002":                  "anna_ex_full_008_002",                  # Auto: Edited
    "anna_ex_full_009_002":                  "anna_ex_full_009_002",                  # Auto: Edited
    "anna_ex_full_010_002":                  "anna_ex_full_010_002",                  # Auto: Edited
    "anna_ex_full_011_002":                  "anna_ex_full_011_002",                  # Auto: Edited
    "anna_ex_full_012_002":                  "anna_ex_full_012_002",                  # Auto: Edited
    "anna_ex_full_013_002":                  "",                                      # Auto: Deleted
    "anna_ex_y_001_001":                     "",                                      # Auto: Deleted
    "anna_ex_y_002_001":                     "",                                      # Auto: Deleted
    "anna_ex_y_003_001":                     "",                                      # Auto: Deleted
    "anna_ex_y_004_001":                     "",                                      # Auto: Deleted
    "anna_ex_y_005_001":                     "",                                      # Auto: Deleted
    "anna_ex_y_006_001":                     "",                                      # Auto: Deleted
    "anna_ex_y_007_001":                     "",                                      # Auto: Deleted
    "anna_ex_y_008_002":                     "",                                      # Auto: Deleted
    "anna_ex_y_009_002":                     "",                                      # Auto: Deleted
    "anna_ex_y_010_002":                     "",                                      # Auto: Deleted
    "anna_ex_y_011_002":                     "",                                      # Auto: Deleted
    "anna_ex_y_012_002":                     "",                                      # Auto: Deleted
    "anna_ex_y_013_002":                     "",                                      # Auto: Deleted
}
