characterMapSean = {
    "sean_base_001":                         "sean_base_001",                         # Auto: Edited
    "sean_base_y_001":                       "",                                      # Auto: Deleted
    "sean_ex_001_001":                       "sean_ex_001_001",                       # Auto: Edited
    "sean_ex_002_001":                       "sean_ex_002_001",                       # Auto: Edited
    "sean_ex_003_001":                       "sean_ex_003_001",                       # Auto: Edited
    "sean_ex_004_001":                       "sean_ex_004_001",                       # Auto: Edited
    "sean_ex_005_001":                       "sean_ex_005_001",                       # Auto: Edited
    "sean_ex_006_001":                       "sean_ex_006_001",                       # Auto: Edited
    "sean_ex_007_001":                       "sean_ex_007_001",                       # Auto: Edited
    "sean_ex_008_001":                       "sean_ex_008_001",                       # Auto: Edited
    "sean_ex_009_001":                       "sean_ex_009_001",                       # Auto: Edited
    "sean_ex_010_001":                       "sean_ex_010_001",                       # Auto: Edited
    "sean_ex_011_001":                       "sean_ex_011_001",                       # Auto: Edited
    "sean_ex_012_001":                       "sean_ex_012_001",                       # Auto: Edited
    "sean_ex_013_001":                       "",                                      # Auto: Deleted
    "sean_ex_014_001":                       "",                                      # Auto: Deleted
    "sean_ex_y_001_001":                     "",                                      # Auto: Deleted
    "sean_ex_y_002_001":                     "",                                      # Auto: Deleted
    "sean_ex_y_003_001":                     "",                                      # Auto: Deleted
    "sean_ex_y_004_001":                     "",                                      # Auto: Deleted
    "sean_ex_y_005_001":                     "",                                      # Auto: Deleted
    "sean_ex_y_006_001":                     "",                                      # Auto: Deleted
    "sean_ex_y_007_001":                     "",                                      # Auto: Deleted
    "sean_ex_y_008_001":                     "",                                      # Auto: Deleted
    "sean_ex_y_009_001":                     "",                                      # Auto: Deleted
    "sean_ex_y_010_001":                     "",                                      # Auto: Deleted
    "sean_ex_y_011_001":                     "",                                      # Auto: Deleted
    "sean_ex_y_012_001":                     "",                                      # Auto: Deleted
    "sean_ex_y_013_001":                     "",                                      # Auto: Deleted
    "sean_ex_y_014_001":                     "",                                      # Auto: Deleted
}
