characterMapMichelle = {
    "michelle_be1_001":                      "michelle_be1_001",                      # Auto: Same
    "michelle_be1_002":                      "michelle_be1_002",                      # Auto: Same
    "michelle_be1_003":                      "michelle_be1_003",                      # Auto: Same
    "michelle_be1_full_001":                 "michelle_be1_full_001",                 # Auto: Same
    "michelle_be1_full_002":                 "michelle_be1_full_002",                 # Auto: Same
    "michelle_be1_full_003":                 "michelle_be1_full_003",                 # Auto: Same
    "michelle_be1_full_naked_001":           "michelle_be1_full_naked_001",           # Auto: Same
    "michelle_be1_full_naked_002":           "michelle_be1_full_naked_002",           # Auto: Same
    "michelle_be1_full_naked_003":           "michelle_be1_full_naked_003",           # Auto: Same
    "michelle_be1_naked_001":                "michelle_be1_naked_001",                # Auto: Same
    "michelle_be1_naked_002":                "michelle_be1_naked_002",                # Auto: Same
    "michelle_be1_naked_003":                "michelle_be1_naked_003",                # Auto: Same
    "michelle_be2_001":                      "michelle_be2_001",                      # Auto: Same
    "michelle_be2_002":                      "michelle_be2_002",                      # Auto: Same
    "michelle_be2_003":                      "michelle_be2_003",                      # Auto: Same
    "michelle_be2_cas_001":                  "michelle_be2_cas_001",                  # Auto: Same
    "michelle_be2_cas_002":                  "michelle_be2_cas_002",                  # Auto: Same
    "michelle_be2_cas_003":                  "michelle_be2_cas_003",                  # Auto: Same
    "michelle_be2_full_001":                 "michelle_be2_full_001",                 # Auto: Same
    "michelle_be2_full_002":                 "michelle_be2_full_002",                 # Auto: Same
    "michelle_be2_full_003":                 "michelle_be2_full_003",                 # Auto: Same
    "michelle_be2_full_cas_001":             "michelle_be2_full_cas_001",             # Auto: Same
    "michelle_be2_full_cas_002":             "michelle_be2_full_cas_002",             # Auto: Same
    "michelle_be2_full_cas_003":             "michelle_be2_full_cas_003",             # Auto: Same
    "michelle_be2_full_gym_001":             "michelle_be2_full_gym_001",             # Auto: Same
    "michelle_be2_full_gym_002":             "michelle_be2_full_gym_002",             # Auto: Same
    "michelle_be2_full_gym_003":             "michelle_be2_full_gym_003",             # Auto: Same
    "michelle_be2_full_naked_001":           "michelle_be2_full_naked_001",           # Auto: Same
    "michelle_be2_full_naked_002":           "michelle_be2_full_naked_002",           # Auto: Same
    "michelle_be2_full_naked_003":           "michelle_be2_full_naked_003",           # Auto: Same
    "michelle_be2_full_nastic_001":          "michelle_be2_full_nastic_001",          # Auto: Same
    "michelle_be2_full_nastic_002":          "michelle_be2_full_nastic_002",          # Auto: Same
    "michelle_be2_full_nastic_003":          "michelle_be2_full_nastic_003",          # Auto: Same
    "michelle_be2_full_under_001":           "michelle_be2_full_under_001",           # Auto: Same
    "michelle_be2_full_under_002":           "michelle_be2_full_under_002",           # Auto: Same
    "michelle_be2_full_under_003":           "michelle_be2_full_under_003",           # Auto: Same
    "michelle_be2_gym_001":                  "michelle_be2_gym_001",                  # Auto: Same
    "michelle_be2_gym_002":                  "michelle_be2_gym_002",                  # Auto: Same
    "michelle_be2_gym_003":                  "michelle_be2_gym_003",                  # Auto: Same
    "michelle_be2_naked_001":                "michelle_be2_naked_001",                # Auto: Same
    "michelle_be2_naked_002":                "michelle_be2_naked_002",                # Auto: Same
    "michelle_be2_naked_003":                "michelle_be2_naked_003",                # Auto: Same
    "michelle_be2_nastic_001":               "michelle_be2_nastic_001",               # Auto: Same
    "michelle_be2_nastic_002":               "michelle_be2_nastic_002",               # Auto: Same
    "michelle_be2_nastic_003":               "michelle_be2_nastic_003",               # Auto: Same
    "michelle_be2_under_001":                "michelle_be2_under_001",                # Auto: Same
    "michelle_be2_under_002":                "michelle_be2_under_002",                # Auto: Same
    "michelle_be2_under_003":                "michelle_be2_under_003",                # Auto: Same
    "michelle_base_001":                     "michelle_base_001",                     # Auto: Edited
    "michelle_base_002":                     "michelle_base_002",                     # Auto: Edited
    "michelle_base_003":                     "michelle_base_003",                     # Auto: Edited
    "michelle_base_cas_001":                 "michelle_base_cas_001",                 # Auto: Edited
    "michelle_base_cas_002":                 "michelle_base_cas_002",                 # Auto: Edited
    "michelle_base_cas_003":                 "michelle_base_cas_003",                 # Auto: Edited
    "michelle_base_dog_001":                 "michelle_base_dog_001",                 # Auto: Edited
    "michelle_base_dog_002":                 "michelle_base_dog_002",                 # Auto: Edited
    "michelle_base_dog_003":                 "michelle_base_dog_003",                 # Auto: Edited
    "michelle_base_dress_001":               "michelle_base_dress_001",               # Auto: Edited
    "michelle_base_dress_002":               "michelle_base_dress_002",               # Auto: Edited
    "michelle_base_dress_003":               "michelle_base_dress_003",               # Auto: Edited
    "michelle_base_full_001":                "michelle_base_full_001",                # Auto: Same
    "michelle_base_full_002":                "michelle_base_full_002",                # Auto: Same
    "michelle_base_full_003":                "michelle_base_full_003",                # Auto: Same
    "michelle_base_full_cas_001":            "michelle_base_full_cas_001",            # Auto: Same
    "michelle_base_full_cas_002":            "michelle_base_full_cas_002",            # Auto: Same
    "michelle_base_full_cas_003":            "michelle_base_full_cas_003",            # Auto: Same
    "michelle_base_full_dog_001":            "michelle_base_full_dog_001",            # Auto: Same
    "michelle_base_full_dog_002":            "michelle_base_full_dog_002",            # Auto: Same
    "michelle_base_full_dog_003":            "michelle_base_full_dog_003",            # Auto: Same
    "michelle_base_full_dress_001":          "michelle_base_full_dress_001",          # Auto: Same
    "michelle_base_full_dress_002":          "michelle_base_full_dress_002",          # Auto: Same
    "michelle_base_full_dress_003":          "michelle_base_full_dress_003",          # Auto: Same
    "michelle_base_full_gym_001":            "michelle_base_full_gym_001",            # Auto: Same
    "michelle_base_full_gym_002":            "michelle_base_full_gym_002",            # Auto: Same
    "michelle_base_full_gym_003":            "michelle_base_full_gym_003",            # Auto: Same
    "michelle_base_full_naked_001":          "michelle_base_full_naked_001",          # Auto: Same
    "michelle_base_full_naked_002":          "michelle_base_full_naked_002",          # Auto: Same
    "michelle_base_full_naked_003":          "michelle_base_full_naked_003",          # Auto: Same
    "michelle_base_full_nastic_001":         "michelle_base_full_nastic_001",         # Auto: Same
    "michelle_base_full_nastic_002":         "michelle_base_full_nastic_002",         # Auto: Same
    "michelle_base_full_nastic_003":         "michelle_base_full_nastic_003",         # Auto: Same
    "michelle_base_full_under_001":          "michelle_base_full_under_001",          # Auto: Same
    "michelle_base_full_under_002":          "michelle_base_full_under_002",          # Auto: Same
    "michelle_base_full_under_003":          "michelle_base_full_under_003",          # Auto: Same
    "michelle_base_gym_001":                 "michelle_base_gym_001",                 # Auto: Edited
    "michelle_base_gym_002":                 "michelle_base_gym_002",                 # Auto: Edited
    "michelle_base_gym_003":                 "michelle_base_gym_003",                 # Auto: Edited
    "michelle_base_naked_001":               "michelle_base_naked_001",               # Auto: Edited
    "michelle_base_naked_002":               "michelle_base_naked_002",               # Auto: Edited
    "michelle_base_naked_003":               "michelle_base_naked_003",               # Auto: Edited
    "michelle_base_nastic_001":              "michelle_base_nastic_001",              # Auto: Edited
    "michelle_base_nastic_002":              "michelle_base_nastic_002",              # Auto: Edited
    "michelle_base_nastic_003":              "michelle_base_nastic_003",              # Auto: Edited
    "michelle_base_under_001":               "michelle_base_under_001",               # Auto: Edited
    "michelle_base_under_002":               "michelle_base_under_002",               # Auto: Edited
    "michelle_base_under_003":               "michelle_base_under_003",               # Auto: Edited
    "michelle_ex_001_001":                   "michelle_ex_001_001",                   # Auto: Same
    "michelle_ex_001_neutral_001":           "michelle_ex_001_neutral_001",           # Auto: Same
    "michelle_ex_001_smile_001":             "michelle_ex_001_smile_001",             # Auto: Same
    "michelle_ex_002_001":                   "michelle_ex_002_smile_001",             # Auto: Renamed
    "michelle_ex_002_smile_001":             "michelle_ex_002_001",                   # Auto: Renamed
    "michelle_ex_003_001":                   "michelle_ex_003_open2_001",             # Auto: Renamed
    "michelle_ex_003_grin2_001":             "michelle_ex_003_grin2_001",             # Auto: Same
    "michelle_ex_003_grin_001":              "michelle_ex_003_grin_001",              # Auto: Same
    "michelle_ex_003_open_001":              "michelle_ex_003_open_001",              # Auto: Same
    "michelle_ex_004_001":                   "michelle_ex_004_open_001",              # Auto: Renamed
    "michelle_ex_004_closed_001":            "michelle_ex_004_001",                   # Auto: Renamed
    "michelle_ex_004_smile_001":             "michelle_ex_004_smile_001",             # Auto: Same
    "michelle_ex_005_001":                   "michelle_ex_004_open2_001",             # Auto: Renamed
    "michelle_ex_005_closed_001":            "michelle_ex_004_001",
    "michelle_ex_006_001":                   "michelle_ex_003_001",                   # Auto: Renamed
    "michelle_ex_007_001":                   "michelle_ex_005_aroused2_001",          # Auto: Renamed
    "michelle_ex_008_001":                   "michelle_ex_003_grit2_001",             # Auto: Renamed
    "michelle_ex_009_002":                   "michelle_ex_005_open_002",              # Auto: Renamed
    "michelle_ex_009_closed_002":            "michelle_ex_005_002",                   # Auto: Renamed
    "michelle_ex_009_smile2_002":            "michelle_ex_005_smile2_002",            # Auto: Renamed
    "michelle_ex_009_smile_002":             "michelle_ex_005_smile_002",             # Auto: Renamed
    "michelle_ex_010_002":                   "michelle_ex_003_irked_002",             # Auto: Renamed
    "michelle_ex_011_002":                   "michelle_ex_009_closed_002",            # Auto: Renamed
    "michelle_ex_011_closed_002":            "michelle_ex_006_002",                   # Auto: Renamed
    "michelle_ex_011_smile2_002":            "michelle_ex_006_smile2_002",            # Auto: Renamed
    "michelle_ex_011_smile_002":             "michelle_ex_006_smile_002",             # Auto: Renamed
    "michelle_ex_012_002":                   "michelle_ex_012_002",                   # Auto: Same
    "michelle_ex_013_002":                   "michelle_ex_012_smile_002",             # Auto: Renamed
    "michelle_ex_014_002":                   "michelle_ex_006_open2_002",             # Auto: Renamed
    "michelle_ex_015_002":                   "michelle_ex_008_002",                   # Auto: Renamed
    "michelle_ex_015_open_002":              "michelle_ex_008_open_002",              # Auto: Renamed
    "michelle_ex_016_002":                   "michelle_ex_003_irked3_002",            # Auto: Renamed
    "michelle_ex_017_003":                   "michelle_ex_010_open_003",              # Auto: Renamed
    "michelle_ex_018_003":                   "michelle_ex_011_003",                   # Auto: Renamed
    "michelle_ex_019_003":                   "michelle_ex_011_open_003",              # Auto: Renamed
    "michelle_ex_020_003":                   "michelle_ex_010_daze2_003",             # Auto: Renamed
    "michelle_ex_021_003":                   "michelle_ex_010_daze_003",              # Auto: Renamed
    "michelle_ex_full_001_001":              "michelle_ex_full_001_001",              # Auto: Same
    "michelle_ex_full_001_neutral_001":      "michelle_ex_full_001_neutral_001",      # Auto: Same
    "michelle_ex_full_001_smile_001":        "michelle_ex_full_001_smile_001",        # Auto: Same
    "michelle_ex_full_002_001":              "michelle_ex_full_002_smile_001",        # Auto: Renamed
    "michelle_ex_full_002_smile_001":        "michelle_ex_full_002_001",              # Auto: Renamed
    "michelle_ex_full_003_001":              "michelle_ex_full_003_open2_001",        # Auto: Renamed
    "michelle_ex_full_003_grin2_001":        "michelle_ex_full_003_grin2_001",        # Auto: Same
    "michelle_ex_full_003_grin_001":         "michelle_ex_full_003_grin_001",         # Auto: Same
    "michelle_ex_full_003_open_001":         "michelle_ex_full_003_open_001",         # Auto: Same
    "michelle_ex_full_004_001":              "michelle_ex_full_004_open_001",         # Auto: Renamed
    "michelle_ex_full_004_closed_001":       "michelle_ex_full_004_001",              # Auto: Renamed
    "michelle_ex_full_004_smile_001":        "michelle_ex_full_004_smile_001",        # Auto: Same
    "michelle_ex_full_005_001":              "michelle_ex_full_004_open2_001",        # Auto: Renamed
    "michelle_ex_full_006_001":              "michelle_ex_full_003_001",              # Auto: Renamed
    "michelle_ex_full_007_001":              "michelle_ex_full_005_aroused2_001",     # Auto: Renamed
    "michelle_ex_full_008_001":              "michelle_ex_full_003_grit2_001",        # Auto: Renamed
    "michelle_ex_full_009_002":              "michelle_ex_full_005_open_002",         # Auto: Renamed
    "michelle_ex_full_009_closed_002":       "michelle_ex_full_005_002",              # Auto: Renamed
    "michelle_ex_full_009_smile2_002":       "michelle_ex_full_005_smile2_002",       # Auto: Renamed
    "michelle_ex_full_009_smile_002":        "michelle_ex_full_005_smile_002",        # Auto: Renamed
    "michelle_ex_full_010_002":              "michelle_ex_full_003_irked_002",        # Auto: Renamed
    "michelle_ex_full_011_002":              "michelle_ex_full_009_closed_002",       # Auto: Renamed
    "michelle_ex_full_011_closed_002":       "michelle_ex_full_006_002",              # Auto: Renamed
    "michelle_ex_full_011_smile2_002":       "michelle_ex_full_006_smile2_002",       # Auto: Renamed
    "michelle_ex_full_011_smile_002":        "michelle_ex_full_006_smile_002",        # Auto: Renamed
    "michelle_ex_full_012_002":              "michelle_ex_full_012_002",              # Auto: Same
    "michelle_ex_full_013_002":              "michelle_ex_full_012_smile_002",        # Auto: Renamed
    "michelle_ex_full_014_002":              "michelle_ex_full_006_open2_002",        # Auto: Renamed
    "michelle_ex_full_015_002":              "michelle_ex_full_008_002",              # Auto: Renamed
    "michelle_ex_full_015_open_002":         "michelle_ex_full_008_open_002",         # Auto: Renamed
    "michelle_ex_full_016_002":              "michelle_ex_full_003_irked3_002",       # Auto: Renamed
    "michelle_ex_full_017_003":              "michelle_ex_full_010_open_003",         # Auto: Renamed
    "michelle_ex_full_018_003":              "michelle_ex_full_011_003",              # Auto: Renamed
    "michelle_ex_full_019_003":              "michelle_ex_full_011_open_003",         # Auto: Renamed
    "michelle_ex_full_020_003":              "michelle_ex_full_010_daze2_003",        # Auto: Renamed
    "michelle_ex_full_021_003":              "michelle_ex_full_010_daze_003",         # Auto: Renamed
}
