characterMapJenna = {
    "jenna_base_001":                        "jenna_base_001",                        # Auto: Edited
    "jenna_base_002":                        "jenna_base_002",                        # Auto: Edited
    "jenna_base_full_001":                   "jenna_base_full_001",                   # Auto: Same
    "jenna_base_full_002":                   "jenna_base_full_002",                   # Auto: Same
    "jenna_base_full_gown_001":              "jenna_base_full_gown_001",              # Auto: Same
    "jenna_base_full_gown_002":              "jenna_base_full_gown_002",              # Auto: Same
    "jenna_base_full_gym_001":               "jenna_base_full_gym_001",               # Auto: Same
    "jenna_base_full_gym_002":               "jenna_base_full_gym_002",               # Auto: Same
    "jenna_base_full_maid_001":              "jenna_base_full_maid_001",              # Auto: Same
    "jenna_base_full_maid_002":              "jenna_base_full_maid_002",              # Auto: Same
    "jenna_base_full_naked_001":             "jenna_base_full_naked_001",             # Auto: Same
    "jenna_base_full_naked_002":             "jenna_base_full_naked_002",             # Auto: Same
    "jenna_base_full_nighty_001":            "jenna_base_full_night_001",             # Auto: Renamed
    "jenna_base_full_nighty_002":            "jenna_base_full_night_002",             # Auto: Renamed
    "jenna_base_full_preg_001":              "jenna_base_full_preg_001",              # Auto: Same
    "jenna_base_full_preg_002":              "jenna_base_full_preg_002",              # Auto: Same
    "jenna_base_full_school_001":            "jenna_base_full_school_001",            # Auto: Same
    "jenna_base_full_school_002":            "jenna_base_full_school_002",            # Auto: Same
    "jenna_base_full_under_001":             "jenna_base_full_under_001",             # Auto: Same
    "jenna_base_full_under_002":             "jenna_base_full_under_002",             # Auto: Same
    "jenna_base_full_wedding_001":           "jenna_base_full_wedding_001",           # Auto: Same
    "jenna_base_full_wedding_002":           "jenna_base_full_wedding_002",           # Auto: Same
    "jenna_base_gown_001":                   "jenna_base_gown_001",                   # Auto: Edited
    "jenna_base_gown_002":                   "jenna_base_gown_002",                   # Auto: Edited
    "jenna_base_gym_001":                    "jenna_base_gym_001",                    # Auto: Edited
    "jenna_base_gym_002":                    "jenna_base_gym_002",                    # Auto: Edited
    "jenna_base_maid_001":                   "jenna_base_maid_001",                   # Auto: Edited
    "jenna_base_maid_002":                   "jenna_base_maid_002",                   # Auto: Edited
    "jenna_base_naked_001":                  "jenna_base_naked_001",                  # Auto: Edited
    "jenna_base_naked_002":                  "jenna_base_naked_002",                  # Auto: Edited
    "jenna_base_nighty_001":                 "",                                      # Auto: Deleted
    "jenna_base_nighty_002":                 "",                                      # Auto: Deleted
    "jenna_base_preg_001":                   "jenna_base_preg_001",                   # Auto: Edited
    "jenna_base_preg_002":                   "jenna_base_preg_002",                   # Auto: Edited
    "jenna_base_school_001":                 "jenna_base_school_001",                 # Auto: Edited
    "jenna_base_school_002":                 "jenna_base_school_002",                 # Auto: Edited
    "jenna_base_under_001":                  "jenna_base_under_001",                  # Auto: Edited
    "jenna_base_under_002":                  "jenna_base_under_002",                  # Auto: Edited
    "jenna_base_wedding_001":                "jenna_base_wedding_001",                # Auto: Edited
    "jenna_base_wedding_002":                "jenna_base_wedding_002",                # Auto: Edited
    "jenna_ex_001_001":                      "jenna_ex_001_001",                      # Auto: Same
    "jenna_ex_001_neutral_001":              "jenna_ex_001_neutral_001",              # Auto: Same
    "jenna_ex_001_smile_001":                "jenna_ex_001_smile_001",                # Auto: Same
    "jenna_ex_002_001":                      "jenna_ex_002_smile_001",                # Auto: Renamed
    "jenna_ex_002_smile_001":                "jenna_ex_002_001",                      # Auto: Renamed
    "jenna_ex_003_001":                      "jenna_ex_003_001",                      # Auto: Same
    "jenna_ex_003_grin2_001":                "jenna_ex_003_grin2_001",                # Auto: Same
    "jenna_ex_003_grin_001":                 "jenna_ex_003_grin_001",                 # Auto: Same
    "jenna_ex_003_open2_001":                "jenna_ex_003_open2_001",                # Auto: Same
    "jenna_ex_003_open_001":                 "jenna_ex_003_open_001",                 # Auto: Same
    "jenna_ex_004_001":                      "jenna_ex_004_open_001",                 # Auto: Renamed
    "jenna_ex_004_closed_001":               "jenna_ex_004_001",                      # Auto: Renamed
    "jenna_ex_004_smile_001":                "jenna_ex_004_smile_001",                # Auto: Same
    "jenna_ex_005_001":                      "jenna_ex_001_smile2_001",               # Auto: Renamed
    "jenna_ex_006_001":                      "jenna_ex_005_aroused2_001",             # Auto: Renamed
    "jenna_ex_007_002":                      "jenna_ex_007_open_002",                 # Auto: Renamed
    "jenna_ex_007_smile_002":                "jenna_ex_007_smile_002",                # Auto: Same
    "jenna_ex_008_002":                      "jenna_ex_008_open_002",                 # Auto: Renamed
    "jenna_ex_009_002":                      "jenna_ex_009_closed_002",               # Auto: Renamed
    "jenna_ex_009_smile_002":                "",                                      # Auto: Deleted
    "jenna_ex_010_002":                      "jenna_ex_010_002",                      # Auto: Same
    "jenna_ex_011_002":                      "jenna_ex_009_002",                      # Auto: Renamed
    "jenna_ex_012_002":                      "jenna_ex_011_002",                      # Auto: Renamed
    "jenna_ex_013_002":                      "jenna_ex_012_002",                      # Auto: Renamed
    "jenna_ex_full_001_001":                 "jenna_ex_full_001_001",                 # Auto: Same
    "jenna_ex_full_001_neutral_001":         "jenna_ex_full_001_neutral_001",         # Auto: Same
    "jenna_ex_full_001_smile_001":           "jenna_ex_full_001_smile_001",           # Auto: Same
    "jenna_ex_full_002_001":                 "jenna_ex_full_002_smile_001",           # Auto: Renamed
    "jenna_ex_full_002_smile_001":           "jenna_ex_full_002_001",                 # Auto: Renamed
    "jenna_ex_full_003_001":                 "jenna_ex_full_003_001",                 # Auto: Same
    "jenna_ex_full_003_grin2_001":           "jenna_ex_full_003_grin2_001",           # Auto: Same
    "jenna_ex_full_003_grin_001":            "jenna_ex_full_003_grin_001",            # Auto: Same
    "jenna_ex_full_003_open2_001":           "jenna_ex_full_003_open2_001",           # Auto: Same
    "jenna_ex_full_003_open_001":            "jenna_ex_full_003_open_001",            # Auto: Same
    "jenna_ex_full_004_001":                 "jenna_ex_full_004_open_001",            # Auto: Renamed
    "jenna_ex_full_004_closed_001":          "jenna_ex_full_004_001",                 # Auto: Renamed
    "jenna_ex_full_004_smile_001":           "jenna_ex_full_004_smile_001",           # Auto: Same
    "jenna_ex_full_005_001":                 "jenna_ex_full_001_smile2_001",          # Auto: Renamed
    "jenna_ex_full_006_001":                 "jenna_ex_full_005_aroused2_001",        # Auto: Renamed
    "jenna_ex_full_007_002":                 "jenna_ex_full_007_open_002",            # Auto: Renamed
    "jenna_ex_full_007_smile_002":           "jenna_ex_full_007_smile_002",           # Auto: Same
    "jenna_ex_full_008_002":                 "jenna_ex_full_008_open_002",            # Auto: Renamed
    "jenna_ex_full_009_002":                 "jenna_ex_full_009_closed_002",          # Auto: Renamed
    "jenna_ex_full_009_smile_002":           "",                                      # Auto: Deleted
    "jenna_ex_full_010_002":                 "jenna_ex_full_010_002",                 # Auto: Same
    "jenna_ex_full_011_002":                 "jenna_ex_full_009_002",                 # Auto: Renamed
    "jenna_ex_full_012_002":                 "jenna_ex_full_011_002",                 # Auto: Renamed
    "jenna_ex_full_013_002":                 "jenna_ex_full_012_002",                 # Auto: Renamed
}
