characterMapMika = {
    "mika_base_001":                         "mika_base_001",                         # Auto: Edited
    "mika_base_002":                         "mika_base_002",                         # Auto: Edited
    "mika_base_cas_001":                     "mika_base_cas_001",                     # Auto: Edited
    "mika_base_cas_002":                     "mika_base_cas_002",                     # Auto: Edited
    "mika_base_fit_001":                     "mika_base_fit_001",                     # Auto: Edited
    "mika_base_fit_002":                     "mika_base_fit_002",                     # Auto: Edited
    "mika_base_full_001":                    "mika_base_full_001",                    # Auto: Same
    "mika_base_full_002":                    "mika_base_full_002",                    # Auto: Same
    "mika_base_full_cas_001":                "mika_base_full_cas_001",                # Auto: Same
    "mika_base_full_cas_002":                "mika_base_full_cas_002",                # Auto: Same
    "mika_base_full_fit_001":                "mika_base_full_fit_001",                # Auto: Same
    "mika_base_full_fit_002":                "mika_base_full_fit_002",                # Auto: Same
    "mika_base_full_gym_001":                "mika_base_full_gym_001",                # Auto: Same
    "mika_base_full_gym_002":                "mika_base_full_gym_002",                # Auto: Same
    "mika_base_full_naked_001":              "mika_base_full_naked_001",              # Auto: Same
    "mika_base_full_naked_002":              "mika_base_full_naked_002",              # Auto: Same
    "mika_base_full_preg_001":               "mika_base_full_preg_001",               # Auto: Same
    "mika_base_full_preg_002":               "mika_base_full_preg_002",               # Auto: Same
    "mika_base_full_sailor_001":             "mika_base_full_sailor_001",             # Auto: Same
    "mika_base_full_sailor_002":             "mika_base_full_sailor_002",             # Auto: Same
    "mika_base_full_swim_001":               "mika_base_full_swim_001",               # Auto: Same
    "mika_base_full_swim_002":               "mika_base_full_swim_002",               # Auto: Same
    "mika_base_full_trench_001":             "mika_base_full_trench_001",             # Auto: Same
    "mika_base_full_trench_002":             "mika_base_full_trench_002",             # Auto: Same
    "mika_base_full_under_001":              "mika_base_full_under_001",              # Auto: Same
    "mika_base_full_under_002":              "mika_base_full_under_002",              # Auto: Same
    "mika_base_gym_001":                     "mika_base_gym_001",                     # Auto: Edited
    "mika_base_gym_002":                     "mika_base_gym_002",                     # Auto: Edited
    "mika_base_male_001":                    "mika_base_male_001",                    # Auto: Edited
    "mika_base_naked_001":                   "mika_base_naked_001",                   # Auto: Edited
    "mika_base_naked_002":                   "mika_base_naked_002",                   # Auto: Edited
    "mika_base_o_001":                       "",                                      # Auto: Deleted
    "mika_base_o_002":                       "",                                      # Auto: Deleted
    "mika_base_o_naked_001":                 "",                                      # Auto: Deleted
    "mika_base_o_naked_002":                 "",                                      # Auto: Deleted
    "mika_base_preg_001":                    "mika_base_preg_001",                    # Auto: Edited
    "mika_base_preg_002":                    "mika_base_preg_002",                    # Auto: Edited
    "mika_base_sailor_001":                  "mika_base_sailor_001",                  # Auto: Edited
    "mika_base_sailor_002":                  "mika_base_sailor_002",                  # Auto: Edited
    "mika_base_swim_001":                    "mika_base_swim_001",                    # Auto: Edited
    "mika_base_swim_002":                    "mika_base_swim_002",                    # Auto: Edited
    "mika_base_trench_001":                  "mika_base_trench_001",                  # Auto: Edited
    "mika_base_trench_002":                  "mika_base_trench_002",                  # Auto: Edited
    "mika_base_under_001":                   "mika_base_under_001",                   # Auto: Edited
    "mika_base_under_002":                   "mika_base_under_002",                   # Auto: Edited
    "mika_ex_001_001":                       "mika_ex_001_001",                       # Auto: Same
    "mika_ex_001_neutral_001":               "mika_ex_001_neutral_001",               # Auto: Same
    "mika_ex_001_open_001":                  "mika_ex_001_open_001",                  # Auto: Same
    "mika_ex_001_smile_001":                 "mika_ex_001_smile_001",                 # Auto: Same
    "mika_ex_002_001":                       "mika_ex_002_smile_001",                 # Auto: Renamed
    "mika_ex_002_open_001":                  "mika_ex_002_open_001",                  # Auto: Same
    "mika_ex_002_smile_001":                 "mika_ex_002_001",                       # Auto: Renamed
    "mika_ex_003_001":                       "mika_ex_003_001",                       # Auto: Same
    "mika_ex_003_grin2_001":                 "mika_ex_003_grin2_001",                 # Auto: Same
    "mika_ex_003_grin_001":                  "mika_ex_003_grin_001",                  # Auto: Same
    "mika_ex_003_grit_001":                  "mika_ex_003_grit_001",                  # Auto: Same
    "mika_ex_003_irked2_001":                "mika_ex_003_irked2_001",                # Auto: Same
    "mika_ex_003_irked_001":                 "mika_ex_003_irked_001",                 # Auto: Same
    "mika_ex_003_open2_001":                 "mika_ex_003_open2_001",                 # Auto: Same
    "mika_ex_003_open_001":                  "mika_ex_003_open_001",                  # Auto: Same
    "mika_ex_004_001":                       "mika_ex_004_open_001",                  # Auto: Renamed
    "mika_ex_004_closed_001":                "mika_ex_004_001",                       # Auto: Renamed
    "mika_ex_004_smile_001":                 "mika_ex_004_smile_001",                 # Auto: Same
    "mika_ex_005_001":                       "mika_ex_005_001",                       # Auto: Same
    "mika_ex_005_aroused_001":               "mika_ex_005_aroused_001",               # Auto: Same
    "mika_ex_005_open_001":                  "mika_ex_005_open_001",                  # Auto: Same
    "mika_ex_005_smile2_001":                "mika_ex_005_smile2_001",                # Auto: Same
    "mika_ex_005_smile_001":                 "mika_ex_005_smile_001",                 # Auto: Same
    "mika_ex_006_001":                       "mika_ex_006_001",                       # Auto: Same
    "mika_ex_006_open_001":                  "mika_ex_006_open_001",                  # Auto: Same
    "mika_ex_006_smile2_001":                "mika_ex_006_smile2_001",                # Auto: Same
    "mika_ex_006_smile_001":                 "mika_ex_006_smile_001",                 # Auto: Same
    "mika_ex_006_wink_001":                  "mika_ex_006_wink_001",                  # Auto: Same
    "mika_ex_007_002":                       "mika_ex_007_open_002",                  # Auto: Renamed
    "mika_ex_008_002":                       "mika_ex_008_open_002",                  # Auto: Renamed
    "mika_ex_009_002":                       "mika_ex_009_002",                       # Auto: Same
    "mika_ex_010_002":                       "mika_ex_010_002",                       # Auto: Same
    "mika_ex_011_002":                       "mika_ex_009_closed_002",                # Auto: Renamed
    "mika_ex_012_002":                       "mika_ex_011_002",                       # Auto: Renamed
    "mika_ex_013_002":                       "mika_ex_012_002",                       # Auto: Renamed
    "mika_ex_full_001_001":                  "mika_ex_full_001_001",                  # Auto: Same
    "mika_ex_full_001_neutral_001":          "mika_ex_full_001_neutral_001",          # Auto: Same
    "mika_ex_full_001_open_001":             "mika_ex_full_001_open_001",             # Auto: Same
    "mika_ex_full_001_smile_001":            "mika_ex_full_001_smile_001",            # Auto: Same
    "mika_ex_full_002_001":                  "mika_ex_full_002_smile_001",            # Auto: Renamed
    "mika_ex_full_002_open_001":             "mika_ex_full_002_open_001",             # Auto: Same
    "mika_ex_full_002_smile_001":            "mika_ex_full_002_001",                  # Auto: Renamed
    "mika_ex_full_003_001":                  "mika_ex_full_003_001",                  # Auto: Same
    "mika_ex_full_003_grin2_001":            "mika_ex_full_003_grin2_001",            # Auto: Same
    "mika_ex_full_003_grin_001":             "mika_ex_full_003_grin_001",             # Auto: Same
    "mika_ex_full_003_grit_001":             "mika_ex_full_003_grit_001",             # Auto: Same
    "mika_ex_full_003_irked2_001":           "mika_ex_full_003_irked2_001",           # Auto: Same
    "mika_ex_full_003_irked_001":            "mika_ex_full_003_irked_001",            # Auto: Same
    "mika_ex_full_003_open2_001":            "mika_ex_full_003_open2_001",            # Auto: Same
    "mika_ex_full_003_open_001":             "mika_ex_full_003_open_001",             # Auto: Same
    "mika_ex_full_004_001":                  "mika_ex_full_004_open_001",             # Auto: Renamed
    "mika_ex_full_004_closed_001":           "mika_ex_full_004_001",                  # Auto: Renamed
    "mika_ex_full_004_smile_001":            "mika_ex_full_004_smile_001",            # Auto: Same
    "mika_ex_full_005_001":                  "mika_ex_full_005_001",                  # Auto: Same
    "mika_ex_full_005_aroused_001":          "mika_ex_full_005_aroused_001",          # Auto: Same
    "mika_ex_full_005_open_001":             "mika_ex_full_005_open_001",             # Auto: Same
    "mika_ex_full_005_smile2_001":           "mika_ex_full_005_smile2_001",           # Auto: Same
    "mika_ex_full_005_smile_001":            "mika_ex_full_005_smile_001",            # Auto: Same
    "mika_ex_full_006_001":                  "mika_ex_full_006_001",                  # Auto: Same
    "mika_ex_full_006_open_001":             "mika_ex_full_006_open_001",             # Auto: Same
    "mika_ex_full_006_smile2_001":           "mika_ex_full_006_smile2_001",           # Auto: Same
    "mika_ex_full_006_smile_001":            "mika_ex_full_006_smile_001",            # Auto: Same
    "mika_ex_full_006_wink_001":             "mika_ex_full_006_wink_001",             # Auto: Same
    "mika_ex_full_007_002":                  "mika_ex_full_007_open_002",             # Auto: Renamed
    "mika_ex_full_008_002":                  "mika_ex_full_008_open_002",             # Auto: Renamed
    "mika_ex_full_009_002":                  "mika_ex_full_009_002",                  # Auto: Same
    "mika_ex_full_010_002":                  "mika_ex_full_010_002",                  # Auto: Same
    "mika_ex_full_011_002":                  "mika_ex_full_009_closed_002",           # Auto: Renamed
    "mika_ex_full_012_002":                  "mika_ex_full_011_002",                  # Auto: Renamed
    "mika_ex_full_013_002":                  "mika_ex_full_012_002",                  # Auto: Renamed
    "mika_ex_male_001_001":                  "mika_ex_male_001_001",                  # Auto: Edited
    "mika_ex_male_002_001":                  "mika_ex_male_002_001",                  # Auto: Edited
    "mika_ex_male_003_001":                  "mika_ex_male_003_001",                  # Auto: Edited
    "mika_ex_male_004_001":                  "mika_ex_male_004_001",                  # Auto: Edited
    "mika_ex_male_004_grin_001":             "",                                      # Auto: Deleted
    "mika_ex_male_005_001":                  "mika_ex_male_005_001",                  # Auto: Edited
    "mika_ex_male_006_001":                  "mika_ex_male_006_001",                  # Auto: Edited
    "mika_ex_male_007_001":                  "mika_ex_male_007_001",                  # Auto: Edited
    "mika_ex_male_008_001":                  "mika_ex_male_008_001",                  # Auto: Edited
    "mika_ex_male_009_001":                  "mika_ex_male_009_001",                  # Auto: Edited
    "mika_ex_male_010_001":                  "mika_ex_male_010_001",                  # Auto: Edited
    "mika_ex_male_011_001":                  "mika_ex_male_011_001",                  # Auto: Edited
    "mika_ex_o_001_001":                     "",                                      # Auto: Deleted
    "mika_ex_o_002_001":                     "",                                      # Auto: Deleted
    "mika_ex_o_003_001":                     "",                                      # Auto: Deleted
    "mika_ex_o_004_001":                     "",                                      # Auto: Deleted
    "mika_ex_o_005_001":                     "",                                      # Auto: Deleted
    "mika_ex_o_006_001":                     "",                                      # Auto: Deleted
    "mika_ex_o_007_001":                     "",                                      # Auto: Deleted
    "mika_ex_o_008_002":                     "",                                      # Auto: Deleted
    "mika_ex_o_009_002":                     "",                                      # Auto: Deleted
    "mika_ex_o_010_002":                     "",                                      # Auto: Deleted
    "mika_ex_o_011_002":                     "",                                      # Auto: Deleted
    "mika_ex_o_012_002":                     "",                                      # Auto: Deleted
    "mika_ex_o_013_002":                     "",                                      # Auto: Deleted
}
