characterMapNurse = {
    "nurse_be1_001":                         "nurse_be1_001",                         # Auto: Same
    "nurse_be1_002":                         "nurse_be1_002",                         # Auto: Same
    "nurse_be1_003":                         "nurse_be1_003",                         # Auto: Same
    "nurse_be1_full_001":                    "nurse_be1_full_001",                    # Auto: Same
    "nurse_be1_full_002":                    "nurse_be1_full_002",                    # Auto: Same
    "nurse_be1_full_003":                    "nurse_be1_full_003",                    # Auto: Same
    "nurse_be1_full_naked_001":              "nurse_be1_full_naked_001",              # Auto: Same
    "nurse_be1_full_naked_002":              "nurse_be1_full_naked_002",              # Auto: Same
    "nurse_be1_full_naked_003":              "nurse_be1_full_naked_003",              # Auto: Same
    "nurse_be1_full_skimp_001":              "nurse_be1_full_skimp_001",              # Auto: Same
    "nurse_be1_full_skimp_002":              "nurse_be1_full_skimp_002",              # Auto: Same
    "nurse_be1_full_skimp_003":              "nurse_be1_full_skimp_003",              # Auto: Same
    "nurse_be1_full_under_001":              "nurse_be1_full_under_001",              # Auto: Same
    "nurse_be1_full_under_002":              "nurse_be1_full_under_002",              # Auto: Same
    "nurse_be1_full_under_003":              "nurse_be1_full_under_003",              # Auto: Same
    "nurse_be1_naked_001":                   "nurse_be1_naked_001",                   # Auto: Same
    "nurse_be1_naked_002":                   "nurse_be1_naked_002",                   # Auto: Same
    "nurse_be1_naked_003":                   "nurse_be1_naked_003",                   # Auto: Same
    "nurse_be1_skimp_001":                   "nurse_be1_skimp_001",                   # Auto: Same
    "nurse_be1_skimp_002":                   "nurse_be1_skimp_002",                   # Auto: Same
    "nurse_be1_skimp_003":                   "nurse_be1_skimp_003",                   # Auto: Same
    "nurse_be1_under_001":                   "nurse_be1_under_001",                   # Auto: Same
    "nurse_be1_under_002":                   "nurse_be1_under_002",                   # Auto: Same
    "nurse_be1_under_003":                   "nurse_be1_under_003",                   # Auto: Same
    "nurse_base_001":                        "nurse_base_001",                        # Auto: Edited
    "nurse_base_002":                        "nurse_base_002",                        # Auto: Edited
    "nurse_base_003":                        "nurse_base_003",                        # Auto: Edited
    "nurse_base_full_001":                   "nurse_base_full_001",                   # Auto: Same
    "nurse_base_full_002":                   "nurse_base_full_002",                   # Auto: Same
    "nurse_base_full_003":                   "nurse_base_full_003",                   # Auto: Same
    "nurse_base_full_naked_001":             "nurse_base_full_naked_001",             # Auto: Same
    "nurse_base_full_naked_002":             "nurse_base_full_naked_002",             # Auto: Same
    "nurse_base_full_naked_003":             "nurse_base_full_naked_003",             # Auto: Same
    "nurse_base_full_skimp_001":             "nurse_base_full_skimp_001",             # Auto: Same
    "nurse_base_full_skimp_002":             "nurse_base_full_skimp_002",             # Auto: Same
    "nurse_base_full_skimp_003":             "nurse_base_full_skimp_003",             # Auto: Same
    "nurse_base_full_under_001":             "nurse_base_full_under_001",             # Auto: Same
    "nurse_base_full_under_002":             "nurse_base_full_under_002",             # Auto: Same
    "nurse_base_full_under_003":             "nurse_base_full_under_003",             # Auto: Same
    "nurse_base_naked_001":                  "nurse_base_naked_001",                  # Auto: Edited
    "nurse_base_naked_002":                  "nurse_base_naked_002",                  # Auto: Edited
    "nurse_base_naked_003":                  "nurse_base_naked_003",                  # Auto: Edited
    "nurse_base_skimp_001":                  "nurse_base_skimp_001",                  # Auto: Edited
    "nurse_base_skimp_002":                  "nurse_base_skimp_002",                  # Auto: Edited
    "nurse_base_skimp_003":                  "nurse_base_skimp_003",                  # Auto: Edited
    "nurse_base_under_001":                  "nurse_base_under_001",                  # Auto: Edited
    "nurse_base_under_002":                  "nurse_base_under_002",                  # Auto: Edited
    "nurse_base_under_003":                  "nurse_base_under_003",                  # Auto: Edited
    "nurse_ex_001_001":                      "nurse_ex_001_001",                      # Auto: Same
    "nurse_ex_001_neutral_001":              "nurse_ex_001_neutral_001",              # Auto: Same
    "nurse_ex_001_smile_001":                "nurse_ex_001_smile_001",                # Auto: Same
    "nurse_ex_002_001":                      "nurse_ex_002_smile_001",                # Auto: Renamed
    "nurse_ex_002_smile_001":                "nurse_ex_002_001",                      # Auto: Renamed
    "nurse_ex_003_001":                      "nurse_ex_003_irked_001",                # Auto: Renamed
    "nurse_ex_003_grin2_001":                "nurse_ex_003_smile2_001",               # Auto: Renamed
    "nurse_ex_003_grin_001":                 "",                                      # Auto: Deleted
    "nurse_ex_003_open2_002":                "nurse_ex_003_open2_002",                # Auto: Same
    "nurse_ex_003_open_001":                 "nurse_ex_003_irked2_001",               # Auto: Renamed
    "nurse_ex_004_001":                      "nurse_ex_004_open_001",                 # Auto: Renamed
    "nurse_ex_004_closed_001":               "nurse_ex_004_001",                      # Auto: Renamed
    "nurse_ex_004_smile_001":                "nurse_ex_004_smile_001",                # Auto: Edited
    "nurse_ex_005_001":                      "nurse_ex_005_001",                      # Auto: Same
    "nurse_ex_005_open_001":                 "nurse_ex_005_open_001",                 # Auto: Same
    "nurse_ex_005_smile2_001":               "nurse_ex_005_smile2_001",               # Auto: Same
    "nurse_ex_005_smile_001":                "nurse_ex_005_smile_001",                # Auto: Same
    "nurse_ex_006_001":                      "nurse_ex_006_001",                      # Auto: Same
    "nurse_ex_006_open_001":                 "nurse_ex_006_open_001",                 # Auto: Same
    "nurse_ex_006_smile2_001":               "nurse_ex_006_smile2_001",               # Auto: Same
    "nurse_ex_006_smile_001":                "nurse_ex_006_smile_001",                # Auto: Same
    "nurse_ex_007_001":                      "nurse_ex_005_aroused2_001",             # Auto: Renamed
    "nurse_ex_008_002":                      "",                                      # Auto: Deleted
    "nurse_ex_009_002":                      "nurse_ex_003_grin_002",                 # Auto: Renamed
    "nurse_ex_010_002":                      "nurse_ex_012_002",                      # Auto: Renamed
    "nurse_ex_011_003":                      "nurse_ex_007_003",                      # Auto: Renamed
    "nurse_ex_012_003":                      "nurse_ex_008_003",                      # Auto: Renamed
    "nurse_ex_013_003":                      "nurse_ex_013_003",                      # Auto: Same
    "nurse_ex_full_001_001":                 "nurse_ex_full_001_001",                 # Auto: Same
    "nurse_ex_full_001_neutral_001":         "nurse_ex_full_001_neutral_001",         # Auto: Same
    "nurse_ex_full_001_smile_001":           "nurse_ex_full_001_smile_001",           # Auto: Same
    "nurse_ex_full_002_001":                 "nurse_ex_full_002_smile_001",           # Auto: Renamed
    "nurse_ex_full_002_smile_001":           "nurse_ex_full_002_001",                 # Auto: Renamed
    "nurse_ex_full_003_001":                 "nurse_ex_full_003_irked_001",           # Auto: Renamed
    "nurse_ex_full_003_grin2_001":           "nurse_ex_full_003_smile2_001",          # Auto: Renamed
    "nurse_ex_full_003_grin_001":            "",                                      # Auto: Deleted
    "nurse_ex_full_003_open2_002":           "nurse_ex_full_003_open2_002",           # Auto: Same
    "nurse_ex_full_003_open_001":            "nurse_ex_full_003_irked2_001",          # Auto: Renamed
    "nurse_ex_full_004_001":                 "nurse_ex_full_004_open_001",            # Auto: Renamed
    "nurse_ex_full_004_closed_001":          "nurse_ex_full_004_001",                 # Auto: Renamed
    "nurse_ex_full_004_smile_001":           "nurse_ex_full_004_smile_001",           # Auto: Edited
    "nurse_ex_full_005_001":                 "nurse_ex_full_005_001",                 # Auto: Same
    "nurse_ex_full_005_open_001":            "nurse_ex_full_005_open_001",            # Auto: Same
    "nurse_ex_full_005_smile2_001":          "nurse_ex_full_005_smile2_001",          # Auto: Same
    "nurse_ex_full_005_smile_001":           "nurse_ex_full_005_smile_001",           # Auto: Same
    "nurse_ex_full_006_001":                 "nurse_ex_full_006_001",                 # Auto: Same
    "nurse_ex_full_006_open_001":            "nurse_ex_full_006_open_001",            # Auto: Same
    "nurse_ex_full_006_smile2_001":          "nurse_ex_full_006_smile2_001",          # Auto: Same
    "nurse_ex_full_006_smile_001":           "nurse_ex_full_006_smile_001",           # Auto: Same
    "nurse_ex_full_007_001":                 "nurse_ex_full_005_aroused2_001",        # Auto: Renamed
    "nurse_ex_full_008_002":                 "",                                      # Auto: Deleted
    "nurse_ex_full_009_002":                 "nurse_ex_full_003_grin_002",            # Auto: Renamed
    "nurse_ex_full_010_002":                 "nurse_ex_full_012_002",                 # Auto: Renamed
    "nurse_ex_full_011_003":                 "nurse_ex_full_007_003",                 # Auto: Renamed
    "nurse_ex_full_012_003":                 "nurse_ex_full_008_003",                 # Auto: Renamed
    "nurse_ex_full_013_003":                 "nurse_ex_full_013_003",                 # Auto: Same
}
